### PR TITLE
Use implied properties to parametrize package manager configuration settings rules

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:

Some rules describe package manager configuration. However, on RHEL we use `yum` and we set configuration settings in `/etc/yum.conf`, but on Fedora we use `dnf`and we set configuration in `/etc/dnf/dnf.conf`.

We can use implied properties to customize the rules and remediations. These variables will be substituted in final output, so there will be "dnf" mentioned in Fedora content and "yum" mentioned in RHEL content. Also, the rules and remediations will contain correct path to the configuration file depending on the package manager used on target platform.

Since this is a radical change, I have used the new approach only in rule `ensure_gpgcheck_globally_activated`. If the feedback on this change will be positive, then I can do a similar changes in all other rules from this group.

#### Rationale:

This will prevent us from copying code.

### CODE REVIEW

**Comment by yuumasato** [comment]
How about setting `pkg_manager_config_file` as an [implied property](https://github.com/OpenSCAP/scap-security-guide/blob/master/ssg/yaml.py#L56)?

I think these implied properties will need more visibility as we put more stuff on it.

**Comment by jan-cerny** [comment]
It's great that we already a mechanism for that. Thanks for showing it.

**Comment by jan-cerny** [comment]
@pep8speaks I don't change this line.

**Comment by yuumasato** [comment]
@jan-cerny looks good to me.
But I wonder if list of implied properties should be listed somewhere in documentation, this can be done later though.

**Comment by jan-cerny** [comment]
Do you think it should be done also for rules that are not included in any Fedora profile?

**Comment by redhatrises** [comment]
Fixes #1727

**Comment by yuumasato** [comment]
@jan-cerny I would limit the scope of this Pr just for Fedora, for now.
Is there anything else keeping this as WIP?

**Comment by jan-cerny** [comment]
I haven't discovered other occurrences of `/etc/yum.conf` in Fedora rules.

There are some rules that suggest in their description to run `yum install` or `yum erase`. Those things should be replaced by Jinja macros. We have already defined them in our .jinja files.  I think that should be done in a separate PR.

**Comment by yuumasato** [comment]
> I haven't discovered other occurrences of /etc/yum.conf in Fedora rules.

Thanks for checking. Ack.

> think that should be done in a separate PR.

Agreed.

**Comment by mpreisler** [comment]
> @jan-cerny I would limit the scope of this Pr just for Fedora, for now.
> Is there anything else keeping this as WIP?

If it was me I would do it for all rules. The reason is simple, once I know the issue and I know how to fix it I can very efficiently fix it for all and save future cost. The cost of figuring out what to fix and picking it up is very high, the cost of running a `sed` command for all rules is very low.

Just my 2c.

**Pull request merged**
