### PR TITLE
Change amount of space needed before exit filter

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Loosen up amount of white space required in regex.

#### Rationale:

- - White space requirements are too rigid, they don't match expected rules.

### CODE REVIEW

**Comment by yuumasato** [comment]
```
$ ./test_suite.py rule --libvirt qemu:///system fedora28-kicked --datastream ~/git/scap-security-guide/build/ssg-fedora-ds.xml --xccdf-id scap_org.open-scap_cref_ssg-fedora-xccdf-1.2.xml audit_rules_unsuccessful_file_modification
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/wsato/git/scap-security-guide/tests/logs/rule-custom-2018-09-12-1704/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_o_trunc_write
INFO - Script o_creat_rules.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script open_rules.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script empty.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script o_trunc_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script rules-amis.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_unlink
INFO - Script default.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script only_eacces.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script empty.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_rule_order
INFO - Script ordered_by_arch.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script one_rule_missing.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script sorted_rules.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script unordered.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script ordered_by_filter.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_chown
INFO - Script one_filter.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script default.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script empty.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open_o_creat
INFO - Script o_creat_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script open_rules.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script empty.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script rules-amis.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script o_trunc_write_rules.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - xccdf_org.ssgproject.content_rule_audit_rules_unsuccessful_file_modification_open
INFO - Script audit_o_trunc_write_rules.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script open_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script audit_o_creat_rules.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script empty.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script rules-amis.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
```

works fine now.

**Comment by redhatrises** [comment]
Aren't they supposed to be rigid? Shouldn't there not be more than whitespace between rules?

**Comment by yuumasato** [comment]
> Shouldn't there not be more than whitespace between rules?

The changes are only loosening amount o whitespaces, it is not about allowing more stuff.

**Comment by dahaic** [comment]
I just rerun tests, it works nice now. Good catch @yuumasato. ACK

**Pull request merged**
