### PR TITLE
Update CIS profiles to use control files

### PR DESCRIPTION
**Pull request by rhmdnd**
Remove all the original rules and mappings we had for CIS version 1.1
and instead rely on the control files for CIS OpenShift 1.4.0 that we
recently implemented.

### CODE REVIEW

**Comment by rhmdnd** [comment]
The OpenShift tests should work a bit better once https://github.com/ComplianceAsCode/content/pull/10841 lands

**Comment by rhmdnd** [comment]
Rebased to pick up the YAML fix in section 5.

https://github.com/ComplianceAsCode/content/pull/10843

**Comment by jhrozek** [comment]
@rhmdnd can you rebase?

**Comment by rhmdnd** [comment]
Filtering worked for the CIS profile. Adding in filtering for the node profile now.

**Comment by rhmdnd** [comment]
cc: @xiaojiey for awareness that these changes are coming to the CIS profile for the next Compliance Operator release.

**Comment by rhmdnd** [comment]
OCP4 CIS testing passed. cc @jhrozek @Vincent056 @yuumasato

**Comment by xiaojiey** [comment]
/label qe-

> cc: @xiaojiey for awareness that these changes are coming to the CIS profile for the next Compliance Operator release.

Got it. Thanks for the notification. Does it mean cis 1.4.0 is available?

**Comment by jhrozek** [comment]
> > cc: @xiaojiey for awareness that these changes are coming to the CIS profile for the next Compliance Operator release.
> 
> Got it. Thanks for the notification. Does it mean cis 1.4.0 is available?

Mostly. We've ported the existing rules and did some changes, but not all. We need to make a second pass to sync the upstream benchmark that we worked on with CIS to the rules, but I don't think there will be many changes. Some parts of CIS are not implementable with CIS yet (some permission issues) outside 4.14+.

But for now this is mostly a different way of building the profile and the references should point to the right controls and sections in upstream CIS.

**Comment by jhrozek** [comment]
It appears that we have either missed some rules or maybe these rules were deprecated:
```
- file_permissions_kube_controller_manager (was in node, 1.1.3, now there is a typo that says file_permissions_kube_apiserver)
- file_owner_kubelet (was in node 4.1.6)
- file_permissions_scheduler (was in node 1.1.5)
- general_configure_imagepolicywebhook (was 5.5.1)
- kubelet_enable_protect_kernel_sysctl (was in node 4.2.6)
- kubelet_enable_protect_kernel_defaults (was in node 4.2.6)
- api_server_admission_control_plugin_securitycontextdeny (was 1.2.13)
- api_server_api_priority_flowschema_catch_all (was 1.2.10)
- api_server_auth_mode_node (was 1.2.8)
- api_server_no_adm_ctrl_plugins_disabled (was 1.2.14)
- controller_rotate_kubelet_server_certs (was 1.3.6)
- general_configure_imagepolicywebhook (was 5.5.1)
- kubelet_configure_tls_key (was 4.2.10)
- var_openshift_audit_profile = WriteRequestBodies (wtf diff, can't find it now)
```

I'll check them out and send PRs for the obvious cases. We can discuss the rest.

**Comment by jhrozek** [comment]
I think we can skip these rules:
```
- general_configure_imagepolicywebhook - I don't see this rule being used in CIS at all except a footnote in 5.5.1
- kubelet_enable_protect_kernel_sysctl (was in node 4.2.6) - unused, is the default in newer OCP versions anyway
- kubelet_enable_protect_kernel_defaults (was in node 4.2.6) - ditto
- api_server_admission_control_plugin_securitycontextdeny - explicitly removed in 1.4
```

**Comment by jhrozek** [comment]
These were also removed:
```
api_server_api_priority_flowschema_catch_all - can't find it in 1.4
api_server_auth_mode_node - CIS now only checks for the mode not being AlwaysAllow
api_server_no_adm_ctrl_plugins_disabled - deprecated in favor of api_server_admission_control_plugin_scc
```

**Comment by jhrozek** [comment]
In this patch, please explicitly set the audit policy to WriteRequestBodies like we do e.g. in the STIG profile: https://github.com/ComplianceAsCode/content/blob/master/products/ocp4/profiles/stig.profile#L28

**Comment by jhrozek** [comment]
I will send some minor patches in a separate PR.

**Review by jhrozek — CHANGES_REQUESTED** [review]
The audit policy needs to be set.

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
