### PR TITLE
Update OVAL templates with oval_affected macro.

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Use `oval_affected` macro in favor of defining specific products per each templated OVAL

### CODE REVIEW

**Comment by redhatrises** [comment]
> More macros! :)
> 
> Ack pending jenkins.

Per @ggbecker, there is more work to do on this. A commit needs to be reverted in this PR.

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by ggbecker** [comment]
> > More macros! :)
> > Ack pending jenkins.
> 
> Per @ggbecker, there is more work to do on this. A commit needs to be reverted in this PR.

I reverted the last commit and going to push a new one with correct fixes.

**Comment by ggbecker** [comment]
Commit 2cd4121cddc526c1e49be34f011855749941ad84 should address the issue with the build.

**Comment by yuumasato** [comment]
@ggbecker Thank you.
This should make it easier to enable rules for new products.

**Pull request merged**
