### PR TITLE
service_rsyncd_disabled - update package name to rsync-daemon

### PR DESCRIPTION
**Pull request by mildas**
#### Description:
Some products have the `rsyncd` service in the `rsync-daemon` package, not in `rsync`.

- rhel8 and Fedora - I have verified that these two products have `rsyncd` in the `rsync-daemon` package,
- ol8 and rhv4 - this is guess (they should be based on rhel8 so I'd say it should be similar as rhel8),
- sle15 - I didn't find any `rsync-daemon` package for sle15, @brett060102 can you verify that the `rsyncd` service is in the `rsync` package?

The `rhcos4` prodtype was removed because `rsyncd` is not available in RHCOS4 (neither `rsync` nor `rsync-daemon` is available there). And this rule is not present in any RHCOS4 profile.

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by vojtapolasek** [comment]
@freddieRv  could you please confirm the guess for ol8?

**Comment by brett060102** [comment]
@mildas for SLES rsyncd is in rsync-*.x86_64

**Comment by carlosmmatos** [comment]
Don't merge until we've confirmed OL8.

**Comment by freddieRv** [comment]
@vojtapolasek guess is correct, `rsyncd` service for OL8 is in `rsync-daemon` package

**Pull request merged**
