### PR TITLE
fixes in file_groupownership template

### LINKED ISSUE #10655: Error during evaluation of file_groupowner_var_log_syslog on RHEL 7
#### Description of problem:
When we scan a RHEL 7 machine with the virtual `(all)` profile, we get an error message about evaluation of rule `file_groupowner_var_log_syslog`. This issue happened during downstream test `/CoreOS/scap-security-guide/Sanity/smoke-scan` on RHEL 7.

The same problem happens also when we scan  an UBI 7 image using oscap-docker with the virtual `(all)` profile, we get an error message about evaluation of rule file_groupowner_var_log_syslog. This issue has happened during downstream test `/CoreOS/scap-security-guide/Sanity/container-scanning` on RHEL 7.

#### SCAP Security Guide Version:
current upstream master branch as of 2023-05-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/47955e5289e104a1ebcb928caec593aea3af43d5

#### Operating System Version:
RHEL 7

#### Steps to Reproduce:

Locally:
1. oscap xccdf eval --oval-results --progress --report all.html --profile '(all)' /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml

With UBI 7 and oscap-docker:

1. oscap-docker image registry.access.redhat.com/ubi7 xccdf eval --progress --benchmark-id xccdf_org.ssgproject.content_benchmark_RHEL-7 --profile "(all)" /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml 1> output.stdout 2> output.stderr

#### Actual Results:
stderr contains error message:

```
E: oscap:     Failed to convert OVAL state to SEXP, id: oval:ssg-state_file_groupowner_var_log_syslog_gid_4_0:ste:1.
```
#### Expected Results:
no errors

#### Additional Information/Debugging Steps:
no

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

Please see commit messages.

#### Rationale:

Recent changes to the template made the OVAL check consider both GIDs and group names. But the parameter `filegid` was considered to be a numeric GID only in case it was equal to 0. This created a problem in case a content author tried to use a gid different than 0 - the result was incorrect, it tried to search for a group name instead of using the gid.
This PR tries to fix the behavior - if the parameter is an integer, it is considered to be a gid. If it is a string, it is considered to be a group name.
This should not be a problem since group names can't be numeric.

Also as Automatus tests have been run on many rules, I have discovered two problems in test scenarios for file_groupownership, file_owner and file_permissions templates.
The first problem is that scenarios try to use the is_directory template variable, but this variable is never stored. It is created only at runtime when templates are used to render checks and remediations. This made test scenarios not working correctly in case the the filepath parameter was a directory.
Also I found out that test scenarios did not account for the case when the filepath parameter was a directory and it did not exist on the system prior the test run.

- Fixes #10655 

#### Review Hints:

You can run automatus on the file_groupownership template in template mode:

```
python automatus.py template --libvirt qemu:///system ssgts_vm file_groupownership
python automatus.py template --libvirt qemu:///system ssgts_vm --remediate-using ansible file_groupownership
```

Or you can try for example these rules:

- file_groupowner_var_log_syslog
- file_groupownership_sshd_private_key
- file_groupowner_etc_shadow

### CODE REVIEW

**Review by Mab879 — CHANGES_REQUESTED** [review]
The PR looks good. However, there is a merge commit from another PR in it. Please take look. Also, I assume you want this to go to stabilization as well.

**Review by matejak — CHANGES_REQUESTED** [review]
I would rename the `filegid` key to `gid_or_name` or something, and not hesitate to mass-rename everything in the project. Changing meaning of a variable implies that you should also rename it if you can, and here, we can do that very easily. Documenting unexpected behavior is better than nothing, but let's follow "working software over comprehensive documentation".
I would also consider enhancing the Python template part to try to convert the `gid_or_name` to int, and if it succeeds, indicate that we have indeed a `gid`.

Moreover, constructs s.a. `if FILEGID | int(-1) != -1` violate our [guidelines](https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer/04_style_guide.md#general-coding-style).

**Comment by vojtapolasek** [comment]
@Mab879  feedback from @matejak  is reasonable. I don't think I will push for this to stabilization, I will rather propose reverting of problematic PRs which led to this situation (in stabilization).
I will rather polish out this PR and merge it later to master only.

**Comment by vojtapolasek** [comment]
@Mab879  @matejak  I have reworked the PR. See the updated description and commit messages.@Mab879  feedback from @matejak  is reasonable. I don't think I will push for this to stabilization, I will rather propose reverting of problematic PRs which led to this situation (in stabilization).
I will rather polish out this PR and merge it later to master only.

**Review by matejak — APPROVED** [review]

**Comment by matejak** [comment]
I like the style of changes introduced very much, great work!
That said, test results show legit failures that need investigation.
I also believe that at least some of the codeclimate warnings are easy to handle, and should be considered.

**Review by Mab879 — CHANGES_REQUESTED** [review]
This PR does improve the clarity around the GID or name parameter in the file_groupowner template. I agree with @matejak that test failures should be looked at. Also, please take look CodeClimate issues, the PEP8 issues need to be fixed before merging, but also take look at the other issues as well.

**Review by Mab879 — APPROVED** [review]

**Comment by vojtapolasek** [comment]
I think this is ready to be merged.
The failing Codeclimate test... I think the code duplication is worth extracting this piece of code into some module loaded by templates. I think it would decrease code readability.
The Automatus test on Fedora is failing on rules file_groupowner_etc_issue and file_groupowner_etc_issue_net. The reason is that on Fedora those files are symlinks. But mentioned rules ignore symlinks.

**Pull request merged**
