### PR TITLE
Update metadata for a few Miminal and Intermediary requirements

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Update metadata for Miminal and Intermediary requirements:
  - R27, R30, R36, R42, R48, R60, R62, R63

#### Rationale:
- Tracking notes and rationale for each requirement helps to understand the reasoning and limitations of why the rule is selected.

### CODE REVIEW

**Comment by matejak** [comment]
LGTM, thanks!

**Comment by yuumasato** [comment]
Thank you for the review

**Pull request merged**
