### PR TITLE
Unselect rules for packages dropped in RHEL8

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Do not select rules for packages dropped in RHEL8

#### Rationale:

-  According to [Changes to packages](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/8.0_beta_release_notes/changes_to_packages) page in Beta  release notes, these packages won't be part of RHEL8.

### CODE REVIEW

**Comment by yuumasato** [comment]
This PR does not drop packages from CSV files, it just unselects rules in profiles

**Comment by matusmarhefka** [comment]
We can also remove the rule `package_sendmail_removed` from rhel8 ospp profile as the package is deprecated.

**Comment by yuumasato** [comment]
> We can also remove the rule `package_sendmail_removed` from rhel8 ospp profile as the package is deprecated.

Nice catch, fixed by ~brute~ force-push

**Comment by redhatrises** [comment]
Great job @yuumasato!

**Pull request merged**
