### PR TITLE
Add remediation and OVAL for UBTU-20-010297

### PR DESCRIPTION
**Pull request by dexterle**
#### Description:

- Fix UBTU-20-010297
- Add Ubuntu2004 Ansible and Bash remediation
- Add Ubuntu2004 OVAL Definition

#### Rationale:

- Part of Ubuntu 20.04 DISA STIG v1r9 profile upgrade
- https://github.com/ComplianceAsCode/content/pull/10738

#### Review Hints:

Build the product:
```
./build_product ubuntu2004
```
To test these changes with Ansible:
```
ansible-playbook build/ansible/ubuntu2004-playbook-stig.yml --tags "DISA-STIG-UBTU-20-010297"
```
To test changes with bash, run the remediation sections: `xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod`

Checkout Manual STIG OVAL definitions, and use software like DISA STIG Viewer to view definitions.
```
git checkout dexterle:add-manual-stig-ubtu-20-v1r9
```

This STIG can be tested with the latest Ubuntu 2004 Benchmark SCAP. For reference, please review the latest artifacts: https://public.cyber.mil/stigs/downloads/

### CODE REVIEW

**Comment by marcusburghardt** [comment]
@dexterle , I saw you opened 41 draft PRs. We definitely appreciate your collaboration in the project, but 41 draft PRs without proper description is making the PRs queue a little messy and consequently hard to review.

Please, take a time and organize your existing PRs:

- Update the description of all PRs respecting the [Project Style Guides](https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#pull-requests). 
- I saw many PRs are really simple but they are still set as Draft. Please, make it clear if you plan to change the draft PRs. Otherwise, move it to "Ready for Review"
  - We usually don't actively review Draft PRs and likely they are closed after some time without interaction.

I also invite you to join the Project room in Gitter:
- https://matrix.to/#/#Compliance-As-Code-The_content:gitter.im

**Comment by dexterle** [comment]
> @dexterle , I saw you opened 41 draft PRs. We definitely appreciate your collaboration in the project, but 41 draft PRs without proper description is making the PRs queue a little messy and consequently hard to review.
> 
> Please, take a time and organize your existing PRs:
> 
> * Update the description of all PRs respecting the [Project Style Guides](https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#pull-requests).
> * I saw many PRs are really simple but they are still set as Draft. Please, make it clear if you plan to change the draft PRs. Otherwise, move it to "Ready for Review"
>   
>   * We usually don't actively review Draft PRs and likely they are closed after some time without interaction.
> 
> I also invite you to join the Project room in Gitter:
> 
> * https://matrix.to/#/#Compliance-As-Code-The_content:gitter.im

@marcusburghardt , apologies for the delay on the PR updates, and thank you for your patience. I have modified all of them with proper descriptions and moved to "Ready for Review". I have also joined the project room in Glitter. I am going to work on rebasing based on feedback received and re-testing.

**Comment by marcusburghardt** [comment]
> > @dexterle , I saw you opened 41 draft PRs. We definitely appreciate your collaboration in the project, but 41 draft PRs without proper description is making the PRs queue a little messy and consequently hard to review.
> > Please, take a time and organize your existing PRs:
> > 
> > * Update the description of all PRs respecting the [Project Style Guides](https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#pull-requests).
> > * I saw many PRs are really simple but they are still set as Draft. Please, make it clear if you plan to change the draft PRs. Otherwise, move it to "Ready for Review"
> >   
> >   * We usually don't actively review Draft PRs and likely they are closed after some time without interaction.
> > 
> > I also invite you to join the Project room in Gitter:
> > 
> > * https://matrix.to/#/#Compliance-As-Code-The_content:gitter.im
> 
> @marcusburghardt , apologies for the delay on the PR updates, and thank you for your patience. I have modified all of the Ubuntu profile upgrade STIG PRs with proper descriptions and moved to "Ready for Review". I have also joined the project room in Glitter, and will spend time rebasing and testing.

Great @dexterle. You do not need to apologize. You are getting used to the project and everything is fine. Most maintainers are on Gitter. You can also contact us there when you need any help.

**Review by marcusburghardt — COMMENTED** [review]
Perhaps it is time to simplify this rule. Currently the OVAL and remediation are named to satisfy only specific products but the rule is be valid for many other products. Ideally, this rule should use the `audit_rules_privileged_commands` template, like other similar rules. If there is any particularity where the template is not suitable, we should unify the files using the `shared` name. What do you think @ComplianceAsCode/suse-maintainers , @ComplianceAsCode/ubuntu-maintainers , @ComplianceAsCode/oracle-maintainers ?

**Comment by dodys** [comment]
> Perhaps it is time to simplify this rule. Currently the OVAL and remediation are named to satisfy only specific products but the rule is be valid for many other products. Ideally, this rule should use the `audit_rules_privileged_commands` template, like other similar rules. If there is any particularity where the template is not suitable, we should unify the files using the `shared` name. What do you think @ComplianceAsCode/suse-maintainers , @ComplianceAsCode/ubuntu-maintainers , @ComplianceAsCode/oracle-maintainers ?

sounds good to me
on this one specifically we (Ubuntu) could share the same remediation and oval as SUSE as the template itself doesn't match our case for this specific rule

**Review by dodys — CHANGES_REQUESTED** [review]
please check our comments above

**Comment by freddieRv** [comment]
> Perhaps it is time to simplify this rule. Currently the OVAL and remediation are named to satisfy only specific products but the rule is be valid for many other products. Ideally, this rule should use the audit_rules_privileged_commands template, like other similar rules. 

This sounds good 👍🏻 

> If there is any particularity where the template is not suitable, we should unify the files using the shared name.

Looking at OL7 and OL8 STIGs, the template works for OL7. However for OL8 DISA is using a different syntax for the rules.
This is correctly shown only on the rule's yaml, but not on OVAL/Ansible/Bash:
```
{{%- if product in ["ol7", "rhel7", "rhel8", "rhel9"] %}}
    {{%- set kmod_audit="-a always,exit -F path=/usr/bin/kmod -F perm=x -F auid>=" ~ uid_min ~ " -F auid!=unset -F key=privileged" %}}
{{%- elif product in ["ubuntu2004", "ubuntu2204"] %}}
    {{%- set kmod_audit="-w /bin/kmod -p x -k modules" %}}
{{%- else %}}
    {{%- set kmod_audit="-w /usr/bin/kmod -p x -k modules" %}}
{{%- endif %}}
```

This is true for a number of audit rules. If other products are in a similar position we could modify the template to accommodate both syntaxes.

**Comment by teacup-on-rockingchair** [comment]
> > Perhaps it is time to simplify this rule. Currently the OVAL and remediation are named to satisfy only specific products but the rule is be valid for many other products. Ideally, this rule should use the `audit_rules_privileged_commands` template, like other similar rules. If there is any particularity where the template is not suitable, we should unify the files using the `shared` name. What do you think @ComplianceAsCode/suse-maintainers , @ComplianceAsCode/ubuntu-maintainers , @ComplianceAsCode/oracle-maintainers ?
> 
> sounds good to me on this one specifically we (Ubuntu) could share the same remediation and oval as SUSE as the template itself doesn't match our case

Completely agree :+1: , let's start with shared and platform restriction there and we can add platforms as we go :)

**Comment by dodys** [comment]
@teacup-on-rockingchair could you check if this looks ok from SUSE's perspective? There are some failing tests.

**Comment by teacup-on-rockingchair** [comment]
> @teacup-on-rockingchair could you check if this looks ok from SUSE's perspective? There are some failing tests.

Those seem to fail for two reasons:
- first missing package requirement in the auditclt related tests, I will add them in a separate file
- missing some patches in the testing infrastructure to recognize SLE platform, this is fixed with rebase

After that I got result 'not applicable' on those since they seem to be only `machine` environment relevant :)

**Review by teacup-on-rockingchair — APPROVED** [review]
:+1: nice stuff

**Review by dodys — APPROVED** [review]
that also lgtm, thanks!

**Pull request merged**
