### PR TITLE
Ticket40450 sshd enable strictmodes

### PR DESCRIPTION
**Pull request by cyarbrough76**
#### Description:

- Edited rule.yml, changed missing parameter pass to false per stig 40450

#### Rationale:

- Scan was showing pass even though parameter was not present in file. Stig shows this as a finding.

### CODE REVIEW

**Comment by cyarbrough76** [comment]
Unclear why both commits above appear in this PR. The first commit (40440) was covered under a separate PR.

**Comment by redhatrises** [comment]
@cyarbrough76 can you remove the offending commit from this PR?

**Comment by cyarbrough76** [comment]
I would like to. I cannot see a way to do that.

**Comment by redhatrises** [comment]
`git rebase -i HEAD~3` then select the commit to drop by changing the word pick to drop.

**Pull request closed without merging**
