### PR TITLE
Restrict rule_auditd_data_retention_flush test scenarios to RHEL7.

### PR DESCRIPTION
**Pull request by ggbecker**
Update test scenarios for rule_auditd_data_retention_flush and restrict to RHEL7.
Also change profile to be applicable.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@ggbecker What is the reason for restricting it to RHEL7?

**Comment by ggbecker** [comment]
> @ggbecker What is the reason for restricting it to RHEL7?

The main idea was because the test scenario uses variable which is different from the one selected in RHEL8 CC profile and RHEL8 OSPP profile doesn't select this rule. Maybe it is not enough to restrict the test to RHEL7. What do you think?

**Comment by jan-cerny** [comment]
RHEL7 OSPP selects `data`, RHEL7 CCC selects `incremental_async`, RHEL8 OSPP doesn't select this rule. #4405 proposes `incremental async`. It looks like that after RHEL8 CCC will get merged into RHEL8 OSPP there will be a different value in RHEL7 OSPP and RHEL8 OSPP.

**Comment by jan-cerny** [comment]
> It looks like that after RHEL8 CCC will get merged into RHEL8 OSPP there will be a different value in RHEL7 OSPP and RHEL8 OSPP.

Based on this, adding RHEL 7 and OSPP to the headers seems to be a reasonable solution.

**Comment by jan-cerny** [comment]
Works for me on an RHEL7 VM target
```
[jcerny@thinkpad tests{update-auditd_data_retention_flush-test}]$ test_rule auditd_data_retention_flush rhel7
Setting console output to log level INFO
INFO - The DataStream contains 2 Benchmarks
INFO - 0 - scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml
INFO - 1 - scap_org.open-scap_cref_ssg-rhel7-pcidss-xccdf-1.2.xml
INFO - Selected Benchmark is 0
INFO - To select a different Benchmark, use --xccdf-id-number option.
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-06-24-1351/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_auditd_data_retention_flush
INFO - Script flush_incremental_async.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script flush_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script flush_incremental.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script flush_data.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script flush_sync.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script flush_none.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
```

**Pull request merged**
