### PR TITLE
Introduce new remediation type Kickstart

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:

This PR introduces new remediation type "kickstart".  This new remediation type will be used by OpenSCAP to generate RHEL kickstarts from our built data streams. These kickstarts will be used for system installation. as a lightweight alternative to OSCAP Anaconda Addon. The URN of this type will be "urn:xccdf:fix:script:kickstart".

The ability to process this remediation type will be added to OpenSCAP in https://github.com/OpenSCAP/openscap/pull/2136. The description of the language and format of the kickstart remediation type can be found in the OpenSCAP PR. 

At this moment, the commands used in this PR are:

* `package install package_name` - adds `package_name` to `%packages` section in the kickstart
* `package remove package_name` - adds `-package_name` to `%packages` section in the kickstart
* `service enable service_name` - adds `service_name` to list in the `--enabled=` option in the `services` command in commands section in the kickstart
* `service disable service_name` - adds `service_name` to list in the `--disabled=` option in the `services` command in commands section in the kickstart
* `logvol path size` - adds `logvol` entry to the commands section of the kickstart that will mount a partition of the given `size` in MB to the given `path` as a mount point
*  `bootloader option` or  `bootloader option=value` - adds `option` or `option=value` to the list in the `--append=` option in the `bootloader` command in commands section in the kickstart

We expect to add support for more commands in OpenSCAP, eg. command to configure firewall or commands for adding custom %post sections in the kickstart.

This PR adds the new kickstart remediations for the most favorite templates (package_installed, package_removed,  service_enabled, service_disabled, mount, grub2_bootloader_template). This way, we will cover most of the rules that need to be configured during the system installation.

For more details, please read commit messages of every commit.

#### Rationale:
This change will enable us to add special remediation content to our rules, needed for enabling and testing the kickstart generator feature of OpenSCAP.

#### Review Hints:
Work together with OpenSCAP feature.

### CODE REVIEW

**Comment by evgenyz** [comment]
Any reason it is still in draft state? It looks like a good boostrap for Kickstart remediations.

**Comment by jan-cerny** [comment]
> Any reason it is still in draft state? It looks like a good boostrap for Kickstart remediations.

@evgenyz We are waiting for content authors working on profiles  to provide early feedback.

**Comment by evgenyz** [comment]
> > Any reason it is still in draft state? It looks like a good boostrap for Kickstart remediations.
> 
> @evgenyz We are waiting for content authors working on profiles to provide early feedback.

I've added @ComplianceAsCode/red-hatters as a reviewer. If you want a particular opinion to move forward, please tag these people. Otherwise it is unclear when we will be able to move forward.

**Review by evgenyz — APPROVED** [review]

**Comment by jan-cerny** [comment]
I have disable Kickstart remediation in partition_for_boot.

**Pull request merged**
