### PR TITLE
Remove bogus nist: FOO-1(a) references

### PR DESCRIPTION
**Pull request by cipherboy**
`Signed-off-by: Alexander Scheel <alex.scheel@canonical.com>`

Addresses comment in #6882.

### CODE REVIEW

**Review by ggbecker — APPROVED** [review]

**Comment by ggbecker** [comment]
I believe ocp tests have no bearing on these proposed changes. Merging it. Thanks

**Comment by JAORMX** [comment]
@ggbecker the log stated otherwise:

```
 -- Generating done
-- Build files have been written to: /content/build
Scanning dependencies of target generate-internal-ocp4-shorthand.xml
[  0%] [ocp4-content] compiling profiles
[  0%] [ocp4-content] generating shorthand.xml
Traceback (most recent call last):
  File "/content/build-scripts/yaml_to_shorthand.py", line 83, in <module>
    main()
  File "/content/build-scripts/yaml_to_shorthand.py", line 70, in main
    loader.process_directory_tree(benchmark_root, add_content_dirs)
  File "/content/ssg/build_yaml.py", line 1460, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/content/ssg/build_yaml.py", line 1453, in _load_group_process_and_recurse
    self._recurse_into_subdirs()
  File "/content/ssg/build_yaml.py", line 1466, in _recurse_into_subdirs
    loader.process_directory_tree(subdir)
  File "/content/ssg/build_yaml.py", line 1460, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/content/ssg/build_yaml.py", line 1453, in _load_group_process_and_recurse
    self._recurse_into_subdirs()
  File "/content/ssg/build_yaml.py", line 1466, in _recurse_into_subdirs
    loader.process_directory_tree(subdir)
  File "/content/ssg/build_yaml.py", line 1460, in process_directory_tree
    self._load_group_process_and_recurse(start_dir)
  File "/content/ssg/build_yaml.py", line 1454, in _load_group_process_and_recurse
    self._process_rules()
  File "/content/ssg/build_yaml.py", line 1498, in _process_rules
    rule = Rule.from_yaml(rule_yaml, self.env_yaml)
  File "/content/ssg/build_yaml.py", line 1091, in from_yaml
    rule.validate_references(yaml_file)
  File "/content/ssg/build_yaml.py", line 1257, in validate_references
    raise ValueError("Empty references section in file %s" % yaml_file)
ValueError: Empty references section in file /content/applications/openstack/cinder/cinder_file_perms/rule.yml
make[3]: *** [ocp4/CMakeFiles/generate-internal-ocp4-shorthand.xml.dir/build.make:82: ocp4/shorthand.xml] Error 1
make[2]: *** [CMakeFiles/Makefile2:1094: ocp4/CMakeFiles/generate-internal-ocp4-shorthand.xml.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:789: ocp4/CMakeFiles/generate-ssg-ocp4-ds.xml.dir/rule] Error 2
make: *** [Makefile:412: generate-ssg-ocp4-ds.xml] Error 2
STEP 7: FROM registry.access.redhat.com/ubi8/ubi-minimal
error: build error: error building at STEP "RUN ./build_product --datastream-only --debug ocp4 rhel7 rhcos4": error while running runtime: exit status 2 
```

**Comment by JAORMX** [comment]
huh... seems that it's working now. I don't understand but it seems to work. So no need for a revert.

**Comment by cipherboy** [comment]
My original push was bad. I pushed a second commit to the PR that fixed the
build error (empty references section). Maybe the logs didn't update before
merge?

**Comment by JAORMX** [comment]
@cipherboy right, so as you say, the logs were from the first commit. Then you pushed a fix for that, and the PR was merged before the OCP jobs ran; hence why I noticed the last run to be a failed job.

**Pull request merged**
