### PR TITLE
Enable checks and remediations for the following SLES-12 STIGs:

### PR DESCRIPTION
**Pull request by guangyee**
- SLES-12-010030 'banner_etc_motd'
- SLES-12-010140 'accounts_logon_fail_delay'
- SLES-14-010400 'no_user_host_based_files'
- SLES-12-010410 'no_host_based_files'
- SLES-12-010610 'disable_ctrlaltdel_reboot'
- SLES-12-010611 'disable_ctrlaltdel_reboot'
- SLES-12-010650 'accounts_no_uid_except_zero'
- SLES-12-020000 'package_audit_installed'
- SLES-12-020010 'service_auditd_enabled'
- SLES-12-020030 'auditd_data_retention_space_left'
- SLES-12-020040 'auditd_data_retention_action_mail_acct'
- SLES-12-020050 'postfix_client_configure_mail_alias'
- SLES-12-020060 'auditd_data_disk_full_action'
- SLES-12-030260 'sshd_enable_x11_forwarding'

#### Description:

- Enable checks and remediations for the following SLES-12 STIGs:
  - SLES-12-010030 'banner_etc_motd'
  - SLES-12-010140 'accounts_logon_fail_delay'
  - SLES-14-010400 'no_user_host_based_files'
  - SLES-12-010410 'no_host_based_files'
  - SLES-12-010610 'disable_ctrlaltdel_reboot'
  - SLES-12-010611 'disable_ctrlaltdel_reboot'
  - SLES-12-010650 'accounts_no_uid_except_zero'
  - SLES-12-020000 'package_audit_installed'
  - SLES-12-020010 'service_auditd_enabled'
  - SLES-12-020030 'auditd_data_retention_space_left'
  - SLES-12-020040 'auditd_data_retention_action_mail_acct'
  - SLES-12-020050 'postfix_client_configure_mail_alias'
  - SLES-12-020060 'auditd_data_disk_full_action'
  - SLES-12-030260 'sshd_enable_x11_forwarding'

#### Rationale:

- Make sure the SLES-12 STIGs are properly check and remediated.

### CODE REVIEW

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by carlosmmatos** [comment]
LGTM

**Pull request merged**
