### PR TITLE
Bump version for 0.1.71

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Bump version for 0.1.71

#### Rationale:
Prepare for the next release.

### CODE REVIEW

**Review by jan-cerny — APPROVED** [review]
The CI failure in testing farm cs9 is really unrelated to the contents of this PR:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to download packages: gnutls-dane-3.7.6-23.el9.x86_64: Cannot download, all mirrors were already tried without success", "results": []}
```

**Review by marcusburghardt — APPROVED** [review]

**Comment by marcusburghardt** [comment]
Error reported in `testing-farm:centos-stream-9-x86_64` test is not related to this PR and can be safely waived in this specific case.

**Pull request merged**
