### PR TITLE
ocp4: Add initial e2e test

### PR DESCRIPTION
**Pull request by JAORMX**
This is an initial and simple implementation of the e2e test for ocp4
compliance.

Currently the test does the following:
* Upload image if needed
* Create namespace
* Deploy compliance operator
* Create ComplianceSuite object
* Check that the ComplianceSuite finishes successfully

Subsequent testing will be done in further iterations. This will
include:

* Applying remediations
* Checking re-scanning to check that the remediations no longer appear
* Doing smoke-test to verify that cluster is still working

You can run the e2e test by doing the following:

```
export PROFILE=moderate
make -f tests/ocp4e2e/Makefile e2e
```

Note that this also updates the compliance-operator version to be
installed to the latest one in the manifest. This helps the installation
go faster (no need to update in the cluster).

### CODE REVIEW

**Comment by JAORMX** [comment]
@jhrozek @mrogers950 could you review this?

**Comment by jhrozek** [comment]
So running the tests fails for me:
```
********
Your image is available at: image-registry.openshift-image-registry.svc:5000/openshift-compliance/openscap-ocp4-ds:latest
Content image built and available through: image-registry.openshift-image-registry.svc:5000/openshift-compliance/openscap-ocp4-ds:latest
pushd /home/jhrozek/devel/compliance-as-code-content/tests/ocp4e2e && \
go test -v -timeout 120m . -profile="moderate" -content-image="image-registry.openshift-image-registry.svc:5000/openshift-compliance/openscap-ocp4-ds:latest"
~/devel/compliance-as-code-content/tests/ocp4e2e ~/devel/compliance-as-code-content
go: downloading github.com/openshift/compliance-operator v0.1.5
# ocp4e2e
./helpers.go:133:3: Fatalf call has error-wrapping directive %w
./helpers.go:136:3: Fatalf call has error-wrapping directive %w
./helpers.go:139:3: Fatalf call has error-wrapping directive %w
./helpers.go:142:3: Fatalf call has error-wrapping directive %w
./helpers.go:151:3: Fatalf call has error-wrapping directive %w
./helpers.go:195:3: Fatalf call has error-wrapping directive %w
./helpers.go:200:3: Fatalf call has error-wrapping directive %w
FAIL    ocp4e2e [build failed]
FAIL
make: *** [tests/ocp4e2e/Makefile:14: e2e] Error 2
```
which is weird, I'm running go 1.14 which already should support the error-wrapping directive. Do you know what's up?

**Comment by JAORMX** [comment]
@jhrozek updated it to simply use %s

**Comment by JAORMX** [comment]
@mrogers950 if you're cool with this, you or @jhrozek can click the "Merge" button :slightly_smiling_face:

**Comment by jhrozek** [comment]
> @mrogers950 if you're cool with this, you or @jhrozek can click the "Merge" button slightly_smiling_face

Looks like I don't have the merge privileges. So feel free to merge yourself. @shawndwells I know you sent some team invitations, but when I tried to accept it the link didn't work. Could you re-send please?

**Pull request merged**
