### PR TITLE
Make Automatus Sanity Pass

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Make Automatus Sanity pass by adjusting how symlinks work in the failing test.

#### Rationale:
Make CI green.

### CODE REVIEW

**Comment by vojtapolasek** [comment]
Thank you for the fix. I understand this fixes the thing from the point of the test scenario, but shouldn't the OVAL handle symlink situation? I mean, I am fine with merging this, but do you think it is worth creating an issue against the template?

**Comment by Mab879** [comment]
> Thank you for the fix. I understand this fixes the thing from the point of the test scenario, but shouldn't the OVAL handle symlink situation? I mean, I am fine with merging this, but do you think it is worth creating an issue against the template?

The OVAL check just skips symlinks so that is why I changed to change the symlink to an actual file. We can create an issue on this template, but it will involve a lot of thinking about what we want this template to do.

**Comment by Mab879** [comment]
With the recent release of F41, that F39 check might never finish.

Should be fine to merge without it.

**Comment by vojtapolasek** [comment]
fyi: https://github.com/ComplianceAsCode/content/issues/12601

**Pull request merged**
