### PR TITLE
Set tmux config files mode

### PR DESCRIPTION
**Pull request by jan-cerny**
Ansible remediation should create the /etc/tmux.conf file with explicit
permissions 0644, otherwise the /etc/tmux.conf's mode will be affected
by umask and might be created with different permissions than 0644 but
that will cause a Permission denied error and a huge delay on each login.

A similar situation happens also when /etc/profile.d/tmux.sh mode is not
set correctly it causes that tmux is not executed after login.

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2064696

### CODE REVIEW

**Comment by jan-cerny** [comment]
QUESTION: Should we add a check for mode in OVAL checks and OCILs in rules configure_tmux_lock_after_time, configure_tmux_lock_command and configure_bashrc_exec_tmux?

**Comment by vojtapolasek** [comment]
@jan-cerny 
I think the check can go into OCIL and OVAL. Question from me: Are we going to check for exact permissions or for some range of them? Is 644 the only correct mode?

**Comment by jan-cerny** [comment]
The tmux.conf file needs to be readable by so-called "others". I have discovered by an experiment that if the tmux.conf file isn't readable by "others" then the "permission denied" issue appears. But, if it's also writable, it doesn't appear. So not only 0644  works, but also 0664, 0666, 0604 work fine. But, usually we don't want to have files in /etc/ writeable by "others". Then I propose to use 0664 in remediations. The OVAL checks can check just for the readability by others.

**Comment by jan-cerny** [comment]
I have added file mode checks (OVAL and OCIL) to rules configure_tmux_lock_command and configure_tmux_lock_after_time but I haven't add anything to rule configure_bashrc_exec_tmux, because the rule isn't about a single file but it examine all file matching regular expression `^/etc/bashrc$|^/etc/profile\.d/.*$`. What do you think?

**Comment by vojtapolasek** [comment]
@jan-cerny  changes look good. What is the reasoning for not using the permission check in configure_bashrc_exec_tmux?

**Comment by vojtapolasek** [comment]
I would leave the file mode check within the rule. I think that in this case the mode check and the file contents check is tightly coupled. I am afraid that since we can't easily enforce dependencies among rules, we might get into trouble if someone decides to taylor out the rule or something like that. But maybe you can create an extra check and include it as a extend_definition to prevent code duplication.

**Comment by vojtapolasek** [comment]
WRT  configure_bashrc_exec_tmux, I would not try to solve the permissions problem right now. We would need to somehow determine list of files in which our pattern matches and check them. I am not sure how to do that in OVAL.

**Comment by jan-cerny** [comment]
I have extract file mode check to an extend definition.

**Comment by jan-cerny** [comment]
@vojtapolasek I think that it's not a mistake - for example, the automatus tested rule chronyd_no_chronyc_network because it uses the ansible_set_config_file macro that I modified in this PR.

**Pull request merged**
