### PR TITLE
Make Rawhide CI Green

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Use registry.fedoraproject.org/fedora:rawhide for rawhide test
#### Rationale:
It should be updated a bit more often DockerHub, hopefully.

### CODE REVIEW

**Comment by Mab879** [comment]
@evgenyz Got any ideas on the CI failure that Jan mentioned above?

**Comment by jan-cerny** [comment]
I think the produced Bash and Ansible code should have the same order of operands as the platform expression. Therefore, the test should be reworked. Then, I assume it will start failing everywhere except Rawhide. It's unclear to me how to fix that. There probably is used a set or a dictionary somewhere where we should use a tuple or a list or other structure that preserves order of the elements. But I haven't found where is the place. I think it needs to be somewhere in the bundled "expressions" library.

**Comment by evgenyz** [comment]
I think that with introduction of new Python ssg/ext/boolean.py started to order elements of the expression differently. It might be not convenient, but technically these expressions are equal from boolean logic point of view.

We can either try and fix boolean.py or stop comparing expressions as strings.

**Comment by evgenyz** [comment]
> I think the produced Bash and Ansible code should have the same order of operands as the platform expression.

Since we use normalization of boolean expressions we can't really depend on order (and even particular set of elements) of the initial expression.

**Comment by evgenyz** [comment]
>  or stop comparing expressions as strings.

There is [an example](https://github.com/ComplianceAsCode/content/blob/eaf79f5e63ef7e085ddf4a0830361dcb7cb08159/tests/unit/ssg-module/test_boolean_expressions.py#L49) of how one could test *features* of the expression rather than its string representation contents.

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
