### PR TITLE
Add automatic detection of platform_package_overrides when using automatus 

### LINKED ISSUE #9869: platform_package_overrides not working with automatus
#### Description of problem:

Back before automatus, it was possible to run rule tests and for packages that were defined in platform_package_overrides would be correctly picked. Now this does not seem to be the case anymore.
For example, this commit was added to make the test pass back in the old test_suite:
https://github.com/ComplianceAsCode/content/pull/7574/commits/56cf904b75052cece57a421ba56f4409045f3ee7

Now the same test doesn't work anymore, and fails with:
```
 DEBIAN_FRONTEND=noninteractive apt install -y audit
 STDOUT: Reading package lists...
 Building dependency tree...
 Reading state information...
 
 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
 
 E: Unable to locate package audit
```

#### SCAP Security Guide Version:
master as of 2022-11-16

#### Operating System Version:
Ubuntu 20.04 LTS

#### Steps to Reproduce:

1. Try to execute a rule tests that contains a package defined in platform_package_overrides.

#### Actual Results:
Failing because it tries to install the package defined in test file instead of the one in platform_package_overrides.

#### Expected Results:
Test to correctly install the package as defined in platform_package_overrides

### PR DESCRIPTION
**Pull request by litios**
#### Description:

- Enable the use of `platform_package_overrides` product section when using automatus for rule testing.

#### Rationale:

- Before performing the install step when testing a rule, ensure that the package is not listed under `platform_package_overrides`. In case it is, replace the package to install with the one specified in `platform_package_overrides`.

- Fixes #9869

#### Review Hints:

- A conversation about implementing the solution with macros was discussed in issue #9869. I tested the proposed solution there and it works as expected. 
- Nevertheless, in PR #7295, it was discussed that it would be better to handle package overrides on the level of the test framework and I also prefer this approach to avoid adding the macro for all tests, which is why I implemented the solution based on this other approach.

### CODE REVIEW

**Comment by ggbecker** [comment]
I like this solution more than the macros solution I proposed in https://github.com/ComplianceAsCode/content/issues/9869#issuecomment-1326587238.

The only thing here is that there would be an implicit behavior for the packages defined in the metadata, meaning that what you see is not what gets used by the system, for example if you specify a package it can be replaced by some other package during the runtime if the platform package overrides contain a matching package. This solution is definitely more clean but we have to keep this in mind. Maybe some form of the documentation can also be included to at least record this information.

https://github.com/ComplianceAsCode/content/blame/master/tests/README.md#L168

**Comment by dodys** [comment]
Hey David,

thanks for handling this! 
I agree with Gabriel that it would be great to have some documentation about it.

Just a small request to improve maintenance, could you please break the first commit into two, one commit just for the test_suite code changes, and a second commit with just the test fixes? 

Thanks in advance

**Comment by jan-cerny** [comment]
I also agree with the need for documentation. Also, please fix the issues reported by Code Climate.

**Comment by litios** [comment]
Thanks everyone for the input!

I broke the first commit as suggested by @dodys, provided documentation and fixed the codeclimate issues.

**Review by dodys — APPROVED** [review]
LGTM, thanks David!
@ggbecker can you just check the tests for fedora, cs8 and cs9, they are failing but not sure if that's really an issue.

**Review by freddieRv — APPROVED** [review]

**Review by ggbecker — APPROVED** [review]
I can confirm that the failures in the Automatus checks are expected and can be waived.

Thank you very much for the contribution and addressing the feedback.

I'd say this is a highlight because the of impact on code reduction it can have.

**Pull request merged**
