### PR TITLE
Fix build of SCAP 1.2 DS

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Fix `OUTPUT` declaration of custom command build for derivative Data Streams
- Fix CMake targets so that the SCAP 1.2 is generated with appropriate version.
  - Introduced intermediary step to builo `ssg-${PRODUCT}-ds-base.xml`, from which the SCAP 1.2 and SCAP 1.3 versions are generated.

#### Rationale:
- The custom command declares that it outputs the derivative 1.2 ds and this causes the actual command that generates the derivative 1.2 not to be run.
- Follow up from https://github.com/ComplianceAsCode/content/pull/7025
- Fixes https://jenkins.complianceascode.io/job/scap-security-guide-nightly-zip/1000/console
  ```257/393 Test #258: validate-ssg-centos8-ds-1.2.xml ...........................................***Failed    0.01 sec
OpenSCAP Error: Unable to open file: '/home/jenkins/workspace/scap-security-guide-nightly-zip/build/ssg-centos8-ds-1.2.xml' [/builddir/build/BUILD/openscap-1.3.5/src/source/oscap_source.c:288]
Unrecognized document type for: /home/jenkins/workspace/scap-security-guide-nightly-zip/build/ssg-centos8-ds-1.2.xml [/builddir/build/BUILD/openscap-1.3.5/src/source/oscap_source.c:341]
```

### CODE REVIEW

**Comment by yuumasato** [comment]
There is another aspect that needs fixing too...

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Review by JAORMX — APPROVED** [review]

**Comment by yuumasato** [comment]
> @matejak @jan-cerny Do you have an idea how to fix this without complicating this with too many `if`s and custom commands?

I've added an intermediary "step" `ssg-${PRODUCT}-ds-base.xml`, this facilitates the `if` cases in CMake.

**Comment by jan-cerny** [comment]
@yuumasato Nice catch! Thank you!

**Pull request merged**
