### PR TITLE
Add Amazon Linux 2 support

### PR DESCRIPTION
**Pull request by 0intro**
#### Description:

This PR adds [Amazon Linux 2](https://aws.amazon.com/fr/amazon-linux-2) support.

This series of changes is based on the Amazon Linux 2 support, available as part of the `scap-security-guide-0.1.40-12.amzn2.0.1.1.src.rpm` package (2019-04-19), distributed as part of Amazon Linux 2.

1. The first two commits are the changes done by Amazon themselves, as part of the `scap-security-guide-0.1.40-12.amzn2.0.1.1.src.rpm` package, but rebased on the current version of ComplianceAsCode:

- `0001-Add-Amazon-Linux-2-derivative.patch`
- `0001-Add-cpe-definitions-and-oval-checks-for-AMZN2.patch`

2. The third commit is a changes to the `enable_derivatives.py` script to use the same profiles as RHEL 7, since Amazon Linux 2 is very close to RHEL 7. For example the `CIS_Amazon_Linux_2_Benchmark_v3.0.0.pdf` document is an extract subset of the `CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v3.1.1.pdf` document.

The Amazon Linux 2 support was originally based on ComplianceAsCode 0.1.40 (2018-07-25), but the changes have been rebased on the current version of ComplianceAsCode.

#### Rationale:

This PR adds supports for [Amazon Linux 2](https://aws.amazon.com/fr/amazon-linux-2), a Linux distribution, rebranded from Red Hat Linux 7, which is widely used on AWS.

The approach I chose was to implement Amazon Linux 2 as a derivative of RHEL 7, since the systems are very close. For example, the [CIS Amazon Linux 2 Benchmark](https://www.cisecurity.org/benchmark/amazon_linux) is a subset of [CIS Red Hat Linux 7 Benchmark](https://www.cisecurity.org/benchmark/red_hat_linux).

### CODE REVIEW

**Comment by jan-cerny** [comment]
I think that creating a new derivative out of RHEL 7 content would be problematic because RHEL 7 is approaching end of maintenance this week and there is a request to remove RHEL 7 content from this project soon, see https://github.com/ComplianceAsCode/content/issues/12044.

I think that a better approach would be to create a new standalone product. That would avoid the collision with the planned RHEL 7 removal.

**Comment by Mab879** [comment]
With RHEL 7 being removed this PR will need to be rewritten to make Amazon Linux 2 as a standalone product.

**Comment by jan-cerny** [comment]
ping

**Comment by Mab879** [comment]
Thanks for opening this PR. 

I believe that opening a new PR and adding Amazon Linux 2 as a standalone product would better than reusing this PR.

Please reach in the discussions here on GitHub or Gitter if have any questions.

**Pull request closed without merging**
