### PR TITLE
Sles 15 010100

### PR DESCRIPTION
**Pull request by rumch-se**
#### Description:

- _SLES-15-010100 rule_

#### Rationale:

- _The rule extends SLES-12-010060 for SLES 15 OS. Review requested _

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

### CODE REVIEW

**Review by vojtapolasek — CHANGES_REQUESTED** [review]
Hi, changes to the dconf rule look good, but why are you deleting those remaining files?

**Comment by rumch-se** [comment]
@vojtapolasek - Thank you for your feedback. I had to make a rebase. My delivery includes only 2 files  - the rule and the stig - the rest files are not part of my delivery. They were proposed by git during the rebase. This was the main reason to delete them - trying to resolve the conflict.

**Comment by vojtapolasek** [comment]
Hello, please fix your PR so that those files are not deleted. Thank you.

**Comment by rumch-se** [comment]
@vojtapolasek - I have created a commit in which I have included the two files requested by you. The commit is https://github.com/ComplianceAsCode/content/pull/7071/commits/82cda0ad048e55259e0f3294a4152951f2ef3b74

**Comment by rumch-se** [comment]
@vojtapolasek - Hello. I have done rebase - for the 2nd time - but the message needs-rebase still exist. I will need your advice/help. I am thinking to close this pull request and to create a new branch/pull request for the same rule - because the change is minor - practically only 2 files need changes.

**Comment by vojtapolasek** [comment]
Well, there was a big change - we moved products to a separate directory to clean the root directory of the project.
https://github.com/ComplianceAsCode/content/pull/7018
So just one more rebase should fix it hopefully.

**Comment by cipherboy** [comment]
@rumch-se I think you need to update your fork's `master` branch to align with upstream's `master` branch. You could probably do a `git fetch --all` and assuming this git origin is named `upstream` you could do a `git rebase upstream/master`.

**Comment by rumch-se** [comment]
@cipherboy thank you for your proposal. I have done what you proposed. Usually when rebase is necessary I follow this article https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request. Unfortunately - no result. My fork was created two months ago. I see 3 options - to create my fork again, to create a new branch/pull request or to find conflicts in the stig.profile. I don't know how to find the conflicts. Any advice will be welcomed.

**Comment by cipherboy** [comment]
@rumch-se It is correct to do:

```
$ git fetch --all
$ git rebase -i upstream/master
```

---

Note that what is suggested in the article is wrong for this purpose:

```
$ git rebase -i HEAD~n
```

Will rebase the current branch off of n commits from HEAD: this is a rebase to re-organize commits and _not_ to rebase it on top of new changes from upstream.

The second approach is also invalid:

```
$ git merge-base fix-typo upstream/master
8312cb606f9a4b2beb14d05458f6f78a9cd18f1a
$ git rebase -i 8312cb606f9a4b2beb14d05458f6f78a9cd18f1a
> noop
```

This fails because `upstream/master` and the original point in time that `master` was at have diverged and `merge-base` doesn't identify that. (It works on branches that correspond to where `upstream/master` currently are). So this is another way of doing the above, just if you don't know how many commits you have from your branch (usually easy to find, the last upstream commit is almost always a merge commit and usually we don't introduce merge commits into feature branches).

---

What we're trying to accomplish here is moving your branch as if it (the single commit in it) was proposed on top of a later `upstream/master` branch rather than the earlier point in time it was actually done. We need to base the existing branch's commits on top of the _updated_ `upstream/master` contents. We're not trying to restructure existing commits. Thus we need to rebase off of the _new_ position (`upstream/master` after a fetch), not the existing position (`HEAD~n` in various forms)  :-)


Anyhow, HTH and let me know if the explanation was more confusing than helpful :D

**Comment by rumch-se** [comment]
@cipherboy - Hello and thank you for your advice. I have done the rebase.

**Comment by vojtapolasek** [comment]
Hello, I am sorry I haven't responded. Thank you @cipherboy  for help with rebase, this can get complicated sometimes. Merging.

**Review by vojtapolasek — APPROVED** [review]

**Comment by vojtapolasek** [comment]
@openscap-ci test this please

**Comment by vojtapolasek** [comment]
@openscap-ci retest this please

**Pull request merged**
