### PR TITLE
Fix ansible remediation for configure_gnutls_tls_crypto_policy

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- make tests applicable for rhel9 as well
- rewrite the remediation

#### Rationale:

The remediation did not apply changes if there was no line which would match regexp.

### CODE REVIEW

**Comment by vojtapolasek** [comment]
I believe the failing test is due to problem with the container. Also cryptopolicies are not part of SLE AFAIK.

**Review by yuumasato — CHANGES_REQUESTED** [review]
> The remediation did not apply changes if there was no line which would match regexp.

The reason the regex does not match is because the syntax of `/etc/crypto-policies/back-ends/gnutls.config` changed significantly in RHEL9, it has the format an ini file now.

The rule should probably be re-evaluated, whether it makes sense for RHEL9, and if the customization to the gnutls TLS crypto policy still make sense.

**Comment by yuumasato** [comment]
I see that this rule is only selected on STIG profiles.
CC @ggbecker and @Mab879 for awareness.

**Comment by vojtapolasek** [comment]
The format of gnutls configuration for rhel9 has changed, it needs a new rule probably. It will be addressed in a different PR.

**Pull request closed without merging**
