### PR TITLE
CIS/1.2: Add some missing e2e tests

### PR DESCRIPTION
**Pull request by JAORMX**
The checks are correct, they're just missing e2e tests.

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
lgtm

**Comment by jhrozek** [comment]
let me just kick the tests so that we get a green run

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now bae6f7c4277ae47248873e9c731d02495a80ec86

**Comment by JAORMX** [comment]
@jhrozek Added a couple of extra e2e test files

**Review by jhrozek — APPROVED** [review]

**Comment by jhrozek** [comment]
Since the github PR tests passed, I'm just going to straight up merge the PR.

**Pull request merged**
