### PR TITLE
SSGTS various test scenarios metadata updates

### PR DESCRIPTION
**Pull request by matusmarhefka**
Update test scenarios metadata, see commit messages for reasoning.

### CODE REVIEW

**Comment by matejak** [comment]
LGTM, the situation with rekey limits is really confusing. In this case a hypothetical `value: 1G` metadata would decouple the test scenarios from products and profiles.

**Comment by mildas** [comment]
I've run tests for those rules at rhel7:
Before
```
$ python3 test_suite.py rule --libvirt qemu:///system test-suite-rhel7 --datastream ../build/
ssg-rhel7-ds.xml sshd_rekey_limit sshd_use_approved_ciphers sysctl_net_ipv4_conf_default_secure_redirects              
INFO - xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_secure_redirects
INFO - Script line_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK                        
INFO - Script comment.fail.sh using profile xccdf_org.ssgproject.content_profile_C2S OK                                
INFO - Script comment.fail.sh using profile xccdf_org.ssgproject.content_profile_cui OK                                
INFO - Script wrong_value.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK                           
INFO - Script correct_value.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK                         
INFO - xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers
INFO - Script stig_correct_value_full.pass.sh using profile xccdf_org.ssgproject.content_profile_stig OK               
INFO - Script correct_scrambled.pass.sh using profile xccdf_org.ssgproject.content_profile_C2S OK                      
INFO - Script line_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_C2S OK                         
INFO - Script correct_value_full.pass.sh using profile xccdf_org.ssgproject.content_profile_C2S OK
INFO - Script comment.fail.sh using profile xccdf_org.ssgproject.content_profile_C2S OK                                
INFO - Script stig_comment.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script stig_line_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK                   
INFO - Script stig_correct_scrambled.pass.sh using profile xccdf_org.ssgproject.content_profile_stig OK                
INFO - Script wrong_value.fail.sh using profile xccdf_org.ssgproject.content_profile_C2S OK
INFO - Script correct_reduced_list.pass.sh using profile xccdf_org.ssgproject.content_profile_C2S OK                   
INFO - Script correct_value.pass.sh using profile xccdf_org.ssgproject.content_profile_C2S OK
INFO - Script stig_wrong_value.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script stig_correct_reduced_list.pass.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - xccdf_org.ssgproject.content_rule_sshd_rekey_limit  
INFO - Script bad_time.fail.sh using profile (all) OK      
INFO - Script no_line.fail.sh using profile (all) OK
INFO - Script bad_size.fail.sh using profile (all) OK
INFO - Script ok.pass.sh using profile (all) OK
ERROR - Script ospp_ok.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_sshd_rekey_limit has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_rekey_limit'.
```

After
```
$ python3 test_suite.py rule --libvirt qemu:///system test-suite-rhel7 --datastream ../build/ssg-rhel7-ds.xml sshd_rekey_limit sshd_use_approved_ciphers sysctl_net_ipv4_conf_default_secure_redirects           
INFO - xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_secure_redirects
INFO - Script line_not_there.fail.sh using profile (all) OK
INFO - Script comment.fail.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers
INFO - Script stig_correct_value_full.pass.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script correct_scrambled.pass.sh using profile (all) OK
INFO - Script line_not_there.fail.sh using profile (all) OK
INFO - Script correct_value_full.pass.sh using profile (all) OK
INFO - Script comment.fail.sh using profile (all) OK
INFO - Script stig_comment.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script stig_line_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script stig_correct_scrambled.pass.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script correct_reduced_list.pass.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script stig_wrong_value.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script stig_correct_reduced_list.pass.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - xccdf_org.ssgproject.content_rule_sshd_rekey_limit
WARNING - Script rhel8_ok.pass.sh is not applicable on given platform
INFO - Script bad_time.fail.sh using profile (all) OK
INFO - Script rhel7.ok.pass.sh using profile (all) OK
INFO - Script no_line.fail.sh using profile (all) OK
INFO - Script bad_size.fail.sh using profile (all) OK
```

LGTM. Tests are using `all` profile and there are no more duplicates (see `comment.fail.sh` test scenario for `sysctl_net_ipv4_conf_default_secure_redirects`). I will post rhel8 results as soon as I will have them.

**Review by mildas — APPROVED** [review]
RHEL8 before
```
$ python3 test_suite.py rule --libvirt qemu:///system test-suite-rhel8 --datastream ../build/
ssg-rhel8-ds.xml sshd_rekey_limit sshd_use_approved_ciphers sysctl_net_ipv4_conf_default_secure_redirects
INFO - xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_secure_redirects                                 
INFO - Script line_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK                        
INFO - Script comment.fail.sh using profile xccdf_org.ssgproject.content_profile_cui OK                                
INFO - Script wrong_value.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK                           
INFO - Script correct_value.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK                         
INFO - xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers                                                     
ERROR - Script stig_correct_value_full.pass.sh using profile xccdf_org.ssgproject.content_profile_stig found issue:    
ERROR - Rule xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.                
WARNING - Script correct_scrambled.pass.sh - profile xccdf_org.ssgproject.content_profile_C2S not found in datastream  
WARNING - Script line_not_there.fail.sh - profile xccdf_org.ssgproject.content_profile_C2S not found in datastream
WARNING - Script correct_value_full.pass.sh - profile xccdf_org.ssgproject.content_profile_C2S not found in datastream 
WARNING - Script comment.fail.sh - profile xccdf_org.ssgproject.content_profile_C2S not found in datastream
ERROR - Script stig_comment.fail.sh using profile xccdf_org.ssgproject.content_profile_stig found issue:               
ERROR - Rule xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
ERROR - Script stig_line_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_stig found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
ERROR - Script stig_correct_scrambled.pass.sh using profile xccdf_org.ssgproject.content_profile_stig found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
WARNING - Script wrong_value.fail.sh - profile xccdf_org.ssgproject.content_profile_C2S not found in datastream
WARNING - Script correct_reduced_list.pass.sh - profile xccdf_org.ssgproject.content_profile_C2S not found in datastream
WARNING - Script correct_value.pass.sh - profile xccdf_org.ssgproject.content_profile_C2S not found in datastream
ERROR - Script stig_wrong_value.fail.sh using profile xccdf_org.ssgproject.content_profile_stig found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
ERROR - Script stig_correct_reduced_list.pass.sh using profile xccdf_org.ssgproject.content_profile_stig found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
INFO - xccdf_org.ssgproject.content_rule_sshd_rekey_limit
INFO - Script bad_time.fail.sh using profile (all) OK
INFO - Script no_line.fail.sh using profile (all) OK
INFO - Script bad_size.fail.sh using profile (all) OK
INFO - Script ok.pass.sh using profile (all) OK
INFO - Script ospp_ok.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
```

After
```
$ python3 test_suite.py rule --libvirt qemu:///system test-suite-rhel8 --datastream ../build/ssg-rhel8-ds.xml sshd_rekey_limit sshd_use_approved_ciphers sysctl_net_ipv4_conf_default_secure_redirects
INFO - xccdf_org.ssgproject.content_rule_sysctl_net_ipv4_conf_default_secure_redirects
INFO - Script line_not_there.fail.sh using profile (all) OK
INFO - Script comment.fail.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers
WARNING - Script stig_correct_value_full.pass.sh is not applicable on given platform
WARNING - Script stig_comment.fail.sh is not applicable on given platform
WARNING - Script stig_line_not_there.fail.sh is not applicable on given platform
WARNING - Script stig_correct_scrambled.pass.sh is not applicable on given platform
WARNING - Script stig_wrong_value.fail.sh is not applicable on given platform
WARNING - Script stig_correct_reduced_list.pass.sh is not applicable on given platform
INFO - Script correct_scrambled.pass.sh using profile (all) OK
INFO - Script line_not_there.fail.sh using profile (all) OK
WARNING - No remediation is available for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
INFO - Script correct_value_full.pass.sh using profile (all) OK
INFO - Script comment.fail.sh using profile (all) OK
WARNING - No remediation is available for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
INFO - Script wrong_value.fail.sh using profile (all) OK
WARNING - No remediation is available for rule 'xccdf_org.ssgproject.content_rule_sshd_use_approved_ciphers'.
INFO - Script correct_reduced_list.pass.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_sshd_rekey_limit
WARNING - Script rhel7.ok.pass.sh is not applicable on given platform
INFO - Script bad_time.fail.sh using profile (all) OK
INFO - Script no_line.fail.sh using profile (all) OK
INFO - Script rhel8_ok.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script bad_size.fail.sh using profile (all) OK
```

No more errors with STIG profile. Warnings that no remediation is available are caused that the rule remediation is not included in rhel8 ds (remediation platform includes wrlinux, rhel7, and ol7).

**Comment by matejak** [comment]
FTR, `sysctl_net_ipv6_conf_all_accept_source_route` `sysctl_net_ipv4_conf_default_secure_redirects` and `sysctl_net_ipv4_conf_all_secure_redirects` rules are the only sysctl rules that have tests are parametrized - a sysctl rule is parametrized if the rule defines `sysctlval` for the template.

Therefore, other sysctl rules than those ones don't need profile metadata for sure.

**Pull request merged**
