### PR TITLE
Fix audit_rules_privileged_commands_kmod rule in RHEL7

### LINKED ISSUE #9434: Rule audit_rules_privileged_commands_kmod fails after remediation and reboot
#### Description of problem:
In the machine-hardening STIG test, rule xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod fails after remediation and reboot.

#### SCAP Security Guide Version:
current upstream as of 2022-08-29 as of HEAD https://github.com/ComplianceAsCode/content/commit/2bcaad252bfc53f65ee54b51f994338fe6359055

#### Operating System Version:
RHEL 7.9

#### Steps to Reproduce:

1. oscap xccdf eval --progress --remediate --profile xccdf_org.ssgproject.content_profile_stig --report /stig_remediate_report.html ssg-rhel7-ds.xml
2. reboot
3. oscap xccdf eval --progress --profile xccdf_org.ssgproject.content_profile_stig --results stig-xccdf-results.xml --report stig.html ssg-rhel7-ds.xml

#### Actual Results:
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod - fail 

#### Expected Results:
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod - pass

#### Additional Information/Debugging Steps:
This issue can be related to https://github.com/ComplianceAsCode/content/issues/9426 which is about the same rule being misaligned with DISA.

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:
- Fix audit_rules_privileged_commands_kmod rule in RHEL7.
  - Address minor issues in the rule and similar templates, for example the
\w+ doesn't accept the hyphen character which could be a problem when
the key is "module-change" for example, with the \S+ it should correctly
match the whole line. A couple of tests scenario were added for this
rule as well.

#### Rationale:

- Fixes #9434

### CODE REVIEW

**Comment by jan-cerny** [comment]
@ggbecker The changes look good to me.

But, I have noticed some weird error during the Ansible remediation on RHEL7. This causes the AutoMatus tests to fail when the `--remediate-using ansible` option is used. But it doesn't happen on RHEL 9. Could you take a look at it when you are in it?

```
[jcerny@thinkpad scap-security-guide{pr/9477}]$ python3 tests/automatus.py rule --remediate-using ansible --libvirt qemu:///system ssgts_rhel7 audit_rules_privileged_commands_kmod
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2022-09-06-1028/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
ERROR - Ansible playbook remediation run has exited with return code 2 instead of expected 0
ERROR - The remediation failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands_kmod'.
```

the logs in audit_rules_privileged_commands_kmod-wrong_value.fail.sh-remediation.verbose.log contain this:

```
 23 TASK [Restart auditd.                                                                                                  service] **********************************************************************************************************    *******************************************************************************************************
 24 fatal: [192.168.122.160]: FAILED! => {"changed": false, "msg": "Unable to restart service auditd.service: Failed       to restart auditd.service: Operation refused, unit auditd.service may be requested by dependency only (it is           configured to refuse manual start/stop).\nSee system logs and 'systemctl status auditd.service' for details.\n"}
```

**Comment by vojtapolasek** [comment]
Agree with @jan-cerny  . I am actually looking into the same thing. The problem is the task which restarts Audit. it won't work:
https://access.redhat.com/solutions/2664811
I suggest removing this task - we do not restart Audit in any remediations.

**Comment by jan-cerny** [comment]
> I suggest removing this task - we do not restart Audit in any remediations.

The restart is probably based on this text in fixtext:

The audit daemon must be restarted for the changes to take effect.

**Comment by ggbecker** [comment]
I've updated the PR with a different approach to reload the audit service which was being used on a different place as well.

[35b70d1](https://github.com/ComplianceAsCode/content/pull/9477/commits/35b70d15764bed1e050b8fac77bf0c659cdb64ba)

**Review by jan-cerny — APPROVED** [review]
It has fixed the problems with running test scenarios on RHEL 7 now and it fixed also the RHEL 9.

**Pull request merged**
