### PR TITLE
Added a new SLE 12/15's rule package_rcpbind_removed

### PR DESCRIPTION
**Pull request by rumch-se**
#### Description:

- _A new rule in addition to the existing rule service_rpcbind_disabled_

#### Rationale:

- This new rule covers CIS's requirement 2.2.8 Ensure rpcbind is not installed or the rpcbind services are masked
(Automated) 

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

### CODE REVIEW

**Review by marcusburghardt — APPROVED** [review]
Thanks

**Comment by Mab879** [comment]
@rumch-se Can you please rebase this PR?

**Review by Mab879 — APPROVED** [review]

**Comment by marcusburghardt** [comment]
@rumch-se and @teacup-on-rockingchair , thanks to @dodys , a thread was started on [Gitter](https://gitter.im/Compliance-As-Code-The/conten) about the package name.
For RHEL and Ubuntu systems, the package is called `rpcbind`. We believe SUSE too.

Could you confirm if the correct package name in SUSE is indeed `rcpbind`, please? Or should it be `rpcbind`?

**Comment by rumch-se** [comment]
Hello @marcusburghardt 
The correct name of the package for SUSE is rpcbind.
In CIS there is a rule for example
"2.2.8 Ensure rpcbind is not installed or the rpcbind services are masked (Automated)"
Have a nice day
Rumen

**Comment by marcusburghardt** [comment]
Ok, so we should rename the rule and its respective content. Thanks @rumch-se .

**Comment by rumch-se** [comment]
Hello @marcusburghardt 
I have created a new PR https://github.com/ComplianceAsCode/content/pull/10054 which corrects this typo error.

Have a nice day
Rumen

**Comment by marcusburghardt** [comment]
> Hello @marcusburghardt I have created a new PR #10054 which corrects this typo error.
> 
> Have a nice day Rumen

Awesome. Thanks Rumen.

**Pull request merged**
