### PR TITLE
2 SLES-15/12 CCE codes added to the rule sshd_set_max_sessions

### PR DESCRIPTION
**Pull request by rumch-se**
#### Description:

- _Two CCE SLES-15/12 codes were added to 'Set SSH MaxSessions limit'  _

#### Rationale:

- The rule will be used in new profile(s)

### CODE REVIEW

**Comment by ggbecker** [comment]
CCEs have been assigned to this rule already on a different PR, you may close and return these CCEs to your pool of CCEs.

**Comment by ggbecker** [comment]
We have duplicated CCE assigned: 

https://github.com/ComplianceAsCode/content/blob/f2ec728ebe856f92c703719ed63818436256ec9e/linux_os/guide/services/cron_and_at/service_cron_enabled/rule.yml#L18

https://github.com/ComplianceAsCode/content/blob/f2ec728ebe856f92c703719ed63818436256ec9e/linux_os/guide/services/cron_and_at/file_permissions_crontab/rule.yml#L21

**Comment by ggbecker** [comment]
It's probably ok to have a bigger pull request when assigning CCEs, it would prevent the problem of duplicated CCE. If the contains only CCE assignments, it should be easy to review.

**Comment by rumch-se** [comment]
Hello @ggbecker
Will be possible to change the status of PR 9615 (not to be approved) - because I would like to change the CCE number in it? 
Thank you in advance 
Rumen

**Comment by ggbecker** [comment]
> Hello @ggbecker Will be possible to change the status of PR 9615 (not to be approved) - because I would like to change the CCE number in it? Thank you in advance Rumen

I'm not sure if I understood it correctly, but I have updated the PR with the duplicated CCE and it is already merged.
https://github.com/ComplianceAsCode/content/pull/9622

Regarding this PR, I believe we can close it since you already added the CCE for these rules in a different PR. Unless you want to change them, then you need to resolve the conflicts first.

**Comment by ggbecker** [comment]
Closing as the desired changes were done on a different pull request

**Pull request closed without merging**
