### PR TITLE
compare_ds.py: Identify new and missing rules while comparing content

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Identify when a rule is removed from the content and print a message about it.
- Identify when a rule is added to the content and generate a diff for the rule.

#### Rationale:

- It is important to track added and removed rules in the content.
- Generating a diff for the added rule facilitates review of the new content.

### CODE REVIEW

**Comment by yuumasato** [comment]
I don't know what is going on with the CI, it is complaining that two rules have the same CCE, but they have completely unrelated CCEs.
```
 44/164 Test  #44: unique-cces .........................................................***Failed    0.37 sec

cce CCE-91667-6 is included in files: 
 - linux_os/guide/services/cron_and_at/file_permissions_crontab/rule.yml
 - linux_os/guide/services/cron_and_at/service_cron_enabled/rule.yml
```
Does anybody from @ComplianceAsCode/red-hatters have any idea what is going on?

**Comment by yuumasato** [comment]
I think we can waive the Code Climtae findings.

**Review by jan-cerny — COMMENTED** [review]
The produced diff is nice!

**Comment by ggbecker** [comment]
@jan-cerny I've tried to address the feedback proposed by you, hopefully it hasn't gone sideways.

**Review by jan-cerny — APPROVED** [review]
I rerun the tests on the DISA manual content using shared/references/disa-stig-rhel7-v3r8-xccdf-manual.xml and it works fine.

The only remaining things are the codeclimate warnings but:
- the code duplication is a false positive, the code would be less readable if we would try to deduplicate it
- the indentation errors are caused by the wrong configuration and will disappear when tested with current upstream config (with merged https://github.com/ComplianceAsCode/content/pull/9653)
- the excess newline is a very minor problem

So I'm waiving them.

**Comment by yuumasato** [comment]
Thanks @jan-cerny and @ggbecker

**Pull request merged**
