### PR TITLE
Set hostname as computer node name in audit logs.

### PR DESCRIPTION
**Pull request by adelton**
#### Description:

- Set hostname as computer node name in audit logs.

#### Rationale:

- If option name_format is left at its default value of none, audit events from different computers may be hard to distinguish.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@adelton The patch looks good to me, but please resolve the conflicting files.

**Comment by adelton** [comment]
Please start with https://github.com/ComplianceAsCode/content/pull/4695 -- that one has already been rebased, and since the other pull requests conflict with each other, we really need to do it in the original order. I'll rebase once https://github.com/ComplianceAsCode/content/pull/4695 is in.

**Comment by jan-cerny** [comment]
@adelton OK, I'll review #4695 first.

**Comment by adelton** [comment]
Thanks. Rebased on master -> 59c9e7e7bb8872bf644e1deba1e28a81522a5f28.

**Pull request merged**
