### PR TITLE
edit rhel6 oval for gconf_gnome_screen_locking_keybindings

### PR DESCRIPTION
**Pull request by cyarbrough76**
#### Description:

- _Change entry name from screen to screensaver per STIG req_

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule gconf_gnome_screen_locking_keybindings:
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product rhel6
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel6-ds.xml gconf_gnome_screen_locking_keybindings

**Comment by redhatrises** [comment]
Great catch! Thanks. This is a typo if anything else. Please note that there are 2 instances of "screen" that need to be updated to "screensaver".

**Comment by mildas** [comment]
**Changes identified:**
Rule gconf_gnome_screen_locking_keybindings:
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product rhel6
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel6-ds.xml gconf_gnome_screen_locking_keybindings

**Comment by vojtapolasek** [comment]
Thank you for this catch. I changed the second occurence and merging it.

**Pull request merged**
