### PR TITLE
Added conditionals to mount options

### PR DESCRIPTION
**Pull request by hhenkel**
#### Description:
The conditionals are required as the device names could be empty and the subsequent task then should be skipped. 

I hope those are the correct files to patch...

#### Rationale:

- See issue #3330

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
@hhenkel Most likely yes, you can run `ctest -j 2 -R ansible -E linkchecker --output-on-failure` locally, it should perform the same set of checks with the same result on your machine.

**Comment by dahaic** [comment]
@hhenkel by clicking on `details` and `console output` on the jenkins, you'll see the output - there are syntax errors in generated C2S ansible role.

**Comment by hhenkel** [comment]
@dahaic Thanks for the info - I already looked at it. I'm currently trying to get the stuff to build on a local machine so I can see what actually is broken.

**Comment by mpreisler** [comment]
I think using block is fine, we should probably do it more. But have the tags for the whole block instead for items inside it.

**Comment by hhenkel** [comment]
@mpreisler Do you mind to trigger the ci stuff once again? I got a local env working now and will look into issues next week.

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
retest this please

**Comment by matejak** [comment]
test this please

**Comment by yuumasato** [comment]
This looks good to me.

The tests on rhel6 and rhel7 nodes are failing, but they should be already fixed by #3368 and #3398.
@hhenkel Can you please rebase on top of master, so we test this works on rhel6 and rhel7?
Thanks.

**Comment by hhenkel** [comment]
@yuumasato I now did the rebase on top of master.

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
Ack, thanks.

**Pull request merged**
