### PR TITLE
Enable the fapolicyd service for OSPP.

### PR DESCRIPTION
**Pull request by adelton**
#### Description:

- Enable the fapolicyd service for OSPP.

#### Rationale:

- The fapolicyd service (File Access Policy Daemon) implements application whitelisting to decide file access rights.

### CODE REVIEW

**Comment by yuumasato** [comment]
Everything looks good.

The failure in CI is caused by absence of `group.yml` file in `linux_os/guide/services/fapolicyd/`.
You can take the [sshd](https://github.com/ComplianceAsCode/content/blob/e5075141f5c3b2a2155635c34f24727fc3619b5a/linux_os/guide/services/ssh/group.yml) as an example:

**Comment by adelton** [comment]
Added `group.yml` -> d2f756b6ab45ce3d087b5e163cdda6adb2540715.

**Comment by adelton** [comment]
Note that this should likely be merged only after https://github.com/ComplianceAsCode/content/pull/4622, so a rebase will be needed once that one is in.

**Comment by jan-cerny** [comment]
@adelton you can rebase now, #4622 has been merged

**Comment by adelton** [comment]
Rebased on master -> 4f3532729f2d3e00f66cf1d57577a1534ab9450f.

**Pull request merged**
