### PR TITLE
OCP4: Look at rendered-config-xyz when checking FIPS, consolidate two rules

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

We used to have two rules that were checking for the cluster being installed
in FIPS mode, one was checking for an MC called 99-master-fips and was
used in the NIST profiles only.

The other rule was looking for both `^[0-9]{2}-worker$` and `^[0-9]{2}-master$`
and was used in PCI-DSS only.

#### Rationale:

This is all confusing, let's consolidate on one rule that checks the
rendered configs for both master and worker pools. This allow us to use
a single rule regardless of the installation method and also support UPI
installations where the manifests can have a custom name:
    https://docs.openshift.com/container-platform/4.10/installing/install_config/installing-customizing.html

Related: rhbz#2111095

### CODE REVIEW

**Comment by jhrozek** [comment]
note: please don't merge the PR before it is confirmed by the reporter in https://bugzilla.redhat.com/show_bug.cgi?id=2111095

I /think/ it should fix their issue but I'm not 100% sure.

**Comment by jhrozek** [comment]
hmm, looks like I need to adjust the unit tests anyway. Interested in e2e tests in the meantime.

**Comment by jhrozek** [comment]
OK, the e2e tests seem to be mostly good, so I'm going to fix up the unit tests and resubmit.

**Comment by jhrozek** [comment]
@Vincent056 @mrogers950 @lbragstad PTAL, the two remaining test failures are "expected" because we don't have any bash remediations.

**Comment by Vincent056** [comment]
wouldn't this check all rendered `rendered-master-*` and `rendered-worker-*`? MCO doesn't delete the old rendered machine config

**Comment by Vincent056** [comment]
I just realized this has to be enabled during the install time, so all rendered machine configs should have it.

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
Thank you for the review!

**Pull request merged**
