### PR TITLE
Use versioned expressions for OS checks

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
Use versioned expressions with the `os_linux` CPE platforms instead of using static applicability checks. This reduces the amount of code needed.

#### Rationale:
Use `os_linux` templated platform and versioned checks in practice.

#### Review Hints:
Review the `platform` element and Bash and Ansible remediation in the built data stream for some rule changed in this PR, for example rule `xccdf_org.ssgproject.content_rule_logind_session_timeout` in `ssg-rhel9-ds.xml`.

### CODE REVIEW

**Comment by jan-cerny** [comment]
The fact that this PR is blocked doesn't prevent anyone from adding feedback.

**Comment by jan-cerny** [comment]
I have rebased this PR on the top of the latest upstream master branch.

**Comment by jan-cerny** [comment]
This PR is now unblocked. I have rebased it on the top of the latest upstream master branch.

**Comment by jan-cerny** [comment]
The fails in testing farm jobs aren't related to this PR, they are caused by https://github.com/ComplianceAsCode/content/issues/10450.

**Comment by vojtapolasek** [comment]
hello @jan-cerny, thank you for the PR. I did some basic testing:
I installed RHEL 8.8 system and I tried OVAL, Bash and Ansible. I kept changing the VERSION_ID parameter in the /etc/os-release file and observed the results.
Bash and Ansible seem to work fine. However, OVAL shows "not applicable" no matter what ID I configure there. I am afraid the OVAL part of the platform is not working correctly at all. It needs more investigation.

**Comment by jan-cerny** [comment]
Thanks for the discovery, I think that the problem is in the regex in the OVAL which didn't allow a dot. I have changed the regex, try it now.

**Review by vojtapolasek — APPROVED** [review]
Looks good now, thank you for the changes.

**Pull request merged**
