### PR TITLE
Fix Ansible linting issues [E206]

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Fix Ansible linting issues

#### Rationale:

- Fix issues described by this job: https://jenkins.complianceascode.io/job/scap-security-guide-lint-check/

### CODE REVIEW

**Comment by mildas** [comment]
**Findings:**
Rule audit_rules_time_stime:
 Ansible remediation changed.
Rule audit_rules_time_clock_settime:
 Ansible remediation changed.
Rule audit_rules_time_adjtimex:
 Ansible remediation changed.
Rule audit_rules_kernel_module_loading:
 Ansible remediation changed.
Rule audit_rules_time_settimeofday:
 Ansible remediation changed.
Macro ansible_audit_augenrules_add_syscall_rule:
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_stime.
 In Ansible remediation for audit_rules_time_clock_settime.
 In Ansible remediation for audit_rules_time_adjtimex.
Macro ansible_audit_auditctl_add_syscall_rule:
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_stime.
 In Ansible remediation for audit_rules_time_clock_settime.
 In Ansible remediation for audit_rules_time_adjtimex.

**Recommended tests to execute:**
 build_product fedora
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_stime
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_clock_settime
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_adjtimex
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_kernel_module_loading
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_settimeofday

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_time_adjtimex:
 Ansible remediation changed.
Rule audit_rules_kernel_module_loading:
 Ansible remediation changed.
Rule audit_rules_time_clock_settime:
 Ansible remediation changed.
Rule audit_rules_time_stime:
 Ansible remediation changed.
Rule audit_rules_time_settimeofday:
 Ansible remediation changed.
Macro ansible_audit_augenrules_add_syscall_rule:
 In Ansible remediation for audit_rules_time_adjtimex.
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_time_clock_settime.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_stime.
Macro ansible_audit_auditctl_add_syscall_rule:
 In Ansible remediation for audit_rules_time_adjtimex.
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_time_clock_settime.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_stime.

**Recommended tests to execute:**
 build_product fedora
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_adjtimex
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_kernel_module_loading
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_clock_settime
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_stime
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_settimeofday

**Comment by jan-cerny** [comment]
@ggbecker I still can see a lot of errors caused by missing space on line 469

**Comment by jan-cerny** [comment]
@ggbecker any plans?

**Comment by ggbecker** [comment]
> @ggbecker any plans?

I'll fix that. Thanks

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_time_adjtimex:
 Ansible remediation changed.
Rule audit_rules_networkconfig_modification:
 Ansible remediation changed.
Rule audit_rules_kernel_module_loading:
 Ansible remediation changed.
Rule audit_rules_time_clock_settime:
 Ansible remediation changed.
Rule audit_rules_time_settimeofday:
 Ansible remediation changed.
Rule audit_rules_time_stime:
 Ansible remediation changed.
Macro ansible_audit_augenrules_add_syscall_rule:
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_time_stime.
 In Ansible remediation for audit_rules_time_clock_settime.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_adjtimex.
 In Ansible remediation for audit_rules_networkconfig_modification.
Macro ansible_audit_auditctl_add_syscall_rule:
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_time_stime.
 In Ansible remediation for audit_rules_time_clock_settime.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_adjtimex.
 In Ansible remediation for audit_rules_networkconfig_modification.

**Recommended tests to execute:**
 build_product fedora
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_adjtimex
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_networkconfig_modification
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_kernel_module_loading
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_clock_settime
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_settimeofday
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_stime

**Comment by ggbecker** [comment]
@jan-cerny Fixed by force push.

**Comment by jan-cerny** [comment]
@ggbecker I'm sorry, but there is one more occurrence of it on line 412.

**Comment by ggbecker** [comment]
> @ggbecker I'm sorry, but there is one more occurrence of it on line 412.
No problem. Sorry for not catching everything before.

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_time_adjtimex:
 Ansible remediation changed.
Rule audit_rules_time_settimeofday:
 Ansible remediation changed.
Rule audit_rules_kernel_module_loading:
 Ansible remediation changed.
Rule audit_rules_time_stime:
 Ansible remediation changed.
Rule audit_rules_time_clock_settime:
 Ansible remediation changed.
Rule audit_rules_networkconfig_modification:
 Ansible remediation changed.
Macro ansible_audit_augenrules_add_syscall_rule:
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_networkconfig_modification.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_stime.
 In Ansible remediation for audit_rules_time_adjtimex.
 In Ansible remediation for audit_rules_time_clock_settime.
Macro ansible_audit_auditctl_add_syscall_rule:
 In Ansible remediation for audit_rules_time_settimeofday.
 In Ansible remediation for audit_rules_networkconfig_modification.
 In Ansible remediation for audit_rules_kernel_module_loading.
 In Ansible remediation for audit_rules_time_stime.
 In Ansible remediation for audit_rules_time_adjtimex.
 In Ansible remediation for audit_rules_time_clock_settime.

**Recommended tests to execute:**
 build_product fedora
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_adjtimex
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_settimeofday
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_kernel_module_loading
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_stime
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_time_clock_settime
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_networkconfig_modification

**Pull request merged**
