### PR TITLE
Remove CNSS REF URL

### LINKED ISSUE #11678: cnss from SSG_REF_URIS points to a broken link
#### Description of problem:
cnss from SSG_REF_URIS (https://github.com/ComplianceAsCode/content/blob/master/ssg/constants.py#L24) points to a broken link - http://www.cnss.gov/Assets/pdf/CNSSI-1253.pdf

#### SCAP Security Guide Version:
master

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Remove CNSS REF URL from the product.
#### Rationale:

* Not used
* Closes #11678

### CODE REVIEW

**Review by teacup-on-rockingchair — APPROVED** [review]
no code, no problem :+1:

**Review by marcusburghardt — APPROVED** [review]
LGTM

**Comment by marcusburghardt** [comment]
Overriding CODEOWNERS since a Oracle approver is not currently available.

**Comment by marcusburghardt** [comment]
FYI @Xeicker

**Pull request merged**
