### PR TITLE
Use full CCI and STIG identifiers

### PR DESCRIPTION
**Pull request by redhatrises**
Reduces confusion and scripting efforts around DISA CCI, STIG ID, and CCE short forms where we don't do this for any other references.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/checks.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_remediations.py.
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.
 Python abstract syntax tree change found in tests/unit/ssg-module/test_build_yaml.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by redhatrises** [comment]
This PR is now ready for review.

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/build_remediations.py.
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/constants.py.
 Python abstract syntax tree change found in tests/unit/ssg-module/test_build_yaml.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by isimluk** [comment]
LGTM.

Initially, I was not applauding to expansion of text/ids, however longer I think about this more I like it. You just lowered the bar for content contribution as authors no longer need to know details of the build system to see what a given number means! :clap:

**Pull request merged**
