### PR TITLE
change URI of CIS benchmark to general one

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- URI pointing to CIS benchmark is changed so that it points to general CIS benchmark for Red Hat Enterprise Linux

#### Rationale:

- the old URL was not working anymore. Because CIS does not allow direct access to benchmark documents, the general URI is chosen.

### CODE REVIEW

**Comment by yuumasato** [comment]
Thanks!

**Comment by redhatrises** [comment]
@yuumasato @vojtapolasek  This just now introduced a bug in the content and removed CIS reference mapping to the benchmark document itself. The reference links have to be mapped to the documents themselves and not some generic url.

**Comment by vojtapolasek** [comment]
> @yuumasato @vojtapolasek This just now introduced a bug in the content and removed CIS reference mapping to the benchmark document itself. The reference links have to be mapped to the documents themselves and not some generic url.

I understand your point. The problem is that although CIS benchmarks are available for everyone for free, you have to go through a form where you input your name, email, company, position etc. And they send you link to the benchmark through email. There is NO direct link to their benchmarks. Actually if you try to access the link for rhel7 CIS benchmark prior to this PR, you will find out that it does not work as expected. Probably CIS changed their web site since the URL was introduced. Any ideas? Maybe I missed something on CIS web site.

**Comment by yuumasato** [comment]
> The reference links have to be mapped to the documents themselves and not some generic url.

@redhatrises I'm happy to update the reference links if you have suggestions.

**Pull request merged**
