### PR TITLE
Include product property in profile class

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

All profiles have a product and having this property defined in profile object is very helpful to collect and classify stats from profiles.

#### Rationale:

Makes it easier to classify stats from profiles.

### CODE REVIEW

**Review by Honny1 — APPROVED** [review]
LGTM

**Review by jan-cerny — APPROVED** [review]
I have add a print statement to the ctor and I have executed most-used-rules and most-used-components subcommand.

**Comment by marcusburghardt** [comment]
This change doesn't affect the failed CI tests with CS8. They can be safely waived.

**Comment by jan-cerny** [comment]
The fail of TF on CS 8 isn't caused by this PR but is caused by the CS 8 sunset.

**Pull request merged**
