### PR TITLE
add rule checking if world writable directories are owned by root

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- add rule, check, remediations, tests

#### Rationale:

anssi effort

### CODE REVIEW

**Comment by redhatrises** [comment]
LGTM

**Comment by ggbecker** [comment]
Why not to select in the https://github.com/ComplianceAsCode/content/blob/master/controls/anssi.yml already.

Also I was taking a looking at the requirement and I had the impression that these permissions should apply to the directories that have the sticky bit set. Is that the case here with this new rule?

**Comment by vojtapolasek** [comment]
I plan to add all rules pertaining to R40 into the policy file in a separate PR. I don't think that this rule is related to sticky bit situation, I created this rule based on 6.16 from the policy.

**Comment by ggbecker** [comment]
> I plan to add all rules pertaining to R40 into the policy file in a separate PR. I don't think that this rule is related to sticky bit situation, I created this rule based on 6.16 from the policy.

You're right, I re-read the requirement and it's clear that directories that are world-writable should be owned by root, despite if sticky bit is set or not.

**Review by ggbecker — APPROVED** [review]

**Pull request merged**
