### PR TITLE
Update SRG-APP-000014-CTR-000040 for OCP4 STIG

### PR DESCRIPTION
**Pull request by DhritiShikhar**
#### Description:

- No automated check -> marked the rule as manual
- Added a check and fixtext.
- The previously linked rule was only tangentially related, so it's been
moved to related_rules.

#### Rationale:

- OCP4 STIG content

### CODE REVIEW

**Review by jhrozek — COMMENTED** [review]
one nit about the line splits. Also would you mind rebasing atop origin/master to get rid of the merge commit? Since all commits are touching the same file and the changes don't seem to be logically separate, would you mind squashing the two commits that touch the control file?

**Comment by DhritiShikhar** [comment]
> one nit about the line splits. Also would you mind rebasing atop origin/master to get rid of the merge commit? Since all commits are touching the same file and the changes don't seem to be logically separate, would you mind squashing the two commits that touch the control file?

Squashed all commits in one.

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
