### PR TITLE
Add ANSSI BP28 Profiles

### PR DESCRIPTION
**Pull request by redhatrises**
#### Description:

- Add new ANSSI BP28 profiles

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Profile anssi_bp28_enhanced on rhel8:
 Newly added profile.
 ANSSI_BP28_ENHANCED profile extends changed ANSSI_BP28_INTERMEDIARY profile.
Profile anssi_bp28_high on rhel8:
 Newly added profile.
 ANSSI_BP28_HIGH profile extends changed ANSSI_BP28_ENHANCED profile.
Profile anssi_bp28_intermediary on rhel8:
 ANSSI_BP28_INTERMEDIARY profile extends changed ANSSI_BP28_MINIMAL profile.
 Newly added profile.
Profile anssi_bp28_minimal on rhel8:
 Newly added profile.

**Recommended tests to execute:**
 build_product rhel8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_enhanced
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_high
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_intermediary
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_minimal

**Comment by matejak** [comment]
> > I see this way of approaching the ANSSI profile unfortunate for the following reasons:
> > 
> > * The RHEL8 version of the profile differs from RHEL7 in rule selections - a couple of selinux boolean rules and one grub2 rule are different, and no reason is given. Note that although the RHEL7 profile has the NT label (pointing to the version 1.1), the latest analysis was based on the BP version 1.2, so the two profile files should be the same, maybe except crypto policies etc.
> 
> You are going to have differences. Period. And is RHEL7 delivered downstream? No. It isn't

If there is no justification why a rule got selected in a profile, then it is impossible to determine whether that selection really should be there, or it landed there by mistake. Maintenance of profiles with such selections is expensive, not to speak about updates of such profiles. This project has already seen rules falling out of a profile by mistake, so let's learn from past mistakes, and let's justify every change of the profile that is not obvious.

> > * We plan to focus on the ANSSI profile in the near future, hopefully with some assistance from ANSSI, and having two instances of the profile in a different set of files implies that extra effort has to be dispatched just to avoid copy-paste errors. Moreover, the linear form of our `.profile` files also doesn't allow for  a well-arranged discussion regarding interpretation of individual sections of the ANSSI policy.
> 
> The effort is incredibly minimal.

Your PR introduces 8th version of ANSSI to the project that is mostly a copy-paste, but not exactly a copy-paste, as outilned in the previous remark. Which means that we are looking at having 32 files that contain ANSSI definitions of the same profile. If we decide to port the profile to Fedora as well to test it closer to the upstream, then add another four files. I think that we should seriously look at how to remove this duplication that doesn't have any value in itself.

> > * References on the rule side are not up-to-date, and there is the NT/BP reference label discrepancy. I think that this demonstrates that having to track profile-related data s.a. references in rule files manually is unsustainable, as there are about 100 rules selected by the "high" flavor of ANSSI.
> 
> This isn't going to change ever. Rules are going to have be reviewed for the applicability to profiles. Rule references are always going to have to be reviewed for their applicability to the rule, profile, and what it is references. This is the security analysis part of the job.

OK, if you prefer it this way, then I guess why not. Changes in your PR introduce rules that are selected by the profile and that don't have the respective ANSSI reference. Moreover, no rule has the BP ANSSI reference, all reference the NT ANSSI.
I don't think that PRs should introduce inconsistencies, so you will probably want to fix it.

**Comment by mildas** [comment]
**Changes identified:**
Profile anssi_bp28_enhanced on rhel8:
 Newly added profile.
 ANSSI_BP28_ENHANCED profile extends changed ANSSI_BP28_INTERMEDIARY profile.
Profile anssi_bp28_high on rhel8:
 ANSSI_BP28_HIGH profile extends changed ANSSI_BP28_ENHANCED profile.
 Newly added profile.
Profile anssi_bp28_intermediary on rhel8:
 ANSSI_BP28_INTERMEDIARY profile extends changed ANSSI_BP28_MINIMAL profile.
 Newly added profile.
Profile anssi_bp28_minimal on rhel8:
 Newly added profile.

**Recommended tests to execute:**
 build_product rhel8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_high
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_enhanced
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_intermediary
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_minimal

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 Node moved within OVAL check.
 Node deleted from OVAL check.
 Deleted attribute from OVAL check.
 Text changed in OVAL check.
 The rule doesn't occur in any profile nor product.
 Text added outsite tags in OVAL check.
Profile anssi_bp28_enhanced on rhel8:
 Newly added profile.
 ANSSI_BP28_ENHANCED profile extends changed ANSSI_BP28_INTERMEDIARY profile.
Profile anssi_bp28_high on rhel8:
 ANSSI_BP28_HIGH profile extends changed ANSSI_BP28_ENHANCED profile.
 Newly added profile.
Profile anssi_bp28_intermediary on rhel8:
 ANSSI_BP28_INTERMEDIARY profile extends changed ANSSI_BP28_MINIMAL profile.
 Newly added profile.
Profile anssi_bp28_minimal on rhel8:
 Newly added profile.
Others:
 Python abstract syntax tree change found in utils/ansible_playbook_to_role.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)
 build_product rhel8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_enhanced
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_high
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_intermediary
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_minimal

**Comment by mildas** [comment]
**Changes identified:**
Profile anssi_bp28_enhanced on rhel8:
 ANSSI_BP28_ENHANCED profile extends changed ANSSI_BP28_INTERMEDIARY profile.
 Newly added profile.
Profile anssi_bp28_high on rhel8:
 Newly added profile.
 ANSSI_BP28_HIGH profile extends changed ANSSI_BP28_ENHANCED profile.
Profile anssi_bp28_intermediary on rhel8:
 Newly added profile.
 ANSSI_BP28_INTERMEDIARY profile extends changed ANSSI_BP28_MINIMAL profile.
Profile anssi_bp28_minimal on rhel8:
 Newly added profile.

**Recommended tests to execute:**
 build_product rhel8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_high
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_enhanced
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_intermediary
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml anssi_bp28_minimal

**Review by matejak — CHANGES_REQUESTED** [review]
I like the reference relabel in rule files and in the CMake setup.

I am against merging the profile for RHEL8 for reasons outlined in https://github.com/ComplianceAsCode/content/pull/6038#issuecomment-686580202, so I suggest that you split the pull request into two, as the reference-related part can be merged right away.

**Comment by redhatrises** [comment]
There is no reason to prevent merging of this profile. EMEA wants them now.

**Comment by vojtapolasek** [comment]
I don't think that merging the profile in current state is a good idea. Sure, the profile will be available in upstream, but from the PR and conversation I would see its accuracy as a bit questionable. I think that with respect to this content, reliability and accuracy should precede availability. There remain questions which were not answered. Moreover, the profile lacks proper metadata (SME, policy version...), so currently if someone finds a bug, there is no clear person to ask for clarifications.

**Comment by dahaic** [comment]
> There is no reason to prevent merging of this profile. EMEA wants them now.

Just so you know, I consider self-merging of conflicted PR unacceptable behavior in the public open source projects. If this was a project where I am the admin, you would lose the write access immediately.

Your justification that "EMEA wants them now" seems flawed. Is this really what they ask for?

Because what they got by this merge is a draft at best, and useless placeholder at worst. Definitely not a full-fledged profile users are usually expecting.
Also content that is merged against the will of project maintainers cannot be considered part of the project, with the same guarantees. So I am not really sure what you try to achieve here by this act.

**Pull request merged**
