### PR TITLE
1.2.31 add client-ca-file api server arg check for ocp4

### PR DESCRIPTION
**Pull request by dlbewley**
#### Description:

- Add test for api server arg contains proper value for client-ca-file on OCP 4

#### Rationale:

- Ensure proper value is defined for location of client CA certificate

**Note:** _Existence of file is not validated._

### CODE REVIEW

**Comment by dlbewley** [comment]
Stand by. I see that I need to update the description to reflect the new location as well.

**Comment by JAORMX** [comment]
@openscap-ci test this please

**Comment by JAORMX** [comment]
@openscap-ci test this please

**Comment by JAORMX** [comment]
@ggbecker how do I re-kick the openscap tests?

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Pull request merged**
