### PR TITLE
Fix Grub remediation

### PR DESCRIPTION
**Pull request by matejak**
make sure that update-grub is called without arguments

Fixes: #8464 

by reverting a change made by mistake in #8180

### CODE REVIEW

**Comment by yuumasato** [comment]
@dodys CC

**Review by dodys — APPROVED** [review]
lgtm

**Comment by yuumasato** [comment]
@matejak Sorry, there are conflicts after https://github.com/ComplianceAsCode/content/pull/8563 got merged.

**Review by yuumasato — APPROVED** [review]

**Comment by yuumasato** [comment]
Not sure what is wrong with the opensfhit tests, are they failing because of ` - Status: FAIL - ` or 
` {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-04-27T14:17:28Z"} ` ?

**Comment by yuumasato** [comment]
The errors seem widespread and not specifically related to this PR.

**Pull request merged**
