### PR TITLE
Update Account Home Folder Rules

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

The following now skip users with home folders defined as `/`.
* Macros 
    * `bash_restrict_permissions_home_directories`  
    * `ansible_restrict_permissions_home_directories`
* Rules
  * accounts_users_home_files_groupownership
  * accounts_users_home_files_ownership 

#### Rationale:
Ensuring the scripts complete successfully with a user doesn't a proper home folder defined.

### CODE REVIEW

**Review by jan-cerny — COMMENTED** [review]
Can we have a test scenario covering the / situation?

**Comment by Mab879** [comment]
> Can we have a test scenario covering the / situation?

I'm working on this, it's taking a bit of time to ensure I don't break other rules in the process.

**Comment by Mab879** [comment]
I have added a test scenario. Since there really isn't way to fix the finding other assigning the user a proper home folder, I have disabled the remediation.

**Review by jan-cerny — APPROVED** [review]
```
jcerny@fedora:~/work/git/scap-security-guide (pr/12465)$ python3 tests/automatus.py  rule --libvirt qemu:///system ssgts_rhel9 accounts_users_home_files_ownership
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2024-10-11-1412/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_accounts_users_home_files_ownership
INFO - Script expected_owner.pass.sh using profile (all) OK
INFO - Script home_dirs_all_absent.pass.sh using profile (all) OK
INFO - Script home_dirs_one_absent.pass.sh using profile (all) OK
INFO - Script unexpected_owner_system_id.fail.sh using profile (all) OK
INFO - Script unexpected_owner_unknown_id.fail.sh using profile (all) OK
INFO - Script warning_home_dirs_swapped_owner.pass.sh using profile (all) OK
INFO - Script interactive_users_absent.pass.sh using profile (all) OK
INFO - Script interactive_user_nologin_ignored.pass.sh using profile (all) OK
INFO - Script root_fs_home.fail.sh using profile (all) OK
jcerny@fedora:~/work/git/scap-security-guide (pr/12465)$ python3 tests/automatus.py  rule --libvirt qemu:///system ssgts_rhel9 --remediate-using ansible accounts_users_home_files_ownership
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2024-10-11-1416/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_accounts_users_home_files_ownership
INFO - Script expected_owner.pass.sh using profile (all) OK
INFO - Script home_dirs_all_absent.pass.sh using profile (all) OK
INFO - Script home_dirs_one_absent.pass.sh using profile (all) OK
INFO - Script unexpected_owner_system_id.fail.sh using profile (all) OK
INFO - Script unexpected_owner_unknown_id.fail.sh using profile (all) OK
INFO - Script warning_home_dirs_swapped_owner.pass.sh using profile (all) OK
INFO - Script interactive_users_absent.pass.sh using profile (all) OK
INFO - Script interactive_user_nologin_ignored.pass.sh using profile (all) OK
INFO - Script root_fs_home.fail.sh using profile (all) OK
jcerny@fedora:~/work/git/scap-security-guide (pr/12465)$ python3 tests/automatus.py  rule --libvirt qemu:///system ssgts_rhel9 accounts_users_home_files_groupownership
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2024-10-11-1418/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_accounts_users_home_files_groupownership
INFO - Script expected_groupowner.pass.sh using profile (all) OK
INFO - Script home_dirs_all_absent.pass.sh using profile (all) OK
INFO - Script home_dirs_one_absent.pass.sh using profile (all) OK
INFO - Script unexpected_groupowner_system_gid.fail.sh using profile (all) OK
INFO - Script unexpected_groupowner_unknown_gid.fail.sh using profile (all) OK
INFO - Script warning_home_dirs_swapped_groupowner.pass.sh using profile (all) OK
INFO - Script interactive_users_absent.pass.sh using profile (all) OK
INFO - Script interactive_user_nologin_ignored.pass.sh using profile (all) OK
INFO - Script root_fs_home.fail.sh using profile (all) OK
jcerny@fedora:~/work/git/scap-security-guide (pr/12465)$ python3 tests/automatus.py  rule --libvirt qemu:///system ssgts_rhel9 --remediate-using ansible accounts_users_home_files_groupownership
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2024-10-11-1421/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_accounts_users_home_files_groupownership
INFO - Script expected_groupowner.pass.sh using profile (all) OK
INFO - Script home_dirs_all_absent.pass.sh using profile (all) OK
INFO - Script home_dirs_one_absent.pass.sh using profile (all) OK
INFO - Script unexpected_groupowner_system_gid.fail.sh using profile (all) OK
INFO - Script unexpected_groupowner_unknown_gid.fail.sh using profile (all) OK
INFO - Script warning_home_dirs_swapped_groupowner.pass.sh using profile (all) OK
INFO - Script interactive_users_absent.pass.sh using profile (all) OK
INFO - Script interactive_user_nologin_ignored.pass.sh using profile (all) OK
INFO - Script root_fs_home.fail.sh using profile (all) OK
```

**Pull request merged**
