### PR TITLE
SSG test suite trivial fix.

### PR DESCRIPTION
**Pull request by matejak**
Fix `map_on_top` for the case when there is nothing to map.

### CODE REVIEW

**Comment by matejak** [comment]
It happens when the function argument `args_list` is an empty list.

**Comment by jan-cerny** [comment]
@matejak And in which situation args_list is an empty list?

**Comment by matejak** [comment]
It already happened, but it is quite rare to trigger this condition with the current code/data. But, more importantly, Python3.6's `map(lambda x: print(f"hello {x}"), [])` doesn't crash, it just won't print anything. Therefore, our `map_on_top` probably shouldn't crash either.

**Comment by mpreisler** [comment]
I agree with @jan-cerny , IMO we want to figure out when/why this even happens. It's obvious that the error happens when args_list is an empty list, the question is why that ever happens. We should fix the root cause, not quickfix the symptom.

**Comment by matejak** [comment]
@jan-cerny Yes, this is the most likely cause.
@mpreisler There may not be any issue that would have that root cause - in the future, we may e.g. filter scenarios that are applicable for containers. In that case, it may happen that there are no scenarios left, and it is totally legitimate. A check for argument count is therefore needed somewhere. I find the body of `map_on_top` to be the best place for that:
- let's be consistent with Python's `map`, and 
- let's check on one place instead of checking before every `map_on_top` invocation.

**Comment by jan-cerny** [comment]
@matejak But the directory has to exist to trigger it?

**Comment by jan-cerny** [comment]
But if the directory exists it fixes it perfectly for me.

**Pull request merged**
