### PR TITLE
OCP4 update CIS 5.6 Rules to CIS 5.7

### PR DESCRIPTION
**Pull request by Vincent056**
#### Description:

To fix the benchmark section number for rule in CIS 5.6 General Policies

#### Rationale:
latest CIS has moved all the rules from section 5.6 to section 5.7, this PR updates all the rules to 5.7

### CODE REVIEW

**Review by jhrozek — CHANGES_REQUESTED** [review]
we should do some more fixes related to this bug:
 - change the other rules that reference 5.6 to reference 5.7
 - in cis.profile, we have comments above those rules, those should be fixed to say 5.7 as well.
(It seems that the latest CIS release got rid of 5.6 as a whole and instead has 5.7, so the rules were all moved)

**Comment by Vincent056** [comment]
> we should do some more fixes related to this bug:
> 
> * change the other rules that reference 5.6 to reference 5.7
> * in cis.profile, we have comments above those rules, those should be fixed to say 5.7 as well.
>   (It seems that the latest CIS release got rid of 5.6 as a whole and instead has 5.7, so the rules were all moved)

I realized that at the time of making the recording, I will update all the other rules with it

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
Actually let's merge this w/o waiting on CI. The patch just changes section IDs.

**Pull request merged**
