### PR TITLE
Add mount[] platform and use it for /tmp and /var/tmp mount option rules

### LINKED ISSUE #10389: mount_option_*_tmp_* is  pass when should be not applicable on RHEL8/RHEL9
#### Description of problem:
The follow rules appear to pass now when their respective partitions do not exist.

- mount_option_var_tmp_nosuid
- mount_option_var_tmp_noexec
- mount_option_var_tmp_bind
- mount_option_tmp_nodev
- mount_option_tmp_nosuid
- mount_option_tmp_noexec

#### SCAP Security Guide Version:
e544b52

#### Operating System Version:
RHEL 8 and RHEL 9

#### Steps to Reproduce:

1. Install RHEL8/RHEL9 without at separate /tmp or /var/tmp
2. Run `oscap xccdf eval --progress --profile '(all)' --rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nodev ssg-rhel9-ds.xml`

#### Actual Results:
Rule pass

#### Expected Results:
Rule is not applicable 

#### Additional Information/Debugging Steps:
Partial regression from: 
https://bugzilla.redhat.com/show_bug.cgi?id=2032403

#10200 may be related.

### PR DESCRIPTION
**Pull request by evgenyz**
#### Description:

This is a continuation on #10295 and, at the same time, a fix for #10389.

#### Rationale:

- The name of the platform is `mount[]` instead `partition[]` because it better reflects the nature of the applicability check.
- It is a tradeoff and a temporary solution until we refactor mount and mount_option related rules.

- Fixes #10389.

#### Review Hints:

- Bash conditional now checks for `findmnt --kernel || findmnt --fstab`.
- Ansible does something. But we don't really care about the details for now, as it won't be used for offline remediation (ever?).

### CODE REVIEW

**Comment by Mab879** [comment]
Please also propose this to the stabilization branch as well.

**Review by Mab879 — APPROVED** [review]
Looks good to me, thanks!

**Comment by marcusburghardt** [comment]
Before the fix:
```
rhel8 - mount_option_tmp_nodev - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_tmp_nodev
INFO - Script fstab.fail.sh using profile (all) OK
INFO - Script separate.pass.sh using profile (all) OK
INFO - Script runtime.pass.sh using profile (all) OK

rhel8 - mount_option_tmp_noexec - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_tmp_noexec
INFO - Script fstab.fail.sh using profile (all) OK
INFO - Script separate.pass.sh using profile (all) OK
INFO - Script runtime.pass.sh using profile (all) OK

rhel8 - mount_option_tmp_nosuid - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_tmp_nosuid
INFO - Script runtime.pass.sh using profile (all) OK
INFO - Script separate.pass.sh using profile (all) OK
INFO - Script fstab.fail.sh using profile (all) OK

rhel8 - mount_option_var_tmp_nodev - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nodev
INFO - Script fstab.fail.sh using profile (all) OK
INFO - Script runtime.pass.sh using profile (all) OK
INFO - Script separate.pass.sh using profile (all) OK
INFO - Script notapplicable.pass.sh using profile (all) OK

rhel8 - mount_option_var_tmp_noexec - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_var_tmp_noexec
INFO - Script runtime.pass.sh using profile (all) OK
INFO - Script fstab.fail.sh using profile (all) OK
INFO - Script separate.pass.sh using profile (all) OK

rhel8 - mount_option_var_tmp_nosuid - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nosuid
INFO - Script separate.pass.sh using profile (all) OK
INFO - Script fstab.fail.sh using profile (all) OK
INFO - Script runtime.pass.sh using profile (all) OK
```

After the fix:
```
rhel8 - mount_option_tmp_nodev - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_tmp_nodev
WARNING - Script runtime.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_nodev evaluation resulted in notapplicable
WARNING - Script fstab.fail.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_nodev evaluation resulted in notapplicable
WARNING - Script separate.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_nodev evaluation resulted in notapplicable

rhel8 - mount_option_tmp_noexec - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_tmp_noexec
WARNING - Script runtime.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_noexec evaluation resulted in notapplicable
WARNING - Script separate.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_noexec evaluation resulted in notapplicable
WARNING - Script fstab.fail.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_noexec evaluation resulted in notapplicable

rhel8 - mount_option_tmp_nosuid - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_tmp_nosuid
WARNING - Script runtime.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_nosuid evaluation resulted in notapplicable
WARNING - Script fstab.fail.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_nosuid evaluation resulted in notapplicable
WARNING - Script separate.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_tmp_nosuid evaluation resulted in notapplicable

rhel8 - mount_option_var_tmp_nodev - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nodev
WARNING - Script fstab.fail.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nodev evaluation resulted in notapplicable
WARNING - Script runtime.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nodev evaluation resulted in notapplicable
WARNING - Script separate.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nodev evaluation resulted in notapplicable
WARNING - Script notapplicable.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nodev evaluation resulted in notapplicable

rhel8 - mount_option_var_tmp_noexec - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_var_tmp_noexec
WARNING - Script separate.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_noexec evaluation resulted in notapplicable
WARNING - Script fstab.fail.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_noexec evaluation resulted in notapplicable
WARNING - Script runtime.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_noexec evaluation resulted in notapplicable

rhel8 - mount_option_var_tmp_nosuid - bash VM
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nosuid
WARNING - Script separate.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nosuid evaluation resulted in notapplicable
WARNING - Script fstab.fail.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nosuid evaluation resulted in notapplicable
WARNING - Script runtime.pass.sh using profile (all) notapplicable
WARNING - Rule xccdf_org.ssgproject.content_rule_mount_option_var_tmp_nosuid evaluation resulted in notapplicable
```

**Review by marcusburghardt — APPROVED** [review]
LGTM

**Pull request merged**
