### PR TITLE
Update testsuite docs to show docker needs sudo

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by jan-cerny** [comment]
No, Docker backend doesn't require sudo, but Podman backend requires sudo.

**Comment by yuumasato** [comment]
if your user is part of `docker` group, you don't require sudo.

**Comment by yuumasato** [comment]
@shawndwells I'll close this, and note in #3732 that you either use `sudo` or add the user to `docker` group.

And the online editing tool didn't create a branch in your fork, we should avoid using it.

**Comment by shawndwells** [comment]
@jan-cerny wrt docker needing sudo.... it did on RHEL7 when @matejak was sitting next to me :)

@yuumasato works for me!

**Pull request closed without merging**
