### PR TITLE
Ansible ssh remediation validate

### LINKED ISSUE #3803: Ansible remediation on ssh server validation fails
#### Description of problem:

All ansible remediation using   _validate: sshd -t -f %s_  fails because full path of sshd must be specified.

#### SCAP Security Guide Version:
0.1.42

#### Operating System Version:
CentOS 7

#### Steps to Reproduce:

Run ssg-centos7-role-nist-800-171-cui.yml playbook against CentOS 7 Minimal install.

#### Actual Results:

TASK [Disable SSH Suport for User Known Hosts] *********************************
fatal: [centostemp]: FAILED! => {"changed": false, "cmd": "sshd -t -f /tmp/tmpzge553", "msg": "[Errno 2] No such file or directory", "rc": 2}

#### Expected Results:

TASK [Disable SSH Support for User Known Hosts] ********************************
changed: [centostemp] => {"backup": "", "changed": true, "msg": "line added"}

#### Addition Information/Debugging Steps:

I can make the changes and submit a pull request changing the validate line.  This would be on 19 different files.  Do these need to be separate pull requests or can they all be included in one?

Original (doesn't work):

- name: Disable SSH Access via Empty Passwords
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^PermitEmptyPasswords
    line: PermitEmptyPasswords no
    validate: sshd -t -f %s

Revised (Works):

- name: Disable SSH Access via Empty Passwords
  lineinfile:
    create: yes
    dest: /etc/ssh/sshd_config
    regexp: ^PermitEmptyPasswords
    line: PermitEmptyPasswords no
    validate: /usr/sbin/sshd -t -f %s

### PR DESCRIPTION
**Pull request by rchayes**
#### Description:

- All ansible remediation using validate: sshd -t -f %s fails because full path of sshd must be specified.

#### Rationale:

- Validate line fails because full path of sshd is not specified.  Added full path to sshd.

- Fixes #3803

### CODE REVIEW

**Comment by redhatrises** [comment]
@rchayes can you remove `763810b` from this PR please? We do not want these commits in our Master branch.

**Comment by rchayes** [comment]
Sorry about that.  I'm ok with the code but I am terrible at git.  Did that fix it?

**Comment by redhatrises** [comment]
> Sorry about that. I'm ok with the code but I am terrible at git. Did that fix it?

@rchayes I fixed it for you. Just an FYI for when you update your master branch, the following procedure is the best:

1. Add the upstream master
`
$ git remote add upstream https://github.com/ComplianceAsCode/content/
`

2. Rebase or pull against the upstream master
`
$ git pull upstream master
`

3. Create your new branch and go to town on changes
`
$ git checkout -b my_new_branch
`

**Comment by redhatrises** [comment]
LGTM. Thanks for the contribution @rchayes!

**Pull request merged**
