### PR TITLE
Remove `sshd_set_idle_timeout` tests that check wrong `sshd_set_keepalive` configuration

### PR DESCRIPTION
**Pull request by mildas**
#### Description:
`sshd_set_idle_timeout` tests cleanup, because it doesn't check `ClientAliveCountMax` (`sshd_set_keepalive` configuration) anymore.

#### Rationale:
Previously, the rule had `extend_definition`checking `sshd_set_keepalive`. But the definition was removed and now `sshd_set_keepalive` is as `requires`. The rule in `requires` is not checked during `oscap xccdf eval --rule`, see https://github.com/OpenSCAP/openscap/issues/1854#issuecomment-1090251235

### CODE REVIEW

**Comment by jan-cerny** [comment]
Should the test scenarios fail on the current master?

**Comment by mildas** [comment]
After this update, the test scenarios should not fail.
@jan-cerny which test fails? On this PR, I've run SSGTS and everything passes:
```
[mlysonek@fedora content]$ python3 tests/test_suite.py rule --libvirt qemu:///session test-suite-rhel7 --datastream build/ssg-rhel7-ds.xml --no-reports sshd_set_idle_timeout
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mlysonek/SCAP/content/logs/rule-custom-2022-04-12-1133/test_suite.log
WARNING - Script correct_value_directory.pass.sh is not applicable on given platform
WARNING - Script param_conflict_directory.fail.sh is not applicable on given platform
WARNING - Script wrong_value_directory.fail.sh is not applicable on given platform
INFO - xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script comment.fail.sh using profile (all) OK
INFO - Script line_not_there.fail.sh using profile (all) OK

[mlysonek@fedora content]$ python3 tests/test_suite.py rule --libvirt qemu:///session test-suite-rhel8 --datastream build/ssg-rhel8-ds.xml --no-reports sshd_set_idle_timeout                                                               
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mlysonek/SCAP/content/logs/rule-custom-2022-04-12-1135/test_suite.log
WARNING - Script correct_value_directory.pass.sh is not applicable on given platform
WARNING - Script param_conflict_directory.fail.sh is not applicable on given platform
WARNING - Script wrong_value_directory.fail.sh is not applicable on given platform
INFO - xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script comment.fail.sh using profile (all) OK
INFO - Script line_not_there.fail.sh using profile (all) OK

[mlysonek@fedora content]$ python3 tests/test_suite.py rule --libvirt qemu:///session test-suite-rhel9 --datastream build/ssg-rhel9-ds.xml --no-reports sshd_set_idle_timeout                                                               
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mlysonek/SCAP/content/logs/rule-custom-2022-04-12-1136/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script correct_value_directory.pass.sh using profile (all) OK
INFO - Script param_conflict_directory.fail.sh using profile (all) OK
INFO - Script wrong_value_directory.fail.sh using profile (all) OK
INFO - Script comment.fail.sh using profile (all) OK
INFO - Script line_not_there.fail.sh using profile (all) OK
```

**Comment by mildas** [comment]
Aha, I see. On master, only RHEL8 fails:
```
$ python3 tests/test_suite.py rule --libvirt qemu:///session test-suite-rhel8 --datastream build/ssg-rhel8-ds.xml --no-reports sshd_set_idle_timeout                                                               
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mlysonek/SCAP/content/logs/rule-custom-2022-04-12-1220/test_suite.log
WARNING - Script correct_value_directory.pass.sh is not applicable on given platform
WARNING - Script param_conflict_directory.fail.sh is not applicable on given platform
WARNING - Script wrong_value_directory.fail.sh is not applicable on given platform
INFO - xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
ERROR - Script comment.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout'.
ERROR - Script line_not_there.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout'.
INFO - Script other_comment.fail.sh using profile (all) OK
INFO - Script other_line_not_there.fail.sh using profile (all) OK
ERROR - Script other_wrong_value.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_sshd_set_idle_timeout'.
```
Because the `extend_definition` is excluded only in rhel8/ol8 - https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/oval/shared.xml#L36
Any idea why #8338 excluded only the 2 products? The check should be consistent across all products.

**Comment by jan-cerny** [comment]
Thanks for investigation.

> Any idea why https://github.com/ComplianceAsCode/content/pull/8338 excluded only the 2 products? The check should be consistent across all products.

No idea, probably we didn't know whether the change is relevant to other products or not.

**Comment by mildas** [comment]
> Because the extend_definition is excluded only in rhel8/ol8 - https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/ssh/ssh_server/sshd_set_idle_timeout/oval/shared.xml#L36
Any idea why https://github.com/ComplianceAsCode/content/pull/8338 excluded only the 2 products? The check should be consistent across all products.

@ggbecker @yuumasato what is your opinion on the `extend_definition` being excluded only in rhel8/ol8? I would say (at least in rhel products) this should be consistent - check it everywhere or nowhere.

**Comment by yuumasato** [comment]
> The check should be consistent across all products.

I slightly disagree, as SSHD behaviour is different across the products WRT to `ClientAliveCountMax`.

The rule is about configuring `ClientAliveInterval`, so technically the `extend_definition` to also check for `ClientAliveCountMax` should not be there. But it was added ( in https://github.com/ComplianceAsCode/content/pull/6293) to assure the intent of the rule (to ensure SSH idle session timeout), so I think it was reasonable.

But since behaviour of [ClientAliveCountMax changed in OpenSSH v8.2](https://bugzilla.mindrot.org/show_bug.cgi?id=2627) the `extend_definition` doesn't make much sense anymore. (See [sshd_set_keepalive](https://github.com/ComplianceAsCode/content/blob/6602cecc7ce21c62273010f990712f3952d1b275/linux_os/guide/services/ssh/ssh_server/sshd_set_keepalive/rule.yml#L12))

Probably products with the "old" `ClientAliveCountMax` behaviour should have the `extend_definition` while products with the "new" behaviour should no have it.
For example, RHEL-8, although it has OpenSSH 8.1 the behavior was [backported](https://pkgs.devel.redhat.com/cgit/rpms/openssh/commit/?h=rhel-8.6.0&id=9de281aa180eedfb08289619c251514d9d9ec206).

**Comment by mildas** [comment]
I've updated the `sshd_set_idle_timeout` oval check to exclude the `ClientAliveCountMax` for RHEL9, because it has OpenSSH 8.7 version.
RHEL7 has OpenSSH 7.4, so for this one I leave other test scenarios that check `ClientAliveCountMax`.

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
