### PR TITLE
Fix Audit related rules in RHEL 10

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- modify OVAL checks which decide if we use augenrules or auditctl to load rules. Point them to the new file audit-rules.service in case we are on rhel10 product
- modify test scenarios of all templates where this scenario occurs
- modify test scenarios of all rules which are in rhel10 product

#### Rationale:

In RHEL 10, there is a special Systemd service file which loads rules.
Previously, this was done through ExecStartPost directive in auditd.service.
In RHEL 10, there is a new file audit-rules.service which achieves the same but through ExecStart directive.

#### Review Hints:

1. review CI results
2. CI might not be able to test all rules so in case of failures, please retest locally through Automatus.

### CODE REVIEW

**Review by ggbecker — CHANGES_REQUESTED** [review]
There might be more places where a change is needed, for example:

https://github.com/ComplianceAsCode/content/blob/75231071aff55f00d33feb3220b152c72c72e269/linux_os/guide/auditing/auditd_configure_rules/audit_rules_suid_auid_privilege_function/ansible/shared.yml#L20

and a few occurrences in this file:

https://github.com/ComplianceAsCode/content/blob/75231071aff55f00d33feb3220b152c72c72e269/linux_os/guide/auditing/group.yml#L22

**Comment by vojtapolasek** [comment]
Hello @ggbecker  and thank you for noticing this. I made some fixes. However, I am not able to fix the rule audit_rules_suid_auid_privilege_function and. I am afraid this will take nontrivial effort. Basically, reloading of auditd service shows us that rules can't be reloaded after remediation. I am stil not entirely sure why, but I would like to tackle this remaining rule and possibly also audit_rules_suid_privilege_function in a separate PR.

**Comment by ggbecker** [comment]
> audit_rules_suid_auid_privilege_function

audit_rules_suid_auid_privilege_function doesn't seem to be included in RHEL10 content, so there shouldn't be any major issue with it. Overall it looks good to me. Thanks

**Review by ggbecker — APPROVED** [review]

**Comment by vojtapolasek** [comment]
@ggbecker  actually I see the rule audit_rules_suid_auid_privilege_function in RHEL 10 CIS level 2 profile for both server and workstation.

**Comment by ggbecker** [comment]
> @ggbecker actually I see the rule audit_rules_suid_auid_privilege_function in RHEL 10 CIS level 2 profile for both server and workstation.

That's true. So please continue with the plan on following up on another pull request.

**Pull request merged**
