### PR TITLE
rhcos4: Remove checks for nmcli permissions

### PR DESCRIPTION
**Pull request by JAORMX**
nmcli is not running on RHCOS

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Profile moderate on rhcos4:
 Rule network_nmcli_permissions removed from moderate profile.

**Recommended tests to execute:**
 build_product rhcos4
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhcos4-ds.xml moderate

**Comment by redhatrises** [comment]
@JAORMX can a non-root user configure networking?

**Comment by JAORMX** [comment]
> @JAORMX can a non-root user configure networking?

Not AFAIK

**Pull request merged**
