### PR TITLE
RHEL8: Fix rules breaking sudo command

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Rule dir_permissions_library_dirs is about preventing group-writable or world-writable directories in the library dirs.
  The Suid bits and the stick bit don't need to be stripped.
- Rule sssd_enable_smartcards was breaking the PAM stack in a way that non-root users were not able to execute commands with `sudo`. The commands are failing with `Sorry, try again` 3 times.

#### Rationale:

- Stripin suid bit from `/usr/bin/sudo` breaks it:
  `sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set`
- Related to #8420
- Related to #8768

### CODE REVIEW

**Comment by yuumasato** [comment]
So fixing the 'sudo' issue caused by `dir_permission_library_dirs` revealed another issue caused by `sssd_enable_smartcards`.
I've added a  temporary fix for the rule for RHEL8.
The commit switches the remediation of the rule to use `authselect enable-feature with-smartcard` instead of creating a custom profile. This unfortunately moves the rule out of alignment with DISA Benchmark.

The misalignment needs to be further discussed, maybe we add the check for `smartcard-auth` or we convice DISA to not require change to it.

**Comment by mildas** [comment]
LGTM

**Review by mildas — APPROVED** [review]

**Comment by mildas** [comment]
`sssd_enable_smartcards` errors in CI because it expects running sssd service. That's not possible as it runs in container.

Tests passed on my local VM, merging.

**Comment by marcusburghardt** [comment]
Also related to https://github.com/ComplianceAsCode/content/issues/8912 issue.

**Comment by jseiser** [comment]
@yuumasato 

Im not following what the fix is here?

We use a downstream Ansible role, built from this [repo.](https://github.com/RedHatOfficial/ansible-role-rhel8-stig) 

They just updated to release 0.1.62 and the RHEL 8 roles now fail to run.

```
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

Which is this code block:

```
- name: Set permissions for /lib/ recursively
  file:
    path: /lib/
    state: directory
    recurse: true
    mode: u-s,g-ws,o-wt
  tags:
  - CCE-88692-9
  - DISA-STIG-RHEL-08-010331
  - NIST-800-53-CM-5
  - NIST-800-53-CM-5(6)
  - NIST-800-53-CM-5(6).1
  - configure_strategy
  - dir_permissions_library_dirs
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  when:
  - configure_strategy | bool
  - dir_permissions_library_dirs | bool
  - low_complexity | bool
  - low_disruption | bool
  - medium_severity | bool
  - no_reboot_needed | bool
```




I have no problem shimming around this issue, until 0.1.63, but im not understanding what was the change done on this MR to fix the issue?

**Comment by yuumasato** [comment]
@jseiser The fix relevant for rule `dir_permissions_library_dirs` is dbdbb40.
It changes mode applied in the remediation from `    mode: u-s,g-ws,o-wt` to `    mode: g-ws,o-wt`, so it doesn't remove the setuid bits anymore.

In `/lib/.build/` there are symlinks to binaries in the system, and the rule was going through them and breaking `sudo` command.

Similar change was done in https://github.com/ComplianceAsCode/content/pull/8768.
And https://github.com/ComplianceAsCode/content/pull/8420 may help you understand the context even more.

**Pull request merged**
