### PR TITLE
Assign RHEL-08-010341 and RHEL-08-010351 to rules

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Assign RHEL-08-010341 and RHEL-08-010351 to rules.
  - Convert rules to use template. Enhance file templates to disregard symlinks.

### CODE REVIEW

**Comment by ggbecker** [comment]
The failing SSGTS test is legit, I'm working on it.

**Comment by ggbecker** [comment]
> The failing SSGTS test is legit, I'm working on it.

The problem should be solved by f82c314

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
