### PR TITLE
Select rules for audit login events

### LINKED ISSUE #5263: CIS 4.1.4 Ensure login and logout events are collected (Scored)
Need rule to audit /var/log/faillog (or do we?)

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Select rules to audit:
  - `/var/run/faillock`: audit_rules_login_events_faillock
  - `/var/log/lastlog`: audit_ruels_login_events_lastlog

#### Rationale:

- Lets not use `audit_rules_login_events`as it also audits `/var/run/tallylog`
- `/var/log/faillog` doesn't exist, and seems to be a typo. In RHEL7 CIS Benchmark, it is correctly listed as `/var/run/faillock`.
- Fixes #5263

### CODE REVIEW

**Comment by redhatrises** [comment]
We should open a new ticket to configure `/var/run/faillock` under `/var/log/faillock`. The default is a bad setting, because it is cleared on reboot. This allows for n number of tries.

**Comment by yuumasato** [comment]
> We should open a new ticket to configure `/var/run/faillock` under `/var/log/faillock`. The default is a bad setting, because it is cleared on reboot. This allows for n number of tries.

@redhatrises I don't understand what you are asking here.

**Comment by vojtapolasek** [comment]
In audit_rules_login_events_faillog, I see there is a reference
cis: 5.2.8
Looking into benchmarks it is unrelated to this rule.

**Comment by vojtapolasek** [comment]
> We should open a new ticket to configure `/var/run/faillock` under `/var/log/faillock`. The default is a bad setting, because it is cleared on reboot. This allows for n number of tries.

@redhatrises  Do you mean opening a ticket against pam which owns the faillock utility? Theoretically yes. But it is not related to this PR.

**Comment by yuumasato** [comment]
> In audit_rules_login_events_faillog, I see there is a reference
> cis: 5.2.8
> Looking into benchmarks it is unrelated to this rule.

Nice catch, I took the chance to piggyback RHEL7 CIS references.

**Comment by vojtapolasek** [comment]
thanks, rest looks good

**Comment by redhatrises** [comment]
> > We should open a new ticket to configure `/var/run/faillock` under `/var/log/faillock`. The default is a bad setting, because it is cleared on reboot. This allows for n number of tries.
> 
> @redhatrises Do you mean opening a ticket against pam which owns the faillock utility? Theoretically yes. But it is not related to this PR.

No. This is already configurable in `/etc/security/faillock.conf`. There needs to be a new rule and check that changes from `/var/run/faillock` to `/var/log/faillock` in our security benchmarks.

**Comment by redhatrises** [comment]
Looks like the ticket already exists upstream. See https://github.com/ComplianceAsCode/content/issues/2851

**Comment by yuumasato** [comment]
> No. This is already configurable in `/etc/security/faillock.conf`. There needs to be a new rule and check that changes from `/var/run/faillock` to `/var/log/faillock` in our security benchmarks.

> Looks like the ticket already exists upstream. See #2851

@redhatrises I see, thanks for pointing the new setting.
From what I see the issue itself would require a new rule, to make the change in `faillock.conf`. And `audit_rules_login_events_faillock` would have to be changed to follow any setting defined by this new rule.
It would probably become a new variable, and the rule would probably move out of the `audit_rules_login_events` template.

This is more than I envisioned for this PR, and I consider to be out of scope.

**Comment by redhatrises** [comment]
> > No. This is already configurable in `/etc/security/faillock.conf`. There needs to be a new rule and check that changes from `/var/run/faillock` to `/var/log/faillock` in our security benchmarks.
> 
> > Looks like the ticket already exists upstream. See #2851
> 
> @redhatrises I see, thanks for pointing the new setting.
> From what I see the issue itself would require a new rule, to make the change in `faillock.conf`. And `audit_rules_login_events_faillock` would have to be changed to follow any setting defined by this new rule.
> It would probably become a new variable, and the rule would probably move out of the `audit_rules_login_events` template.
> 
> This is more than I envisioned for this PR, and I consider to be out of scope.

Agreed. That's why I asked for a ticket to be opened. However, we already have one open.

**Pull request merged**
