### PR TITLE
OCP4: Add Google IdP for CI testing for rule idp_is_configured

### PR DESCRIPTION
**Pull request by Vincent056**
The current keycloak deployment keeps failing the CI test, so let's use Google IdP for testing

### CODE REVIEW

**Comment by jhrozek** [comment]
The `moderate-node` and the `pci-dss` failures look just like the cluster didn't install, but this one:
```
helpers.go:808: E2E-ERROR: The e2e YAML for rule 'file_permissions_controller_manager_kubeconfig' is malformed: {map[master:PASS worker:NOT-APPLICABLE] <nil>} . Got error: the role specified in the test doesn't match an existing role
```
is weird. Let's see if just re-running fixes things.

**Comment by jhrozek** [comment]
Still can't install clusters..
/retest

**Comment by jhrozek** [comment]
The failing rules were removed, let's try again...
/retest

**Comment by Vincent056** [comment]
@jhrozek finally found out why the CI is falling, we had manual remediation reject unsigned image, and it is cause the mustgather pod failing to pull the image from `registry.build03.ci.openshift.org`, in the original script, only `registry.build01.ci.openshift.org` and `registry.build02.ci.openshift.org` were accepted, that's why we had inconsistent CI runs. 

```
error: gather did not start for pod must-gather-mrlpm: unable to pull image: ImagePullBackOff: Back-off pulling image "registry.build03.ci.openshift.org/ci-op-24n6mrpg/stable@sha256:d8bd3c25f0974f2ceec780f10166cab12b7d73ebb557d0d4a3839575e2cbc6e7"
```

https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/integrity/reject_unsigned_images_by_default/tests/default_reject.pass.sh

**Comment by Vincent056** [comment]
@jhrozek we should do a new CO upstream release, the CI is getting two CO repliceset, one eks, and one normal CO.
```
$oc get replicaset -n openshift-compliance
NAME                                        DESIRED   CURRENT   READY   AGE
compliance-operator-57fdb7844               0         0         0       5m52s
compliance-operator-744ffdc7dd              1         1         1       4m25s
e2e-cis-node-master-rs-7c74854c67           1         1         1       20m
e2e-cis-node-worker-rs-6bbd89c6bd           0         0         0       5m5s
e2e-openshift-compliance-pp-7575845567      1         1         1       36m
eks-openshift-compliance-pp-8679467775      1         1         1       4m50s
ocp4-openshift-compliance-pp-66dbb54494     1         1         1       36m
rhcos4-openshift-compliance-pp-85574d5658   1         1         1       36m
```
And compliance operators are in restarting loop because of that 
https://github.com/openshift/compliance-operator/pull/787

**Comment by jhrozek** [comment]
> @jhrozek we should do a new CO upstream release, the CI is getting two CO repliceset, one eks, and one normal CO.
> 
> ```
> $oc get replicaset -n openshift-compliance
> NAME                                        DESIRED   CURRENT   READY   AGE
> compliance-operator-57fdb7844               0         0         0       5m52s
> compliance-operator-744ffdc7dd              1         1         1       4m25s
> e2e-cis-node-master-rs-7c74854c67           1         1         1       20m
> e2e-cis-node-worker-rs-6bbd89c6bd           0         0         0       5m5s
> e2e-openshift-compliance-pp-7575845567      1         1         1       36m
> eks-openshift-compliance-pp-8679467775      1         1         1       4m50s
> ocp4-openshift-compliance-pp-66dbb54494     1         1         1       36m
> rhcos4-openshift-compliance-pp-85574d5658   1         1         1       36m
> ```
> 
> And compliance operators are in restarting loop because of that [openshift/compliance-operator#787](https://github.com/openshift/compliance-operator/pull/787)

Yes, we need to do an upstream release. This would also unblock other rules that are waiting on review.

**Comment by Vincent056** [comment]
The CI has passed nevertheless @jhrozek

**Comment by jhrozek** [comment]
> The CI has passed nevertheless @jhrozek

Wohoo!

**Comment by Vincent056** [comment]
@jhrozek could we merge this one?

**Pull request merged**
