### PR TITLE
Test missing references in a data stream

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
Update `profile_tool.py` to support also SCAP source data streams and change upstream test `missing-references` to consume data stream.

For more details, please read commit message of every commit.

#### Rationale:
This makes one test independent from XCCDF 1.1 which will help us to remove XCCDF 1.1 in future.

### CODE REVIEW

**Comment by jan-cerny** [comment]
I have resolved the conflict and rebased on the top of the latest supstream master branch.

**Comment by vojtapolasek** [comment]
Hello @jan-cerny , please rebase.

**Comment by jan-cerny** [comment]
I have rebased the PR on the top of the upstream master branch.

**Comment by jan-cerny** [comment]
@vojtapolasek I have rebased it again because they have changed the list of required tests in the CI. But, I would prefer to avoid a fourth rebase.

**Comment by jan-cerny** [comment]
We were discussing the codeclimate report with @vojtapolasek and it seems that codeclimate doesn't fully recognize the visual indentation which is allowed by PEP8. So when fixing the codeclimate issues the pep8speaks would start to fail. We can avoid this by reformatting the code so that it would use hanging indent with indentation that are multiples of 4 and with no arguments after the opening parethesis. But, in general, we prefer to avoid checking in only whitespace changes in PRs if not necessary. I guess we need to improve the codeclimate configuration.

**Review by vojtapolasek — APPROVED** [review]
Looks good now. Codeclimate is reporting style errors, but they are caused by visual indentation. Functionality is not impacted.

**Pull request merged**
