### PR TITLE
Change oval check to verify if we're in OCP4

### PR DESCRIPTION
**Pull request by JAORMX**
The check used to verify if it was a RHEL node, but this is not ideal.
This changes it so that we rely on an object fetched from the cluster
that contains the version, and we check that the version is correct.

This effectively makes the OCP4 product only usable for API/platform
checks (meaning, kubernetes checks).

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 Text changed in OVAL check.
 The rule doesn't occur in any profile nor product.
 New node inserted to OVAL check.

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 Deleted attribute from OVAL check.
 Text changed in OVAL check.
 New node inserted to OVAL check.
 The rule doesn't occur in any profile nor product.

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 New node inserted to OVAL check.
 Text changed in OVAL check.
 The rule doesn't occur in any profile nor product.
 Deleted attribute from OVAL check.

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 New node inserted to OVAL check.
 Deleted attribute from OVAL check.
 Text changed in OVAL check.
 The rule doesn't occur in any profile nor product.
 Node moved within OVAL check.

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 Node moved within OVAL check.
 Text changed in OVAL check.
 New node inserted to OVAL check.
 The rule doesn't occur in any profile nor product.
 Deleted attribute from OVAL check.
Others:
 Python abstract syntax tree change found in build-scripts/cpe_generate.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by yuumasato** [comment]
Hopefully I've addressed the build problem with the `cpe-oval`.

Now the `cpe-oval` file for all products contain variables`ocp4_dump_location` and `ocp_data_root`.
I run a smoke evaluation with rhel8 and it worked fine for me.

I don't know how an evaluation for `ocp4` will work though, needs testing, :).
1. I don't know if the value of `ocp_data_root` will be the default or undefined.
1. I don't know if the Profile can influence the value of the variable.
1. I don't know if an environment variable can influence it, like `export ocp_data_root=/foo/bar`

**Comment by JAORMX** [comment]
> Hopefully I've addressed the build problem with the `cpe-oval`.
> 
> Now the `cpe-oval` file for all products contain variables`ocp4_dump_location` and `ocp_data_root`.
> I run a smoke evaluation with rhel8 and it worked fine for me.
> 
> I don't know how an evaluation for `ocp4` will work though, needs testing, :).
> 
>     1. I don't know if the value of `ocp_data_root` will be the default or undefined.
> 
>     2. I don't know if the Profile can influence the value of the variable.
> 
>     3. I don't know if an environment variable can influence it, like `export ocp_data_root=/foo/bar`

That's awesome! Let me try it out

**Comment by yuumasato** [comment]
Build failed, :disappointed:. I'll check what is wrong.

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 Deleted attribute from OVAL check.
 Node deleted from OVAL check.
 The rule doesn't occur in any profile nor product.
 Node moved within OVAL check.
 Text changed in OVAL check.
 New node inserted to OVAL check.
Others:
 Python abstract syntax tree change found in build-scripts/cpe_generate.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by JAORMX** [comment]
/retest

image registry is having issues

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 Node moved within OVAL check.
 The rule doesn't occur in any profile nor product.
 New node inserted to OVAL check.
 Node deleted from OVAL check.
 Deleted attribute from OVAL check.
 Text changed in OVAL check.

**Comment by evgenyz** [comment]
So, in the end we can't use variables in CPE checks? Even after @yuumasato fix?

**Comment by yuumasato** [comment]
> So, in the end we can't use variables in CPE checks? Even after @yuumasato fix?

`external_variable`s are the problematic ones, AFAIK there is no way to set them when doing `oscap xccdf eval`.

`local_variable`s should be fine, I'll push a fix soon.

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 Node deleted from OVAL check.
 Deleted attribute from OVAL check.
 Node moved within OVAL check.
 Text changed in OVAL check.
 The rule doesn't occur in any profile nor product.
 New node inserted to OVAL check.
Others:
 Python abstract syntax tree change found in build-scripts/cpe_generate.py.
 Python abstract syntax tree change found in ssg/build_cpe.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 New node inserted to OVAL check.
 Node moved within OVAL check.
 Node deleted from OVAL check.
 Text changed in OVAL check.
 Deleted attribute from OVAL check.
 The rule doesn't occur in any profile nor product.
Others:
 Python abstract syntax tree change found in build-scripts/cpe_generate.py.
 Python abstract syntax tree change found in ssg/build_cpe.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by yuumasato** [comment]
@JAORMX heads that I force pushed to your branch.

I dropped 6bc5295, which tried to make function more robust, but it relies on functions that are not fit for the purpose.
Let's just follow with a simple dumb fix.

**Comment by JAORMX** [comment]
This is not being tested on CI yet, but I tested locally. Should be good to go.

**Pull request merged**
