### PR TITLE
Add ansible remediation for accounts_have_homedir_login_defs

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Add ansible remediation for accounts_have_homedir_login_defs

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule accounts_have_homedir_login_defs:
 Text added outsite tags in OVAL check.
 Text changed in OVAL check.
 New node inserted to OVAL check.
 Node moved within OVAL check.
 Ansible remediation newly added.
 Node deleted from OVAL check.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by mildas** [comment]
**Changes identified:**
Rule accounts_have_homedir_login_defs:
 Ansible remediation newly added.
 Node moved within OVAL check.
 Node deleted from OVAL check.
 Text added outsite tags in OVAL check.
 New node inserted to OVAL check.
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs

**Comment by vojtapolasek** [comment]
Please resolve conflicts, othervise looks good.

**Comment by ggbecker** [comment]
> Please resolve conflicts, othervise looks good.

Done

**Comment by mildas** [comment]
**Changes identified:**
Rule accounts_have_homedir_login_defs:
 New node inserted to OVAL check.
 Node deleted from OVAL check.
 Ansible remediation newly added.
 Node moved within OVAL check.
 Text added outsite tags in OVAL check.
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs

**Comment by mildas** [comment]
**Changes identified:**
Rule accounts_have_homedir_login_defs:
 Node moved within OVAL check.
 Text changed in OVAL check.
 Node deleted from OVAL check.
 Templatization usage changed.
 Ansible remediation newly added.
 New node inserted to OVAL check.
 Text added outsite tags in OVAL check.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs

**Comment by matejak** [comment]
oops, I just wanted to suggest a change. Anyway, you can get rid of it easily by rebasing.

Is there a reason not to have `multi_platform_all` in the remediation body? i.e. what about Fedora?

**Comment by ggbecker** [comment]
> oops, I just wanted to suggest a change. Anyway, you can get rid of it easily by rebasing.
> 
> Is there a reason not to have `multi_platform_all` in the remediation body? i.e. what about Fedora?

Fedora is not in the `prodtype` list.

**Comment by mildas** [comment]
**Changes identified:**
Rule accounts_have_homedir_login_defs:
 Node moved within OVAL check.
 Templatization usage changed.
 New node inserted to OVAL check.
 Text added outsite tags in OVAL check.
 Ansible remediation newly added.
 Text changed in OVAL check.
 Node deleted from OVAL check.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml accounts_have_homedir_login_defs

**Comment by ggbecker** [comment]
> > oops, I just wanted to suggest a change. Anyway, you can get rid of it easily by rebasing.
> > Is there a reason not to have `multi_platform_all` in the remediation body? i.e. what about Fedora?
> 
> Fedora is not in the `prodtype` list.

Ok, but I see no reason why not to include Fedora into the list. Done in ca62bf8

**Comment by ggbecker** [comment]
@vojtapolasek I guess there is nothing else to be done here. Can you please check it again? Thank you.

**Comment by vojtapolasek** [comment]
right, lgtm, merging. Thank you.

**Pull request merged**
