### PR TITLE
test_machine_only_rules.py should read files in the UTF-8 encoding

### LINKED ISSUE #3763: test_machine_only_rules.py fails on unicode content
#### Description of problem:
During the build process (on ubuntu) the test sequence fails on test "machine-only-rules" due to fact that some content is UTF-8 while reading content.
Possible faulty code would be in tests/test_machine_only_rules.py function check_if_machine_only.

#### SCAP Security Guide Version:
Version 0.1.42 (git clone)

#### Operating System Version:
Ubuntu 18.04.2 LTS

#### Actual Results:

```
47/227 Test: machine-only-rules
Command: "/usr/bin/env" "PYTHONPATH=/src/scap-security-guide_0.1.42" "/usr/bin/python3" "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py" "--source_dir" "/src/scap-security-guide_0.1.42" "--build_dir" "/src/scap-security-guide_0.1.42/obj-x86_64-linux-gnu"
Directory: /src/scap-security-guide_0.1.42/obj-x86_64-linux-gnu/tests
"machine-only-rules" start time: Feb 13 23:36 UTC
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 111, in <module>
    main()
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 21, in main
    if not check_product(args.build_dir, product, guide_dir):
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 26, in check_product
    input_groups, input_rules = scan_rules_groups(guide_dir, False)
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 104, in scan_rules_groups
    subdir_path, is_machine_only)
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 104, in scan_rules_groups
    subdir_path, is_machine_only)
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 104, in scan_rules_groups
    subdir_path, is_machine_only)
  [Previous line repeated 3 more times]
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 98, in scan_rules_groups
    if check_if_machine_only(dirpath, "rule.yml", parent_machine_only):
  File "/src/scap-security-guide_0.1.42/tests/test_machine_only_rules.py", line 84, in check_if_machine_only
    yml_file_contents = yml_file.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 789: ordinal not in range(128)
<end of output>
Test time =   0.42 sec
----------------------------------------------------------
Test Failed.
"machine-only-rules" end time: Feb 13 23:36 UTC
```

#### Expected Results:
Test Success.

#### Addition Information/Debugging Steps:

Proposed fix:

```diff
diff --git a/tests/test_machine_only_rules.py b/tests/test_machine_only_rules.py
index 94a2e4e03..3a2e93371 100755
--- a/tests/test_machine_only_rules.py
+++ b/tests/test_machine_only_rules.py
@@ -80,7 +80,7 @@ def check_if_machine_only(dirpath, name, is_machine_only_group):
         if is_machine_only_group:
             return True
         yml_path = os.path.join(dirpath, name)
-        with open(yml_path, "r") as yml_file:
+        with open(yml_path, "r", encoding="utf-8") as yml_file:
             yml_file_contents = yml_file.read()
             if "platform: machine" in yml_file_contents:
                 return True

```

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #3763

### CODE REVIEW

**Comment by matejak** [comment]
You should be fine if you use `io.open`, as Python3 `open` can't do `encoding`.

**Comment by redhatrises** [comment]
> You should be fine if you use `io.open`, as Python2 `open` can't do `encoding`.

Thanks @matejak! You are right. I totally forgot that we were python3 now.... Shame on me.

**Comment by redhatrises** [comment]
@matejak should be fixed now

**Comment by matejak** [comment]
ACK, thank you for the fix!

**Pull request merged**
