### PR TITLE
OL7 stig v2r9 update

### PR DESCRIPTION
**Pull request by freddieRv**
#### Description:

- Bump OL7 stig profile version to v2r9
- Update the XCCDF manual reference
- Add missing audit rules to the OL7 stig profile
- Add OL7 to the platform list on the `audispd_remote_daemon` rules

#### Rationale:

- OL7 STIG efforts

### CODE REVIEW

**Review by ggbecker — APPROVED** [review]
LGTM

**Comment by ggbecker** [comment]
@freddieRv I believe you have to approve the PR as well in order to merge it :P

**Comment by freddieRv** [comment]
@ggbecker GitHub won't let me approve my own PRs 🤔

**Comment by ggbecker** [comment]
> 

I suspected something like that... we will figure it out how to make it work... probably by removing the need for the group to approve.

**Review by Mab879 — APPROVED** [review]
LGTM. Using project admin to merge without CODEOWNERS.

**Pull request merged**
