### PR TITLE
SLE15 Add selinux rules to HIPAA profile

### PR DESCRIPTION
**Pull request by teacup-on-rockingchair**
#### Description:
Add selinux rules to SLE15 HIPAA profile

#### Rationale:

Add rules:
- sebool_selinuxuser_execheap
- sebool_selinuxuser_execmod
- sebool_selinuxuser_execstack

to HIPAA profile for SUSE Linux Enterprise 15 platform

### CODE REVIEW

**Comment by jan-cerny** [comment]
Hi @teacup-on-rockingchair, I'm sorry for my long delay. But, the pull requests shouldn't contain any "Merge ..." commit.  Please remove the "Merge ..." commit from this pull request. You can use git rebase on master and the force push to do that. Otherwise LGTM.

**Comment by teacup-on-rockingchair** [comment]
> Hi @teacup-on-rockingchair, I'm sorry for my long delay. But, the pull requests shouldn't contain any "Merge ..." commit. Please remove the "Merge ..." commit from this pull request. You can use git rebase on master and the force push to do that. Otherwise LGTM.

Thanks for the feedback @jan-cerny  , I am not sure how I could end up with such strange history of commit, but I think on third attempt plus rebase now looks ok.

**Review by JAORMX — APPROVED** [review]
/retest

Note that this doesn't affect the OCP jobs, they're just being flaky...

**Pull request merged**
