### PR TITLE
Delete rules in favour of package_subscription-manager_installed

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

-  Delete some rules in favour of `package_subscription-manager_installed`

Rules deleted:
- `package_python-rhsm_installed`
- `package_python3-subscription-manager-rhsm_installed`

#### Rationale:

- These rules are not being used by any profile and they are obsoleted by `package_subscription-manager_installed`

### CODE REVIEW

**Comment by redhatrises** [comment]
@ggbecker it sounds like we should merge this rules with `package_subscription-manager_installed`, no?

**Comment by ggbecker** [comment]
> @ggbecker it sounds like we should merge this rules with `package_subscription-manager_installed`, no?

Yes, sounds good. I would go for only `package_subscription-manager_installed` as these packages are installed as dependencies anyway.

**Comment by ggbecker** [comment]
@openscap-ci test this please

**Comment by ggbecker** [comment]
> @ggbecker it sounds like we should merge this rules with `package_subscription-manager_installed`, no?

I have changed the approach to delete unused rules in favour of `package_subscription-manager_installed`

**Comment by redhatrises** [comment]
@ggbecker is `package_python3-subscription-manager-rhsm_installed` no longer required because of the `package_subscription-manager-installed` rule?

**Comment by ggbecker** [comment]
> @ggbecker is `package_python3-subscription-manager-rhsm_installed` no longer required because of the `package_subscription-manager-installed` rule?

Yes, `python3-subscription-manager-rhsm` is installed as a dependency of `subscription-manager`. Also `package_python3-subscription-manager-rhsm_installed` was created at some point to be included in RHEL8/ospp.profile but it then got dropped from the profile in favour of `package_subscription-manager-installed`, as you can see here: https://github.com/ComplianceAsCode/content/commit/b023144bf7c676ed83d1d7f46538601ab7279700#diff-594d17d05d6865670f04b0657a0ed7fcL172

**Comment by jan-cerny** [comment]
@ggbecker please resolve conflicts

**Pull request merged**
