### PR TITLE
Replace legacy @RULE_ID@ AND @RULE_TITLE@ substitutions with jinja

### PR DESCRIPTION
**Pull request by matejak**
This PR unifies the Ansible functionality used to

* generate general remediations output, and
* add rule-specific metadata to the Ansible output.

Moreover, it adds functionality for expanding templates the jinja way.

In order to accomplish this, the existing code (and it's respective tests) had to be moved around, so there are no circular dependencies.

Fixes: #3830, #3831

### CODE REVIEW

**Comment by jan-cerny** [comment]
I have noticed that some rules, eg.` sysctl_kernel_randomize_va_space` now have a new tag in their Ansible tasks, eg. `DISA-STIG-RHEL-08-040201`. Is that expected?

**Comment by matejak** [comment]
The problem is that the STIG ID is not always product-qualified, we have `grep -R --include rule.yml stigid: linux_os/ | wc -l` == 67 rules that have unqualified STIG IDs in the `linux_os` tree. At the same time, we have 445 rules that have qualified STIG IDs (some of them have both).
However, this change is not expected, so I have pushed a commit fixing that.

**Comment by jan-cerny** [comment]
Great! However, I tried to build the RHEL 6 datastream with the latest update but I think this is also not expected: Before: `DISA-STIG-RHEL-06-RHEL-06-000256`, After: `DISA-STIG--RHEL-06-000256` Notice the double dash in the latter tag.

Regarding the substitutions in Ansible Playbooks, they work for me.

**Comment by jan-cerny** [comment]
@matejak please resolve the conflicts

**Pull request merged**
