### PR TITLE
Move the templated sshd OVAL check to a macro

### PR DESCRIPTION
**Pull request by matejak**
That way, it can be reused e.g. in tests.

### CODE REVIEW

**Comment by matusmarhefka** [comment]
@matejak I get this error when testing `sshd_disable_pubkey_auth` on Fedora 34 VM:
```
INFO - xccdf_org.ssgproject.content_rule_sshd_disable_pubkey_auth
INFO - Script correct_value_directory.pass.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script missing_value.fail.sh using profile (all) OK
INFO - Script commented.fail.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script conflict.fail.sh using profile (all) OK
ERROR - Rule evaluation resulted in error, instead of expected fixed during remediation stage 
ERROR - The remediation failed for rule 'xccdf_org.ssgproject.content_rule_sshd_disable_pubkey_auth'.
```

**Comment by matejak** [comment]
oops, one unexpanded macro. Fixed now.

**Comment by matusmarhefka** [comment]
Now it looks good, thank you.
```
INFO - xccdf_org.ssgproject.content_rule_sshd_disable_pubkey_auth
INFO - Script correct_value_directory.pass.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script missing_value.fail.sh using profile (all) OK
INFO - Script commented.fail.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script conflict.fail.sh using profile (all) OK
```

**Review by matusmarhefka — APPROVED** [review]

**Pull request merged**
