### PR TITLE
Fix e2e expected test result for configure_usbguard_auditbackend

### PR DESCRIPTION
**Pull request by Vincent056**
Fix e2e expected test result for configure_usbguard_auditbackend. The CPE evaluation changed after remediation applied, and it is causing some issue in e2e test.

### CODE REVIEW

**Comment by jhrozek** [comment]
Thank you for tracking this down. Do you know what does the CPE change to? I think we had an issue like this before but I can't remember what did it relate to exactly, do you?

**Comment by Vincent056** [comment]
> Thank you for tracking this down. Do you know what does the CPE change to? I think we had an issue like this before but I can't remember what did it relate to exactly, do you?

usbguard, it checks if usbguard is installed

**Comment by jhrozek** [comment]
> > Thank you for tracking this down. Do you know what does the CPE change to? I think we had an issue like this before but I can't remember what did it relate to exactly, do you?
> 
> usbguard, it checks if usbguard is installed

OK, so this would allow our e2e test to pass, but our customers would still have the issue and the rule would be NOT-APPLICABLE also for them?

**Comment by jhrozek** [comment]
> > > Thank you for tracking this down. Do you know what does the CPE change to? I think we had an issue like this before but I can't remember what did it relate to exactly, do you?
> > 
> > 
> > usbguard, it checks if usbguard is installed
> 
> OK, so this would allow our e2e test to pass, but our customers would still have the issue and the rule would be NOT-APPLICABLE also for them?

If that is the case, do we need a Jira card and a release note with a known bug?

**Comment by Vincent056** [comment]
> > > > Thank you for tracking this down. Do you know what does the CPE change to? I think we had an issue like this before but I can't remember what did it relate to exactly, do you?
> > > 
> > > 
> > > usbguard, it checks if usbguard is installed
> > 
> > 
> > OK, so this would allow our e2e test to pass, but our customers would still have the issue and the rule would be NOT-APPLICABLE also for them?
> 
> If that is the case, do we need a Jira card and a release note with a known bug?

There is a Jira Card here: https://issues.redhat.com/browse/CMP-1542?filter=-2

**Comment by Vincent056** [comment]
I think `NOT-APPLICABLE` will not show in the CCR?  `package_usbguard_installed` rule has remediation that changes the CPE for this rule.

**Comment by jhrozek** [comment]
> I think `NOT-APPLICABLE` will not show in the CCR? `package_usbguard_installed` rule has remediation that changes the CPE for this rule.

Sorry about my confusion. I thought that the CPE changing might affect other rules than the usbguard related ones so that' why I was trying to be very defensive.

Vincent explained on Slack that the only affected rule is the usbguard one, which is fine. I'm going to ack the patch.

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
