### PR TITLE
Complete the CIS requirement to prevent rsyslog from receiving logs from remote clients

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

The `rsyslog_nolisten` rule was updated to also check RainerScript sysntax in rsyslog configuration files.
In addition:
- Test scenarios were updated
- Bash and Ansible remedition were included

#### Rationale:

Better CIS coverage for RHEL 8 and RHEL 9.

### CODE REVIEW

**Comment by marcusburghardt** [comment]
The codeclimate issue can be waived. Some variables are defined in that shared file used by different rules. The test scenario scripts in rules use those variables.

**Review by vojtapolasek — CHANGES_REQUESTED** [review]
Hello @marcusburghardt, it looks good, thank you. Just one small thing - in the Bash remediation you restart the service, in the Ansible remediation you don't. Please align it.

**Comment by marcusburghardt** [comment]
> Hello @marcusburghardt, it looks good, thank you. Just one small thing - in the Bash remediation you restart the service, in the Ansible remediation you don't. Please align it.

Fixed @vojtapolasek

**Comment by vojtapolasek** [comment]
Hello @marcusburghardt, thanks for the fix. However, there is still a small discrepancy between Bash and Ansible. The Bash remediation will restart the service unconditionally, but the Ansible remediation will restart it only if some changes were applied... could you please also align this?

**Comment by marcusburghardt** [comment]
> Hello @marcusburghardt, thanks for the fix. However, there is still a small discrepancy between Bash and Ansible. The Bash remediation will restart the service unconditionally, but the Ansible remediation will restart it only if some changes were applied... could you please also align this?

I don't see this as necessary in Bash but I can make it better, of course. Just a minute.

**Comment by marcusburghardt** [comment]
> > Hello @marcusburghardt, thanks for the fix. However, there is still a small discrepancy between Bash and Ansible. The Bash remediation will restart the service unconditionally, but the Ansible remediation will restart it only if some changes were applied... could you please also align this?
> 
> I don't see this as necessary in Bash but I can make it better, of course. Just a minute.

Done

**Review by vojtapolasek — APPROVED** [review]
Looks great now, thank you.

**Pull request merged**
