### PR TITLE
OCP: Add Azure and GCP disk encryption rules to `machine_volume_encrypted`

### PR DESCRIPTION
**Pull request by JAORMX**
The aforementioned rule is meant to encompass disk encryption for
several cloud providers. This makes sure it also checks Azure and GCP.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now b8106df2cfda4b3ea5831874af647add749d8c74

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 0d1b4557a62142589ce9bd0760c868e31dbd3d44

**Review by sherine-k — APPROVED** [review]
That's great! we now cover it for the major cloud providers!

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 544a89364a6e949d049fced220d08ccdc9a3ad59

**Comment by JAORMX** [comment]
/retest

application timeout

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
