### PR TITLE
ocp4: Add --datastream-only flag to helpers

### PR DESCRIPTION
**Pull request by JAORMX**
This flag allows us to build the content faster. So let's take it into
use.

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
`   * could not run steps: step e2e-aws-rhcos4-e8 failed: template pod "e2e-aws-rhcos4-e8" failed: the pod ci-op-sm2vh0q2/e2e-aws-rhcos4-e8 failed after 46m9s (failed containers: test): ContainerFailed one or more containers exited `

**Review by ggbecker — APPROVED** [review]

**Pull request merged**
