### PR TITLE
Update accounts_umask_etc_profile remediation regex to handle comments

### PR DESCRIPTION
**Pull request by brett060102**
The current regex in the bash and ansible remediation won't fire
if the umask line is commented out.

#### Description:

- Handle cases when umask line is commented out.

#### Rationale:

- Should remediate if umask line is missing or commented out.

### CODE REVIEW

**Review by vojtapolasek — CHANGES_REQUESTED** [review]
Looks good. Could you please add a test with commented umask?

**Comment by brett060102** [comment]
Test has been added.

**Review by vojtapolasek — APPROVED** [review]
LGTM, thank you

**Pull request merged**
