### PR TITLE
increase coverage RHEL-08-010770 and RHEL-07-020710

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- modify RHEL 8 STIG profile and use the file_permission_user_init_files_root rule instead of file_permission_user_init_files
- also add appropriate variable so that all dot files are examined during the scan

#### Rationale:

- increase STIG coverage
- this was discovered during work on #11890 

#### Review Hints:

build rhel8 products and examine stig and stig_gui profiles

### CODE REVIEW

**Review by Mab879 — APPROVED** [review]
LGTM.

**Review by Mab879 — CHANGES_REQUESTED** [review]
The testing farm failures look valid.

**Comment by vojtapolasek** [comment]
@Mab879  since rhel7 product is no longer in this repo, I modified the PR to include only rhel8 related changes.

**Review by Mab879 — APPROVED** [review]
LGTM.

Thanks for the PR.

**Pull request merged**
