### PR TITLE
OSPP consolidation

### PR DESCRIPTION
**Pull request by dahaic**
#### Description:

- Confusion caused by `ccc` `ospp` and `ospp42` profiles in RHEL7 product should no longer occur. New split is between `ospp` profile, which closely follows OSPP guidance, and `ncp` profile, which inherits generality of the old profile under `ospp` id.

### CODE REVIEW

**Comment by dahaic** [comment]
As there are significant shuffling changes, please review per commit. I have tried to make it clear and readable.

**Comment by redhatrises** [comment]
Is the `nccp` profile for the NIST National Checklist Program? If so, should be `ncp`.

**Comment by dahaic** [comment]
> Is the `nccp` profile for the NIST National Checklist Program? If so, should be `ncp`.

I've used the abbreviation I got from the discussion notes with @shawndwells It might be a typo though. Shawn, can you confirm? :)

**Comment by dahaic** [comment]
I have created blocker issue to track the rename of `nccp` to anything else. Thus I believe this PR is not blocked anymore.

**Comment by shawndwells** [comment]
On 8/10/19 9:32 AM, Marek Haičman wrote:
>
>     Is the |nccp| profile for the NIST National Checklist Program? If
>     so, should be |ncp|.
>
> I've used the abbreviation I got from the discussion notes with 
> @shawndwells <https://github.com/shawndwells> It might be a typo 
> though. Shawn, can you confirm? :)
>

NIST National Checklist Program.... nncp.

But IIRC this was intended to be a working title and we have all of 
August to figure out something more permanent.

**Comment by redhatrises** [comment]
> On 8/10/19 9:32 AM, Marek Haičman wrote: Is the |nccp| profile for the NIST National Checklist Program? If so, should be |ncp|. I've used the abbreviation I got from the discussion notes with @shawndwells <https://github.com/shawndwells> It might be a typo though. Shawn, can you confirm? :)
> NIST National Checklist Program.... nncp. But IIRC this was intended to be a working title and we have all of August to figure out something more permanent.

NIST calls it the National Checklist Program and abbreviates it as NCP, so why not just go with that (make it lower case of course)? It's simple and lines up with NIST's abbreviation and will avoid confusion in addition to it possibly being viewed as a typo if it is `nncp`.

**Comment by dahaic** [comment]
I've reuploaded to fix merge conflicts - this time, I haven't extended `ncp` profile with `ospp` one - will do that after this PR is merged.

**Comment by yuumasato** [comment]
@dahaic Please, also update the test for stable IDs.

**Pull request merged**
