### PR TITLE
Update CCI Numbers due to new STIG/SRG GPOS

### PR DESCRIPTION
**Pull request by Mab879**
#### Description and Rationale:

Keep the CCI numbers updated.

#### Review Hints:
* Spot check the rules based on the RHEL 9 control file and the STIG.
* ~This PR is dependent on #12373~

### CODE REVIEW

**Comment by vojtapolasek** [comment]
Hello @Mab879  and thanks for this update. I have few questions.
1. Would you consider modifying the script clean_up_dupkeys.py so that your home path is not there? I don't see this as a good security practice. The path can be set through a variable.
2. How did you actually get list of paths used in the clean_up_dupkeys.py?
3. Just so that I understand... the workflow was like running the update_cci.py and then clean_up_dupkeys?
4. How were commits d6387117cc7780bedb5b7000f5dbb417b71f97e4 and de5fafc39da87be83d2b525a4d669e93e7230d82 created? The description is vague.

Thank you for answering these questions.

**Comment by Mab879** [comment]
> Hello @Mab879 and thanks for this update. I have few questions.
> 
>     1. Would you consider modifying the script clean_up_dupkeys.py so that your home path is not there? I don't see this as a good security practice. The path can be set through a variable.

I just remove my home folder. Paths are now relative to `SSG_ROOT`.

>     2. How did you actually get list of paths used in the clean_up_dupkeys.py?

I used `grep` to find files with two `disa` keys`.

>     3. Just so that I understand... the workflow was like running the update_cci.py and then clean_up_dupkeys?

The vast majority was done that way.

>     4. How were commits [d638711](https://github.com/ComplianceAsCode/content/commit/d6387117cc7780bedb5b7000f5dbb417b71f97e4) and [de5fafc](https://github.com/ComplianceAsCode/content/commit/de5fafc39da87be83d2b525a4d669e93e7230d82) created? The description is vague.

* `d6387117cc7780bedb5b7000f5dbb417b71f97e4` - Was my try manual updates
* `de5fafc39da87be83d2b525a4d669e93e7230d82` - Was the automated tests

**Comment by vojtapolasek** [comment]
Hello @Mab879  and thank you for explanation.
I wrote a simple script trying to check ccis in the content against the latest RHEL 9 STIG. I am attaching it to this comment.

I built the rhel9 content and I ran it from the project's root directory. This is the output I get:
```
❯ python check_ccis.py 
xccdf_org.ssgproject.content_rule_configure_crypto_policy seems to not have matching ccis when compared to original stig guide.
Stigid(s) from content: ['RHEL-09-671010', 'RHEL-09-672030', 'RHEL-09-672045']
Related rule titles from original stig guide: RHEL 9 must enable FIPS mode.,RHEL 9 must implement DOD-approved TLS encryption in the GnuTLS package.,RHEL 9 must implement a system-wide encryption policy.
CCIs from content: {'CCI-002450', 'CCI-003123', 'CCI-002890'}
CCIs from stig guide: {'CCI-002418', 'CCI-002890', 'CCI-003123', 'CCI-000068', 'CCI-000877', 'CCI-001453', 'CCI-002450'}
xccdf_org.ssgproject.content_rule_package_mcafeetp_installed contains stigid which does not exist in the original stig guide.
xccdf_org.ssgproject.content_rule_package_mcafeetp_installed seems to not have matching ccis when compared to original stig guide.
Stigid(s) from content: ['RHEL-09-211025']
Related rule titles from original stig guide: 
CCIs from content: {'CCI-001263', 'CCI-000366'}
CCIs from stig guide: set()
xccdf_org.ssgproject.content_rule_agent_mfetpd_running contains stigid which does not exist in the original stig guide.
xccdf_org.ssgproject.content_rule_agent_mfetpd_running seems to not have matching ccis when compared to original stig guide.
Stigid(s) from content: ['RHEL-09-211025']
Related rule titles from original stig guide: 
CCIs from content: {'CCI-001263', 'CCI-000366'}
CCIs from stig guide: set()
xccdf_org.ssgproject.content_rule_dconf_gnome_disable_autorun seems to not have matching ccis when compared to original stig guide.
Stigid(s) from content: ['RHEL-09-271030', 'RHEL-09-271035']
Related rule titles from original stig guide: RHEL 9 must disable the graphical user interface autorun function unless required.,RHEL 9 must prevent a user from overriding the disabling of the graphical user interface autorun function.
CCIs from content: {'CCI-000366', 'CCI-001958', 'CCI-000778'}
CCIs from stig guide: {'CCI-000366', 'CCI-001764', 'CCI-000778', 'CCI-001958'}
xccdf_org.ssgproject.content_rule_enable_authselect contains stigid which does not exist in the original stig guide.
xccdf_org.ssgproject.content_rule_enable_authselect seems to not have matching ccis when compared to original stig guide.
Stigid(s) from content: ['needed_rules']
Related rule titles from original stig guide: 
CCIs from content: {'CCI-000213'}
CCIs from stig guide: set()
xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_password_auth contains stigid which does not exist in the original stig guide.
xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_password_auth seems to not have matching ccis when compared to original stig guide.
Stigid(s) from content: ['RHEL-09-611015']
Related rule titles from original stig guide: 
CCIs from content: {'CCI-000200'}
CCIs from stig guide: set()
xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_system_auth contains stigid which does not exist in the original stig guide.
xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_system_auth seems to not have matching ccis when compared to original stig guide.
Stigid(s) from content: ['RHEL-09-611020']
Related rule titles from original stig guide: 
CCIs from content: {'CCI-000200'}
CCIs from stig guide: set()
```

I think findings are valid. Could you please check these results?
[check_ccis.py.txt](https://github.com/user-attachments/files/17130674/check_ccis.py.txt)

**Review by vojtapolasek — APPROVED** [review]
LGTM now, thank you.
I am waiving failing tests because they are unrelated to changes in this PR. This PR changes only references.

**Pull request merged**
