### PR TITLE
Add version to profile element in the data stream

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Adds version numbers for profiles to the data stream based on the metadata version information.

#### Rationale:

To aid in future features.
#### Review Hints:
1. `./build_product -j10 rhel8`
2. `grep xccdf-1.2:version build/ssg-*-ds.xml`

### CODE REVIEW

**Comment by Mab879** [comment]
cc @yuumasato @lbragstad

**Review by jan-cerny — COMMENTED** [review]
This is great!

We need a test for this feature.


It would be nice to fix the code complexity although it's been very complex before.

**Review by jan-cerny — APPROVED** [review]
I have built the data stream and I have viewed the version elements and their contents.

Thanks for this change!

**Pull request merged**
