### PR TITLE
Add initial support kube remediation templating

### PR DESCRIPTION
**Pull request by Vincent056**
Description:
Add initial remediation templating variable support for following rule:

chronyd_or_ntpd_specify_remote_server
auditd_data_disk_error_action
auditd_data_disk_full_action
auditd_data_retention_admin_space_left_action
auditd_data_retention_flush
auditd_data_retention_max_log_file
auditd_data_retention_max_log_file_action
auditd_data_retention_num_logs
auditd_data_retention_space_left
auditd_data_retention_space_left_action
auditd_freq
auditd_local_events
uditd_log_format
auditd_name_format
auditd_write_logs

Rationale:
In the past, we are using fixed default XCCDF values in Kubernetes Remediations, this PR introduce XCCDF variable name into Kubernetes Remediations, so these variable name can be read and processed in compliance operator, and later replaced by values that set directly from compliance operator. It is more flexible, because the user of compliance operator is able to choose which value to use for those XCCDF variable in their remediation without the need of creating a new content file.

### CODE REVIEW

**Comment by Vincent056** [comment]
My previous PR got accidentally closed, @JAORMX , I synced up with latest, and made the commit again.

**Comment by Vincent056** [comment]
> /retest

This ones needs a new upstream release to test it

**Comment by JAORMX** [comment]
/retest

This now uses the v0.1.41 release

**Comment by Vincent056** [comment]
@JAORMX I think we should take out  `helpers.go:941: Running manual remediation /go/src/github.com/ComplianceAsCode/content/linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/tests/ocp4/e2e-remediation.sh' since we will be able to remediate this with ntp server variable default value.

**Comment by Vincent056** [comment]
@JAORMX I also noticed that some remediation that has previously fixed xccdf value different than the default value from the selection

**Comment by JAORMX** [comment]
> @JAORMX I think we should take out `helpers.go:941: Running manual remediation /go/src/github.com/ComplianceAsCode/content/linux_os/guide/services/ntp/chronyd_or_ntpd_specify_remote_server/tests/ocp4/e2e-remediation.sh` since we will be able to remediate this with ntp server variable default value.

Can you fix that in this PR?

**Comment by JAORMX** [comment]
> @JAORMX I also noticed that some remediation that has previously fixed xccdf value different than the default value from the selection

which one? We'll need that fixed as well

**Comment by Vincent056** [comment]
> > @JAORMX I also noticed that some remediation that has previously fixed xccdf value different than the default value from the selection
> 
> which one? We'll need that fixed as well

https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/configure_auditd_data_retention/var_auditd_max_log_file.var For example, if you look at this one, the values from existing remediation is 8, but the default is 6

**Comment by Vincent056** [comment]
I have removed the value-required for NTP server, let's find a new rule that dose require value-required annotation, and add the tailorprofile to the e2e CI test as well. @JAORMX

**Review by JAORMX — APPROVED** [review]
Yes!

**Pull request merged**
