### PR TITLE
Expose Prometheus metrics on GitHub Pages

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

Complementing the https://github.com/ComplianceAsCode/content/pull/11040 , this PR will generate and expose updated Prometheus metrics after each PR be merged into master branch.

Once merged, the new metrics should be exposed here https://complianceascode.github.io/content-pages/
Once exposed, any Prometheus instance will be able to collect these metrics.

#### Rationale:

- Automation to keep metrics updated
- Enable Prometheus to collect metrics about control files

### CODE REVIEW

**Review by Mab879 — APPROVED** [review]
LGTM. Thanks!

**Review by Mab879 — CHANGES_REQUESTED** [review]
Please check the python dependencies for the pages job.

**Comment by marcusburghardt** [comment]
> Please check the python dependencies for the pages job.

Fixed

**Comment by marcusburghardt** [comment]
Here is how the Prometheus Metrics will be exposed in https://complianceascode.github.io/content-pages/:
Screenshot from 2023-09-08 09-56-19

When clicking on the link:

Screenshot from 2023-09-08 09-58-10

**Review by Mab879 — APPROVED** [review]
LGTM

**Pull request merged**
