### PR TITLE
Add initial remediation templating support

### PR DESCRIPTION
**Pull request by Vincent056**
#### Description:
Add initial remediation templating variable support for following rule:

chronyd_or_ntpd_specify_remote_server
auditd_data_disk_error_action
auditd_data_disk_full_action
auditd_data_retention_admin_space_left_action
auditd_data_retention_flush
auditd_data_retention_max_log_file
auditd_data_retention_max_log_file_action
auditd_data_retention_num_logs
auditd_data_retention_space_left
auditd_data_retention_space_left_action
auditd_freq
auditd_local_events
uditd_log_format
auditd_name_format
auditd_write_logs

#### Rationale:

In the past, we are using fixed default XCCDF values in Kubernetes Remediations, this PR introduce XCCDF variable name into Kubernetes Remediations, so these variable name can be read and processed in compliance operator, and later replaced by values that set directly from compliance operator. It is more flexible, because the user of compliance operator is able to choose which value to use for those XCCDF variable in their remediation without the need of creating a new content file.

### CODE REVIEW

**Comment by JAORMX** [comment]
/test all

The new changes on CI hadn't been reflected.

**Comment by JAORMX** [comment]
The CI tests are failing, which means that this PR is not doing what it should. Does this require a newer CO release? it's currently using v0.1.40

**Comment by Vincent056** [comment]
> The CI tests are failing, which means that this PR is not doing what it should. Does this require a newer CO release? it's currently using v0.1.40

What should I do for this

**Comment by Vincent056** [comment]
Closed, opened this one instead https://github.com/ComplianceAsCode/content/pull/7558

**Pull request closed without merging**
