### PR TITLE
[WIP] Add SAP profile to rhel

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by matejak** [comment]
Check out prodtypes in rule YAMLs, they don't include RHEL7,8.

**Comment by redhatrises** [comment]
Thanks @matejak ! I am slowly working on this as the local users rules will have to be reworked a little.

**Comment by shawndwells** [comment]
Much of this work was picked up by the linux-system-roles project:
https://github.com/linux-system-roles/sap-hana-preconfigure

May want to ping them for alignment, or see if an SCAP profile continues to make sense.

**Comment by redhatrises** [comment]
> Much of this work was picked up by the linux-system-roles project:
> https://github.com/linux-system-roles/sap-hana-preconfigure
> 
> May want to ping them for alignment, or see if an SCAP profile continues to make sense.

There is a lot that is missing and doesn't really reference the security aspect for SAP.

**Comment by dahaic** [comment]
@redhatrises do you feel this PR is resurrectable? :) Or should we close it?

**Comment by redhatrises** [comment]
> @redhatrises do you feel this PR is resurrectable? :) Or should we close it?

Keep open please.

**Comment by adelton** [comment]
Could you please rebase on the latest master?

**Comment by shawndwells** [comment]
@redhatrises should this PR be closed? There has not been much movement, and organizational interest in an SAP profile seems to have dissipated.

**Comment by shawndwells** [comment]
Closing PR - has been over a year. Feel free to reopen if work resumes!

**Pull request closed without merging**
