### PR TITLE
[WIP] Document one-off utilities

### PR DESCRIPTION
**Pull request by cipherboy**
This commits the `utils/find_similar.py` utility for merging rules into the Linux OS Guide. 

I noticed it was missing from utils directory and want to restructure part of this code for common use.

### CODE REVIEW

**Comment by cipherboy** [comment]
I'm marking this as WIP and taking it as an AI to rework into documenting all of the one-off utilities.

**Comment by jan-cerny** [comment]
@cipherboy We think it would be better to focus on just this one utility in this PR. Do not try to add all other utilities.
Do you still have plans to work on this? Otherwise somebody will pick it up.

**Comment by cipherboy** [comment]
@jan-cerny I'd prefer if someone could pick this one up. :) Thanks!

**Comment by matejak** [comment]
jenkins test this please

**Comment by matejak** [comment]
jenkins test this please

**Comment by matejak** [comment]
jenkins test this please

**Comment by matejak** [comment]
jenkins test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
jenkins test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
jenkins test this please

**Comment by matejak** [comment]
jenkins test this please

**Comment by matejak** [comment]
xxx test this please

**Comment by matejak** [comment]
retest this please

**Comment by matejak** [comment]
retest this please

**Comment by cipherboy** [comment]
I don't delete branches; so this PR serves as documentation enough. I'm going to close this since there's no real need to merge it now that the deduplication has been performed.

**Pull request closed without merging**
