### PR TITLE
SRG-APP-000090-CTR-000155: No longer Does not Meet, but instead covered by setting the OCP audit profile

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- The SRG SRG-APP-000090-CTR-000155 was marked as does not met in the original draft. It's been changed to applicable/configurable
  with the advice to configure the appropriate audit level

#### Rationale:

- OCP4 STIG

#### Review Hints:

- I will post the links to the SRG export later

### CODE REVIEW

**Comment by jhrozek** [comment]
oops, the rule was missing the control reference

**Review by rhmdnd — APPROVED** [review]

**Comment by rhmdnd** [comment]
The testing farm CI has been failing a lot lately. Just comment to ensure it's not related to this patch, right?

**Comment by jhrozek** [comment]
> The testing farm CI has been failing a lot lately. Just comment to ensure it's not related to this patch, right?

I think not, I think the PR was created when there were legitimate issues caused by the changes to the GID check functions. I rebased the PR and will check the CI results.

**Comment by jhrozek** [comment]
The EOF check was failing. I just added one EOF to the control file.

**Pull request merged**
