### PR TITLE
Fix platforms -> platform in test metadata

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

`grep -lr '# platforms = ' linux_os | xargs sed -i "s/# platforms =/# platform =/"`

The keyword `platforms` is not valid.

#### Rationale:

Make the tests work as expected.

### CODE REVIEW

**Comment by Mab879** [comment]
@dodys @mpurg just an FYI.

The reason why I caught this is testing after #12042 was merged.

I might try to add some CI to catch this.

**Comment by dodys** [comment]
perhaps this should be in the ctests?

**Comment by Mab879** [comment]
> @Mab879 Can we have a check in the headers parser for invalid keywords? I assume that it could be difficult because of various comments but we could limit it to check the lines that contains an = sign.

I can, but that should in a separate PR.

**Review by dodys — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
