### PR TITLE
Adopt changes in yamlfilecontent_* check for yamlfile_value template

### PR DESCRIPTION
**Pull request by evgenyz**
These changes would allow to use `yamlfile_value` macro with the new version of the YAML check (openscap 1.3.4).

### CODE REVIEW

**Comment by evgenyz** [comment]
@openshift-ci-robot test this please

**Review by jhrozek — APPROVED** [review]
This seems to unblock the scanner in the sense that it now runs, the rules are checked and report results.
Thank you very much.

**Review by JAORMX — APPROVED** [review]
Waiting for CI run before merging.

**Pull request merged**
