### PR TITLE
Remove warning from kubelet rule

### PR DESCRIPTION
**Pull request by montaguethomas**
#### Description:

#10464 did a major refactor of the kubelet rules to move them from running as "Platform" checkType to "Node". This rule was missed to remove the `warnings` flag, as this causes CO to consider the rule as a Platform checkType.

CO Rule parsing logic:
- https://github.com/ComplianceAsCode/compliance-operator/blob/6bcc5d5d8853885eeec4cf41e7861e467a57eece/pkg/profileparser/profileparser.go#L686-L693
- https://github.com/ComplianceAsCode/compliance-operator/blob/6bcc5d5d8853885eeec4cf41e7861e467a57eece/pkg/utils/parse_arf_result.go#L646-L647C40

#### Rationale:

While trying to tailor out the rule in Compliance Operator, it's impossible to do so as the rule is run as a Node scan but is imported as a Platform checkType.

### CODE REVIEW

**Comment by Vincent056** [comment]
that's a good catch, thanks for fixing it!

**Comment by yuumasato** [comment]
@montaguethomas Hi, thanks for the patch.

Could you rebase on top of latest master?

**Comment by xiaojiey** [comment]
verification passed. 
```
Without the PR, the node type is Platform
$ oc get rule ocp4-kubelet-configure-tls-min-version -o=jsonpath={.checkType}
Platform
With the PR, the node type is Node:
$ oc get rule upstream-ocp4-kubelet-configure-tls-min-version -o=jsonpath={.checkType}
Node
$ oc get ccr | grep kubelet-configure-tls-min-version
upstream-ocp4-high-node-master-kubelet-configure-tls-min-version                        PASS     medium
upstream-ocp4-high-node-worker-kubelet-configure-tls-min-version                        PASS     medium
```

**Review by Vincent056 — APPROVED** [review]

**Pull request merged**
