### PR TITLE
Add Ubuntu 22.04 product

### PR DESCRIPTION
**Pull request by JAORMX**
#### Description:

This introduces Ubuntu 22.04 as a new product.

Also, this tags rules applicable to ubuntu2004 as applicable to ubuntu2204 too
and tags Ubuntu CIS references for 22.04.

### CODE REVIEW

**Review by ggbecker — APPROVED** [review]
The code looks great. It builds correctly, all tests passing. Jinja macro conditions where ubuntu2004 were applicable are also updated with ubuntu2204.

**Comment by ggbecker** [comment]
Let's give a bit more time so somebody else can take a look and see if I didn't miss anything obvious. Probably one more approval here is desired.

**Review by ggbecker — CHANGES_REQUESTED** [review]
I have found more place where you probably need to include `ubuntu2204`:

I basically looked for the keyword `"ubuntu2004"` and `'ubuntu2004'` under the `linux_os/guide` files

https://pastebin.com/CrJLM0DD

**Comment by JAORMX** [comment]
@ggbecker I'll fix those.

**Review by ggbecker — APPROVED** [review]

**Pull request merged**
