### PR TITLE
Add bats to gating and docs

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Installs `bats` in gating and add a doc for it.

#### Rationale:

Will cause issues like #7522 to surface

### CODE REVIEW

**Comment by matejak** [comment]
Why not to add `python3-pytest` and `payhon3-pytest-cov` while we are at it?

**Comment by Mab879** [comment]
@matejak done.

**Comment by jan-cerny** [comment]
@Mab879 I have merged https://github.com/ComplianceAsCode/content/pull/7544 so now please rebase this.

**Comment by ggbecker** [comment]
I have started this https://github.com/ggbecker/content/pull/10 some time ago which adds `bats` among others things... I'll rebase it when this is done.

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
