### PR TITLE
remove deprecated sshd config from e8 profile

### PR DESCRIPTION
**Pull request by shaneboulden**
#### Description:

- The sshd_config UsePrivilegeSeparation option is deprecated, per https://www.openssh.com/txt/release-7.5

### CODE REVIEW

**Comment by redhatrises** [comment]
Ack

**Review by JAORMX — COMMENTED** [review]
Mind removing it from the rhcos4 profiles as well?

**Comment by mildas** [comment]
**Changes identified:**
Profile e8 on rhel7:
 Rule sshd_use_priv_separation removed from e8 profile.
Profile e8 on rhel8:
 Rule sshd_use_priv_separation removed from e8 profile.
Profile ism_o on rhel8:
 ISM_O profile extends changed E8 profile.
Profile e8 on tests:
 Rule sshd_use_priv_separation removed from e8 profile.

**Recommended tests to execute:**
 build_product tests
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-tests-ds.xml e8
 build_product rhel8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml ism_o
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml e8
 build_product rhel7
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel7-ds.xml e8

**Comment by mildas** [comment]
**Changes identified:**
Profile e8 on rhcos4:
 Rule sshd_use_priv_separation removed from e8 profile.
Profile e8 on rhel7:
 Rule sshd_use_priv_separation removed from e8 profile.
Profile hipaa on rhel7:
 Rule sshd_use_priv_separation removed from hipaa profile.
Profile e8 on rhel8:
 Rule sshd_use_priv_separation removed from e8 profile.
Profile ism_o on rhel8:
 ISM_O profile extends changed E8 profile.
Profile hipaa on rhel8:
 Rule sshd_use_priv_separation removed from hipaa profile.
Profile e8 on tests:
 Rule sshd_use_priv_separation removed from e8 profile.

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel7-ds.xml e8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel7-ds.xml hipaa
 build_product rhel8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml ism_o
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml e8
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel8-ds.xml hipaa
 build_product tests
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-tests-ds.xml e8
 build_product rhcos4
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhcos4-ds.xml e8

**Comment by shaneboulden** [comment]
@JAORMX I've removed this from the E8 RHCOS profile.

@redhatrises I also noticed this check in the HIPAA profiles for RHEL7/RHEL8 - I've added a separate commit here, I can drop it out if you want to retain the config option.

**Pull request merged**
