### PR TITLE
Increase OCP4 e2e sleep

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by shawndwells** [comment]
@JAORMX saw your edit in https://github.com/ComplianceAsCode/content/pull/5589/ to increase the e2e timeout. What do you think about splitting that part off from your PR and merging here? Looks like we are both hitting the same issues. Hopefully this unblocks both of us while we work on other PRs :)

**Comment by JAORMX** [comment]
@shawndwells I actually tracked down the issue and already submitted a PR. It was a bug in the compliance-operator: https://github.com/openshift/compliance-operator/pull/213

The PR hasn't merged cause the openshift installer is currently broken... and so is all of OpenShift CI today.

**Comment by shawndwells** [comment]
> @shawndwells I actually tracked down the issue and already submitted a PR. It was a bug in the compliance-operator: [openshift/compliance-operator#213](https://github.com/openshift/compliance-operator/pull/213)
> 
> The PR hasn't merged cause the openshift installer is currently broken... and so is all of OpenShift CI today.

Well dang. Do you suggest we hold off on merging OpenShift-related PRs today?

**Comment by JAORMX** [comment]
Yep. Let's hold off until CI gets fixed.

**Comment by JAORMX** [comment]
This is no longer needed. OpenShift CI is working again, and the issue is fixed in the compliance-operator.

**Pull request closed without merging**
