### PR TITLE
Enable RHV-H and RHEL-H draft STIG profiles

### PR DESCRIPTION
**Pull request by redhatrises**
Since this are being mapped and developed now, let's enable them.

### CODE REVIEW

**Comment by shawndwells** [comment]
@redhatrises multiple build failures

**Comment by redhatrises** [comment]
> @redhatrises multiple build failures

That's fun. I will submit the fix at a later time.

**Comment by redhatrises** [comment]
@shawndwells build is passing now.

**Comment by shawndwells** [comment]
Nice! Thanks for adding the prodtype mappings.

**Pull request merged**
