### PR TITLE
Banner and cron permissions and owners

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Update CIS profile with rules and cron file permissions and owners
- Add rules for banner permissions
- Update CIS references for all rules mentioned above

### CODE REVIEW

**Comment by redhatrises** [comment]
If the CIS references are literally the same, I don't think it makes sense to break them out.

**Comment by redhatrises** [comment]
If the CIS references are literally the same, I don't think it makes sense to break them out.

**Comment by yuumasato** [comment]
> If the CIS references are literally the same, I don't think it makes sense to break them out.

Now they are specific for RHEL instead of being totally generic. The requirement number varies greatly from product and version.

**Comment by vojtapolasek** [comment]
I am not sure if there is any benefit in adding the chmod / chown commands directly to the profile as a comment. From my point of view it is another thing which needs to be checked if it matches with the corresponding rule... othervise LGTM. Thank you.

**Comment by vojtapolasek** [comment]
Concerning the cis references, I see a benefit in having them split now even if they are currently the same for rhel7 and rhel8. I think this is a futureproof solution. We have no certainty that they won't change for example for rhel9. If we keep it as it is, we will have to go through all of them later and create variants for rhel7 / rhel8 / rhel9 in case they change in rhel9 or even later.

**Comment by yuumasato** [comment]
> I am not sure if there is any benefit in adding the chmod / chown commands directly to the profile as a comment. From my point of view it is another thing which needs to be checked if it matches with the corresponding rule...

I followed the practice in the PR for other rules.
From my PoV, it makes it very clear what rules are covering what aspects of the requirement.
But it also means more work for the author, and also for the reviewer, as you mentioned.
If the Benchmark is updated these comments can go out of date.

I don't have a strong opinion on this.

**Comment by vojtapolasek** [comment]
I agree that these notes are very ilustrative. Maybe we could later, when the profile is finalized, state somewhere, that these notes might not be exactly up-to-date. Other things look goot in this PR.

**Pull request merged**
