### PR TITLE
products/alinux3: supports Alibaba Cloud Linux 3

### LINKED ISSUE #8657: products: Support Alibaba Cloud Linux 3
#### Description of problem:

Now OpenSCAP supports many products but it doesn't support Alibaba Cloud Linux 3.

So I want to add the produce/alinux3 into OpenSCAP.

### PR DESCRIPTION
**Pull request by hustliyilin**
#### Description:

products/alinux3: supports Alibaba Cloud Linux 3.

#### Rationale:

- OpenSCAP now supports many products. Alibaba Cloud Linux 3 is an OS product and it is compatible with Redhat 8. So I want to add the produce/alinux3 into OpenSCAP.

- Fixes #8657

### CODE REVIEW

**Comment by ggbecker** [comment]
@hustliyilin please rebase this and resolve conflicts as alinux2 has been merged.

**Comment by hustliyilin** [comment]
> @hustliyilin please rebase this and resolve conflicts as alinux2 has been merged.

Hi @ggbecker ,

Thanks a lot, I rebased the master branch and resolved all conflicts.  And the testings of CI/CDs is now underway, thanks again.

**Comment by hustliyilin** [comment]
> Thanks a lot. I already rebased these codes and resolved all conflicts. All Gate CI/CDs passed. I would be very grateful if you could review this pr again. Thanks again

Hi @jan-cerny , 

Thanks a lot. I already rebased these codes and resolved all conflicts. All Gate CI/CDs passed. I would be very grateful if you could review this pr again. Thanks again

**Review by jan-cerny — APPROVED** [review]
The sanity looks great! Thank you very much!

**Pull request merged**
