### PR TITLE
OCP4 STIG: Fix up rules that dealt with network policy

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

This PR started as a patch to fix SRG-APP-000038-CTR-000105 but I went a
little overboard and checked all controls that deal with network policies
and routes.

- OCP4 STIG: SRG-APP-000038-CTR-000105: Move metadata to the policy file, select the correct rules - This is the meat of this PR. This control is resolved by making sure that all namespaces have NetworkPolicies. Let's move the checks and fixes to the per-rule policy files and remove all unrelated SRGs from rhe rules themselves.
- OCP4 STIG: SRG-APP-000141-CTR-000315: Add artifact description and justification, remove spurious rule: A rule that is inherently met shouldn't be resolved by a rule.
- OCP4 STIG: SRG-APP-000141-CTR-000320: Fix rules, add check and fix, fix status - This is a manual rule that is not solved by a particular rule, but instead has a number of other related rules that pertain to configuration of registries. Also adds the check and fix texts.
- OCP4 STIG: SRG-APP-000142-CTR-000325: Remove spurious rule, add mitigation and status_justification - A rule with a does not meet status should have a mitigation and status justification.
- OCP4 STIG: SRG-APP-000645-CTR-001410: Fix rules, add artifact_description and status_justification - A rule that's inherently met shouldn't be resolved by a rule, but should have supporting evidence and status justification.
- OCP4 STIG: Remove configure_network_policies and configure_network_policies_namespaces from controls that are not resolved by these rules - This is a catch-all where we remove configure_network_policies_namespaces and configure_network_policies and routes_protected_by_tls from the `rules:` attribute of unrelated controls. We fix those controls in a later patch.
- OCP4 STIG: routes_protected_by_tls pertains to SRG-APP-000441-CTR-001090 and SRG-APP-000442-CTR-001095, not SRG-APP-000441-CTR-001090 - SRG-APP-000441-CTR-001090 and SRG-APP-000442-CTR-001095 talk about integrity, SRG-APP-000441-CTR-001090 is about network segmentation.

#### Rationale:

- Clean up the OCP4 STIG.

#### Review Hints:

- `./build_product --debug ocp4`
- `export PYTHONPATH=$(pwd); python3 ./utils/rule_dir_json.py`
- `export PYTHONPATH=$(pwd); python3 utils/create_srg_export.py -c controls/srg_ctr.yml -p ocp4 -m shared/references/disa-ctr-srg-v1r3.xml --out-format html --output /tmp/srg-mapping-ocp4.html`
- compare the controls touched by this PR with [STIG draft](https://docs.google.com/spreadsheets/d/1oTUEUSkpumEpGqeBvhEHkJxcGUxMgoG1/edit#gid=959715005)

### CODE REVIEW

**Comment by jhrozek** [comment]
/retest
none of the test clusters installed

**Comment by jhrozek** [comment]
more cluster install issues
/retest

**Comment by jhrozek** [comment]
This time the operator didn't install, might be an outage
/retest

**Comment by jhrozek** [comment]
/test e2e-aws-ocp4-e8
inredible, only one OCP test failed

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
