### PR TITLE
Ubuntu 24.04 1.3.1.1 Ensure AppArmor is installed

### PR DESCRIPTION
**Pull request by ericeberry**
#### Description:

- Ubuntu 24.04 1.3.1.1 Ensure AppArmor is installed

#### Rationale:

- Implement Ubuntu 24.04 1.3.1.1 Ensure AppArmor is installed

### CODE REVIEW

**Review by mpurg — APPROVED** [review]
lgtm

**Review by dodys — CHANGES_REQUESTED** [review]
this is failing in ctest:
```
Rule 'package_apparmor-utils_installed' must be assigned to component 'apparmor-utils', because rule uses template 'package_installed' with 'pkgname' parameter set to 'apparmor-utils' which is a package that already belongs to component 'apparmor-utils'.
```

**Comment by ericeberry** [comment]
> this is failing in ctest:
> 
> ```
> Rule 'package_apparmor-utils_installed' must be assigned to component 'apparmor-utils', because rule uses template 'package_installed' with 'pkgname' parameter set to 'apparmor-utils' which is a package that already belongs to component 'apparmor-utils'.
> ```

New apparmor-utils created

**Comment by mpurg** [comment]
Looks like it needs to be also in the `apparmor` component:
```
Rule 'package_apparmor-utils_installed' must be in component 'apparmor' because it's a member of 'apparmor' group.
```

**Comment by ericeberry** [comment]
> Looks like it needs to be also in the `apparmor` component:
> 
> ```
> Rule 'package_apparmor-utils_installed' must be in component 'apparmor' because it's a member of 'apparmor' group.
> ```

Added back

**Review by dodys — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
