### PR TITLE
Update ISM and E8 profile SMEs

### PR DESCRIPTION
**Pull request by shaneboulden**
Updates the SMEs for the Australian ISM and E8 profiles

### CODE REVIEW

**Comment by vojtapolasek** [comment]
Hello @shaneboulden . The PR is technically OK. However, I have a question.
What are your expectations from appending the list of SMEs for those profiles?And what can we expect from them?
The concept of SMEs is currently a little blury.
The reason why I am asking is the fact that it was not possible to get much information from Github profiles of handles you want to add. Therefore, we do not know much about experience or expertise of those people... Could you bring a bit more information please?
There was an idea of restructuring the SME field a bit more to provide more information, but the conclusion has not been done yet.Thank you.

**Comment by shaneboulden** [comment]
Hi @vojtapolasek 

I completely agree. 

Often when creating a new profile or aligning technical controls with a policy document there is a lot of behind-the-scenes work that occurs, however only one user will be reflected in the CaC commit history.

These handles have all contributed significantly to mapping ISM controls to technical controls. However, there was only a single commit made initially to the repo. We can expect that these contributors will be able to understand contextually any changes made to the profile, and understand the impacts and provide guidance for usage of the profile.

Maybe SMEs isn't the best section - collaborators? contributors?

**Review by vojtapolasek — APPROVED** [review]
Hello @shaneboulden and thank you for the explanation. It suffices and I will merge the PR.
I have two notes:
1. You wrote: These handles have all contributed significantly to mapping ISM controls to technical controls.
Have you considered using our control files instead of simple profile definitions? I see several benefits if you decide to use them. They better represent the relationship among security policy controls and actual technical controls. They allow usage of various attributes and notes so that the file is more comfortable to read and easier to analyze. You can see the example control file here:
https://github.com/ComplianceAsCode/content/blob/master/controls/cis_rhel8.yml
And you can read more about control files here:
https://complianceascode.readthedocs.io/en/latest/manual/developer/03_creating_content.html#controls
2. I think that new contributors you add in this PR should consider joining our project Gitter located at
https://gitter.im/Compliance-As-Code-The/content
It is a place where discussions among community members happen.

**Pull request merged**
