### PR TITLE
OCP4: Add check that a FIO object exists in the cluster

### PR DESCRIPTION
**Pull request by jhrozek**
This is needed for controls such as SC-4(23),SI-6,SI-7,SI-7(1),CM-6(a)

Jira: CMP-900

note that the test will most probably fail until CI runs the next release
of CO..

### CODE REVIEW

**Comment by JAORMX** [comment]
```
 INFO[2021-05-27T13:35:35Z]     helpers.go:723: E2E-FAILURE: The expected result for the file_integrity_exists rule didn't match. Expected 'PASS', Got 'FAIL' 
```

This is an expected failure. We need a new CO release for this to work.

**Review by JAORMX — APPROVED** [review]
lgtm

**Comment by JAORMX** [comment]
@jhrozek feel free to merge if it passes CI

**Comment by jhrozek** [comment]
/retest
looks like cluster install failed

**Comment by jhrozek** [comment]
Cluster install error again:
``ERRO[2021-06-02T15:14:34Z] level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change`
```

**Comment by JAORMX** [comment]
Seems there's something wrong in the rule:
```
 INFO[2021-06-03T07:27:47Z]     helpers.go:723: E2E-FAILURE: The expected result for the file_integrity_exists rule didn't match. Expected 'PASS', Got 'FAIL' 
```

**Comment by JAORMX** [comment]
The issue is that you were missing executable permissions from the remediation script:
```
helpers.go:913: Failed applying remediation '/go/src/github.com/ComplianceAsCode/content/applications/openshift/integrity/file_integrity_exists/tests/ocp4/e2e-remediation.sh': fork/exec /go/src/github.com/ComplianceAsCode/content/applications/openshift/integrity/file_integrity_exists/tests/ocp4/e2e-remediation.sh: permission denied 
```

**Comment by JAORMX** [comment]
@openscap-ci test this please

**Pull request merged**
