### PR TITLE
Document rule.yml modification utilities

### PR DESCRIPTION
**Pull request by cipherboy**
`Signed-off-by: Alexander Scheel <alex.scheel@canonical.com>`

---

This provides documentation for `mod_prodtype.py` and the utilities/modifications to utilities in #6882, ~~#6906~~, #6907, and #6908.

It should probably wait to merge until all of those utilities have merged.

### CODE REVIEW

**Comment by carlosmmatos** [comment]
Just my 2c - but wouldn't it make more sense to keep the doc updates together with the utility updates/additions? Since your PR's are still open for those, seems like we can still accomplish this. What do you think?

**Comment by cipherboy** [comment]
> What do you think?

I actually got distracted right after I submitted this PR chasing other shiny things. :D

I was hoping to also document `utils/mod_checks.py`, `utils/mod_fixes.py`, `rule_dir_stats.py` and `rule_dir_diff.py`. 

Those plus `fix_rules.py` and `mod_prodtype.py` are technically existing (minus the new functionality in `fix_rules.py` and its rename from `fix-rules.py` -- so I figured I'd rather group the doc changes while I was writing them.  `¯\_(ツ)_/¯`

I can split them if you'd prefer though.

**Review by Mab879 — APPROVED** [review]
LGTM

**Comment by cipherboy** [comment]
Thanks Matt! Since this is a documentation PR (and the corresponding code changes landed in #6882 and other PRs), going ahead and merging. We can always document more later.

**Pull request merged**
