### PR TITLE
Add nodev Option to /var.

### PR DESCRIPTION
**Pull request by adelton**
#### Description:

- Add nodev Option to /var.

#### Rationale:

- The only legitimate location for device files is the /dev directory located on the root partition.

### CODE REVIEW

**Comment by adelton** [comment]
Similar to https://github.com/ComplianceAsCode/content/pull/4452 or https://github.com/ComplianceAsCode/content/pull/4453, we'd need to know the severity, the references, whether to list older RHEL versions, and if to add this to the `ospp.profile` files right away.

**Comment by yuumasato** [comment]
@adelton References and severity can be set similar to #4452.
As `ospp` profile is being reworked, I suggest to add the rule there later.
And I would say to enlist older RHEL versions and their profiles later, to avoid scope creeping this PR.

**Comment by shawndwells** [comment]
CM-7 for the NIST references.

**Comment by adelton** [comment]
Updated, rebased on master -> 6e11fdb1762fb7e730c6e509f5ec0ee76fca0005.

**Pull request merged**
