### PR TITLE
Add password pam accounts rules to fedora

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Fill up csv file for `accounts_password_pam_` rules
- Add test for `accounts_password_pam_ocredit`

#### Rationale:

- These rules apply for Fedora, lets just generate them all.

### CODE REVIEW

**Comment by yuumasato** [comment]
I plan to add tests for other rules, or work something out for the templated rules.
Some smart testing for templated rules...

**Comment by dahaic** [comment]
@yuumasato so are we waiting for #3244 ? Or will you just make preliminary trivial test coverage, and proper one will be added later?

**Comment by yuumasato** [comment]
> @yuumasato so are we waiting for #3244 ?

@dahaic I was waiting for it, but the author seems to be slacking off.

> Or will you just make preliminary trivial test coverage, and proper one will be added later?

We can reduce scope of this to just test `accounts_password_pam_ocredit`, and expand it later...

**Comment by yuumasato** [comment]
I'll extend the test for other rules when template testing is introduced.

**Pull request merged**
