### PR TITLE
Update sysctl template's OVAL and tests to align with STIG

### PR DESCRIPTION
**Pull request by Xeicker**
#### Description:

- Update OVAL to allow multiple static values, but ensure all of them are valid
- Update tests to validate new behavior
- The code to generate `SYSCTL_WRONG_VALUE` was updated since the tests were having an issue when setting the runtime value. Apparently the previous way of obtaining that value was generating invalid confs 

#### Rationale:

- The condition to only accept one configuration was introduced here: https://github.com/ComplianceAsCode/content/pull/8656 as a STIG alignment. But now the STIG requirement has been updated from

> If results are returned from more than one file location, this is a finding.

to

> If conflicting results are returned, this is a finding.

### CODE REVIEW

**Review by yuumasato — CHANGES_REQUESTED** [review]
Great work, @Xeicker 

Thank you for updating the tests and adding new ones!

Please, update the template documentation as well:
https://github.com/ComplianceAsCode/content/blob/master/docs/templates/template_reference.md#sysctl

**Comment by Mab879** [comment]
> I don't know what is going on with the CI, it is complaining that two rules have the same CCE, but they have completely unrelated CCEs.
> 
> ```
>  44/164 Test  #44: unique-cces .........................................................***Failed    0.37 sec
> 
> cce CCE-91667-6 is included in files: 
>  - linux_os/guide/services/cron_and_at/file_permissions_crontab/rule.yml
>  - linux_os/guide/services/cron_and_at/service_cron_enabled/rule.yml
> ```
> 
> Does anybody from @ComplianceAsCode/red-hatters have any idea what is going on?

That should be fixed by #9622.

**Comment by yuumasato** [comment]
@Mab879 So does @Xeicker need to rebase latest master?

**Comment by Mab879** [comment]
> @Mab879 So does @Xeicker need to rebase latest master?

Yes

**Review by yuumasato — APPROVED** [review]
The changes look good to me, but I think CI is still flaking out here.

**Comment by ggbecker** [comment]
There was a github outage yesterday and that's probably why the github checks have not started. https://www.githubstatus.com/history

@Xeicker can you please amend the last commit message and force push so it can trigger the required jobs?

Thank you.

**Pull request merged**
