### PR TITLE
Adding RHEL-08-010120 to RHEL 8 STIG profile

### PR DESCRIPTION
**Pull request by carlosmmatos**
#### Description:

Add RHEL8 to existing `accounts_password_all_shadowed_sha512` rule to satisfy STIG ID: RHEL-08-010120

### CODE REVIEW

**Comment by ggbecker** [comment]
Maybe you could add some test scenarios to validate the OVAL. This rule doesn't have any.

**Comment by carlosmmatos** [comment]
> Maybe you could add some test scenarios to validate the OVAL. This rule doesn't have any.

I can do that.

**Review by ggbecker — APPROVED** [review]
LGTM

**Pull request merged**
