### PR TITLE
Fix automatus podman

### PR DESCRIPTION
**Pull request by alanmcanonical**
#### Description:

- Create test_suite-ubuntu2204
- Fix the container sshd problem

### CODE REVIEW

**Comment by jan-cerny** [comment]
In the logs we can see that the problem is `No profile matching suffix "(all)" was found. Get available profiles using`. I think that it might be caused by the prehistoric version of OpenSCAP, but I don't remember from the top of my head in which version the virtual all profile has been introduced.

**Comment by jan-cerny** [comment]
So according to https://github.com/OpenSCAP/openscap/blob/main/NEWS the virtual profiles have been introduced in 1.3.0. I don't know if Ubuntu/Debians have backported it to older version but it doesn't seem so.

**Comment by dodys** [comment]
> So according to https://github.com/OpenSCAP/openscap/blob/main/NEWS the virtual profiles have been introduced in 1.3.0. I don't know if Ubuntu/Debians have backported it to older version but it doesn't seem so.

would it be possible to just define a profile, instead of running with virtual profiles?

**Comment by jan-cerny** [comment]
We want to test the rule separately, outside of the profile context, as the rules are in general shared among multiple profiles.

**Comment by dodys** [comment]
@jan-cerny @Mab879 so we went with the easy path of in the container manually building and installing openscap. Let me know your thoughts.

**Comment by Mab879** [comment]
> @jan-cerny @Mab879 so we went with the easy path of in the container manually building and installing openscap. Let me know your thoughts.

I'm okay that. It doesn't seem to take too long, just about minute or two.

**Comment by Mab879** [comment]
> @Mab879 or @jan-cerny if we could merge this one today, it would be nice to use to test some PRs that arrived recently

Everything is looks good. The example commit triggering the CI needs to removed then we can merge.

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
