### PR TITLE
Add basic test scenarios for a few audit rules

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

Basic test scenarios for following rules:
- audit_rules_dac_modification_fchown
- audit_rules_file_deletion_events_rename
- audit_rules_kernel_module_loading_init
- audit_rules_media_export
- audit_rules_networkconfig_modification

Basic test scenario means, no rules configured, and correct rules
are there (in single -S arg)

### CODE REVIEW

**Comment by jan-cerny** [comment]
@yuumasato The code looks good to me, but there is an offending test scenario in rule `audit_rules_kernel_module_loading_init`. Can you take a look at it?

```
[jcerny@thinkpad tests{yuumasato-basic_audit_test_scenarios}]$ python3 test_suite.py rule --libvirt qemu:///system ssgts_rhel8 --datastream ../build/ssg-rhel8-ds.xml audit_rules_dac_modification_fchown
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-10-08-1433/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_dac_modification_fchown
INFO - Script rules_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script correct_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
[jcerny@thinkpad tests{yuumasato-basic_audit_test_scenarios}]$ python3 test_suite.py rule --libvirt qemu:///system ssgts_rhel8 --datastream ../build/ssg-rhel8-ds.xml audit_rules_file_deletion_events_rename
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-10-08-1435/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_file_deletion_events_rename
INFO - Script rules_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script correct_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
[jcerny@thinkpad tests{yuumasato-basic_audit_test_scenarios}]$ python3 test_suite.py rule --libvirt qemu:///system ssgts_rhel8 --datastream ../build/ssg-rhel8-ds.xml audit_rules_kernel_module_loading_init
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-10-08-1437/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_init
ERROR - Script default.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_init has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_kernel_module_loading_init'.
INFO - Script correct_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
[jcerny@thinkpad tests{yuumasato-basic_audit_test_scenarios}]$ python3 test_suite.py rule --libvirt qemu:///system ssgts_rhel8 --datastream ../build/ssg-rhel8-ds.xml audit_rules_media_export
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-10-08-1438/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_media_export
INFO - Script rules_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script correct_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
[jcerny@thinkpad tests{yuumasato-basic_audit_test_scenarios}]$ python3 test_suite.py rule --libvirt qemu:///system ssgts_rhel8 --datastream ../build/ssg-rhel8-ds.xml audit_rules_networkconfig_modification
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/scap-security-guide/tests/logs/rule-custom-2019-10-08-1439/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_networkconfig_modification
INFO - Script rules_not_there.fail.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script correct_rules.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
```

**Comment by yuumasato** [comment]
@jan-cerny Nice catch, test scenario metadata upated.

**Comment by jan-cerny** [comment]
@yuumasato you're great

**Comment by yuumasato** [comment]
Thanks for the review.

**Pull request merged**
