### PR TITLE
Initial OSPP Control File

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:
Create Initial OSPP control file.

This is an automatically created using the script in this branches history.

#### Rationale:
Get the RHEL 10  draft OSPP profile ready.

### CODE REVIEW

**Comment by marcusburghardt** [comment]
@ggbecker , could you take a look, please?

**Comment by Mab879** [comment]
@ggbecker If you suggestions for titles please let me know.

**Comment by Mab879** [comment]
Script for creating this has been posted in #11916

**Comment by ggbecker** [comment]
> @ggbecker If you suggestions for titles please let me know.

A few things I noticed here.

First, some references changed from OSPP 4.2.1 to 4.3, for example: https://www.niap-ccevs.org/MMO/PP/-442-/#FCS_COP.1(1) is now https://www.niap-ccevs.org/MMO/PP/OS%204.3%20PP/#FCS_COP.1/ENCRYPT, so there is a small change in how it's represented: FCS_COP.1(1) -> FCS_COP.1/ENCRYPT.

Second, you can use the title as defined in this for example: https://www.niap-ccevs.org/MMO/PP/OS%204.3%20PP/#FCS_COP.1/ENCRYPT -> `Cryptographic Operation - Encryption/Decryption (Refined)`

and last, this table contains the rationale for each requirement that could be used in the description of each control defined: https://www.niap-ccevs.org/MMO/PP/OS%204.3%20PP/#obj-req-map

**Pull request merged**
