### PR TITLE
create new ignition files for /etc/audit/auditd.conf

### PR DESCRIPTION
**Pull request by npoyant**
…_pattern/ignition/shared.yml

#### Description:

- created ignition file for sysctl rule

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci  test this please

**Comment by JAORMX** [comment]
/hold

Let's hold off merging these ones. First let's come up with unit tests to identify that the contents that change the same file are identical.

**Comment by JAORMX** [comment]
Adding unit tests here: https://github.com/ComplianceAsCode/content/pull/5743

**Comment by JAORMX** [comment]
Could this be rebased so we run the unit tests on this?

**Pull request merged**
