### PR TITLE
Anssi R18 password robustness

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Establish a general password robustness baseline for ANSSI R18 based on [ANSSI DAT-NT-001](https://www.ssi.gouv.fr/guide/mot-de-passe/).
- The baseline should be reviwed and tailored to each deployment.
- The baseline applies to root and unprivileged user.
  - Renew passwords every 90 days
  - Ensure passwords with minimum of 12 characters
  - Enforce password length for new accounts
  - Require at Least 1 Special Character in Password
  - Require at Least 1 Numeric Character in Password
  - Require at Least 1 Uppercase Character in Password
  - Require at Least 1 Lowercase Character in Password
  - Lock out the user after 3 failed authentication attempts within 15 min
  - Automatically unlock user after 15 min to prevent DoS
  - Do not reuse last two passwords

### CODE REVIEW

**Review by jan-cerny — APPROVED** [review]
looks fine

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
Much needed to finalize the minimal level of hardening. Thanks!

**Pull request merged**
