### PR TITLE
Added SLES 12 and SLES 15 CCE codes to the rule package_openldap-serv…

### PR DESCRIPTION
**Pull request by rumch-se**
…ers_removed

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

### CODE REVIEW

**Comment by rumch-se** [comment]
Two CCE for SLE 12 and SLE 15 codes are added to the rule 
./services/ldap/openldap_server/package_openldap-servers_removed

**Review by ggbecker — CHANGES_REQUESTED** [review]
you need to put the CCEs after the RHEL ones because of a test that checks for lexicographical order

**Comment by rumch-se** [comment]
Hi @ggbecker 
Thank you for your feedback.
I have done the proposed change. https://github.com/ComplianceAsCode/content/pull/9605/commits/c3f4f14b37f34d66b507a6d84a62b5606934dc65 
Have a nice day

**Review by ggbecker — APPROVED** [review]

**Comment by ggbecker** [comment]
please rebase this on latest main branch so we can merge it. Thanks

**Comment by rumch-se** [comment]
Hello 
@ggbecker 
I have done rebase
Have a nice day
Rumen

**Pull request merged**
