### PR TITLE
Remove kubernetes hardcoded solution for templated service_debug rules

### PR DESCRIPTION
**Pull request by CoreyCook8**
#### Description:

service_debug-shell_disabled and service_autofs_disabled have hardcoded remediations for the Kubernetes lang but templates exist for these rules.

Also, updates the jinja macro to reflect masking the service/socket.

Prior to this change there are two different fixes created for ignition and kubernetes

```
<xccdf-1.2:fix system="urn:xccdf:fix:script:kubernetes" id="service_autofs_disabled">---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - enabled: false
        name: autofs.service
</xccdf-1.2:fix>
<xccdf-1.2:fix system="urn:xccdf:fix:script:ignition" id="service_autofs_disabled" complexity="low" disruption="medium" reboot="true" strategy="disable">apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - name: autofs.service
        enabled: false
        mask: true
      - name: autofs.socket
        enabled: false
        mask: true
</xccdf-1.2:fix>
```

After this change, the kubernetes lang takes the templated version and the two fixes are identical.

```
<xccdf-1.2:fix system="urn:xccdf:fix:script:kubernetes" id="service_autofs_disabled" complexity="low" disruption="medium" reboot="true" strategy="disable">apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - name: autofs.service
        enabled: false
        mask: true
      - name: autofs.socket
        enabled: false
        mask: true
</xccdf-1.2:fix>
<xccdf-1.2:fix system="urn:xccdf:fix:script:ignition" id="service_autofs_disabled" complexity="low" disruption="medium" reboot="true" strategy="disable">apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - name: autofs.service
        enabled: false
        mask: true
      - name: autofs.socket
        enabled: false
        mask: true
</xccdf-1.2:fix>
```

#### Rationale:

There is no need to create hardcoded remediation files for these since the template files exist.

Also, when using the OpenShift Compliance Operator, the fix used for this depends on the ordering of these fixes. In my case, the kubernetes fix was before the ignition fix in the list. This caused the compliance operator to apply the kubernetes fix which failed to mask the service.

If the rule is going to check for the services to be masked, then all of the available remediations should mask the service.

### CODE REVIEW

**Comment by CoreyCook8** [comment]
👋 Could I get some eyes on here when someone has a chance?

**Comment by CoreyCook8** [comment]
Hey @rhmdnd could I get some 👀 on this one when you have a chance please? 🙏

**Comment by rhmdnd** [comment]
Thanks for the patch @CoreyCook8.

Testing this rule against a dev cluster and I noticed the default result changed since https://github.com/ComplianceAsCode/content/commit/1ce0c75b2d9e33f659301874450286b6d9c69dc4 landed.

Running e2e tests to see what the outcome is of this patch with those changes.

**Comment by rhmdnd** [comment]
Based on the e2e results - this appears to be failing because the autofs package isn't installed.

https://github.com/ComplianceAsCode/content/pull/11546 should fix the e2e issues, but we might need to validate a different way to make sure the remediation still works (installing autofs manually).

**Comment by CoreyCook8** [comment]
Hey @rhmdnd looks like we are passing the tests now

**Comment by rhmdnd** [comment]
@CoreyCook8 looks like some of the build tests are hung up. @Mab879 should we just rekick these?

**Comment by CoreyCook8** [comment]
Any way I can help rekick those?

**Comment by Mab879** [comment]
> @CoreyCook8 looks like some of the build tests are hung up. @Mab879 should we just rekick these?

Sorry, I just saw this. First time contributors need approval for the CI to run. I just gave the approval. 

@rhmdnd you should be able to do this as well.

**Comment by CoreyCook8** [comment]
@rhmdnd looks good to go?

**Comment by yuumasato** [comment]
@CoreyCook8 Hi, sorry for the delay, the changes look good to me.

But could you please remove the `merge` commits? One way to do it is to:
```console
$ git rebase --onto master 49de0664014309054881de12e2b73993951849ce~1 a710b6f5fbfa6ad22145c283505d2ec5148c1238
$ git checkout -B patch-1 HEAD
```

**Comment by CoreyCook8** [comment]
👋 @yuumasato Look alright now?

**Review by yuumasato — APPROVED** [review]

**Pull request merged**
