### PR TITLE
edit bash for smartcard_configure_cert_checking

### PR DESCRIPTION
**Pull request by cyarbrough76**
#### Description:

- _add condition to check for and install pcsc-lite_

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule smartcard_configure_cert_checking:
 Found change in bash remediation.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml smartcard_configure_cert_checking

**Comment by vojtapolasek** [comment]
Hello, thank you for the proposed change. As this rule does not have oval check, it is not possible to test it. Could you please explain why do you propose this change?

**Comment by matejak** [comment]
Regarding what they write at https://pcsclite.apdu.fr/ it looks like that it is a package that is related to smart cards. Therefore, I think that it can't cause regressions, and it looks quite reasonable.

**Comment by matejak** [comment]
I take it back - running `yum whatprovides /etc/pam_pkcs11/pam_pkcs11.conf` (file referenced later in the remediation) returns the `pam_pkcs11` package, `pcsc-lite` provides different files.
Therefore, the proposed change breaks the remediation, and the change hasn't been explained. Therefore, I close this PR.

**Pull request closed without merging**
