### PR TITLE
OCP4: Port ocp4-cis rules to moderate profile

### PR DESCRIPTION
**Pull request by JAORMX**
They are relevant since they address the CM-6 control. This also adds
the needed references.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now e270ea4f158afe21ca11b56ddf05fe602e5089a4

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now b3301ba584c21816d9677bf386e3c42fd1f6fb36

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 65371b8438e69aafec60a0a396fb42f1c6bfe7a9

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 074a9f7545e944feae121958b3b93f8f8cf3d02f

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now cb49d3e4779d0b9494783d53e4a3d86fca52cf30

**Review by jhrozek — APPROVED** [review]
lgtm

**Pull request merged**
