### PR TITLE
Fix manual remediation for SPO rule

### PR DESCRIPTION
**Pull request by rhmdnd**
We have a manual remediation for installing SPO, but it was failing
in our e2e suite with the following error:

  fork/exec /go/src/github.com/ComplianceAsCode/content/applications/openshift/confinement/security_profiles_operator_exists/tests/ocp4/e2e-remediation.sh: permission denied

This commit updates the script so that it's executable and doesn't fail
when applied.

### CODE REVIEW

**Comment by rhmdnd** [comment]
Looks like we need another fix for the remediation:

```
installing security profiles operator
+ oc apply -f /go/src/github.com/ComplianceAsCode/content/ocp-resources/e2e/spo-install.yaml --server-side=true
error: the path "/go/src/github.com/ComplianceAsCode/content/ocp-resources/e2e/spo-install.yaml" does not exist 
```

**Comment by yuumasato** [comment]
> Looks like we need another fix for the remediation:
> 
> ```
> installing security profiles operator
> + oc apply -f /go/src/github.com/ComplianceAsCode/content/ocp-resources/e2e/spo-install.yaml --server-side=true
> error: the path "/go/src/github.com/ComplianceAsCode/content/ocp-resources/e2e/spo-install.yaml" does not exist 
> ```

Well, that is weird, the file exists...

**Comment by rhmdnd** [comment]
> > Looks like we need another fix for the remediation:
> > ```
> > installing security profiles operator
> > + oc apply -f /go/src/github.com/ComplianceAsCode/content/ocp-resources/e2e/spo-install.yaml --server-side=true
> > error: the path "/go/src/github.com/ComplianceAsCode/content/ocp-resources/e2e/spo-install.yaml" does not exist 
> > ```
> 
> Well, that is weird, the file exists...

I don't see it in that directory.

```
╭─lbragstad@p1 ~/Projects/content ‹master›
╰─➤  $ git log -n1           
commit aa881c3d0d589eb8e726bed948eb572b0ed84636 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: 53f90ecc18 0df3c5dd1d
Author: Eduardo Barretto <eduardo.barretto@canonical.com>
Date:   Tue Aug 20 11:52:17 2024 +0200

    Merge pull request #12298 from ericeberry/master
    
    Ubuntu 22.04 STIG V2R1 changes
╭─lbragstad@p1 ~/Projects/content ‹master›
╰─➤  $ find . -type f -name spo-install.yaml
╭─lbragstad@p1 ~/Projects/content ‹master›
╰─➤  $ 
```

https://github.com/ComplianceAsCode/content/tree/master/ocp-resources/e2e shows some of the other files we rely on - but it looks like we forgot to add `spo-install.yaml`.

**Comment by yuumasato** [comment]
No way!
```
git status ocp-resources/
On branch update_ocp4_stig_to_v2r1
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ocp-resources/e2e/spo-install.yaml

nothing added to commit but untracked files present (use "git add" to track)

```

**Comment by yuumasato** [comment]
@rhmdnd pushed the file on https://github.com/ComplianceAsCode/content/pull/12317
I forgot to add it, :facepalm:

**Comment by rhmdnd** [comment]
Rebased to pickup https://github.com/ComplianceAsCode/content/pull/12317

**Comment by yuumasato** [comment]
@rhmdnd Addressing the metadata in 72743aa

/test 4.16-e2e-aws-ocp4-pci-dss-4-0

**Comment by yuumasato** [comment]
> Looks like the deployment times out, causing the manual remediation to fail.
> 
> ```
> Error from server (NotFound): subscriptions.operators.coreos.com "security-profiles-operator" not found
> ```

The subscription name was wrong, :facepalm: .

**Comment by rhmdnd** [comment]
Cool - this worked as expected in the e2e tests for PCI-DSS v4.0:

```
helpers.go:872: Result - Name: e2e-pci-dss-4-0-security-profiles-operator-exists - Status: PASS - Severity: medium
helpers.go:1060: Rule e2e-pci-dss-4-0-security-profiles-operator-exists matched expected result
```

**Review by yuumasato — APPROVED** [review]
/lgtm

**Pull request merged**
