### PR TITLE
remove remediations from audit_rule_unsuccessful_file_modification_*

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

Removed Bash and Ansible remediations from templated rules about auditing of unsuccessful file modifications.

#### Rationale:

These rules are templated but they had still Bash or Ansible remediations. During the build these remediations were generated instead of templated ones. They were NOT alligned with rule description.

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_unsuccessful_file_modification_creat:
 Bash remediation was deleted. No test for it will be selected.
 Ansible remediation for audit_rules_unsuccessful_file_modification_creat was deleted.
Rule audit_rules_unsuccessful_file_modification_ftruncate:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open_by_handle_at:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open_by_handle_at_o_creat:
 Bash remediation was deleted. No test for it will be selected.
 Ansible remediation for audit_rules_unsuccessful_file_modification_open_by_handle_at_o_creat was deleted.
Rule audit_rules_unsuccessful_file_modification_open_by_handle_at_o_trunc_write:
 Ansible remediation for audit_rules_unsuccessful_file_modification_open_by_handle_at_o_trunc_write was deleted.
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open_by_handle_at_rule_order:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open_o_creat:
 Ansible remediation for audit_rules_unsuccessful_file_modification_open_o_creat was deleted.
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open_o_trunc_write:
 Bash remediation was deleted. No test for it will be selected.
 Ansible remediation for audit_rules_unsuccessful_file_modification_open_o_trunc_write was deleted.
Rule audit_rules_unsuccessful_file_modification_open_rule_order:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_openat:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_openat_o_creat:
 Ansible remediation for audit_rules_unsuccessful_file_modification_openat_o_creat was deleted.
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_openat_o_trunc_write:
 Ansible remediation for audit_rules_unsuccessful_file_modification_openat_o_trunc_write was deleted.
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_openat_rule_order:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_truncate:
 Bash remediation was deleted. No test for it will be selected.

**Comment by yuumasato** [comment]
> These rules are templated but they had still Bash or Ansible remediations. During the build these remediations were generated instead of templated ones. They were NOT alligned with rule description.

This is a tricky one, they were added in #4107 to address ordering issues between some of these audit rules, that the template cannot handle.

Any profile selecting only the "simple syscall rule" will be fine, e.g. a profile that only selects `audit_rules_unsuccessful_file_modification_open_by_handle_at`.
But the audit rules added by `o_creat` and `o_trunc_write` rules need to be placed in the correct order of the audit rules, e.g. a profile that selects `audit_rules_unsuccessful_file_modification_open_by_handle_at_o_creat`  and `audit_rules_unsuccessful_file_modification_open_by_handle_at_o_trunc_write`

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_unsuccessful_file_modification_creat:
 Bash remediation was deleted. No test for it will be selected.
 Ansible remediation for audit_rules_unsuccessful_file_modification_creat was deleted.
Rule audit_rules_unsuccessful_file_modification_ftruncate:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_open_by_handle_at:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_openat:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_truncate:
 Bash remediation was deleted. No test for it will be selected.

**Comment by vojtapolasek** [comment]
OK I hope I understand. I removed it only from subset of original rules. Is that ok now?

**Comment by yuumasato** [comment]
@vojtapolasek Sorry for the delay.
I think the following should not be removed:
- `audit_rules_unsuccessful_file_modification_open`
- `audit_rules_unsuccessful_file_modification_open_by_handle_at`
- `audit_rules_unsuccessful_file_modification_openat`

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_unsuccessful_file_modification_creat:
 Bash remediation was deleted. No test for it will be selected.
 Ansible remediation for audit_rules_unsuccessful_file_modification_creat was deleted.
Rule audit_rules_unsuccessful_file_modification_ftruncate:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_truncate:
 Bash remediation was deleted. No test for it will be selected.

**Comment by vojtapolasek** [comment]
OK I force pushed changes again.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_unsuccessful_file_modification_creat:
 Bash remediation was deleted. No test for it will be selected.
 Ansible remediation for audit_rules_unsuccessful_file_modification_creat was deleted.
Rule audit_rules_unsuccessful_file_modification_ftruncate:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_truncate:
 Bash remediation was deleted. No test for it will be selected.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by mildas** [comment]
**Changes identified:**
Rule audit_rules_unsuccessful_file_modification_creat:
 Bash remediation was deleted. No test for it will be selected.
 Ansible remediation for audit_rules_unsuccessful_file_modification_creat was deleted.
Rule audit_rules_unsuccessful_file_modification_ftruncate:
 Bash remediation was deleted. No test for it will be selected.
Rule audit_rules_unsuccessful_file_modification_truncate:
 Bash remediation was deleted. No test for it will be selected.

**Review by yuumasato — APPROVED** [review]

**Pull request merged**
