### PR TITLE
Feature suse 15

### PR DESCRIPTION
**Pull request by eradot4027**
#### Description:

- Started adding SLE 15 product. I would like to work on it to add it

#### Rationale:

- SLE 15 is in heavy use in the HPC community and there is a great need for automating security checks for it.

### CODE REVIEW

**Comment by eradot4027** [comment]
Forgive me as I am new to this and just really want to help. I am sure I broke protocol here somewhere and I apologize ahead of time.

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by redhatrises** [comment]
@eradot4027 please remove `sles15_product.sh` from this PR

**Comment by ggbecker** [comment]
@openscap-ci test this

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by redhatrises** [comment]
Merged! Thanks for the contribution @eradot4027 !

**Pull request merged**
