### PR TITLE
Remove OpenStack products and checks

### PR DESCRIPTION
**Pull request by JAORMX**
These have not been maintained for a long time and don't really work.

Let's remove them to avoid further confusion.

If/When OpenStack checks get created in CaC, they'll need to recreate
the `applications/openstack` directory and a product for the relevant
version (e.g. the current RHOSP version is `16.1` and work is on-going
for 17).

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by ggbecker** [comment]
I believe you have to remove occurrences such as: 

https://github.com/ComplianceAsCode/content/blob/a64f9de17fcb690b0ed21af26c12956915ffc0eb/CMakeLists.txt#L399

and maybe there are more in CMake files and python scripts.

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now fa7e2578a8374302a9d4d0f1aa1485afe9f3e38d

**Comment by matejak** [comment]
It looks like that this PR makes the CI fail. @jhrozek any thoughts on this?

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
