### PR TITLE
OCP4/CIS 4.2.6: add kubelet_enable_protect_kernel_defaults

### PR DESCRIPTION
**Pull request by mrogers950**
@JAORMX @redhatrises here's the corrected rule to check _for_ protectKernelDefaults: true. Currently should be a default fail.

### CODE REVIEW

**Comment by JAORMX** [comment]
@mrogers950 could you add a script to remediate the issue? This way we could verify that it eventually gets to a compliant state. the workflow is documented here https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc#writing-e2e-tests-for-specific-rules

**Comment by JAORMX** [comment]
huh.... there might be a bug with the remediation application:

```
     helpers.go:747: Running manual remediation '/go/src/github.com/ComplianceAsCode/content/applications/openshift/kubelet/kubelet_enable_protect_kernel_defaults/tests/ocp4/e2e-remediation.sh'
    helpers.go:747: Running manual remediation '/go/src/github.com/ComplianceAsCode/content/applications/openshift/kubelet/kubelet_enable_protect_kernel_defaults/tests/ocp4/e2e-remediation.sh'
    helpers.go:758: Failed applying remediation '/go/src/github.com/ComplianceAsCode/content/applications/openshift/kubelet/kubelet_enable_protect_kernel_defaults/tests/ocp4/e2e-remediation.sh': exit status 1
        + echo 'applying kernel tuning for kubelet'
        applying kernel tuning for kubelet
        + oc apply -f -
        + cat
        machineconfig.machineconfiguration.openshift.io/75-master-kubelet-sysctls unchanged
        Error from server (AlreadyExists): error when creating "STDIN": machineconfigs.machineconfiguration.openshift.io "75-worker-kubelet-sysctls" already exists 
```

**Comment by JAORMX** [comment]
It got applied and then seems that happened again... it should either be idempotent... or just run once (ideally)

**Review by jhrozek — APPROVED** [review]

**Pull request merged**
