### PR TITLE
Some new rules and  mostly related fixes

### PR DESCRIPTION
**Pull request by maage**
#### Description:

Support `init_on_free`, more rules to disable rarely used kernel module, subsystems not usually in use in servers, and some newer sysctls.

#### Rationale:

Just expand rules to match my view.

#### Review Hints:

Docustrings should be checked for validity and readability.

I enabled most new features only on fedora and there is no linkage to any external documents.

### CODE REVIEW

**Comment by maage** [comment]
Automatus tests fail because those tests are not going to work under podman based test envs. Again my proposal to fix this #10387

**Comment by maage** [comment]
Added more new features and rebased.

**Comment by maage** [comment]
Moved some stuff to #10519.
Added local_port_range handling with variable.
Moved n_hdlc to proper place.

I'm not so sure about current status where about the same rules are sprinked over 3(?) branches based on assumed subsystem.

**Comment by jan-cerny** [comment]
Closing due to inactivity. If you still want to work on this PR, please reopen it and resolve the conflicts.

**Pull request closed without merging**
