### PR TITLE
Add Kubernetes remediation for rule configure_crypto_policy

### PR DESCRIPTION
**Pull request by Vincent056**
Added Kubernets auto remediation for rule `configure_crypto_policy`

Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2062530

### CODE REVIEW

**Comment by jhrozek** [comment]
Hi @Vincent056 it seems like the e2e tests are catching some issue here:
```
     helpers.go:808: Result - Name: e2e-e8-worker-configure-crypto-policy - Status: FAIL - Severity: high
    helpers.go:815: E2E-FAILURE: The expected result for the configure_crypto_policy rule didn't match. Expected 'PASS', Got 'FAIL' 
```

**Comment by Vincent056** [comment]
Remove e2e test, `rhcos4-moderate` profile has different default variable for `var_system_crypto_policy` than `rhcos4-e8`, this makes the first scan fail on `rhcos4-e8` but not on `rhcos4-moderate`.

**Comment by jhrozek** [comment]
So now the tests related to your rule are all passing, but here is this failure:
```
  helpers.go:812: Excluded Rule from counting - Name: e2e-high-master-configure-usbguard-auditbackend
    helpers.go:815: E2E-FAILURE: The expected result for the configure_usbguard_auditbackend rule didn't match. Expected 'PASS', Got 'NOT-APPLICABLE'
```
Because other rhcos4 rules are passing, I wonder if we have an issue with installing usbguard?
Does the rule pass manually for you?

**Comment by Vincent056** [comment]
> So now the tests related to your rule are all passing, but here is this failure:
> 
> ```
>   helpers.go:812: Excluded Rule from counting - Name: e2e-high-master-configure-usbguard-auditbackend
>     helpers.go:815: E2E-FAILURE: The expected result for the configure_usbguard_auditbackend rule didn't match. Expected 'PASS', Got 'NOT-APPLICABLE'
> ```
> 
> Because other rhcos4 rules are passing, I wonder if we have an issue with installing usbguard? Does the rule pass manually for you?

Yes, this rule passes manually for me

**Comment by xiaojiey** [comment]
test cases details could be seen from: https://url.corp.redhat.com/8162b96
@Vincent056 Could you please help to review? Thanks.

**Comment by Vincent056** [comment]
> test cases details could be seen from: https://url.corp.redhat.com/8162b96 @Vincent056 Could you please help to review? Thanks.

Thanks for adding the test case, it looks good to me

**Review by jhrozek — APPROVED** [review]

**Pull request merged**
