### PR TITLE
CIS Node 4.2.3 - add template to kubelet_configure_client_ca/rule.yml

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

#### Description:

- Adds a template to CIS Node 4.2.3 kubelet_configure_client_ca/rule.yml

#### Rationale:

- Required to run the scan

### CODE REVIEW

**Comment by lsm5** [comment]
@jhrozek @yuumasato alright, compliancescan says COMPLIANT. Ready for review I guess. PTAL.

**Comment by redhatrises** [comment]
ok-to-test

**Pull request merged**
