### PR TITLE
Add timer_logrotate_enabled back to RHEL 7 and RHEL 8

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Add rhel7 and rhel8 back to timer_logrotate_enabled.

#### Rationale:

This is needed as last release this rule did not have a prodtype since one was added we need to add back rhel7 and rhel8 ensure that we don't break tailoring for users.

### CODE REVIEW

**Review by jan-cerny — COMMENTED** [review]
I have verified that the rule is present in the RHEL 7 and RHEL 8 data streams.

But the rule now appeared in the ANSSI enhanced and ANSSI high profiles. Is that expected?

**Comment by Mab879** [comment]
> I have verified that the rule is present in the RHEL 7 and RHEL 8 data streams.
> 
> But the rule now appeared in the ANSSI enhanced and ANSSI high profiles. Is that expected?

Expected but not desired. I have excluded it from RHEL 7 and RHEL 8 profiles.

**Comment by jan-cerny** [comment]
@Mab879 you removed the rule from the ANSSI enhanced profiles but not from ANSSI high profiles, I think it should be removed also from the ANSSI high profiles.

**Comment by Mab879** [comment]
> @Mab879 you removed the rule from the ANSSI enhanced profiles but not from ANSSI high profiles, I think it should be removed also from the ANSSI high profiles.

Fixed.

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
