### PR TITLE
Finish rule accounts_passwords_pam_faillock_interval for Fedora

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
This PR:
* Adds more criteria to the OVAL definition to align the OVAL definition with the description in XCCDF rule
* Fixes formatting of XCCDF rule description and OCIL description
* Adds multi_platform_fedora to both OVAL and Bash remediation
* Adds basic test scenarios for this rule
* Fixes bugs found in Bash remediation by the new tests

#### Rationale:
This rule is a part of Fedora OSPP profile.

### CODE REVIEW

**Comment by mildass** [comment]
Thank @jan-cerny Works great, but wouldn't it be better to use `set_faillock_option_to_value_in_pam_file` from shared functions in that bash remediation?

**Comment by jan-cerny** [comment]
I have added a baseline configuration for test scenarios and a new test.

**Comment by mildass** [comment]
@jan-cerny If that remediation doesn't work properly on this rule, then I think it doesn't work on others (e.g. `accounts_passwords_pam_faillock_unlock_time` - same as this one, but works with unlock_time parameter).

Maybe it would be good if you make your remediation function configurable (to change/add value for arbitrary option, not only `fail_interval`) and add it to `shared/bash_remediation_functions` so we can use it for other `accounts_passwords_pam` rules.

**Comment by jan-cerny** [comment]
@mildass That is a great observation. I'll try to look into where it is still used.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by dahaic** [comment]
Looks great, thank you @jan-cerny . ACK

**Pull request merged**
