### PR TITLE
[RFC] Reuse controls/srg_gpos for RHCOS

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

I'm filing this PR as an RFC, because it contains a mix of patches that probably
should be split into individual PRs. The intent was to go through the
`controls/srg_gpos` tree and try to find patterns in which the control replies
and the rule usage differs between RHEL and RHCOS. The patches that either the
rules or the control files themselves are each addressing one kind of divergence.

The result should be both the rhcos profile should be usable and the SRG export
should reflect the appropriate controls. In the SRG export part, there's one
part that I couldn't get right yet, reusing of the jinja macros we use to generate
remediations with to generate the fixtext - I'm fighting some indentation issues
there.

The individual commits have commit messages that should describe them in
more detail.

#### Rationale:

- Generate both the SRG mapping and the DS for RHCOS from the same control
files as RHEL.

#### Review Hints:

- `export PYTHONPATH=$(pwd); python3 utils/create_srg_export.py -c controls/srg_gpos.yml -p rhcos4 -m shared/references/disa-os-srg-v2r3.xml --out-format html --output /tmp/srg-mapping-rhcos4.html`

### CODE REVIEW

**Comment by jhrozek** [comment]
this push should fix some of the failing tests although several were failing due to ubuntu/debian mirrors being down..

**Comment by jhrozek** [comment]
looks like installing OCP4 clusters is fubar again...will retry tomorrow

**Comment by jhrozek** [comment]
cluster install woes

**Review by ggbecker — COMMENTED** [review]
You might want to extend this workflow to generate the spreadsheets for the RHCOS product as well that also serve as a smoke test for the script: https://github.com/ComplianceAsCode/content/blob/master/.github/workflows/srg-mapping-table.yaml#L47

This will attach xlsx,html archives to the pull request and when it's merged, it will render the files under this page: https://complianceascode.github.io/content-pages/srg_mapping/index.html

**Comment by jhrozek** [comment]
On Tue, Feb 07, 2023 at 02:01:58AM -0800, Gabriel Becker wrote:
> @ggbecker commented on this pull request.
> 
> You might want to extend this workflow to generate the spreadsheets for the RHCOS product as well that also serve as a smoke test for the script: https://github.com/ComplianceAsCode/content/blob/master/.github/workflows/srg-mapping-table.yaml#L47
> 
> This will attach xlsx,html archives to the pull request and when it's merged, it will render the files under this page: https://complianceascode.github.io/content-pages/srg_mapping/index.html

Yes, thank you, I'm still fighting somewhat with reusing the templates
in the policy files to get the check and fix rendered nicely. But I can
try doing that already, the OCP and RHCOS SRG mappings are drafts for
the time being.

**Comment by jhrozek** [comment]
The new push includes the SRG mapping GH action, all other patches are untouched

**Comment by jhrozek** [comment]
Closing. We won't be needing this PR.

**Pull request closed without merging**
