### PR TITLE
OCP4: New rule image_pruner_active covers SRG-APP-000454-CTR-001110 and SRG-APP-000454-CTR-001115

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- A new rule that covers two SRGs

#### Rationale:

- OCP4 STIG

#### Review Hints:

- I will post the SRG export later

### CODE REVIEW

**Comment by rhmdnd** [comment]
Looks like a legitimate e2e-aws-ocp4-stig failure where the first can send scans fail.

Spinning up an environment to try and recreate.

**Comment by jhrozek** [comment]
There was a typo in the API path. I also fixed some issues in the unit tests, hopefully we'll get a clean pass now.

**Comment by jhrozek** [comment]
time outs and cluster install failures
/retest

**Comment by jhrozek** [comment]
Blocked by https://github.com/ComplianceAsCode/compliance-operator/pull/262

**Comment by rhmdnd** [comment]
Looks good to me once the dependent patch goes in.

**Comment by jhrozek** [comment]
Rebased atop master in order to pick up the change that tests against CO HEAD.

**Comment by jhrozek** [comment]
just rebased to pick up RBAC changes

**Comment by jhrozek** [comment]
Great, the STIG CI test finally passes.
@Vincent056 @rhmdnd PTAL

**Review by rhmdnd — APPROVED** [review]
/lgtm

Thanks!

**Pull request merged**
