### PR TITLE
Do not remove blank lines when building profile playbook

### LINKED ISSUE #9808: `audit_ospp_general` fails after Ansible remediation because of missing blank lines
#### Description of problem:
`audit_ospp_general` Ansible remediation doesn't properly remediate the rule.

#### SCAP Security Guide Version:
d8e4c7d

#### Operating System Version:
RHEL8, RHEL9, CS8, CS9

#### Steps to Reproduce:
1. `ansible-playbook -c local -i "localhost," -t audit_ospp_general centos8-playbook-ospp.yml`
2. `oscap xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_audit_ospp_general ssg-centos8-ds.xml`

#### Actual Results:
```
Title   Perform general configuration of Audit for OSPP
Rule    xccdf_org.ssgproject.content_rule_audit_ospp_general
Result  fail
```

#### Expected Results:
```
Title   Perform general configuration of Audit for OSPP
Rule    xccdf_org.ssgproject.content_rule_audit_ospp_general
Result  pass
```

#### Additional Information/Debugging Steps:
Content of `/etc/audit/rules.d/30-ospp-v42.rules` is missing few blank lines - instead of double blank lines there are only single blank lines:
After remediation (part of `/etc/audit/rules.d/30-ospp-v42.rules`):
```
##
## original copies may be found in /usr/share/audit/sample-rules/

## User add delete modify. This is covered by pam. However, someone could
## open a file and directly create or modify a user, so we'll watch passwd and
```
[Expected](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/policy_rules/audit_ospp_general/rule.yml#L23):
```
##
## original copies may be found in /usr/share/audit/sample-rules/


## User add delete modify. This is covered by pam. However, someone could
## open a file and directly create or modify a user, so we'll watch passwd and
```

The rule check expects exact string, there can't be any discrepancies.

Ansible snippet in datastream and built Ansible rule playbooks are correct. Only profile playbooks are missing the blank lines.

### PR DESCRIPTION
**Pull request by mildas**
#### Description:
Removal of blank lines breaks remediations when working with exact string.
For example [audit_ospp_general rule](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/auditing/policy_rules/audit_ospp_general/rule.yml#L7)

#### Rationale:
Fixes #9808 

Fixes CS8 Testing farm https://artifacts.dev.testing-farm.io/3c424748-3e5f-42a7-b147-b8ac92e4fc0d/work-ansible-osppnCOL9l/tests/fmf-plans/ansible-ospp/execute/data/Sanity/ansible-machine-hardening/ospp/output.txt

### CODE REVIEW

**Comment by mildas** [comment]
@jan-cerny @matejak Do you remember why the removal of blank lines was introduced? Is there any risk when we don't remove them?

**Comment by jan-cerny** [comment]
@mildas I don't know exactly. I have found that this was introduced by https://github.com/ComplianceAsCode/content/pull/3688 and I dig in the history that there were multiple similar PRs at that time: https://github.com/ComplianceAsCode/content/pull/3687, https://github.com/ComplianceAsCode/content/pull/3685, https://github.com/ComplianceAsCode/content/pull/3684 etc. They are all related to Ansible roles, Ansible lint and Ansible Galaxy. My theory is that the blank lines cause some warning when the generated roles were uploaded in Ansible Galaxy.

But, we have a CI job here that builds the Ansible Roles and runs the Ansible Lint and its still green. What do you think about this CI job?

Side note: I discovered that this is the only call of the remove_multiple_blank_lines function so if we will remove it we can also remove the function.

**Comment by mildas** [comment]
@jan-cerny 
> My theory is that the blank lines cause some warning when the generated roles were uploaded in Ansible Galaxy.

There could be warning for multiple blank lines between Ansible tasks or between task parameters. But multiple blank lines in multi-line string shouldn't be a problem in my opinion as users might need to have such content there.

> But, we have a CI job here that builds the Ansible Roles and runs the Ansible Lint and its still green. What do you think about this CI job?

The job looks useful to me and it doesn't skip any warning related to blank lines.

> Side note: I discovered that this is the only call of the remove_multiple_blank_lines function so if we will remove it we can also remove the function.

Great catch! I've removed it in last commit

**Review by jan-cerny — APPROVED** [review]

**Comment by jan-cerny** [comment]
The CI fail in Fedora rawhide is unrelated to this PR, it's caused by libxml2 ABI break, see https://bugzilla.redhat.com/show_bug.cgi?id=2139546

**Pull request merged**
