### PR TITLE
Remove rhel7 only rules

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Remove rules that where only used in RHEL 7.

#### Rationale:

Clean up rules that are no longer needed.
#### Review Hints:
The script in #12110 maybe useful for review.

### CODE REVIEW

**Comment by steveandreassend** [comment]
It was helpful having RHEL7 coverage. RedHat has just announced they are offering 3 year extended support for this release because the installed base continues to remain on this release.

**Comment by Mab879** [comment]
> It was helpful having RHEL7 coverage. RedHat has just announced they are offering 3 year extended support for this release because the installed base continues to remain on this release.

Thanks for your comment. The RHEL 7 content in RHEL 7 isn't going anywhere. It will be there for the reminder of the EUS period. Please use the content from the `scap-security-guide` package to use the content created by this project. However due to agencies like CIS stopping updates at the end of the maintenance on 30 June 2024, Red Hat stopped updating the complacence content for RHEL 7 on 30 June 2024, see [this blog post from the Red Hat blog](https://www.redhat.com/en/blog/red-hat-enterprise-linux-7-end-compliance-content-june-30-2024) for more details. Also the RHEL 7 product is already gone from this project see #12093.

**Comment by steveandreassend** [comment]
Understood. Having this page was really handy https://complianceascode.github.io/content-pages/tables/table-rhel7-cces.html for quick lookups.

**Review by jan-cerny — APPROVED** [review]
I have verified that these rules aren't used anywhere.

**Pull request merged**
