### PR TITLE
Updated 6 rules 2 for sle micro

### PR DESCRIPTION
**Pull request by rumch-se**
#### Description:

- _The PR includes updates of 6 rules to support new SUSE product sle micro according to DISA STIG_

#### Rationale:

- The list of the rules is 
auditd_audispd_network_failure_action
auditd_audispd_disk_full_action 
accounts_have_homedir_login_defs 
no_empty_passwords_etc_shadow 
no_empty_passwords 
audit_rules_enable_syscall_auditing

### CODE REVIEW

**Review by teacup-on-rockingchair — APPROVED** [review]
:+1:

**Comment by teacup-on-rockingchair** [comment]
@ComplianceAsCode/trusted-developers anyone can help with the failing test that prevent this PR from merging?

**Comment by marcusburghardt** [comment]
> @ComplianceAsCode/trusted-developers anyone can help with the failing test that prevent this PR from merging?

It seems the issue with the `no_empty_passwords` rule is legit. I couldn't go deep investigating the cause of the issue, but tested the rule with master branch and it worked fine. When testing it with this PR, it is failing. Could you review any change involving this rule, please?

**Comment by teacup-on-rockingchair** [comment]
> > @ComplianceAsCode/trusted-developers anyone can help with the failing test that prevent this PR from merging?
> 
> It seems the issue with the `no_empty_passwords` rule is legit. I couldn't go deep investigating the cause of the issue, but tested the rule with master branch and it worked fine. When testing it with this PR, it is failing. Could you review any change involving this rule, please?

thanks :bow:

**Pull request merged**
