### PR TITLE
Replace login_defs platform by package platform

### PR DESCRIPTION
**Pull request by jan-cerny**
The `login_defs` platform has slightly special meaning, the purpose isn't to check for some `login_defs` package but the purpose is to check for a package that provides `/etc/login.defs` file. However, there is very little benefit in this logic. Instead, we can unify it and check directly for the package because we know its name. To do that, we will use the templated `package` platform. It is a different package on different distributions, so we will as usually use the upstream project name as the `package` platform key.

### CODE REVIEW

**Comment by vojtapolasek** [comment]
Hello @ComplianceAsCode/ubuntu-maintainers  @ComplianceAsCode/suse-maintainers  @ComplianceAsCode/oracle-maintainers  could you please confirm correctness of the name of the package which provides login_defs?
Thank you.

**Comment by dodys** [comment]
> Hello @ComplianceAsCode/ubuntu-maintainers @ComplianceAsCode/suse-maintainers @ComplianceAsCode/oracle-maintainers could you please confirm correctness of the name of the package which provides login_defs? Thank you.

the /etc/login.defs file is provided by `login`

do you need something more?

**Comment by freddieRv** [comment]
@vojtapolasek on OL{7,8,9} the /etc/login.defs file is provided by the `shadow-utils` package

**Comment by vojtapolasek** [comment]
Hello @teacup-on-rockingchair  could you please confirm that the file /etc/login.defs is provided by the shadow package on SLE?

**Comment by teacup-on-rockingchair** [comment]
> Hello @teacup-on-rockingchair could you please confirm that the file /etc/login.defs is provided by the shadow package on SLE?

affirmative :+1:

**Review by vojtapolasek — APPROVED** [review]
Thank you for the change, it simplifies the move to templated platforms.

**Pull request merged**
