### PR TITLE
Fix for bug 1195520

### PR DESCRIPTION
**Pull request by anivan-suse**
#### Description:

Add sle15.sh and sle12.sh bash remediation for rule: set_password_hashing_algorithm_systemauth

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes bug #1195520 https://bugzilla.suse.com/show_bug.cgi?id=1195520

### CODE REVIEW

**Review by ggbecker — COMMENTED** [review]
I would be more in favor of merging these files with the shared.sh and using Jinja macros to define the filepath and the regexes used. They kind of look similar and we avoid duplicated code.

We probably should reevaluate all of the `sle12.*` `sle15.*` and see if can something similar.

**Review by jan-cerny — CHANGES_REQUESTED** [review]
@anivan-suse After you have moved the SLE12/15 code to `shared.sh` you should now delete the files `sle12.sh` and `sle15.sh`.

**Comment by anivan-suse** [comment]
Thanks for pointing that out - removed.

**Review by jan-cerny — APPROVED** [review]

**Review by jan-cerny — CHANGES_REQUESTED** [review]
You have a test failing on SLE 15:

```
175/190 Test #171: sle15-bash-shellcheck ....................................................***Failed   10.24 sec

In /__w/content/content/build/sle15/fixes/bash/set_password_hashing_algorithm_systemauth.sh line 5:
AUTH_FILES[0]="/etc/pam.d/system-auth"
^-----------^ SC2034: AUTH_FILES appears unused. Verify use (or export if used externally).

For more information:
  https://www.shellcheck.net/wiki/SC2034 -- AUTH_FILES appears unused. Verify...
```

**Comment by brett060102** [comment]
@anivan-suse You need to move the block
```
AUTH_FILES[0]="/etc/pam.d/system-auth"
{{%- if product == "rhel7" %}}
AUTH_FILES[1]="/etc/pam.d/password-auth"
{{%- endif %}}
```
under the {{% else %}}
to address the failing test issue.

**Comment by jan-cerny** [comment]
bump!

**Comment by brett060102** [comment]
@anivan-suse not sure you saw the last note the code need to change to the following to fix the failing test:
`# platform = multi_platform_all

{{% if product in ["sle15", "sle12"] -%}}
if ! grep -q "^password.*required.*pam_unix.so.*sha512" /etc/pam.d/common-password ; then
   sed -i --follow-symlinks "/^password.*required.*pam_unix.so/ s/$/ sha512/" /etc/pam.d/common-password
fi
{{%- else -%}}
AUTH_FILES[0]="/etc/pam.d/system-auth"
{{%- if product == "rhel7" %}}
AUTH_FILES[1]="/etc/pam.d/password-auth"
{{%- endif %}}
for pamFile in "${AUTH_FILES[@]}"
do
	if ! grep -q "^password.*sufficient.*pam_unix.so.*sha512" $pamFile; then
		sed -i --follow-symlinks "/^password.*sufficient.*pam_unix.so/ s/$/ sha512/" $pamFile
	fi
done
{{%- endif %}}

`

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
