### PR TITLE
OCP4 STIG: Add coverage for SRGs that relate to NIST CM-6

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

This PR touches a lot of controls, because some of the controls in the CM-6
family are catch all, in particular SRG-APP-000516-CTR-001325, but for some
reason a lot of other rules were referencing SRG-APP-000516-CTR-001330,
and SRG-APP-000516-CTR-001335 as well. The commit messages include the sed
commands I used to edit the rules for easier review.

- OCP4 STIG: SRG-APP-000516-CTR-000790: Add mitigation and status justification to a Does Not Meet control
- OCP4 STIG: Remove references to SRG-APP-000516-CTR-001330, the rule is inherently met
- OCP4: New rule: `container_security_operator_exists` covers SRG-APP-000516-CTR-001335, remove all the other references to this control

#### Rationale:

- OCP4 STIG coverage

#### Review Hints:

- I will post the links to the generated SRG export and the candidate
sheet later.

### CODE REVIEW

**Comment by jhrozek** [comment]
rebased on top of current master and ensured that all files touched have a newline at the end to conform with the project's coding standards

**Comment by jhrozek** [comment]
To review, compare the [SRG mapping](https://github.com/ComplianceAsCode/content/suites/11229939105/artifacts/574902247) generated by the GH actions with the [current version](https://docs.google.com/spreadsheets/d/1ouRalvXzRHuhPPN_AKMvqqscUqGvVOkkEdMP3YYBO44/edit#gid=1859516253) of the DISA STIG.

**Comment by jhrozek** [comment]
The automatus failures are unrelated.
@Vincent056 @rhmdnd PTAL

**Review by rhmdnd — APPROVED** [review]
Looks consistent with the generated report.

**Pull request merged**
