### PR TITLE
OCP4 STIG: Cover controls that correspond to NIST CM-5

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- OCP4 STIG: SRG-APP-000131-CTR-000285 is configurable with reject_unsigned_images_by_default
- OCP4 STIG: The majority of controls related to CM-5 are inherently met

The majority of controls are inherently met, those just got the proper status
justification and rationale.

SRG-APP-000131-CTR-000285 is configurable with an existing rule.
SRG-APP-000381-CTR-000905 is configurable with an RHCOS rule and we'll deal with that control later, along with the other RHCOS controls

#### Rationale:

- OCP4 STIG

#### Review Hints:

- I will post the SRG export once the GH actions finish

### CODE REVIEW

**Comment by jhrozek** [comment]
To review, please compare the [SRG mapping](https://github.com/ComplianceAsCode/content/suites/11110406862/artifacts/566044163) with the [current draft](https://docs.google.com/spreadsheets/d/1ouRalvXzRHuhPPN_AKMvqqscUqGvVOkkEdMP3YYBO44/edit#gid=959715005)

**Comment by jhrozek** [comment]
Still the same issue:
```
    helpers.go:579: The Compliance Suite 'e2e-pci-dss-node' didn't get to DONE phase: still waiting for the scans to be done
```
last try on a re-run,then I'll debug the CI run interactively.

**Comment by jhrozek** [comment]
rebased to resolve a conflict

**Comment by jhrozek** [comment]
/retest
not sure what was up with CI, I just tested running a scan from that branch and it worked fine.

**Comment by jhrozek** [comment]
To review, compare the [SRG mapping](https://github.com/ComplianceAsCode/content/suites/11169363735/artifacts/570380018) generated by the GH actions with the [current version](https://docs.google.com/spreadsheets/d/1ouRalvXzRHuhPPN_AKMvqqscUqGvVOkkEdMP3YYBO44/edit#gid=1859516253) of the DISA STIG.

**Comment by jhrozek** [comment]
@Vincent056 @rhmdnd PTAL

**Review by rhmdnd — APPROVED** [review]

**Pull request merged**
