### PR TITLE
Add ocp-node checks to master

### PR DESCRIPTION
**Pull request by redhatrises**
I accidentally removed this when I shouldn't have.

### CODE REVIEW

**Comment by shawndwells** [comment]
Should there be two OCP profiles? Would there be a simplified user experience if there was a single profile (e.g. STIG) that contained logic to evaluate node/master as appropriate?

**Comment by shawndwells** [comment]
vs having ``--profile ocp-stig-node`` ``--profile ocp-stig-master``

**Comment by redhatrises** [comment]
> vs having `--profile ocp-stig-node` `--profile ocp-stig-master`

How would you envision doing that?

**Comment by jan-cerny** [comment]
We could have CPEs to check if the target is OCP node or OCP master and set the `platform:` in each rule YAML. It would require to improve handling of this key in our build system, for example we will need to support a list instead of a single value there.

**Comment by jan-cerny** [comment]
But let's do that in separate PR.

**Pull request merged**
