### PR TITLE
Virt mapping

### PR DESCRIPTION
**Pull request by redhatrises**
More VMM SRG mappings.

### CODE REVIEW

**Comment by redhatrises** [comment]
> `SRG-OS-000445-VMM-001780` (#4001) is a weird requirement about verifying the _functionality_ of various security features. Not sure this maps cleanly to SELinux enablement since the control is about functional testing (akin to what's done in common criteria).
> 
> Noticed VMWare doesn't have this control selected in their baselines.
> 
> What do you think about mapping this to installed_os_is_rhel/rhv since common criteria validates functional testing?

@shawndwells was mapping this one to some degree based on the NIST and DISA identifiers. Maybe those are wrong?

**Comment by shawndwells** [comment]
On 3/14/19 3:40 PM, Gabe Alford wrote:
> @shawndwells <https://github.com/shawndwells> was mapping this one to 
> some degree based on the NIST and DISA identifiers. Maybe those are wrong?

Could be. Liberties are often taken when mapping NIST controls, 
creatively mapping them to support/justify configuration rules.

Do you think it makes sense to remove for now, and ask Ted to ping DISA 
about how to interpret this control?

**Comment by redhatrises** [comment]
> On 3/14/19 3:40 PM, Gabe Alford wrote: @shawndwells <https://github.com/shawndwells> was mapping this one to some degree based on the NIST and DISA identifiers. Maybe those are wrong?
> Could be. Liberties are often taken when mapping NIST controls, creatively mapping them to support/justify configuration rules. Do you think it makes sense to remove for now, and ask Ted to ping DISA about how to interpret this control?

@shawndwells removed `SRG-OS-000445-VMM-001780` so that we can figure it out later.

**Comment by shawndwells** [comment]
@redhatrises works for me!

**Pull request merged**
