### PR TITLE
FMF plans and CI machine hardening tests

### PR DESCRIPTION
**Pull request by mildas**
#### Description:
New hardening tests introduced via separate FMF plans to isolate them from other tests. Hardening tests are isolated because they are destructive.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@mildas any plans?

**Comment by mildas** [comment]
@jan-cerny This PR is not meant to be merged. It's only for polishing [CI tests](https://src.fedoraproject.org/tests/scap-security-guide) to be ready for Testing Farm. When test is in good state, it will get `packit` tag and then this PR will be closed.

**Comment by mildas** [comment]
@jan-cerny This PR is not meant to be merged. It's only for polishing [CI tests](https://src.fedoraproject.org/tests/scap-security-guide) to be ready for Testing Farm. When test is in good state, it will get `packit` tag and then this PR will be closed.

**Comment by matusmarhefka** [comment]
I looked into failures on CS9:

* `file_permissions_etc_audit_rulesd` - known issue, https://github.com/ComplianceAsCode/content/issues/8947
* `no_empty_passwords` - known issue, https://github.com/ComplianceAsCode/content/issues/8857
* `accounts_user_interactive_home_directory_defined` - reported a new issue, https://github.com/ComplianceAsCode/content/issues/9042
* `usbguard_generate_policy` - still needs investigation

Btw TF uses `ec2` images from https://cloud.centos.org/centos/9-stream/x86_64/images/ and https://cloud.centos.org/centos/8-stream/x86_64/images/ and installs beakerlib from the upstream repo.

**Comment by matusmarhefka** [comment]
CS8 failures:

* `configure_bashrc_exec_tmux` - known issue, https://github.com/ComplianceAsCode/content/issues/8913
* `file_permissions_etc_audit_rulesd` - known issue, https://github.com/ComplianceAsCode/content/issues/8947
* `usbguard_generate_policy` - new issue found, rule does not work correctly when system has no usb bus, we can fix it by updating our remediation to either add a comment into `/etc/usbguard/rules.conf` or add a "reject all" rule into the config file as there won't be any usb devices connected to such system
* bios_enable_execution_restrictions - still needs investigation

**Review by matusmarhefka — APPROVED** [review]
Test plans and results look great, thanks!

**Pull request merged**
