### PR TITLE
Tool for identifying the most used rules

### PR DESCRIPTION
**Pull request by Honny1**
#### Description:
This PR adds a subcommand `profile_tool.py` that generates a list of rules with the number of uses in profiles in different formats.

#### Rationale:
It is known that many rules are common among profiles so we can infer that much less than 1825 rules are in fact used for RHEL, but we are including thousands of rules in the data stream because we don't know exactly what is needed or not.

We have many rules without Ansible remediation, some rules without Bash remediation and some few rules without OVAL check. It is great to close the gaps, but it would be smart to prioritize the most used rules.

It is hard to identify these most used rules and consequently optimize our efforts.

#### Review Hints:
To generate a list of the most used rules in the `rhel9` benchmark you can run this command:
```bash
    $ ./build_product rhel9
    $ ./build-scripts/profile_tool.py most-used-rules  build/ssg-rhel9-xccdf.xml
```
Or you can run this command to get info about the whole project:

```bash
    $ ./build-scripts/profile_tool.py most-used-rules
```

Depends on: #11438

### CODE REVIEW

**Comment by jan-cerny** [comment]
@Honny1 It would be great to sort the output by the count of the rules.

**Comment by Honny1** [comment]
@jan-cerny  The rules are listed in descending order.

**Comment by jan-cerny** [comment]
@Honny1 It doesn't sort for me

**Comment by jan-cerny** [comment]
now it sorts for me, thanks

**Comment by marcusburghardt** [comment]
@Honny1 , I saw the changes in https://github.com/ComplianceAsCode/content/pull/11438 are also incorporated here. Did I miss any change there but not here?

**Comment by Honny1** [comment]
@marcusburghardt Yes, the changes from #11438 should be incorporated into this PR. I will rebase on the master after merging #11438.

**Review by marcusburghardt — CHANGES_REQUESTED** [review]
I have tested all the functions and they are working as expected. I have only some minor comments mainly about readability. After that I believe it would be good to be merged.

**Pull request merged**
