### PR TITLE
Update CIS RHEL9 control file to v2.0.0

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

This PR update the controls based on CIS RHEL9 v2.0.0.

A new version of CIS RHEL9 policy is in `Accepted` state and is expected to move to `published` state in 2024-06-20.
Until the policy is moved to `published` state I will keep this PR in Draft. But it is already good for review.

#### Rationale:

Keep CIS RHEL9 profiles updated.

#### Review Hints:

Best way to review is going commit by commit chronologically. The commits are ordering according to the order the requirements are presented in the policy.

References:
https://workbench.cisecurity.org/benchmarks/18210

### CODE REVIEW

**Review by Mab879 — CHANGES_REQUESTED** [review]
Thanks for the PR.

All rules in Section 6.2.3 should be under `related_rules`. Section 6.2 is a pick one section, like the firewall section.

**Review by Mab879 — APPROVED** [review]
Thanks for the PR!

**Review by Mab879 — CHANGES_REQUESTED** [review]
Please take look the testing farm failures, they look valid enough to investigate.

**Comment by marcusburghardt** [comment]
> Please take look the testing farm failures, they look valid enough to investigate.

Thanks for reviewing @Mab879 . The failures should be fixed now.

**Review by Mab879 — APPROVED** [review]
Thanks for the effort on this PR.

LGTM.

**Pull request merged**
