### PR TITLE
Make the FIPS mode remediation idempotent in ansible.

### LINKED ISSUE #7314: Enabling FIPS mode could be make idempotent in ansible remediations
#### Description of problem:
Right now, in release 0.1.52, the remediation for enabling FIPS mode in the RHEL 8 CUI role is not idempotent; it is marked as 'changed' even if the current configuration has FIPS is enabled.

#### Steps to Reproduce:

1.  Run the remediation for FIPS (perhaps with the specific enable_fips ansible flag) on the ansible role ansible-role-rhel8-cui

#### Actual Results:
Each time the script is run, the FIPS enablement is marked as changed.

#### Expected Results:
The ansible would reflect that it is changed only if the FIPS mode was changed.  Even more ideally, the command to set FIPS mode would never be run unless it is detected to not be in FIPS mode.

### PR DESCRIPTION
**Pull request by justchris1**
#### Description:

Checks the status of FIPS mode before setting FIPS mode, to make the play idempotent.

#### Rationale:

Makes the play idempotent so it only is marked changed if a change to FIPS mode occurred.  

- Fixes #7314

### CODE REVIEW

**Comment by justchris1** [comment]
Can someone please help me understand what test is failing?  I tried running locally before I pushed with `ctest -L quick`, `ctest -LE quick` and 'ctest' which all passed.  However, the error message from the CI build of SSGTS Run Tests:

```
Run exit 1
  exit 1
  shell: /usr/bin/bash -e {0}
Error: Process completed with exit code 1.
```
Is pretty vague and I have no idea what to look for to resolve.

Also, I am stumped on Content Test Filtering on Ubuntu Latest test:
```
Run python3 ./ctf/content_test_filtering.py pr --output-format markdown 7315
Traceback (most recent call last):
  File "./ctf/content_test_filtering.py", line 56, in <module>
    list_of_tests = connect_to_labels.get_labels(tests, options.output)
  File "/home/runner/work/content/content/ctf/ctf/connect_to_labels.py", line 30, in get_labels
    test_scenarios = test.get_tests(yaml_content)
  File "/home/runner/work/content/content/ctf/ctf/ContentTests.py", line 55, in get_tests
    tests = self.test_command(yaml_content)
  File "/home/runner/work/content/content/ctf/ctf/ContentTests.py", line 64, in test_command
    self.tests.append(rule_test)
AttributeError: 'NoneType' object has no attribute 'append'
Error: Process completed with exit code 1.
```
Since I didn't touch anything in ContentTests.py and it appears to have ab attribute error.  I can try to work through it, but I could use a little nudge in the right direction for the project.

**Comment by Mab879** [comment]
This is a bug, try rebaseing off of `master` and that should fix it.

**Comment by justchris1** [comment]
I am not exactly sure what is going on here.  I am familiar with git, but not in forked repos.  I apologize for the noise here as I thought I was up to date with master before I started this process, but that appears to be wrong at this point.  I might just start over here (close this PR and open a new one) so only the file changed is the correct one. The patch is simple enough I can reapply and test later this afternoon.

**Comment by Mab879** [comment]
All good, the fix was merged few hours after opened this PR. Thanks for your effort on this contribution.

**Comment by justchris1** [comment]
Sorry to chat on a closed PR, but I presume master is the project's stable?  Just curious because a clean rebase and attempt to build master is getting errors, when I had no issues from wherever I was building from originally.

```
[ 36%] [ol7-tables] generating STIG XML overlay
Traceback (most recent call last):
  File "/home/user/test-compliance/content/utils/create-stig-overlay.py", line 180, in <module>
    main()
  File "/home/user/test-compliance/content/utils/create-stig-overlay.py", line 176, in main
    new_stig_overlay(disa_xccdftree, ssg_xccdftree, args.output_file, args.quiet)
  File "/home/user/test-compliance/content/utils/create-stig-overlay.py", line 110, in new_stig_overlay
    dom = xml.dom.minidom.parseString(ET.tostring(new_stig_overlay, encoding="UTF-8", xml_declaration=True))
TypeError: tostring() got an unexpected keyword argument 'xml_declaration'
make[2]: *** [ol7/overlays/stig_overlay.xml] Error 1
make[1]: *** [ol7/CMakeFiles/generate-ol7-table-stig.dir/all] Error 2
```

**Comment by ggbecker** [comment]
> Sorry to chat on a closed PR, but I presume master is the project's stable? Just curious because a clean rebase and attempt to build master is getting errors, when I had no issues from wherever I was building from originally.
> 
> ```
> [ 36%] [ol7-tables] generating STIG XML overlay
> Traceback (most recent call last):
>   File "/home/user/test-compliance/content/utils/create-stig-overlay.py", line 180, in <module>
>     main()
>   File "/home/user/test-compliance/content/utils/create-stig-overlay.py", line 176, in main
>     new_stig_overlay(disa_xccdftree, ssg_xccdftree, args.output_file, args.quiet)
>   File "/home/user/test-compliance/content/utils/create-stig-overlay.py", line 110, in new_stig_overlay
>     dom = xml.dom.minidom.parseString(ET.tostring(new_stig_overlay, encoding="UTF-8", xml_declaration=True))
> TypeError: tostring() got an unexpected keyword argument 'xml_declaration'
> make[2]: *** [ol7/overlays/stig_overlay.xml] Error 1
> make[1]: *** [ol7/CMakeFiles/generate-ol7-table-stig.dir/all] Error 2
> ```
This is a problem that only appears in python2. If you can use python3, please use it instead during the build. I'm going to investigate if I can fix this issue with python2 in the meantime.

**Comment by justchris1** [comment]
Python3 shouldn't be a problem as I do have it installed also.  I am not sure if there is a configuration file in CaC that allows me to override the python path.  Looks like hard coded to system python.  If there isn't an easy way, I will move over to a RedHat 8 machine and try again.

**Comment by justchris1** [comment]
I just moved over to a RHEL 8 machine that doesn't even have python2 installed and got the same error (python 3.6 installed):
```
[ 33%] [ol7-tables] generating STIG XML overlay
Traceback (most recent call last):
  File "/home/ccosta_a_local/temp9/content/utils/create-stig-overlay.py", line 180, in <module>
    main()
  File "/home/ccosta_a_local/temp9/content/utils/create-stig-overlay.py", line 176, in main
    new_stig_overlay(disa_xccdftree, ssg_xccdftree, args.output_file, args.quiet)
  File "/home/ccosta_a_local/temp9/content/utils/create-stig-overlay.py", line 110, in new_stig_overlay
    dom = xml.dom.minidom.parseString(ET.tostring(new_stig_overlay, encoding="UTF-8", xml_declaration=True))
TypeError: tostring() got an unexpected keyword argument 'xml_declaration'
make[2]: *** [ol7/CMakeFiles/generate-ol7-table-stig.dir/build.make:119: ol7/overlays/stig_overlay.xml] Error 1
make[1]: *** [CMakeFiles/Makefile2:16922: ol7/CMakeFiles/generate-ol7-table-stig.dir/all] Error 2
make: *** [Makefile:170: all] Error 2
```

**Comment by ggbecker** [comment]
> Python3 shouldn't be a problem as I do have it installed also. I am not sure if there is a configuration file in CaC that allows me to override the python path. Looks like hard coded to system python. If there isn't an easy way, I will move over to a RedHat 8 machine and try again.

This #7317 should fix the problem. But it can take until tomorrow to be merged depending on reviewers. You can hack the file (utils/create-stig-overlay.py) and just remove the `xml_declaration` parameter and it should work for now.

This keyword `xml_declaration` was introduced in python 3.8.

**Pull request closed without merging**
