### PR TITLE
OCPBUGS-42177: Fix resource quota

### PR DESCRIPTION
**Pull request by Vincent056**
This PR fixes resource quota rule, resource_requests_quota did not include the updated jq filter from #12344

### CODE REVIEW

**Comment by xiaojiey** [comment]
Pre-merge verification pass with ghcr.io/complianceascode/k8scontent:12399:
```
% oc get resourcequota --all-namespaces
NAMESPACE                NAME                            AGE    REQUEST                                                              LIMIT
foo                      test-quota                      109m   count/daemonsets.apps: 0/0, count/deployments.apps: 0/0, pods: 0/0   limits.cpu: 0/0, limits.memory: 0/0
openshift-host-network   host-network-namespace-quotas   149m   count/daemonsets.apps: 0/0, count/deployments.apps: 0/0, pods: 0/0   limits.cpu: 0/0, limits.memory: 0/0
test-no-rate-limit       example-1                       116m   pods: 0/4, requests.cpu: 0/1, requests.memory: 0/1Gi                 limits.cpu: 0/2, limits.memory: 0/2Gi

% oc get ccr | grep resource-requests-quota
ocp4-moderate-resource-requests-quota                                            FAIL     medium
upstream-ocp4-moderate-resource-requests-quota                                   PASS     medium

% oc get ccr upstream-ocp4-moderate-resource-requests-quota -o=jsonpath={.instructions}
Run the following command to retrieve the ClusterResourceQuota objects in the system:
$ oc get clusterquota --all-namespaces
Make sure there exists at least one ClusterResourceQuota object in the cluster.
 
Or
 
Verify that the every non-control plane namespace has an appropriate ResourceQuota.
 
To get all the non-control plane namespaces, you can do the
following command $ oc get  namespaces -o json | jq '[.items[] | select((.metadata.name | startswith("openshift") | not) and (.metadata.name | startswith("kube-") | not) and .metadata.name != "default" and .metadata.name != "rhacs-operator" and (true)) | .metadata.name]'
 
To get all the non-control plane namespaces with a ResourceQuota, you can do the
following command $ oc get --all-namespaces resourcequota -o json | jq '[.items[] | select((.metadata.namespace | startswith("openshift") | not) and (.metadata.namespace | startswith("kube-") | not) and .metadata.namespace != "default" and .metadata.namespace != "rhacs-operator" and (true)) | .metadata.namespace] | unique'
 
Make sure that the namespaces displayed in the commands of the commands match.
Is it the case that Resource requests and limits is not set?%                                                                           

 % oc get  namespaces -o json | jq '[.items[] | select((.metadata.name | startswith("openshift") | not) and (.metadata.name | startswith("kube-") | not) and .metadata.name != "default" and .metadata.name != "rhacs-operator" and (true)) | .metadata.name]'
[
  "foo",
  "test-no-rate-limit"
]
% oc get --all-namespaces resourcequota -o json | jq '[.items[] | select((.metadata.namespace | startswith("openshift") | not) and (.metadata.namespace | startswith("kube-") | not) and .metadata.namespace != "default" and .metadata.namespace != "rhacs-operator" and (true)) | .metadata.namespace] | unique'
[
  "foo",
  "test-no-rate-limit"
]
```

**Comment by xiaojiey** [comment]
lgtm

**Review by yuumasato — APPROVED** [review]
Thank you @Vincent056

**Pull request merged**
