### PR TITLE
Introduce `/rpmbuild-ctest-fedora` CI for all Fedora versions

### PR DESCRIPTION
**Pull request by mildas**
#### Description:
Re-introduce `rpmbuild-ctest` for all supported Fedora versions. The test takes srpm, builds it from sources, and runs ctest for all Fedora enabled products.

`rpmbuild-ctest` got necessary update related in https://github.com/RHSecurityCompliance/contest/pull/224 Now, it installs recommended packages to enable more unit tests.

Also improve TMT plan regexes to not match multiple profiles.
Before:
[testing-farm:centos-stream-8-x86_64:/hardening/host-os/ansible/cis](https://artifacts.dev.testing-farm.io/5f7e67b8-3724-4cf4-ad27-80e571522ef7/) - matches all `cis` profiles because of regex match
After:
[testing-farm:centos-stream-8-x86_64:/hardening/host-os/ansible/cis](https://artifacts.dev.testing-farm.io/c9e0f240-9681-4677-adca-225ef8fbe648/) - matches only `cis` profile as intended

#### Rationale:
Recently, one of our unit tests was failing on Fedora Rawhide and it was not caught by CI.

#### Review Hints:
See Testing Farm `/rpmbuild-ctest-fedora` Fedora jobs.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@mildas  Is the no space left on deviceproblem caused by the fact that we build every SSG product on Fedora?

**Comment by mildas** [comment]
@jan-cerny Yes, from what I've checked it seem so

**Comment by Mab879** [comment]
@mildas What needs to be done to move this PR a long?

**Comment by mildas** [comment]
@Mab879 Sorry, I completely forgot about this PR and didn't get notification from your ping. I will investigate what is going on with Fedora and try to fix

**Comment by mildas** [comment]
Problem related to rpmbuild fixed in Contest and PR description updated. Now it's ready for merge.

**Review by Mab879 — APPROVED** [review]
Thanks!

**Pull request merged**
