### PR TITLE
Preserve Ansible YAML Order

### PR DESCRIPTION
**Pull request by redhatrises**
#### Description:

For example, `tasks/main.yml` was not preserving the key order that is created in the Ansible scripts.
This was making the `yml` difficult to read.

### CODE REVIEW

**Comment by jan-cerny** [comment]
There are multiple PEP8 problems.
```
utils/upload_ansible_roles_to_galaxy.py:33:1: E302 expected 2 blank lines, found 1
utils/upload_ansible_roles_to_galaxy.py:34:3: E111 indentation is not a multiple of four
utils/upload_ansible_roles_to_galaxy.py:36:1: E302 expected 2 blank lines, found 1
utils/upload_ansible_roles_to_galaxy.py:37:3: E111 indentation is not a multiple of four
utils/upload_ansible_roles_to_galaxy.py:39:1: E305 expected 2 blank lines after class or function definition, found 1
utils/upload_ansible_roles_to_galaxy.py:39:22: E201 whitespace after '('
utils/upload_ansible_roles_to_galaxy.py:39:46: E203 whitespace before ','
utils/upload_ansible_roles_to_galaxy.py:39:65: E202 whitespace before ')'
utils/upload_ansible_roles_to_galaxy.py:40:22: E201 whitespace after '('
utils/upload_ansible_roles_to_galaxy.py:40:53: E202 whitespace before ')'
```

**Comment by shawndwells** [comment]
@jan-cerny where are those errors discovered, since they're not exposed by jenkins? Do you run tests by hand on PRs? Could they be integrated into jenkins somehow?

**Comment by jan-cerny** [comment]
@shawndwells I have noticed the problem by looking at the patch and then I run manually `pycodestyle` and copy-pasted the output because I didn't want to write a lot of comments here.

But there used to be pep8speaks bot running that reported Python code style problems automatically to the PR. I  have to check why it isn't run anymore.

**Comment by redhatrises** [comment]
> There are multiple PEP8 problems.
> 
> ```
> utils/upload_ansible_roles_to_galaxy.py:33:1: E302 expected 2 blank lines, found 1
> utils/upload_ansible_roles_to_galaxy.py:34:3: E111 indentation is not a multiple of four
> utils/upload_ansible_roles_to_galaxy.py:36:1: E302 expected 2 blank lines, found 1
> utils/upload_ansible_roles_to_galaxy.py:37:3: E111 indentation is not a multiple of four
> utils/upload_ansible_roles_to_galaxy.py:39:1: E305 expected 2 blank lines after class or function definition, found 1
> utils/upload_ansible_roles_to_galaxy.py:39:22: E201 whitespace after '('
> utils/upload_ansible_roles_to_galaxy.py:39:46: E203 whitespace before ','
> utils/upload_ansible_roles_to_galaxy.py:39:65: E202 whitespace before ')'
> utils/upload_ansible_roles_to_galaxy.py:40:22: E201 whitespace after '('
> utils/upload_ansible_roles_to_galaxy.py:40:53: E202 whitespace before ')'
> ```

Thanks @jan-cerny! pep8 complaints should be fixed.

**Comment by redhatrises** [comment]
@pep8speaks suggest diff

**Pull request merged**
