### PR TITLE
Drop "esc" package from install_smartcard_packages rule

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Drop "esc" package from install_smartcard_packages rule and use [package_installed](https://github.com/ComplianceAsCode/content/blob/master/docs/manual/developer_guide.adoc#732-list-of-available-templates) template to generate new content since now it contains only the instruction to install `pam_pkcs11` package.

#### Rationale:

- Reference: https://vaulted.io/library/disa-stigs-srgs/red_hat_enterprise_linux_7_security_technical_implementation_guide/V-72417?version=V1R4&compareto=v2r8

- This package is not recommended anymore by STIG. Unless we want to keep it in a similar way as `smartcard_auth` has when `GConf2/dconf` is installed: [smartcard_auth/oval/shared.xml#L16](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_auth/oval/shared.xml#L16)

- It also fixes some SRG mappings that are still typos in official RHEL7 STIG, these are the actual SRG that were used as reference:
    - [SRG-OS-000377-GPOS-00162](https://vaulted.io/library/disa-stigs-srgs/general_purpose_operating_system_srg/V-56813)
    - [SRG-OS-000376-GPOS-00161](https://vaulted.io/library/disa-stigs-srgs/general_purpose_operating_system_srg/V-56815)

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule install_smartcard_packages:
 OVAL check for install_smartcard_packages was deleted.
 Bash remediation was deleted. No test for it will be selected.

**Comment by jan-cerny** [comment]
@ggbecker Please resolve the conflicts.

**Comment by ggbecker** [comment]
> @ggbecker Please resolve the conflicts.

Done

**Comment by mildas** [comment]
**Changes identified:**
Rule install_smartcard_packages:
 Bash remediation was deleted. No test for it will be selected.
 OVAL check for install_smartcard_packages was deleted.

**Pull request merged**
