### PR TITLE
adjust test scenarios for audit_file_contents template

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- create test scenarios for templates
- remove custom test scenarios and test data

#### Rationale:

cleanup

### CODE REVIEW

**Comment by matusmarhefka** [comment]
There is an issue with the `rules_from_audit_package.pass.sh` scenarios when testing on the RHEL-8.4 compose. It is because of older audit package which has a different content in the `/usr/share/audit/sample-rules/...` files compared to what our rules expect. I would vote for removing these custom scenarios as we no longer depend on contents of the files provided in the `audit` package, wdyt?

**Comment by vojtapolasek** [comment]
I think we should actually keep these tests to prevent breakage from future Audit releases. Doesn't the 8.4 have a different OVAL than the master branch here?

**Comment by jan-cerny** [comment]
@vojtapolasek It would be more transparent if the status of the PR would be described in the PR in a form of a comment or as a part of the PR's description.

**Comment by vojtapolasek** [comment]
I am closing this PR. We have decided to do some additional changes to these rules. Removal of redundant tests will be part of the new PR.

**Pull request closed without merging**
