### PR TITLE
OCP: Add SA-4(8) to the list of controls addressed by having compliance operator

### PR DESCRIPTION
**Pull request by jhrozek**
SA-4(8) says:
A successful control response will document how to achieve continuous
monitoring of control/standards as identified in CA-7.

### CODE REVIEW

**Comment by jhrozek** [comment]
And now with the correct patch, sorry.

**Review by JAORMX — APPROVED** [review]
LGTM.

Feel free to merge once it passes CI

**Comment by jhrozek** [comment]
Interesting:
```
    helpers.go:720: Result - Name: e2e-moderate-node-master-file-permissions-var-log-kube-audit - Status: INCONSISTENT - Severity: medium
    helpers.go:723: E2E-FAILURE: The expected result for the file_permissions_var_log_kube_audit rule didn't match. Expected 'map[master:PASS worker:NOT-APPLICABLE]', Got 'INCONSISTENT'
```
Now..I don't really understand how the check result could end up inconsistent, all the master checks in the CM are passing and all the worker checks are notapplicable. I'll leave the PR open and try to re-test it tomorrow interactively..

**Pull request merged**
