### PR TITLE
Fix ansible lint spacing issues.

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Fix ansible lint issues

#### Rationale:

- Fixes https://jenkins.complianceascode.io/job/scap-security-guide-lint-check/

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule sshd_rekey_limit:
 Template usage changed in ansible remediation.

**Recommended tests to execute:**
 build_product ol8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml sshd_rekey_limit

**Comment by jan-cerny** [comment]
@ggbecker The patch looks good to me and the test scenarios for this rule are passing. But, I wonder, What is the string `[0/453]` on line 1 good for?

**Comment by ggbecker** [comment]
> @ggbecker The patch looks good to me and the test scenarios for this rule are passing. But, I wonder, What is the string `[0/453]` on line 1 good for?

I have no idea. Haven't noticed that... it's too far to the right haha... I'll remove that

**Comment by mildas** [comment]
**Changes identified:**
Rule sshd_rekey_limit:
 Template usage changed in ansible remediation.

**Recommended tests to execute:**
 build_product ol8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml sshd_rekey_limit

**Comment by mildas** [comment]
**Changes identified:**
Rule sshd_rekey_limit:
 Template usage changed in ansible remediation.

**Recommended tests to execute:**
 build_product fedora
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-fedora-ds.xml sshd_rekey_limit

**Pull request merged**
