### PR TITLE
Sle15 cis

### PR DESCRIPTION
**Pull request by eradot4027**
#### Description:

-Updated CIS profile is SLE15 to reflect changes in the profile

#### Rationale:

For evaluating systems with an up to date profile

- Fixes # 
None

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Profile cis on sle15:
 Rule set_firewalld_default_zone, disable_prelink, package_firewalld_installed, service_firewalld_enabled added to cis profile.
 Rule selinux_policytype, kernel_module_freevxfs_disabled, no_legacy_plus_entries_etc_group, package_libselinux_installed, configure_etc_hosts_deny, package_mcstrans_removed, kernel_module_hfs_disabled, no_legacy_plus_entries_etc_shadow, package_tcp_wrappers_installed, grub2_enable_selinux, kernel_module_jffs2_disabled, sshd_allow_only_protocol2, service_tftp_disabled, selinux_state, kernel_module_rds_disabled, selinux_confinement_of_daemons, kernel_module_hfsplus_disabled, no_legacy_plus_entries_etc_passwd, package_setroubleshoot_removed, kernel_module_tipc_disabled removed from cis profile.

**Recommended tests to execute:**
 build_product sle15
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-sle15-ds.xml cis

**Comment by mildas** [comment]
**Changes identified:**
Profile cis on sle15:
 Rule grub2_enable_selinux, kernel_module_hfsplus_disabled, package_mcstrans_removed, package_tcp_wrappers_installed, kernel_module_freevxfs_disabled, configure_etc_hosts_deny, sshd_allow_only_protocol2, selinux_state, no_legacy_plus_entries_etc_group, package_libselinux_installed, kernel_module_tipc_disabled, kernel_module_rds_disabled, no_legacy_plus_entries_etc_shadow, kernel_module_hfs_disabled, package_setroubleshoot_removed, service_tftp_disabled, kernel_module_jffs2_disabled, selinux_confinement_of_daemons, selinux_policytype, no_legacy_plus_entries_etc_passwd removed from cis profile.
 Rule disable_prelink, set_firewalld_default_zone, service_firewalld_enabled added to cis profile.

**Recommended tests to execute:**
 build_product sle15
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-sle15-ds.xml cis

**Comment by mildas** [comment]
**Changes identified:**
Profile cis on sle15:
 Rule kernel_module_hfs_disabled, kernel_module_jffs2_disabled, no_legacy_plus_entries_etc_shadow, kernel_module_hfsplus_disabled, configure_etc_hosts_deny, package_tcp_wrappers_installed, kernel_module_tipc_disabled, kernel_module_freevxfs_disabled, no_legacy_plus_entries_etc_group, package_libselinux_installed, no_legacy_plus_entries_etc_passwd, selinux_state, selinux_confinement_of_daemons, package_setroubleshoot_removed, service_tftp_disabled, kernel_module_rds_disabled, sshd_allow_only_protocol2, selinux_policytype, package_mcstrans_removed, grub2_enable_selinux removed from cis profile.
 Rule disable_prelink added to cis profile.

**Recommended tests to execute:**
 build_product sle15
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-sle15-ds.xml cis

**Comment by eradot4027** [comment]
Commented out missing checks.  Should compile now.  I apologize

**Comment by mildas** [comment]
**Changes identified:**
Profile cis on sle15:
 Rule disable_prelink added to cis profile.
 Rule kernel_module_freevxfs_disabled, selinux_policytype, service_tftp_disabled, configure_etc_hosts_deny, no_legacy_plus_entries_etc_group, package_mcstrans_removed, kernel_module_rds_disabled, kernel_module_tipc_disabled, sshd_allow_only_protocol2, kernel_module_hfsplus_disabled, package_libselinux_installed, no_legacy_plus_entries_etc_shadow, kernel_module_jffs2_disabled, selinux_confinement_of_daemons, kernel_module_hfs_disabled, no_legacy_plus_entries_etc_passwd, package_tcp_wrappers_installed, selinux_state, package_setroubleshoot_removed, grub2_enable_selinux removed from cis profile.

**Recommended tests to execute:**
 build_product sle15
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-sle15-ds.xml cis

**Comment by yuumasato** [comment]
Changes look good to me, but I haven't verified the alignment with SLE15 CIS.
@eradot4027 do you have someone who can review that for you?

**Comment by eradot4027** [comment]
I have been working on this completely by myself and referencing the CIS Workbench STIG.  I can see if I can get someone else to review.  Seems like most people don't use SUSE.

**Comment by yuumasato** [comment]
@eradot4027 We don't need to block this PR waiting for review on the alignment.
I'm fine merging it as updates can come later if needed.

**Comment by eradot4027** [comment]
I plan on using it in production so I am being meticulous as possible to ensure it is correct.

Thanks again for allowing me to contribute to your project

**Pull request merged**
