### PR TITLE
OCP4 STIG: Add artifact description to SRG-APP-000033

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- Sorry for the PR spam, but in my previous PR I forgot to add
  `artifact_description` to these two controls, my sync script
  was only recently enhanced with that.

#### Rationale:

- Render the controls correctly

#### Review Hints:

- `./build_product --debug ocp4`
- `export PYTHONPATH=$(pwd); python3 ./utils/rule_dir_json.py`
- `export PYTHONPATH=$(pwd); python3 utils/create_srg_export.py -c controls/srg_ctr.yml -p ocp4 -m shared/references/disa-ctr-srg-v1r3.xml --out-format html --output /tmp/srg-mapping-ocp4.html`
- compare with the current DISA STIG spreadsheet

### CODE REVIEW

**Comment by jhrozek** [comment]
/retest
cluster install failures

**Comment by jhrozek** [comment]
there's no reason for a test to fail when just metadata was added, nonetheless, let's try for a clean CI
/test e2e-aws-ocp4-stig-node

**Comment by jhrozek** [comment]
Clean CI, PTAL

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
