### PR TITLE
OCP4: Don't limit prometheus rules to 500

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

The rules were fetching only the first 500 prometheus rules in an
attempt to limit the API server load, but this seems to be missing some
rules and ultimately failing the rules.

Let's just fetch them all.

#### Rationale:

- Fixes OCPBUGS-11477

#### Review Hints:

- I guess create many prometheus rule but only one would be addressing the checks

### CODE REVIEW

**Comment by jhrozek** [comment]
stupid CI, finding bugs in my code..

**Comment by jhrozek** [comment]
@rhmdnd @Vincent056 PTAL

**Comment by jhrozek** [comment]
> This is similar to [82b4273](https://github.com/ComplianceAsCode/content/commit/82b4273dd2a9af38d847e0e54194cd5442b79505).
> 
> Do you know why we had a limit of 500 in the first place?

I don't remember exactly but I suspect it was simply because that's what `kubectl` or `oc` default to:
```
$ oc get -v6 pods
I0419 14:57:17.151354 3782865 loader.go:373] Config loaded from file:  /home/jhrozek/openshift/cluster-installs/latest/auth/kubeconfig
I0419 14:57:17.462450 3782865 round_trippers.go:553] GET https://api.jhrozek-cluster-04-19-09-54.devcluster.openshift.com:6443/api/v1/namespaces/default/pods?limit=500 200 OK in 306 milliseconds
```
maybe we could handle the limit in the api-resource-collector, but we would have to know a bit more about the search. For cases where any resource satisfies the check we could use paging and break if the query matches at least one object, but for cases where all resources must satisfy the check there's no other way than really looking at everything (paging might be useful to spread the load on the server and not keep all objects in memory though).

**Comment by xiaojiey** [comment]
/hold
It is a little weird that after PR applied, the alert could not raised.
@jhrozek Could you please help to check? Thanks.

**Comment by xiaojiey** [comment]
Sorry, found the root cause: the ns was not labeled.
$ oc label ns openshift-compliance openshift.io/cluster-monitoring=true
namespace/openshift-compliance labeled
After applied the label, the alert could be fired for compliance operator. 
Also checked for FIO, the alert could also be fired.

**Comment by jhrozek** [comment]
> openshift.io/cluster-monitoring=true

glad you found it, but the namespace should have been labeled by default when installing from `make deploy-local` at least. Did you maybe install from the GUI and didn't select the monitoring option?

**Comment by xiaojiey** [comment]
/unhold
Install CO and applied content in the PR,
did a regression test. The 3 related rules could PASS:
$ oc get ccr | grep alert
upstream-ocp4-moderate-audit-error-alert-exists                                     PASS     high
$ oc get ccr | grep notification
upstream-ocp4-moderate-compliance-notification-enabled                              PASS     medium
upstream-ocp4-moderate-file-integrity-notification-enabled                          PASS     medium
$ oc get ccr | grep alert
upstream-ocp4-moderate-audit-error-alert-exists                                     PASS     high

**Comment by jhrozek** [comment]
@rhmdnd @Vincent056 PTAL

**Review by rhmdnd — APPROVED** [review]

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
