### PR TITLE
Remove not applicable rules for OL8 & OL9

### PR DESCRIPTION
**Pull request by Xeicker**
#### Description:

- Delete default profiles in OL8 & OL9 as we found some non applicable rules in there so they are not reliable even for reference
- Remove rules that depend on packages not available in OL8 & OL9 yum repos

#### Rationale:

- This would allow to test rule `ALL` with automatus

### CODE REVIEW

**Comment by Mab879** [comment]
The default profile is for keeping rules in the data stream, by removing it you risk breaking existing tailoring files. Just double checking to see if this is what you wanted.

**Comment by Xeicker** [comment]
I didn't consider that scenario, thanks for mentioning it. So better just removed rules that weren't applicable or are not ready for OL8 & 9

**Review by Mab879 — APPROVED** [review]
Waving CI failures as they not related to this PR.

**Pull request merged**
