### PR TITLE
Add ansible remediation for dconf_gnome_screensaver_idle_activation_locked

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Add ansible remediation for dconf_gnome_screensaver_idle_activation_locked.
- Add RHEL8 CCE
- Add Fedora platform in bash remediation

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule dconf_gnome_screensaver_idle_activation_locked:
 Ansible remediation newly added.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml dconf_gnome_screensaver_idle_activation_locked

**Comment by mildas** [comment]
**Changes identified:**
Rule dconf_gnome_screensaver_idle_activation_locked:
 Ansible remediation newly added.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml dconf_gnome_screensaver_idle_activation_locked

**Comment by vojtapolasek** [comment]
Please fix conflicts, othervise looks good

**Comment by ggbecker** [comment]
> Please fix conflicts, othervise looks good

It's the CCE that got changed lately. I'll fix that real quick.

**Comment by mildas** [comment]
**Changes identified:**
Rule dconf_gnome_screensaver_idle_activation_locked:
 Ansible remediation newly added.

**Recommended tests to execute:**
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml dconf_gnome_screensaver_idle_activation_locked

**Comment by vojtapolasek** [comment]
Thank you, merging

**Pull request merged**
