### PR TITLE
fix rule accounts_password_pam_unix_remember

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- add tests
- make oval check for both system-auth and password-auth like the description states
- rewrite remediations to keep pam_unix.so if already used but prefer pam_pwhistory.so, as pam_unix.so is not being supported in later pam versions

#### Rationale:

- remediations and checks were not aligned with rule description

### CODE REVIEW

**Review by yuumasato — COMMENTED** [review]
NAck.

The approach to keep adding `remember` to `pam_unix` if it is present is not a good one, `pam_unix` will most likely be always present.
Similar approach would be to check if `pam_unix` is already used for `remember` purposes, but that doesn't work either.
Changing the password after it expires doesn't work when `pam_unix .* remember` is configured in `rhel7` and `rhel8`.
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1778929

**Comment by yuumasato** [comment]
Snack for discussion: A rule should probably address `system-auth` and `password-auth` independently.

**Comment by yuumasato** [comment]
How about taking [accounts_password_pam_pwhistory_remember](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember/rule.yml) and making `system-auth` and `password-auth` version?

**Comment by ggbecker** [comment]
> How about taking [accounts_password_pam_pwhistory_remember](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember/rule.yml) and making `system-auth` and `password-auth` version?

To add a bit of context, this rule was introduced by Suse folks and they were following SLE12 STIG strictly. We are in the process of asking DISA to split these similar rules in RHEL8. Hopefully, when they accept it, these changes will also be reflected in STIG for other products.

**Comment by yuumasato** [comment]
> > How about taking [accounts_password_pam_pwhistory_remember](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_pwhistory_remember/rule.yml) and making `system-auth` and `password-auth` version?
> 
> To add a bit of context, this rule was introduced by Suse folks and they were following SLE12 STIG strictly. We are in the process of asking DISA to split these similar rules in RHEL8. Hopefully, when they accept it, these changes will also be reflected in STIG for other products.

I see now that rule actually configurew two things, `remember` and `use_authtok`.

**Comment by yuumasato** [comment]
This has been superseded by #6672.

**Pull request closed without merging**
