### PR TITLE
Create script to build datastream images from source

### PR DESCRIPTION
**Pull request by JAORMX**
This script runs the build_product script (taking the product as a
parameter), and it pushes the `ssg-$PRODUCT-ds.xml` file to a container.

The container is created by using a BuildConfig and an ImageStream,
these are updated by pushing the local XML file to the container build.

This is just one step of the build process which helps with local
development. In further iterations, I'll create a BuildConfig that builds
inside a container as opposed to requiring a local file.

Example:

    ./utils/build_ds_container.sh ocp4

### CODE REVIEW

**Comment by JAORMX** [comment]
Note that this makes some assumptions (e.g. the naming scheme of the ds file is ssg-<product name>-ds.xml). This works for ocp4 and that's what I tested. I haven't tested this for rhel yet.

**Comment by JAORMX** [comment]
Just tested it with RHEL and did some fixes.

**Comment by jan-cerny** [comment]
@JAORMX Great! Thanks. Please move it to `utils` directory or elsewhere.

**Comment by JAORMX** [comment]
@jan-cerny done! thanks for the feedback

**Pull request merged**
