### PR TITLE
OCP4 STIG: Add status justification to SRG-APP-000178-CTR-000470, covering IA-6

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- The IA family is mostly covered by setting up the IDP, this commit just adds
  artifact description and status justification to two rules in the IA-11 family

#### Rationale:

- OCP4 STIG

#### Review Hints:

- I will post a link to the SRG export later

### CODE REVIEW

**Comment by jhrozek** [comment]
pushed a new version that just adds empty line at the end of the control file as required by the project coding standards. Also rebased on master.

**Comment by jhrozek** [comment]
To review, compare the [SRG mapping]( https://github.com/ComplianceAsCode/content/suites/11228939598/artifacts/574793456) generated by the GH actions with the [current version](https://docs.google.com/spreadsheets/d/1ouRalvXzRHuhPPN_AKMvqqscUqGvVOkkEdMP3YYBO44/edit#gid=1859516253) of the DISA STIG.

**Comment by jhrozek** [comment]
@rhmdnd @Vincent056 PTAL

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
