### PR TITLE
Fix remediation of accounts_password_pam_unix_remember

### LINKED ISSUE #7133: accounts_password_pam_unix_remember - remediation doesn't work properly in some cases
#### Description of problem:
The `accounts_password_pam_unix_remember` rule has a test scenario - `rhel8_wrong_value.fail.sh` - that fails in remediation stage.

#### SCAP Security Guide Version:
`2580c56`

#### Operating System Version:
RHEL 8.4

#### Steps to Reproduce:

1.  `python3 tests/test_suite.py rule --libvirt qemu:///system test-suite-rhel8 --datastream build/ssg-rhel8-ds.xml accounts_password_pam_unix_remember`

#### Actual Results:
```
INFO - xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_remember
INFO - Script rhel8_wrong_value.fail.sh using profile (all) OK
ERROR - Rule evaluation resulted in error, instead of expected fixed during remediation stage 
ERROR - The remediation failed for rule 'xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_remember'.
INFO - Script argument_missing.fail.sh using profile (all) OK
INFO - Script rhel8_correct_value.pass.sh using profile (all) OK
```

#### Expected Results:
```
INFO - xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_remember
INFO - Script rhel8_wrong_value.fail.sh using profile (all) OK
INFO - Script argument_missing.fail.sh using profile (all) OK
INFO - Script rhel8_correct_value.pass.sh using profile (all) OK
```

#### Additional information:
The remediation also fails in rhel7 but in after `wrong_value.fail.sh`.
```
INFO - xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_remember
INFO - Script argument_missing.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
ERROR - Rule evaluation resulted in fail, instead of expected pass during final stage 
ERROR - The check after remediation failed for rule 'xccdf_org.ssgproject.content_rule_accounts_password_pam_unix_remember'.
```

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Fix remediation of accounts_password_pam_unix_remember.
  - It needs to additionally account for pam_pwhistory with controls of kinds "requisite"
and "required" in both system-auth and password-auth.

- Fixes #7133

### CODE REVIEW

**Review by jan-cerny — COMMENTED** [review]
The `rule.yml` doesn't mention `/etc/pam.d/password-auth`, only `/etc/pam.d/system-auth` is used in the description, so the rule description probably should be improved. The OVAL also checks only  `/etc/pam.d/system-auth`. The rule description, OVAL, Bash and Ansible need to be consistent.

Also it would be nice to mentions the requisite/required and sufficient/required in the rule description.

I also think think that the test scenarios need to be extended so that they would cover all the situations. They seem to set values in both files at once, but what would happen if only one of the files or one of the modules are used?

**Comment by ggbecker** [comment]
> @ggbecker I'm not opposed to updating the existing pam_unix rule, however, I would not include the pam_pwhistory as I've already solved this with another PR: #7055
> 
> This takes care of the password-auth and system-auth, along with the correct type of requisite|required for pam_pwhistory. This existing rule is outdated and not sure if we would like to continue to keep it here for backwards compat.

I agree. We probably just have to remove the test scenario though and make sure that the ansible remediation iterates over the two files (system-auth and password-auth).

**Comment by ggbecker** [comment]
> > @ggbecker I'm not opposed to updating the existing pam_unix rule, however, I would not include the pam_pwhistory as I've already solved this with another PR: #7055
> > This takes care of the password-auth and system-auth, along with the correct type of requisite|required for pam_pwhistory. This existing rule is outdated and not sure if we would like to continue to keep it here for backwards compat.
> 
> I agree. We probably just have to remove the test scenario though and make sure that the ansible remediation iterates over the two files (system-auth and password-auth).

Also, this rule is selected by many profiles... so we can keep at least consistent.

```
./ol7/profiles/pci-dss.profile:    - accounts_password_pam_unix_remember
./ol7/profiles/stig.profile:    - accounts_password_pam_unix_remember
./ol7/profiles/ospp.profile:    - accounts_password_pam_unix_remember
./rhv4/profiles/pci-dss.profile:    - accounts_password_pam_unix_remember
./rhv4/profiles/rhvh-stig.profile:    - accounts_password_pam_unix_remember
./rhv4/profiles/rhvh-vpp.profile:    - accounts_password_pam_unix_remember
./rhel8/profiles/pci-dss.profile:    - accounts_password_pam_unix_remember
./rhel8/profiles/rht-ccp.profile:    - accounts_password_pam_unix_remember
./rhel8/profiles/ospp.profile:    - accounts_password_pam_unix_remember
./rhel8/profiles/cis.profile:    - accounts_password_pam_unix_remember
./rhel7/profiles/C2S.profile:    - accounts_password_pam_unix_remember
./rhel7/profiles/pci-dss.profile:    - accounts_password_pam_unix_remember
./rhel7/profiles/stig.profile:    - accounts_password_pam_unix_remember
./rhel7/profiles/rht-ccp.profile:    - accounts_password_pam_unix_remember
./rhel7/profiles/ospp.profile:    - accounts_password_pam_unix_remember
./rhel7/profiles/rhelh-stig.profile:    - accounts_password_pam_unix_remember
./rhel7/profiles/rhelh-vpp.profile:    - accounts_password_pam_unix_remember
./sle15/profiles/stig.profile:    - accounts_password_pam_unix_remember
./wrlinux1019/profiles/draft_stig_wrlinux_disa.profile:    - accounts_password_pam_unix_remember
./ol8/profiles/pci-dss.profile:    - accounts_password_pam_unix_remember
./ol8/profiles/ospp.profile:    - accounts_password_pam_unix_remember
./fedora/profiles/pci-dss.profile:    - accounts_password_pam_unix_remember
```

**Comment by ggbecker** [comment]
@carlosmmatos Now the remediations only touch pam_unix.so module even though the OVAL still considers pam_pwhistory as a valid configuration same way it was before so we don't break any existing system.

I've noticed one of the `sed`s in some test scenarios was missing the target file, so I fixed that.

**Comment by carlosmmatos** [comment]
@ggbecker I know that it's mentioned in many profiles, but I couldn't find any official benchmarks that required this. For example (and we should update this), the [RHEL 7 STIG](https://vaulted.io/library/disa-stigs-srgs/red_hat_enterprise_linux_7_security_technical_implementation_guide/V-204422) does not use pam_unix for the remember option, instead, it uses the newer pam_pwhistory module. I'm pretty sure oracle is the same.

**Comment by jan-cerny** [comment]
@ggbecker What are your plans?

**Comment by ggbecker** [comment]
Closing as different solution have been already implemented.

**Pull request closed without merging**
