### PR TITLE
Remove rhel7 product

### LINKED ISSUE #12044: [Product Removal Request] RHEL7
#### Product to be removed:

RHEL 7

#### Reason for Product removal:

* Product End-Of-Maintenance is on 2024-06-30 according to [Red Hat](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance). 
 
* Added: 2024-06-03 21:57 UTC Red Hat also stated that they no longer plan on updating RHEL 7 content after 2024-06-30, see the [Red Blog](https://www.redhat.com/en/blog/red-hat-enterprise-linux-7-end-compliance-content-june-30-2024) for more details.

#### Last contributors for the respective product:

1. @Mab879 
2.  @marcusburghardt 
3. @jan-cerny 
4. @evgenyz 
5. @vojtapolasek

#### Deadline to receive comments or objections:
2024-06-24 17:00 (UTC)

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

* Removes RHEL 7 product
* Cleans up testing due to RHEL 7 being gone

There still might some remain references to RHEL 7 in the testing and those will be cleaned up in a separate PR.

#### Rationale:

Fixes #12044

#### Review Hints:
Review the commits as they have details on the why.

### CODE REVIEW

**Comment by Mab879** [comment]
Once this is ready to merge we will need to make RHEL 7 no longer required as a test.

**Review by jan-cerny — COMMENTED** [review]
The changes I have seen are great. But, I can still grep some occurrences of `RHEL 7`, `rhel7` and similar strings. It isn't necessary to remove all of them, sometimes they can't be removed, but I think some of them should be removed, for example, the directory `tests/data/profile_stability/rhel7` should be removed.

**Comment by jan-cerny** [comment]
you plan to clean up the tests in a separate PR, so please disregard the comment about tests/data/profile_stability/rhel7

**Review by jan-cerny — APPROVED** [review]

**Review by jan-cerny — APPROVED** [review]
It makes sens to me to remove the RHEL 7 product because this old product is end of maintenance now, as of 2024-06-30, see https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance

**Pull request merged**
