### PR TITLE
SUSE audit_rules_privileged_commands_kmod add bash remediation SLE12/15

### PR DESCRIPTION
**Pull request by brett060102**
Ansible remediations existed, but not bash.

#### Description:

- Bash remediations were missing.

#### Rationale:

- Ansible is not officially support on all sle instamces

### CODE REVIEW

**Review by Mab879 — CHANGES_REQUESTED** [review]
You can combine these files to the `shared.sh` and just add the `# platform = multi_platform_sle` line to get the same effect

**Comment by brett060102** [comment]
@Mab879 I thought that having as shared.yml and share.sh would supersede the template in the rule.yml. Are you saying that will only happen for sle, if that is the only item in the platform spec?

**Comment by brett060102** [comment]
@Mab879  updated to combine ansible and basj sle15 and sle12 remediation files into singe shared. I am concerned about interaction with the template in the rule.yml.

But I can always revert if that is an issue.

**Comment by Mab879** [comment]
> @Mab879 updated to combine ansible and basj sle15 and sle12 remediation files into singe shared. I am concerned about interaction with the template in the rule.yml.
> 
> But I can always revert if that is an issue.

Ah thanks for catching that, looks like a revert is necessary. 

I assume you know this but `multi_platform_sle` is in the template.

**Comment by brett060102** [comment]
Change reverted.  Did know that sle is supported for the template, but it was not remediating correctly. I don't remember why.
I will come back to this when I have more time to track this down. Must likely as an effort to get rid of all of the sle12 and sl15 specific files.

**Comment by brett060102** [comment]
@Mab879 This one is ready for re-review.

**Comment by brett060102** [comment]
@Mab879 Can I please get a re-review on this one?
Thanks

**Review by Mab879 — APPROVED** [review]
Thanks for the PR. 

Waving the SSGTS failure due to no tests.

**Pull request merged**
