### PR TITLE
Add an unit test for the to_ocil() method

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
This commit adds an unit test for the ssg.build_yaml.Rule.to_ocil()
method and test whether it generates correct OCIL elements.

#### Rationale:

This PR is blocked by #9548 and #9617 and will be rebased on the top of master after they will be merged.

### CODE REVIEW

**Comment by Mab879** [comment]
Please rebase this PR.

**Comment by jan-cerny** [comment]
@Mab879 from the description: This PR is blocked by https://github.com/ComplianceAsCode/content/pull/9548 and https://github.com/ComplianceAsCode/content/pull/9617 and will be rebased on the top of master after they will be merged.

**Comment by jan-cerny** [comment]
I have rebased the PR on the top of the latest upstream master and I have changed the test to use the xmldiff module.

**Review by matejak — APPROVED** [review]
LGTM, thank you for the PR!
I would define an aspirational goal of reducing the amount of overall volume of the test content, e.g. by simplifying test data, but that can be done much later.

**Pull request merged**
