### PR TITLE
Set the `requires` to `sshd_set_keepalive` on `sshd_set_idle_timeout`

### LINKED ISSUE #11803: CCE-90811-1 is `notselected` by SSG, however for DISA STIG it `fail`
#### Description of problem:

The content is misaligned with an external (third party) content that targets the same policy - typically, this means that a system hardened by our content doesn't pass the scan by the external content.

#### Details:
Rule CCE-90811-1 which is `sshd_set_idle_timeout` is `notselected` in our content. The equivalent rule in DISA STIG checks the requirement and results in fail.

#### Outcome:
SSG and DISA contents are aligned

#### SCAP Security Guide Version:
latest master

####  External Content's Version:
REHL9 V1R2

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Clean up the `requires` for  sshd_set_keepalive.

#### Rationale:

Fixes #11803

### CODE REVIEW

**Comment by Mab879** [comment]
> The rule `sshd_set_idle_timeout` has the platform `os_linux[rhel]<=8.5`, on RHEL 9 the session timeout should be set by the rule `logind_session_timeout` instead.

I just removed the restriction. The [STIG doesn't have this](https://stigaview.com/products/rhel8/v1r13/RHEL-08-010201/) and there still value in this rule for RHEL 8.5+.

**Review by marcusburghardt — APPROVED** [review]
LGTM

**Pull request merged**
