### PR TITLE
Create shared.sh

### PR DESCRIPTION
**Pull request by cyarbrough76**
#### Description:

- _Added remediation for disabling dhcp configuration in sysconfig_networking_bootproto_ifcfg_

#### Rationale:

- _No remediation previously exist_

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule sysconfig_networking_bootproto_ifcfg:
 Bash remediation is newly added.

**Recommended tests to execute:**
 build_product rhel6
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel6-ds.xml sysconfig_networking_bootproto_ifcfg

**Comment by matejak** [comment]
test this please

**Comment by mildas** [comment]
**Changes identified:**
Rule sysconfig_networking_bootproto_ifcfg:
 Bash remediation is newly added.

**Recommended tests to execute:**
 build_product rhel6
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel6-ds.xml sysconfig_networking_bootproto_ifcfg

**Comment by thenefield** [comment]
Yes this was just done for BOOTPROT= because that is what is specifically called for in the STIG. We just implemented the check and remediation based on the STIG guidance.

**Comment by redhatrises** [comment]
> Yes this was just done for BOOTPROT= because that is what is specifically called for in the STIG. We just implemented the check and remediation based on the STIG guidance.

Agree with @matejak. As part of this PR, handling the case where BOOTPROT is not configured should be addressed.

**Comment by cyarbrough76** [comment]
changing and retesting...

**Comment by mildas** [comment]
**Changes identified:**
Rule sysconfig_networking_bootproto_ifcfg:
 Bash remediation is newly added.

**Recommended tests to execute:**
 build_product rhel6
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel6-ds.xml sysconfig_networking_bootproto_ifcfg

**Comment by matejak** [comment]
LGTM, thanks!

**Pull request merged**
