### PR TITLE
Update ubuntu2404 control 2.3.3.1 

### PR DESCRIPTION
**Pull request by mpurg**
#### Description:

- Added rule and vars for Ubuntu 2404 CIS control 2.3.3.1 - "Ensure chrony is configured with authorized timeserver"
- Marked as a partial implementation since the rule does not check configs included via confdir and sourcedir directives
- Fixed the tests

### CODE REVIEW

**Review by dodys — APPROVED** [review]
lgtm, thanks!

**Comment by comps** [comment]
@mpurg @dodys Are you sure this PR fixed the tests?

Because multi-line `# variables = ` are not supported: [tests/file_missing.fail.sh](https://github.com/ComplianceAsCode/content/blob/8b4019ccbb0aacbe001dc600986a6e47c0f4f777/tests/ssg_test_suite/rule.py#L620-L634) (line 627, `variables = []` is done when a new `# variables = ` line is encountered).

So I believe there should be just one line, written as
```
# variables = var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org,var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org
```
(note that multiple commas in the value are fine, because the python logic concatenates them towards the left).

**Comment by mpurg** [comment]
@comps I believe it works as expected. Adding `print(variables)` after [line 634](https://github.com/ComplianceAsCode/content/blob/8b4019ccbb0aacbe001dc600986a6e47c0f4f777/tests/ssg_test_suite/rule.py#L634) results in this output:
```
$ python3 tests/automatus.py rule --libvirt qemu:///system sec-noble-amd64 --datastream build/ssg-ubuntu2404-ds.xml --remediate-using bash --profile "(all)"  --dontclean  chronyd_configure_pool_and_server

Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
['var_multiple_time_servers=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org', 'var_multiple_time_pools=0.suse.pool.ntp.org,1.suse.pool.ntp.org,2.suse.pool.ntp.org,3.suse.pool.ntp.org']
INFO - xccdf_org.ssgproject.content_rule_chronyd_configure_pool_and_server
INFO - Script incorrect_line3.fail.sh using profile (all) OK
INFO - Script incorrect_line2.fail.sh using profile (all) OK
INFO - Script incorrect_line4.fail.sh using profile (all) OK
INFO - Script file_empty.fail.sh using profile (all) OK
INFO - Script correct_chrony_configuration.pass.sh using profile (all) OK
INFO - Script incorrect_line1.fail.sh using profile (all) OK
INFO - Script file_missing.fail.sh using profile (all) OK
INFO - Script multiple_servers.pass.sh using profile (all) OK

```

**Comment by comps** [comment]
@mpurg Is this because of my fix https://github.com/ComplianceAsCode/content/pull/13252 or did it work before it?

**Comment by mpurg** [comment]
I'll just add that although the variables weren't read in properly, the tests were actually passing prior to the fix.
This is because the OVAL requires only one of the configuration options to be set (server _OR_ pool).
With this in mind, the tests should ideally also check the variables separately.

**Pull request merged**
