### PR TITLE
ocp4: add sshd golden config as sshd_set_loglevel_info remediation

### PR DESCRIPTION
**Pull request by JAORMX**
The golden config was missing the loglevel setting, so it was added.

### CODE REVIEW

**Comment by jhrozek** [comment]
I know that this is marked as WIP, but the decoded file doesn't seem to be different from the others...

**Comment by JAORMX** [comment]
@jhrozek it isn't. The decoded file indeed address this specific configuration.

**Comment by matejak** [comment]
test this please

**Pull request merged**
