### PR TITLE
OCP4: Kubernetes 1.24+ does not support the insecure-port flag

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

Kubernetes 1.24 removed the insecure-port flag completely:
    https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#deprecation
so let's change the rule that checks for the option setting to only be
applicable for older releases.

#### Rationale:

We need to support OCP 4.11

For failure, see https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/29623/rehearse-29623-pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-moderate/1538803521816629248/build-log.txt

### CODE REVIEW

**Comment by jhrozek** [comment]
/retest
tests timed out

**Comment by jhrozek** [comment]
I brought up the failures to pull the must gather image from build05 on slack on forum-testplatform, someone is looking into it.

**Review by Vincent056 — COMMENTED** [review]
I think the PR looks good, let's wait for the CI to pass

**Comment by rhmdnd** [comment]
/retest

Looks good to me. Waiting on a clean run from CI (most recent failure looks unrelated.)

**Comment by jhrozek** [comment]
```
     helpers.go:610: E2E-FAILURE: Waiting for pool worker timed out 
```
/retest

**Comment by rhmdnd** [comment]
/retest

Looks like the operator is having issues coming up, which cascaded into a bunch of other failures.

```
helpers.go:326: Operator deployment was never created: getting deployment: deployments.apps "compliance-operator" not found
```

**Comment by jhrozek** [comment]
/test e2e-aws-ocp4-high-node
there was supposedly a workaround deployed to the RH, let's see if it works. It's unclear to me from the Jira card if the workaround only works for pulling images by SHA (which would not have helped us) or also by tag.

**Comment by jhrozek** [comment]
@Vincent056 @rhmdnd can either of you please click the "Approve keyword" so that we can merge the fix? CI is green :-)

**Review by rhmdnd — APPROVED** [review]

**Pull request merged**
