### PR TITLE
 stop using rules about ssh idle timeout

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- remove rules and variable configurations from all profiles:

    - sshd_set_idle_timeout

    - sshd_set_keepalive

- replace rule with accounts_tmout where current prodtype of accounts_tmout allows it

#### Rationale:

It turned out that rules sshd_set_idle_timeout and sshd_set_keepalive are not designed in a way so that they could enhance security. Therefore they are being removed and replaced by accounts_tmout in cases when it makes sense. Configuration options connected to these rules are not tied to SSH interactive session timeouts at all.

### CODE REVIEW

**Comment by vojtapolasek** [comment]
@redhatrises  @JAORMX  please review changes. Thank you.

**Comment by redhatrises** [comment]
100% nack.

**Comment by matejak** [comment]
If we want to keep that rules, we will need to come up with different description.

The current incorrect assumption was that the setting terminates SSH sessions that are idle for a given period of time.
In reality, those settings terminate the connection if there is no activity from the SSH client. If the session is active, there will be activity from the client for sure. However, there may be activity from the client even if the session is idle.

**Comment by redhatrises** [comment]
> If we want to keep that rules, we will need to come up with different description.
> 
> The current incorrect assumption was that the setting terminates SSH sessions that are idle for a given period of time.
> In reality, those settings terminate the connection if there is no activity from the SSH client. If the session is active, there will be activity from the client for sure. However, there may be activity from the client even if the session is idle.

Which is the same thing. Active sessions are active user sessions.

**Comment by matejak** [comment]
> Active sessions are active user sessions.

I don't think so, the session can be lively even if the user is away from the keyboard - the system may post messages to the console, and those get forwarded back to the user. But I think that you should discuss the matter with Mr. Poole in https://bugzilla.redhat.com/show_bug.cgi?id=1873547 as he seem to be better informed than us.

**Comment by redhatrises** [comment]
> > Active sessions are active user sessions.
> 
> I don't think so, the session can be lively even if the user is away from the keyboard - the system may post messages to the console, and those get forwarded back to the user. But I think that you should discuss the matter with Mr. Poole in https://bugzilla.redhat.com/show_bug.cgi?id=1873547 as he seem to be better informed than us.

And that is the definition of an active remote user session.

**Comment by redhatrises** [comment]
Closing this as this goes against NSA SNAC guidance which is also a part of NIST 800-53 requirements.

**Pull request closed without merging**
