### PR TITLE
Adjust rule assertions 11.11

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Adjust assertions for:
  - RHCOS4
    - 4.17 and 4.16
    - `stig`, `moderate` and `high` profiles
  - OCP4
    - 4.17
      - `moderate`

#### Rationale:

- Based on the latest failures:
 - [4.16](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.16/runs?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522timestamp%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25221731178800000%2522%257D%252C%257B%2522columnField%2522%253A%2522job%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522ComplianceAsCode-content%2522%257D%252C%257B%2522columnField%2522%253A%2522overall_result%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522equals%2522%252C%2522value%2522%253A%2522S%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sortField=timestamp)
 - [4.17](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/runs?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522timestamp%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25221731178800000%2522%257D%252C%257B%2522columnField%2522%253A%2522job%2522%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522ComplianceAsCode-content%2522%257D%252C%257B%2522columnField%2522%253A%2522overall_result%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522equals%2522%252C%2522value%2522%253A%2522S%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D&sortField=timestamp)

#### Review Hints:

- Check if CI is green after these assertion adjustments.

### CODE REVIEW

**Review by rhmdnd — COMMENTED** [review]
Looks good, did the partition rules get adjusted recently to make them not applicable?

**Comment by yuumasato** [comment]
> Looks good, did the partition rules get adjusted recently to make them not applicable?

Yes, forgot to link:
https://github.com/ComplianceAsCode/content/pull/12562/files#diff-b1bbfcc1d8a9716415cf3a4fcc17a44ebb8a2c098f2b7a40182cf92f8d58d875

**Review by rhmdnd — APPROVED** [review]
/lgtm

Just waiting on the remaining CI jobs to finish.

**Pull request merged**
