### PR TITLE
Enable set_nftables_table rule for RHEL

### LINKED ISSUE #5244: CIS 3.4.3.2 Ensure a table exists (Scored)
Needs new rule

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

The `set_nftables_table` rule is also valid for RHEL and satisfy CIS requirements.

#### Rationale:

Better CIS coverage for RHEL.

- Fixes #5244

### CODE REVIEW

**Comment by jan-cerny** [comment]
@marcusburghardt This time, it isn't CentOS 8 that is failing, but it's a CentOS 7. And the fail seems related to the contents of the PR:

```

TASK [Collect Existing Nftables] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "nft list tables", "msg": "[Errno 2] No such file or directory", "rc": 2}
```

**Comment by marcusburghardt** [comment]
> @marcusburghardt This time, it isn't CentOS 8 that is failing, but it's a CentOS 7. And the fail seems related to the contents of the PR:
> 
> ```
> 
> TASK [Collect Existing Nftables] ***********************************************
> fatal: [localhost]: FAILED! => {"changed": false, "cmd": "nft list tables", "msg": "[Errno 2] No such file or directory", "rc": 2}
> ```

Sorry, my commend about CentOS 8 was to the wrong PR. Never mind.

But this CentOS 7 error is legit. I will review it and I am even considering how relevant is this rule for RHEL7. I will take a look and do the necessary changes. Thanks.

**Comment by marcusburghardt** [comment]
> > @marcusburghardt This time, it isn't CentOS 8 that is failing, but it's a CentOS 7. And the fail seems related to the contents of the PR:
> > ```
> > 
> > TASK [Collect Existing Nftables] ***********************************************
> > fatal: [localhost]: FAILED! => {"changed": false, "cmd": "nft list tables", "msg": "[Errno 2] No such file or directory", "rc": 2}
> > ```
> 
> Sorry, my commend about CentOS 8 was to the wrong PR. Never mind.
> 
> But this CentOS 7 error is legit. I will review it and I am even considering how relevant is this rule for RHEL7. I will take a look and do the necessary changes. Thanks.

I rebased the PR to the last master and also amended the first commit. The only change by amending the first commit was in the rhel7 control file, where changed the requirement status to `supported` and moved the rule to `related_rules`, for reference.

Unlike RHEL8 and RHEL9, for RHEL7 there is no CIS requirement to ensure the nftables package is installed. `nftables` is not the default backend for `firewalld` in RHEL7, so it is better to not include this rule in the CIS profile.

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
