### PR TITLE
OCP4 STIG: Mark SRG-APP-000560-CTR-001340 with three existing controls

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- Covers SRG-APP-000560-CTR-001340 with three existing TLS rules. In addition,
  moves the FIPS rule to related because while it provides some value in choosing
  the right crypto, it's not what solves the control

#### Rationale:

- OCP4 STIG coverage

#### Review Hints:

- As usual compare the rendered sheet with the original

### CODE REVIEW

**Comment by jhrozek** [comment]
@Vincent056 PTAL
To review, compare [the artifact](https://github.com/ComplianceAsCode/content/suites/10890016115/artifacts/549739251) with the current [DISA STIG spreadsheet](https://docs.google.com/spreadsheets/d/1oTUEUSkpumEpGqeBvhEHkJxcGUxMgoG1/edit#gid=959715005), search for SRG-APP-000560-CTR-001340 in both.

**Review by Vincent056 — APPROVED** [review]
/lgtm

I think adding those three rules covers TLS requirements at all three places.

**Pull request merged**
