### PR TITLE
Resolve information before writing to audit logs.

### PR DESCRIPTION
**Pull request by adelton**
#### Description:

- Resolve information before writing to audit logs.

#### Rationale:

- If local log_format isn't set to ENRICHED, the audit records will be stored in a format exactly as the kernel sends them.

### CODE REVIEW

**Comment by adelton** [comment]
Fixed type, rebased on master -> da1022544ab53ed5ab82f6c5f39020c3d114e70f.

**Comment by adelton** [comment]
One more copied-wrong-content fix -> cb7b0b21ede469384cf8cb858f59fa19fcf41acd.

**Comment by adelton** [comment]
Rebased on master -> 7d2c87b33f95ef3c47cbece036b8f102ebc1fce5.

**Comment by jan-cerny** [comment]
Thanks

**Pull request merged**
