### PR TITLE
Improve SSG Test Suite. [WIP]

### PR DESCRIPTION
**Pull request by matejak**
The SSG Test Suite results analysis has been expanded.

- Profile test runs analysis has been introduced.
- Single test result analysis (summary) has been introduced both for rule and profile test runs.
- Offline libvirt-based scan has been enabled.

As a result, code needed to be refactored:
- Renamed `Scenario_run` to `Run_id`, as the data structure stores rule ID and `name` of the run (was: `script`).
- Renamed stage `initial` to `initial_scan` and `final` to `final_scan`, so they are more descriptive and consistent with the analysis code.
- Extracted the common functionality of a result class to a base class of `RuleResult` and `ProfileResult`.

### CODE REVIEW

**Comment by jan-cerny** [comment]
I have problems with using it because I get a traceback when I wanted to analyze my test run.

```
[jcerny@thinkpad tests{profile_analysis}]$ python3 ./test_suite.py rule --libvirt qemu:///system ssg-test-suite-fedora --datastream ../build/ssg-fedora-ds.xml  --xccdf-id scap_org.open-scap_cref_ssg-fedora-xccdf-1.2.xml sshd_disable_kerb_auth
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/scap-security-guide/tests/logs/rule-custom-2018-10-23-1127/test_suite.log                                                                                                        
INFO - xccdf_org.ssgproject.content_rule_sshd_disable_kerb_auth
INFO - Script wrong_value.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
ERROR - Scan has exited with return code 2, instead of expected 0 during stage remediation
ERROR - The remediation failed for rule 'xccdf_org.ssgproject.content_rule_sshd_disable_kerb_auth'.
INFO - Script correct_value.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script comment.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script line_not_there.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
[jcerny@thinkpad tests{profile_analysis}]$ python analyze_results_rule.py logs/rule-custom-2018-10-23-1127/results.json                                                                                           
Traceback (most recent call last):
  File "analyze_results_rule.py", line 143, in <module>
    main()
  File "analyze_results_rule.py", line 139, in main
    sum_up_result(results[0])
  File "analyze_results_rule.py", line 118, in sum_up_result
    failed_in[get_failure_string(result.passed_stages_count)].add(result.name)
AttributeError: 'RuleResult' object has no attribute 'name'
```

**Comment by jan-cerny** [comment]
@matejak Do you have any updates?

**Comment by matejak** [comment]
Stay tuned, I am working on this in the background.

**Comment by jan-cerny** [comment]
@matejak please resolve the conflicts

**Pull request closed without merging**
