### PR TITLE
SRG-APP-000447-CTR-001100: This control is inherently met

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- One forgotten rule. Easy change, just adds status justfication for something that's inherently met.

#### Rationale:

- OCP4 STIG

#### Review Hints:

- I will post the SRG export when the GH actions finish

### CODE REVIEW

**Comment by jhrozek** [comment]
For review, please inspect the [SRG export](https://github.com/ComplianceAsCode/content/suites/12159484650/artifacts/641617817) as created by GH actions.

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by jan-cerny** [comment]
The fails in the TF CS 8 and 9 GH CI jobs are caused by https://github.com/ComplianceAsCode/content/issues/10450 and aren't related to the contents of this PR.

**Comment by jhrozek** [comment]
> The fails in the TF CS 8 and 9 GH CI jobs are caused by #10450 and aren't related to the contents of this PR.

@ggbecker @marcusburghardt given the above, could either of you override the gating and merge the PR?

**Pull request merged**
