### PR TITLE
Fix OCP4 unit test from kubelet_enable_streaming_connections

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Fix OCP4 unit test from kubelet_enable_streaming_connections

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
LGTM

**Comment by ggbecker** [comment]
> LGTM

@jhrozek with this fix in one of our tools: https://github.com/mildas/content-test-filtering/pull/33

OCP4 product always takes precedence over the EKS product when testing and test results are good now:
https://github.com/ComplianceAsCode/content/runs/7564834982?check_suite_focus=true

Check the step `Run tests in a container - Bash` for example and you will see that tests got executed correctly.

**Comment by jhrozek** [comment]
> > LGTM
> 
> @jhrozek with this fix in one of our tools: [mildas/content-test-filtering#33](https://github.com/mildas/content-test-filtering/pull/33)
> 
> OCP4 product always takes precedence over the EKS product when testing and test results are good now: https://github.com/ComplianceAsCode/content/runs/7564834982?check_suite_focus=true
> 
> Check the step `Run tests in a container - Bash` for example and you will see that tests got executed correctly.

Really cool, thank you!

**Pull request merged**
