### PR TITLE
add new product openeuler supporting

### PR DESCRIPTION
**Pull request by StevenYGui**
I closed a previous PR, because there are some conflicts. 
For more info for this PR, please refer https://github.com/ComplianceAsCode/content/pull/11272
Thank you for your attention.

#### Description:
- OpenScap is a well-known security configuration baseline scanning organization in the industry. The tools provided by OpenScap provide security scanning functions for most operating systems around the world. OpenEuler also hopes to join the OpenScap family and use the powerful functions of OpenScap to complete and provide security configuration baseline scanning capabilities.

- The openEuler community, known as the OpenAtom openEuler community, is an open source community for operating systems. The openEuler or openEuler community is incubated and operated by the Open Atomic Open Source Foundation.

- The openEuler operating system supports application scenarios such as servers, cloud computing, edge computing, and embedded computing, and supports diversified computing. It is committed to providing a secure, stable, and easy-to-use operating system. Support OT applications and the integration of OT and ICT by providing qualitative assurance capabilities for applications.

- Through an open community, the openEuler community works with global developers to build an open, pluralistic and inclusive software ecosystem. Incubate and support a variety of processor architectures, cover the whole scene of the word infrastructure, and promote the development of the software and hardware of the enterprise's word infrastructure and the application ecology.

- As of June 2023, the number of openEuler community members exceeded 970 and the number of community downloads exceeded 1.45 million. With more than 14,000 developers, its living global contributors are likely to continue to promote the global ecology of openEuler.

- openeuler2203 is a long term support version of openEuler.

#### Rationale:
This pr contains two code submissions. One is to build the openEuler-related support framework, and the other is to add common openEuler check items.

#### Review Hints:
Please review it and any feedback is my appreciate.

### CODE REVIEW

**Review by vojtapolasek — CHANGES_REQUESTED** [review]
Hello and thank you, continuing my feedback from the previous PR.
1. Please modify the policy file so that the IDs of controls contain numbers only. There is no need for words, they are contained in the title. e.g. it is enough to have
```
id: 1.1.1
```
instead of 
```
id: 1.1.1_no_unowner_ungroup_files
```

2. I would strongly consider keeping only versioned products. That means, I think that the "openeuler" product without numbering should not be added. It might seem like a good idea, but imagine that something (filename, file structure) gets changed along the Openeuler development and the rule would become broken. It would be necessary to restrict applicability of such a rule with platforms. I admit this can happen even for versioned products, but the chance is lower.

What do you think about this?

**Comment by StevenYGui** [comment]
> Hello and thank you, continuing my feedback from the previous PR.
> 
> 1. Please modify the policy file so that the IDs of controls contain numbers only. There is no need for words, they are contained in the title. e.g. it is enough to have
> 
> ```
> id: 1.1.1
> ```
> 
> instead of
> 
> ```
> id: 1.1.1_no_unowner_ungroup_files
> ```
> 
> 2. I would strongly consider keeping only versioned products. That means, I think that the "openeuler" product without numbering should not be added. It might seem like a good idea, but imagine that something (filename, file structure) gets changed along the Openeuler development and the rule would become broken. It would be necessary to restrict applicability of such a rule with platforms. I admit this can happen even for versioned products, but the chance is lower.
> 
> What do you think about this?

thanks for your quickly response, I removed version of "openeuler", and changed the rules id to numbers only, please check it again, thank you very much.

**Comment by vojtapolasek** [comment]
LGTM, please rebase.

**Comment by StevenYGui** [comment]
> Hello @StevenYGui , could you please rebase the branch on the latest master? There is a fix for one of checks which are required to pass before I can merge the PR. In the mean time I will be reviewing the PR. Thank you.

yes, I rebased it, and waiting for the checking finished, thanks.

**Comment by vojtapolasek** [comment]
Hello @StevenYGui  and sorry for delay. I went through the PR and it looks fine. Please try one more rebase and I will merge it as soon as possible.

**Comment by StevenYGui** [comment]
> Hello @StevenYGui and sorry for delay. I went through the PR and it looks fine. Please try one more rebase and I will merge it as soon as possible.

Thanks @vojtapolasek, I have rebased.

**Comment by vojtapolasek** [comment]
Hello @StevenYGui  and I am sorry for even more inconvenience... but I will need one more rebase.
We have just landed a big change related to prodtypes. To put it simple, we stopped using the "prodtype" key to signify which product the rule belongs to and we infer this only from its presence in a profile.
This makes it necessary to rebase again.
But, it will make the PR much smaller because you will not need to add openeuler prodtype to each rule.
Here is the discussion within the issue to get more context.
https://github.com/ComplianceAsCode/content/issues/11382

**Comment by StevenYGui** [comment]
> Hello @StevenYGui and I am sorry for even more inconvenience... but I will need one more rebase. We have just landed a big change related to prodtypes. To put it simple, we stopped using the "prodtype" key to signify which product the rule belongs to and we infer this only from its presence in a profile. This makes it necessary to rebase again. But, it will make the PR much smaller because you will not need to add openeuler prodtype to each rule. Here is the discussion within the issue to get more context. #11382

@vojtapolasek , you're welcome. I think the modification of prodtype is a friendly modification that can be convenient for developers. I've rebaseed it. Please check it again. Thank you.

**Review by vojtapolasek — APPROVED** [review]

**Comment by vojtapolasek** [comment]
Thank you, looks good now. Merging.

**Comment by StevenYGui** [comment]
> Thank you, looks good now. Merging.

Thank you very much. I will continue to contribute to the community.

**Pull request merged**
