### PR TITLE
OCP4: Add enforcement remediations for etcd encryption

### PR DESCRIPTION
**Pull request by JAORMX**
Depends-on: https://github.com/openshift/compliance-operator/pull/652

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 4f2626a76e0d02d2e3339e44e1809220c6903ffc

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 4f2626a76e0d02d2e3339e44e1809220c6903ffc

**Review by mrogers950 — APPROVED** [review]
/lgtm

**Pull request merged**
