### PR TITLE
Enable dconf profiles in Ubuntu CIS/STIG profiles

### PR DESCRIPTION
**Pull request by mpurg**
#### Description:

Modified Ubuntu profiles to enable dconf profiles `gdm` and `user`.

#### Rationale:

On Ubuntu, dconf profiles `gdm` and `user` are not explictly configured by default. When the profiles aren't explicitly
defined and don't point to `gdm.d` and `local.d` dconf databases, respectively, the remediations from dconf rules will have no affect on gnome settings and the checks will give false positives.

The rules that are affected on Ubuntu:
- dconf_gnome_banner_enabled
- dconf_gnome_disable_automount
- dconf_gnome_disable_automount_open
- dconf_gnome_disable_autorun
- dconf_gnome_disable_ctrlaltdel_reboot
- dconf_gnome_disable_user_list
- dconf_gnome_login_banner_text
- dconf_gnome_screensaver_idle_delay
- dconf_gnome_screensaver_lock_delay
- dconf_gnome_screensaver_lock_enabled

### CODE REVIEW

**Comment by dodys** [comment]
@marcusburghardt

**Comment by marcusburghardt** [comment]
@mpurg , currently we can't re-trigger the stalled testing-farm tests in CI, unfortunately. Could you rebase or simply amend the last commit to re-trigger them, please?

**Review by dodys — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
