### PR TITLE
Fixed dconf_gnome_screensaver_idle_activation_enabled wrt RHEL7 STIG

### PR DESCRIPTION
**Pull request by matejak**
- Fixed the STIG ID.
- Adjusted the timeout to the STIG value.

https://vaulted.io/library/disa-stigs-srgs/red_hat_enterprise_linux_7_security_technical_implementation_guide/V-71893?version=v2r7

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Profile stig on rhel7:
 Rule  added to stig profile.
 Rule  removed from stig profile.

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel7-ds.xml stig

**Review by ggbecker — CHANGES_REQUESTED** [review]
I think this rule is already correct. The 15 minutes delay is associated with the rule: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/gnome/gnome_screen_locking/dconf_gnome_screensaver_idle_delay/rule.yml and the variable being used for the 15 minutes is `inactivity_timeout_value=15_minutes`

**Comment by matejak** [comment]
I see, there is a lock delay (short) and inactivity timeout (long).

**Comment by matejak** [comment]
Closing, I can confirm that this PR was based on the confusion between lock delay and idle delay.

**Pull request closed without merging**
