### PR TITLE
Fedora remediation for rule banner_etc_issue

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
Merge remediations for rule banner_etc_issue and also adds multi_platform_fedora to the list.

#### Rationale:
This rule is a part of Fedora OSPP profile.

### CODE REVIEW

**Comment by dahaic** [comment]
@jan-cerny can you put some fedora profile in tests so it's applicable? `stig-rhel7-disa` is not :)

**Comment by jan-cerny** [comment]
@dahaic Thank you very much. Yes, I can.

**Comment by jan-cerny** [comment]
A pass test scenario is already present in https://github.com/ComplianceAsCode/content/blob/master/tests/data/group_system/group_accounts/group_accounts-banners/rule_banner_etc_issue/banner_etc_issue_ospp_usbcg_banner.pass.sh

**Comment by dahaic** [comment]
Thank you @jan-cerny. ACK

**Pull request merged**
