### PR TITLE
Fix ANSSI Ansible fmf test plan

### PR DESCRIPTION
**Pull request by mildas**
#### Review Hints:
See Testing Farm test results and what test each fmf plan ran.

### CODE REVIEW

**Comment by jan-cerny** [comment]
When I look at the failed test do I understand it well that issues like https://github.com/ComplianceAsCode/content/issues/11752 would be discovered in GitHub CI ?

**Comment by mildas** [comment]
@jan-cerny Correct. I've proposed waivers update to make the ANSSI profile green for now so this PR can be merged

**Review by marcusburghardt — APPROVED** [review]

**Pull request merged**
