### PR TITLE
Add SLES-12-010080 & SLES-15-010120 to dconf_gnome_screensaver_idle_delay

### PR DESCRIPTION
**Pull request by brett060102**
#### Description:

- Add SLES-12-010080 & SLES-15-010120 to dconf_gnome_screensaver_idle_delay

#### Rationale:

- Need to make sure session lock time out is set.

### CODE REVIEW

**Comment by brett060102** [comment]
@ggbecker Thanks,  I tried variuos forms of:

template:
    name: dconf_ini_file
    vars:
        parameter: idle-delay
        value: "uint32 900"
        section: "org/gnome/desktop/session"
        path: /etc/dconf/db/local.d/

In the rule.yml, the above worked but value hard coded:
every form of 
value: {{{ xccdf_value("inactivity_timeout_value") }}}
value: '{{{ xccdf_value("inactivity_timeout_value") }}}'
etc failed with:
Traceback (most recent call last):
  File "/home/vagrant/ComplianceAsCodeContent/build-scripts/combine_remediations.py", line 110, in <module>
    main()
  File "/home/vagrant/ComplianceAsCodeContent/build-scripts/combine_remediations.py", line 78, in main
    remediation.process(remediation_obj, env_yaml, fixes, rule_id)
  File "/home/vagrant/ComplianceAsCodeContent/ssg/build_remediations.py", line 245, in process
    result = remediation.parse_from_file_with_jinja(env_yaml)
  File "/home/vagrant/ComplianceAsCodeContent/ssg/build_remediations.py", line 346, in parse_from_file_with_jinja
    parsed = ssg.yaml.ordered_load(result.contents)
  File "/home/vagrant/ComplianceAsCodeContent/ssg/yaml.py", line 178, in ordered_load
    return yaml.load(stream, OrderedLoader)
  File "/usr/lib64/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib64/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 11, column 5:
        dest: /etc/dconf/db/local.d//00- ... 
        ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 14, column 25:
        value: "<sub idref="inactivity_timeout_value" />"

**Comment by brett060102** [comment]
@ggbecker I have kept made to update from sreensaver in ansible, but not moved to the dconf_ini_file template in the rule, because I could not get that working unless the time out value was had coded.

**Comment by ggbecker** [comment]
> @ggbecker I have kept made to update from sreensaver in ansible, but not moved to the dconf_ini_file template in the rule, because I could not get that working unless the time out value was had coded.

You have to include a new template section under the `rule.yml` first, something like:

```
template:
   name: dconf_ini_file
   vars:
      ....
```

**Comment by brett060102** [comment]
@ggbecker I stread that, the following worked:
template:
name: dconf_ini_file
vars:
parameter: idle-delay
value: "uint32 900"
section: "org/gnome/desktop/session"
path: /etc/dconf/db/local.d/


But any thing like: using {{{ xccdf_value("inactivity_timeout_value") }}} for the value such as:
template:
name: dconf_ini_file
vars:
parameter: idle-delay
value: {{{ xccdf_value("inactivity_timeout_value") }}}
section: "org/gnome/desktop/session"
path: /etc/dconf/db/local.d/

Failed with the error above. 
File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
"expected , but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
in "", line 11, column 5:
dest: /etc/dconf/db/local.d//00- ...
^
expected , but found ''
in "", line 14, column 25:
value: ""

I had tied various quoting, and with and without uint32, without success. 
The only other use of docnf_ini_file was in dconf_ini_file was in linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_user_admin/rule.yml and it uses a hard code value.
I also checked the use of "value: in all other rules and could not find  use of xccdf_value("
Is there something I am missing here?

**Comment by ggbecker** [comment]
> @ggbecker I stread that, the following worked:
> template:
> name: dconf_ini_file
> vars:
> parameter: idle-delay
> value: "uint32 900"
> section: "org/gnome/desktop/session"
> path: /etc/dconf/db/local.d/
> 
> But any thing like: using {{{ xccdf_value("inactivity_timeout_value") }}} for the value such as:
> template:
> name: dconf_ini_file
> vars:
> parameter: idle-delay
> value: {{{ xccdf_value("inactivity_timeout_value") }}}
> section: "org/gnome/desktop/session"
> path: /etc/dconf/db/local.d/
> 
> Failed with the error above.
> File "/usr/lib64/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
> "expected , but found %r" % token.id, token.start_mark)
> yaml.parser.ParserError: while parsing a block mapping
> in "", line 11, column 5:
> dest: /etc/dconf/db/local.d//00- ...
> ^
> expected , but found ''
> in "", line 14, column 25:
> value: ""
> 
> I had tied various quoting, and with and without uint32, without success.
> The only other use of docnf_ini_file was in dconf_ini_file was in linux_os/guide/system/software/gnome/gnome_system_settings/dconf_gnome_disable_user_admin/rule.yml and it uses a hard code value.
> I also checked the use of "value: in all other rules and could not find use of xccdf_value("
> Is there something I am missing here?

All right, I have overlooked that the template does not support using XCCDF variables. So in this case we cannot use the template. Please disregard my suggestion, sorry for the noise. You may leave the pull request as it is and I'll be reviewing it again soon.

**Comment by brett060102** [comment]
@ggbecker thank you and NP, I learned a lot through this.

**Review by ggbecker — APPROVED** [review]
LGTM

**Pull request merged**
