### PR TITLE
Fix oracle documentation links

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Fix oracle documentation links.
- FYI @iokomin 

#### Rationale:

- Broken links are not nice

### CODE REVIEW

**Comment by iokomin** [comment]
@ggbecker thanks for doc references update! 
I noticed we have Oracle Linux documentation location changed from time to time and exiting links becomes broken. I'll review other refs for Oracle prodtypes.

**Comment by freddieRv** [comment]
I found two other links we should update:
- `linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml` link is also broken
-  link to Java 8 supported settings in `jre/guide/java/group.yml`. This one is not broken but it does not directly point to the supported settings page like the other two links.

Also I found entries for [SSD](https://docs.oracle.com/en/operating-systems/oracle-linux/8/userauth/auth.html#sssd-auth) and [Chrony](https://docs.oracle.com/en/operating-systems/oracle-linux/8/network/ol-nettime.html#ol-nettime-chrony-about) on **OL8** documentation. Should we add jinja macros to add links to OL7/OL8 documentation were possible?

Lastly I would suggest changing the `SELinux` doc link to [this one](https://docs.oracle.com/en/operating-systems/oracle-linux/selinux/) since the link proposed on this PR just points to that site:

Screenshot from 2021-03-23 12-05-38

Other than that, changes LGTM, @iokomin.

**Comment by ggbecker** [comment]
> I found two other links we should update:
> 
>     * `linux_os/guide/system/software/disk_partitioning/encrypt_partitions/rule.yml` link is also broken
> 
I forgot to add this to the commit. Adding it.

>     * link to Java 8 supported settings in `jre/guide/java/group.yml`. This one is not broken but it does not directly point to the supported settings page like the other two links.

I don't know exactly what to change here.
> 
> 
> Also I found entries for [SSD](https://docs.oracle.com/en/operating-systems/oracle-linux/8/userauth/auth.html#sssd-auth) and [Chrony](https://docs.oracle.com/en/operating-systems/oracle-linux/8/network/ol-nettime.html#ol-nettime-chrony-about) on **OL8** documentation. Should we add jinja macros to add links to OL7/OL8 documentation were possible?

That's probably the best.

> 
> Lastly I would suggest changing the `SELinux` doc link to [this one](https://docs.oracle.com/en/operating-systems/oracle-linux/selinux/) since the link proposed on this PR just points to that site:

I'll update it.
> 
> Screenshot from 2021-03-23 12-05-38
> 
> Other than that, changes LGTM, @iokomin.
> @ggbecker I could add these changes to this PR (if that is even possible?) or I can open a new PR

**Comment by iokomin** [comment]
@ggbecker change looks good to me, I'll set approved to this PR from my side. java link issue will be addressed by @freddieRv in a separate PR.

**Review by iokomin — APPROVED** [review]

**Comment by ggbecker** [comment]
Merging as approved by @iokomin

**Pull request merged**
