### PR TITLE
CMP-2375: Implement a new rule for checking audit logging is enabled

### PR DESCRIPTION
**Pull request by rhmdnd**
We already have a rule that checks that audit logging is configured to a
specific level called audit_profile_set. While this works, it was being
used for CIS OpenShift controls 3.2.1 and 3.2.2.

CIS 3.2.1 is really just checking if audit logging is enabled, or that
the profile isn't set to `None`.

CIS 3.2.2 is checking that the audit profile is set to
`WriteRequestBodies`.

Using the same rule for both controls was causing confusion because
control 3.2.1 should be satisfied by default with OpenShift using the
`Default` audit profile. Control 3.2.2 is a level 2 control that
requires users to make a change to the api server configuration to
remediate the finding.

This commit breaks the rule into two separate rules so that its easier
to see that one rule is clearly for CIS 3.2.1 and the other is for CIS
3.2.2.

### CODE REVIEW

**Comment by xiaojiey** [comment]
Verification pass.
```
% oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.16.0-0.nightly-2024-03-13-061822   True        False         56m     Cluster version is 4.16.0-0.nightly-2024-03-13-061822
% cat ssb_cis.yaml 
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-compliance
  namespace: openshift-compliance
profiles:
  - name: upstream-ocp4-cis
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1

% oc apply -f ssb_cis.yaml
scansettingbinding.compliance.openshift.io/cis-compliance created
% oc get suite
NAME             PHASE   RESULT
cis-compliance   DONE    NON-COMPLIANT
% oc get ccr upstream-ocp4-cis-audit-logging-enabled
upstream-ocp4-cis-audit-logging-enabled                                    PASS     medium
% oc get ccr upstream-ocp4-cis-audit-logging-enabled  -o=jsonpath={.instructions}
Run the following command to retrieve the current audit profile:
$ oc get apiservers cluster -ojsonpath='{.spec.audit.profile}'
Make sure the value is not set to `None`.%
% oc get ccr upstream-ocp4-cis-audit-profile-set 
NAME                                  STATUS   SEVERITY
upstream-ocp4-cis-audit-profile-set   FAIL     medium
% oc get ccr upstream-ocp4-cis-audit-profile-set -o=jsonpath={.instructions}
Run the following command to retrieve the current audit profile:
$ oc get apiservers cluster -ojsonpath='{.spec.audit.profile}'
Make sure the profile returned matches the one that should be used.%                                                                        
% oc get apiservers cluster -ojsonpath='{.spec.audit.profile}'              
Default%
```

**Comment by xiaojiey** [comment]
Verification pass.
```
% oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.16.0-0.nightly-2024-03-13-061822   True        False         56m     Cluster version is 4.16.0-0.nightly-2024-03-13-061822
% cat ssb_cis.yaml 
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-compliance
  namespace: openshift-compliance
profiles:
  - name: upstream-ocp4-cis
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1

% oc apply -f ssb_cis.yaml
scansettingbinding.compliance.openshift.io/cis-compliance created
% oc get suite
NAME             PHASE   RESULT
cis-compliance   DONE    NON-COMPLIANT
% oc get ccr upstream-ocp4-cis-audit-logging-enabled
upstream-ocp4-cis-audit-logging-enabled                                    PASS     medium
% oc get ccr upstream-ocp4-cis-audit-logging-enabled  -o=jsonpath={.instructions}
Run the following command to retrieve the current audit profile:
$ oc get apiservers cluster -ojsonpath='{.spec.audit.profile}'
Make sure the value is not set to `None`.%
% oc get ccr upstream-ocp4-cis-audit-profile-set 
NAME                                  STATUS   SEVERITY
upstream-ocp4-cis-audit-profile-set   FAIL     medium
% oc get ccr upstream-ocp4-cis-audit-profile-set -o=jsonpath={.instructions}
Run the following command to retrieve the current audit profile:
$ oc get apiservers cluster -ojsonpath='{.spec.audit.profile}'
Make sure the profile returned matches the one that should be used.%                                                                        
% oc get apiservers cluster -ojsonpath='{.spec.audit.profile}'              
Default%
```

**Review by Vincent056 — APPROVED** [review]
/lgtm
Thanks for adding this rule

**Pull request merged**
