### PR TITLE
update accounts_maximum_age_login_defs

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

-    unify Bash remediations, no need for Fedora specific

-    fix wrong regex in oval

-    add tests for multiple profiles to make sure Fedora is remediated correctly

#### Rationale:

STIG effort

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule fedora:
 Bash remediation was deleted. No test for it will be selected.
Rule accounts_maximum_age_login_defs:
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product ol8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml accounts_maximum_age_login_defs

**Comment by jan-cerny** [comment]
@vojtapolasek 
Hi Vojta, The changes look fine. But I'm wondering which command do you use for running the test suite. I'm getting a lot of errors. Maybe I miss some profile adjustment? See the following output:

```
[jcerny@thinkpad scap-security-guide{pr/6027}]$ python3 tests/test_suite.py rule --libvirt qemu:///system ssgts_rhel7 --datastream build/ssg-rhel7-ds.xml accounts_maximum_age_login_defs     
Setting console output to log level INFO                                                                                                                                                      
INFO - The DataStream contains 2 Benchmarks                                                                                                                                                   
INFO - 0 - scap_org.open-scap_cref_ssg-rhel7-xccdf-1.2.xml                                                                                                                                    
INFO - 1 - scap_org.open-scap_cref_ssg-rhel7-pcidss-xccdf-1.2.xml                                                                                                                             
INFO - Selected Benchmark is 0                                                                                                                                                                
INFO - To select a different Benchmark, use --xccdf-id-number option.                                                                                                                         
INFO - The base image option has not been specified, choosing libvirt-based test environment.                                                                                                 
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2020-08-31-1002/test_suite.log                                                                                 
INFO - xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs                                                                                                                      
INFO - Script incorrect_stig.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK                                                                                               
ERROR - Script correct_standard.pass.sh using profile xccdf_org.ssgproject.content_profile_standard found issue:                                                                              
ERROR - Rule xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs has not been evaluated! Wrong profile selected in test scenario?                                               
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs'.                                                                                 
ERROR - Script incorrect_standard.fail.sh using profile xccdf_org.ssgproject.content_profile_standard found issue:                                                                            
ERROR - Rule xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs has not been evaluated! Wrong profile selected in test scenario?                                               
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs'.                                                                                 
INFO - Script correct_stig.pass.sh using profile xccdf_org.ssgproject.content_profile_stig OK                                                                                                 
INFO - Script commented_stig.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK                                                                                               
ERROR - Script commented_standard.fail.sh using profile xccdf_org.ssgproject.content_profile_standard found issue:                                                                            
ERROR - Rule xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_accounts_maximum_age_login_defs'.
```

**Comment by vojtapolasek** [comment]
Well I created actually two sets of tests. One for stig profile and one for standard profile. Each of them has a different value there. I actually created tests for standard profile only because a remediation for Fedora was removed as part of this PR and I wanted to make sure that the general remediation works as expected. Should I remove the tests for the standard profile? I tested it works ok on Fedora.

**Comment by mildas** [comment]
**Changes identified:**
Rule fedora:
 Bash remediation was deleted. No test for it will be selected.
Rule accounts_maximum_age_login_defs:
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product fedora
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-fedora-ds.xml accounts_maximum_age_login_defs

**Comment by jan-cerny** [comment]
@vojtapolasek Yes, adding platform tags is way better. It follows the guidance to leave the test applicability decision up to the test automation.

**Pull request merged**
