### PR TITLE
Format OS SRG

### PR DESCRIPTION
**Pull request by shawndwells**
Ran the OS SRG through an XML formatter.

### CODE REVIEW

**Comment by redhatrises** [comment]
@shawndwells is this necessary? As the SRG xml file is updated over time, this type of update will get lost.

**Comment by shawndwells** [comment]
> @shawndwells is this necessary? As the SRG xml file is updated over time, this type of update will get lost.

Necessary? Maybe not.  But super useful. Otherwise devs who want to review this file have to manually (re)parse each time this file is accessed.

**Comment by redhatrises** [comment]
> > @shawndwells is this necessary? As the SRG xml file is updated over time, this type of update will get lost.
> 
> Necessary? Maybe not. But super useful. Otherwise devs who want to review this file have to manually (re)parse each time this file is accessed.

Does `oscap xccdf generate guide` not work in this case?

**Comment by shawndwells** [comment]
> > > @shawndwells is this necessary? As the SRG xml file is updated over time, this type of update will get lost.
> > 
> > 
> > Necessary? Maybe not. But super useful. Otherwise devs who want to review this file have to manually (re)parse each time this file is accessed.
> 
> Does `oscap xccdf generate guide` not work in this case? I imagine that most devs would use that or parse in other ways.

No, generate guide creates an HTML report. Sometimes need to review the XML directly.

**Comment by jan-cerny** [comment]
@shawndwells Please remove unrelated commits and remove also merge commits from this PR. Interactive git rebase on top of fresh fetched upstream master usually does the trick.

**Comment by shawndwells** [comment]
Was addressed elsewhere.

**Pull request closed without merging**
