### PR TITLE
rsyslog: Improve OVAL and Bash handling of include() syntax

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Fix OVAL check to not consider paths refering to `.conf` files as `.log` files. (179cf6b)
  - Assumes that `.conf` files are accompanied by `include` or `$IncludeConfig`.
- Improves remediation to fix permissions of `.log` files referenced via `include()` syntax.
  - Previously only `.log` files referenced via `$IncludeConfig` were fixed.

#### Notes:

- Fixes item 3 of #5213

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule rsyslog_files_permissions:
 New node inserted to OVAL check.
 Found change in bash remediation.
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product ol8
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate bash --datastream build/ssg-ol8-ds.xml rsyslog_files_permissions

**Comment by mildas** [comment]
**Changes identified:**
Rule rsyslog_files_groupownership:
 Text changed in OVAL check.
 New node inserted to OVAL check.
Rule rsyslog_files_ownership:
 Text changed in OVAL check.
 New node inserted to OVAL check.
Rule rsyslog_files_permissions:
 Text changed in OVAL check.
 Found change in bash remediation.
 New node inserted to OVAL check.

**Recommended tests to execute:**
 build_product ol8
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate bash --datastream build/ssg-ol8-ds.xml rsyslog_files_groupownership
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate bash --datastream build/ssg-ol8-ds.xml rsyslog_files_ownership
 test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate bash --datastream build/ssg-ol8-ds.xml rsyslog_files_permissions

**Comment by vojtapolasek** [comment]
Thank you for this fix. Do you think it is worth adding some regression test? e.g. test scenario with .pass.sh containing some .conf file with wrong permissions...

**Comment by yuumasato** [comment]
> Do you think it is worth adding some regression test? e.g. test scenario with .pass.sh containing some .conf file with wrong permissions...

@vojtapolasek I think they are covered already, the `.conf` files are created with default permissions and `umask`.

**Comment by vojtapolasek** [comment]
You are right. Thank you, merging.

**Pull request merged**
