### PR TITLE
added ignition for max hard logins

### PR DESCRIPTION
**Pull request by urena-01**

### CODE REVIEW

**Comment by shawndwells** [comment]
@openscap-ci add to white list

**Comment by shawndwells** [comment]
@openscap-ci ok to test

**Comment by JAORMX** [comment]
@urena-01 @shawndwells if you wanna verify this remediation in CI, you could add it to the moderate profile.

**Comment by shawndwells** [comment]
@JAORMX @redhatrises We did not know what to name some of the limits.d files .... so created limits.d/<checkname>.config. Do you think there is a better way? Will hit this issue also with sysctl and some other areas.

**Comment by JAORMX** [comment]
Some files al malformed, as seen in the unit test results:
```
     helpers.go:37: The object in the following path is malformed '/go/src/github.com/ComplianceAsCode/content/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_interval/ignition/shared.yml': error converting YAML to JSON: yaml: line 17: could not find expected ':'
    helpers.go:37: The object in the following path is malformed '/go/src/github.com/ComplianceAsCode/content/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/ignition/shared.yml': error converting YAML to JSON: yaml: line 17: could not find expected ':' 
```

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
There is also a typo: `'docucmentation_complete': 'true'` docu**c**mentation

**Comment by matejak** [comment]
Closing, as this PR still has unresolved issues for a very long period of time, and there is no feedback.

**Pull request closed without merging**
