### PR TITLE
Align logind_session_timeout value with STIG

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

This rule is used both by RHEL 8 and RHEL 9 and relies on the value of `var_logind_session_timeout` variable.
The default value is 300 while STIG asks 900.

#### Rationale:

Small adjust in STIG profiles for RHEL 8 and RHEL 9.

### CODE REVIEW

**Comment by marcusburghardt** [comment]
> Please update the profile stability.

Done.

**Review by Mab879 — APPROVED** [review]
LGTM.

**Pull request merged**
