### PR TITLE
Fix Python2.7 and Python2.6 incompatibilities.

### PR DESCRIPTION
**Pull request by matejak**
PR fixes issues introduced in #3220

### CODE REVIEW

**Comment by mpreisler** [comment]
I am pretty sure this was a race condition :-D Sorry @jan-cerny

**Comment by mpreisler** [comment]
ACK

**Comment by shawndwells** [comment]
Looks like this PR broke jenkins builds =/ Should we revert it?

**Comment by shawndwells** [comment]
e.g. on RHEL6 builds:
`````
-- Scanning for dependencies of jre checks (OVAL)...
Traceback (most recent call last):
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/build-scripts/yaml_to_shorthand.py", line 10, in <module>
    import ssg.build_yaml
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/ssg/build_yaml.py", line 11, in <module>
    from .checks import is_cce_valid
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/ssg/checks.py", line 8, in <module>
    from .oval import parse_affected
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel6/ssg/oval.py", line 28, in <module>
    ET._namespace_map[ovalns] = "oval"
`````

and rhel7:
`````
39/193 Test  #40: validate-parse-platform ..................................................***Failed    0.10 sec
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/tests/test_parse_platform.py", line 25
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
`````

**Comment by matejak** [comment]
Tests started to fail because I have switched the RHEL7 and RHEL6 tests on (before only Fedora was tested). The PR #3398 hopefully fixes the other outstanding issues.

**Pull request merged**
