### PR TITLE
Fix automatus for ubuntu2204

### PR DESCRIPTION
**Pull request by Mab879**
Description:

Install `xsltproc` for Automatus content build on Ubuntu 22.04.

Rationale:

So the tests work.
Review Hints:
- Review the CI and ensure that "Automatus Ubuntu 22.04" passes.
- Once approved I will remove the example commit that triggered the CI.

### CODE REVIEW

**Review by vojtapolasek — APPROVED** [review]
@Mab879  LGTM, I encountered this issue as well and came with the same fix, so I approve.

**Comment by Mab879** [comment]
> @Mab879 LGTM, I encountered this issue as well and came with the same fix, so I approve.

This fixes the build step but the running step is still needs some attention.

**Comment by vojtapolasek** [comment]
@ComplianceAsCode/ubuntu-maintainers  any idea how to fix this please?

**Comment by dodys** [comment]
I am currently on holiday but I can definitely take a look next Monday

**Comment by dodys** [comment]
@Mab879 did https://github.com/ComplianceAsCode/content/pull/12175 fix the issue? Should we close this one?

**Comment by Mab879** [comment]
That doesn't slove 

> @Mab879 did #12175 fix the issue? Should we close this one?

That solves one of the issues. However, the `Dockerfiles/test_suite-ubt22` file still doesn't exist which is problem.

**Comment by dodys** [comment]
> That doesn't slove
> 
> > @Mab879 did #12175 fix the issue? Should we close this one?
> 
> That solves one of the issues. However, the `Dockerfiles/test_suite-ubt22` file still doesn't exist which is problem.

@alanmcanonical could you check this second issue too?

**Comment by Mab879** [comment]
Closing in favor #12230

**Pull request closed without merging**
