### PR TITLE
OCP4: use utf-8 as default xml encoding

### PR DESCRIPTION
**Pull request by Vincent056**
This commit make UTF-8 as default xml encoding. In a recent change to the build system, xml encoding was changed from not specific(UTF-8) to US-ASCII . 

When writing XCCDF XML file, python xml uses the output encoding US-ASCII as default if not set, however this causes issues in Compliance Operator parser, using US-ASCII, the parser is not able to get the prefix of xml node, therefore crash the parser pod.

snippet of XCCDF print out using utf-8
```
 <?xml version="1.0" encoding="utf-8"?>
```
parsed into
```
ds:data-stream-collection
ds:data-stream-collection/ds:data-stream
ds:data-stream-collection/ds:data-stream/ds:dictionaries
ds:data-stream-collection/ds:data-stream/ds:dictionaries/ds:component-ref
ds:data-stream-collection/ds:data-stream/ds:dictionaries/ds:component-ref/cat:catalog
ds:data-stream-collection/ds:data-stream/ds:dictionaries/ds:component-ref/cat:catalog/cat:uri
ds:data-stream-collection/ds:data-stream/ds:checklists
ds:data-stream-collection/ds:data-stream/ds:checklists/ds:component-ref
ds:data-stream-collection/ds:data-stream/ds:checklists/ds:component-ref/cat:catalog
ds:data-stream-collection/ds:data-stream/ds:checklists/ds:component-ref/cat:catalog/cat:uri
ds:data-stream-collection/ds:data-stream/ds:checks
ds:data-stream-collection/ds:data-stream/ds:checks/ds:component-ref
```

snippet of XCCDF print out using us-ascii parsed into:
```
<?xml version="1.0" encoding="us-ascii"?>
```

```
data-stream-collection
data-stream-collection/data-stream
data-stream-collection/data-stream/dictionaries
data-stream-collection/data-stream/dictionaries/component-ref
data-stream-collection/data-stream/dictionaries/component-ref/catalog
data-stream-collection/data-stream/dictionaries/component-ref/catalog/uri
data-stream-collection/data-stream/checklists
data-stream-collection/data-stream/checklists/component-ref
data-stream-collection/data-stream/checklists/component-ref/catalog
data-stream-collection/data-stream/checklists/component-ref/catalog/uri
data-stream-collection/data-stream/checks
data-stream-collection/data-stream/checks/component-ref
```

### CODE REVIEW

**Comment by Vincent056** [comment]
AWS quota hit

**Review by yuumasato — APPROVED** [review]
LGTM.

Pushing the thin DS PR content image results in `CrashLoopBackOff`:
`$ utils/build_ds_container.py -i ghcr.io/complianceascode/k8scontent:11549`

But this PR's image works fine:
`$ utils/build_ds_container.py -i ghcr.io/complianceascode/k8scontent:11614`

**Comment by Honny1** [comment]
@yuumasato I have no objection.

**Review by rhmdnd — APPROVED** [review]
/lgtm

**Review by Honny1 — APPROVED** [review]

**Pull request merged**
