### PR TITLE
Add ansible remediation for grub2_enable_fips_mode

### PR DESCRIPTION
**Pull request by justin-stephenson**
#### Description:

- Add ansible remediation for grub2_enable_fips_mode

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
Good stuff, I have tested the content, and oscap scan is still failing after playbook is run.
Reason is that the the Ansible snippet is not installing `dracut-fips-aesni` when applicable.
This is an oversight when review https://github.com/ComplianceAsCode/content/pull/4300.

Incorporating snippet similar to remediation of [package_dracut-fips-aesni_installed](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed/ansible/shared.yml) should be enough.

The Bash remediation needs to fixed as well, but this in scope of another PR.

**Comment by justin-stephenson** [comment]
Thanks for the review @yuumasato , PR updated - please re-check.

**Comment by yuumasato** [comment]
Thank you for updating the PR.
I have tested and found small issue in the `dracut-fips-aesni`, but this also affects the rule at https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/software/integrity/fips/package_dracut-fips-aesni_installed.
I'll file a PR addressing it and the bash remediation.

**Pull request merged**
