### PR TITLE
Fix Ansible remediation for accounts_umask_etc_profile

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

The Ansible remediation was using a regex which was causing inconsistency
to the /etc/profile file by removing unnecessary content. In another case, it was
creating a new entry where the existing entries were already in compliance.

During the fix of this specific Ansible remediation, it was noticed similar rules with duplicated code.
An issue was created to improve this in another opportunity: https://github.com/ComplianceAsCode/content/issues/8919

### CODE REVIEW

**Comment by jan-cerny** [comment]
@marcusburghardt Can you add a test scenario that would fail with the current master and would pass with the change in this PR?

**Comment by marcusburghardt** [comment]
> @marcusburghardt Can you add a test scenario that would fail with the current master and would pass with the change in this PR?

@jan-cerny , I afraid these test scenarios are not worth because it would also demand much more complexity to the OVAL assessment.

These are the relevant lines of a typical `/etc/profile` file:
```
if [ $UID -gt 199 ] && [ "`/usr/bin/id -gn`" = "`/usr/bin/id -un`" ]; then
    umask 002
else
    umask 022
fi
```
The current remediation is transforming these lines in this:
```
umask 027
fi
```
In this case, the remediation is actually fixing the umask value, but is breaking the original condition (only the `fi` keeps there).

####

In the second case I mentioned in the description, the conditional for the second Ansible task was triggered only when the first task was not changed. This logic is valid when there is no `umask` defined in the file or an `umask` is defined with an unexpected value. However, if `umask` is defined with expected value (already in compliance), the first Ansible task won't return `changed` and the second task will be triggered, causing a new `umask` entry at the end of the file.

In these two cases, the remediation is actually ensuring the proper value for umask, but with some undesired side effects. Therefore, a test scenario for the first case is unfeasible and for the second case would demand an additional duplicity check in OVAL, which would make the rule more complex. I think this additional test would be good but is not critical for now, after the remediation updates proposed in this PR.

**Comment by jan-cerny** [comment]
OK, so my understanding is that the old remediation actually fixes the checked settings but breaks the context of the config file.

**Review by jan-cerny — APPROVED** [review]

**Comment by wokis** [comment]
Won't prefixing ansible modules with `ansible.builtin` break Ansible remediation with <= 2.9?

**Comment by wokis** [comment]
> > @marcusburghardt Can you add a test scenario that would fail with the current master and would pass with the change in this PR?
> 
> @jan-cerny , I afraid these test scenarios are not worth because it would also demand much more complexity to the OVAL assessment.
> 
> These are the relevant lines of a typical `/etc/profile` file:
> 
> ```
> if [ $UID -gt 199 ] && [ "`/usr/bin/id -gn`" = "`/usr/bin/id -un`" ]; then
>     umask 002
> else
>     umask 022
> fi
> ```
> 
> The current remediation is transforming these lines in this:
> 
> ```
> umask 027
> fi
> ```
> 
> In this case, the remediation is actually fixing the umask value, but is breaking the original condition (only the `fi` keeps there).
> 
> In the second case I mentioned in the description, the conditional for the second Ansible task was triggered only when the first task was not changed. This logic is valid when there is no `umask` defined in the file or an `umask` is defined with an unexpected value. However, if `umask` is defined with expected value (already in compliance), the first Ansible task won't return `changed` and the second task will be triggered, causing a new `umask` entry at the end of the file.
> 
> In these two cases, the remediation is actually ensuring the proper value for umask, but with some undesired side effects. Therefore, a test scenario for the first case is unfeasible and for the second case would demand an additional duplicity check in OVAL, which would make the rule more complex. I think this additional test would be good but is not critical for now, after the remediation updates proposed in this PR.

I don't see how this MR fixes the first case. The regex `^[^#]*umask` still breaks `/etc/profile` leaving it with a dangling `fi`.

**Pull request merged**
