### PR TITLE
Add GRUB2 rule for slab_nomerge and mce

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Add a rule to disables merge of SLABS
- Add a rule to ensure the system kernel panics on a hardware error

### CODE REVIEW

**Comment by yuumasato** [comment]
Note: test scenario `correct_value.pass.sh` will fail on RHEL8 systems. See fix on #8281

**Review by Mab879 — COMMENTED** [review]
Looks good to me. I will hold off merging to #8281 has been merged.

**Comment by yuumasato** [comment]
@Mab879 Thank you for the review. I fixed some typos by rebase.

**Comment by yuumasato** [comment]
Rebased after #8281 was merged

**Review by Mab879 — APPROVED** [review]

**Comment by Mab879** [comment]
Tests passed on a VM. The CI run of SSGTS is expected to fail with GRUB2 rules.

**Pull request merged**
