### PR TITLE
Use package CPE

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Add more packages CPEs
- Set relevant rules with platform

#### Rationale:

- Some environments may not have packages installed

#### Notes:
- Based on https://github.com/ComplianceAsCode/content/pull/4243
- https://github.com/ComplianceAsCode/content/pull/4225 is handled in d8dfd5c
- The way we handle the CPE dictionaries is not great, and will need improvements to scale.

### CODE REVIEW

**Comment by redhatrises** [comment]
While we are doing this, could you also add gnome cpe checks as well?

**Comment by yuumasato** [comment]
> While we are doing this, could you also add gnome cpe checks as well?

@redhatrises You are looking at https://github.com/ComplianceAsCode/content/issues/2445, right?
Do you hane any comment for the analysis in https://github.com/ComplianceAsCode/content/pull/2616#issue-170951205?

I prefer opening a new PR for the gdm/gnome packages.

**Comment by yuumasato** [comment]
> Do you hane any comment for the analysis in [#2616 (comment)](https://github.com/ComplianceAsCode/content/pull/2616#issue-170951205)?

Besides what you already mention in the review.

I think this can be reviewed and merged, I plan work on the gdm/gnome tomorrow.

**Comment by shawndwells** [comment]
(realized I didn't hit comment earlier..)

for the GNOME checks, lets do a future PR.

**Pull request merged**
