### PR TITLE
Fix Filename for UBI test

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:
I introduced a minor bug in the Automatus UBI8 test in #12100, this should fix that.

#### Rationale:
So the tests work.
#### Review Hints:
* Review the CI and ensure that "Automatus UBI8" passes.
* Once approved I will remove the example commit trigger the CI.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@Mab879 the UBI8 job runs and doesn't fail but the rule is evaluated as "notapplicable", is that expected?

**Comment by Mab879** [comment]
> @Mab879 the UBI8 job runs and doesn't fail but the rule is evaluated as "notapplicable", is that expected?

Due to the reduced package set in RHEL 8, that seems to be expected.

```
[root@c47f06594a31 /]# dnf install tmux
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:02:55 ago on Wed Jul 10 09:34:06 2024.
No match for argument: tmux
Error: Unable to find a match: tmux
```

**Comment by Mab879** [comment]
> LGTM. Just a comment, would it be interesting to also rename the `automatus-cs8.yaml` file to `automatus-ubi8.yaml`?

So moved.

**Review by jan-cerny — APPROVED** [review]
LGTM.

Please remove the example test scenario now.

**Comment by Mab879** [comment]
> LGTM.
> 
> Please remove the example test scenario now.

Done

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
