### PR TITLE
Edit checks for gnome banner enabled and gnome banner text

### PR DESCRIPTION
**Pull request by cyarbrough76**
#### Description:

- _Edited oval checks for dconf_gnome_banner_enabled and dconf_gnome_banner_text to include gdm and distro. Edited macros-bash to not exclude /distro. Add line return in  banner txt .var_

#### Rationale:

- _Update for current STIG requirement_

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule dconf_gnome_banner_enabled:
 Found change in bash remediation.
 Node moved within OVAL check.
 Text changed in OVAL check.
 Attribute value changed in OVAL check.
 New node inserted to OVAL check.
Rule dconf_gnome_login_banner_text:
 New node inserted to OVAL check.
 Found change in bash remediation.
 Attribute value changed in OVAL check.
 Text changed in OVAL check.
Rule dconf_gnome_screensaver_user_info:
 Found change in bash remediation.
Rule dconf_gnome_remote_access_encryption:
 Found change in bash remediation.
Rule dconf_gnome_disable_geolocation:
 Found change in bash remediation.
Rule dconf_gnome_disable_ctrlaltdel_reboot:
 Found change in bash remediation.
Rule dconf_gnome_disable_user_list:
 Found change in bash remediation.
Rule dconf_gnome_disable_restart_shutdown:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_activation_enabled:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_lock_enabled:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_delay:
 Found change in bash remediation.
Rule dconf_gnome_enable_smartcard_auth:
 Found change in bash remediation.
Rule dconf_gnome_disable_user_admin:
 Found change in bash remediation.
Rule dconf_gnome_disable_thumbnailers:
 Found change in bash remediation.
Rule dconf_gnome_disable_wifi_create:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_lock_delay:
 Found change in bash remediation.
Rule dconf_gnome_login_retries:
 Found change in bash remediation.
Rule dconf_gnome_disable_automount:
 Found change in bash remediation.
Rule dconf_gnome_remote_access_credential_prompt:
 Found change in bash remediation.
Rule dconf_gnome_disable_wifi_notification:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_mode_blank:
 Found change in bash remediation.
Macro bash_dconf_settings:
 In Bash remediation for dconf_gnome_disable_wifi_notification.
 In Bash remediation for dconf_gnome_disable_geolocation.
 In Bash remediation for dconf_gnome_screensaver_lock_delay.
 In Bash remediation for dconf_gnome_screensaver_lock_enabled.
 In Bash remediation for dconf_gnome_disable_user_admin.
 In Bash remediation for dconf_gnome_disable_user_list.
 In Bash remediation for dconf_gnome_screensaver_user_info.
 In Bash remediation for dconf_gnome_disable_thumbnailers.
 In Bash remediation for dconf_gnome_screensaver_idle_activation_enabled.
 In Bash remediation for dconf_gnome_remote_access_encryption.
 In Bash remediation for dconf_gnome_banner_enabled.
 In Bash remediation for dconf_gnome_enable_smartcard_auth.
 In Bash remediation for dconf_gnome_remote_access_credential_prompt.
 In Bash remediation for dconf_gnome_screensaver_idle_delay.
 In Bash remediation for dconf_gnome_disable_wifi_create.
 In Bash remediation for dconf_gnome_login_retries.
 In Bash remediation for dconf_gnome_login_banner_text.
 In Bash remediation for dconf_gnome_disable_automount.
 In Bash remediation for dconf_gnome_disable_ctrlaltdel_reboot.
 In Bash remediation for dconf_gnome_disable_restart_shutdown.
 In Bash remediation for dconf_gnome_screensaver_mode_blank.

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_screensaver_user_info
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_geolocation
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_ctrlaltdel_reboot
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_user_list
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_restart_shutdown
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_user_admin
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_thumbnailers
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_wifi_create
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_login_retries
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_automount
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_wifi_notification
 build_product ol8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml dconf_gnome_remote_access_encryption
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml dconf_gnome_screensaver_idle_activation_enabled
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml dconf_gnome_screensaver_lock_enabled
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml dconf_gnome_screensaver_idle_delay
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml dconf_gnome_remote_access_credential_prompt
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml dconf_gnome_screensaver_mode_blank
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml dconf_gnome_banner_enabled
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml dconf_gnome_login_banner_text
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml dconf_gnome_enable_smartcard_auth
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml dconf_gnome_screensaver_lock_delay

**Comment by redhatrises** [comment]
Sorry, but per GDM and RHEL documentation and vendor guidance, using `distro.d` is not correct. This is reflected correctly in the rhel8 draft stig.

**Comment by matejak** [comment]
@cyarbrough76 please try to include more details in the description - it is difficult for some of us to see intent and justification of the change, which also makes discussion and review difficult, as there is not much to base it upon.

**Comment by jan-cerny** [comment]
Also, the test scenarios don't pass, for example:

```
[jcerny@thinkpad tests{pr/5877}]$ python3 test_suite.py rule --libvirt qemu:///system ssgts_rhel8 --datastream ../build/ssg-rhel8-ds.xml dconf_gnome_login_banner_text                     
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/tests/logs/rule-custom-2020-06-26-1016/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_dconf_gnome_login_banner_text
WARNING - Script wrapped_banner.fail.sh is not applicable on given platform
WARNING - Script wrong_value.fail.sh is not applicable on given platform
WARNING - Script correct_value.pass.sh is not applicable on given platform
INFO - Script missing_value_stig.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK
INFO - Script wrong_value_stig.fail.sh using profile xccdf_org.ssgproject.content_profile_stig OK
ERROR - Script correct_value_stig.pass.sh using profile xccdf_org.ssgproject.content_profile_stig found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_dconf_gnome_login_banner_text'.
[jcerny@thinkpad tests{pr/5877}]$ 
```

Please ensure all tests are passing. 

Consider adding new test scenarios. Tests could help understand the reviewers the exact problem that you are trying to fix.

**Comment by cyarbrough76** [comment]
If including the distro setting is indeed incorrect and thus the stig incorrect then this change request is probably moot. will close PR

**Pull request closed without merging**
