### PR TITLE
Enable the (all) virtual profile in the rule-based test suite.

### PR DESCRIPTION
**Pull request by matejak**
Following changes were needed:

1. The `(all)` profile is not visible in the datastream, it is a virtual profile that `oscap` creates.
1. Brackets were not allowed as value in test scenario headers.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@matejak please resolve conflicts

Does it mean scenario authors have to specify `# profile = (all)` in their test scenarios explicitely?
If yes, why? I think it could work this way: If no `# profile` is present in the scenario header, the `(all)` profile will be used automatically.

**Comment by mildas** [comment]
Tried it with rhel7/rhel8/fedora and still getting:
```
[mlysonek@localhost tests]$ ./test_suite.py rule --libvirt qemu:///system test-suite-rhel8 --datastream ../build/ssg-rhel8-ds.xml java_jre_configure_crypto_policy
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mlysonek/SCAP/content/tests/logs/rule-custom-2019-06-25-1018/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_java_jre_configure_crypto_policy
ERROR - Failed to cleanup file '/home/mlysonek/SCAP/content/tests/logs/rule-custom-2019-06-25-1018/xccdf_org.ssgproject.content_rule_java_jre_configure_crypto_policy-commented_out.fail.sh-initial.html'
ERROR - Script commented_out.fail.sh using profile (all) found issue:
ERROR - Rule xccdf_org.ssgproject.content_rule_java_jre_configure_crypto_policy has not been evaluated! Wrong profile selected in test scenario?
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_java_jre_configure_crypto_policy'.
...
```
Is there something I'm missing?

**Comment by jan-cerny** [comment]
@mildas , yes, you need to patch OpenSCAP by https://github.com/OpenSCAP/openscap/pull/1366

**Comment by matejak** [comment]
I have implemented @jan-cerny's suggestion - when there is no profile, the `(all)` is assumed.

Thank you for looking into the failing case as well.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
great

**Pull request merged**
