### PR TITLE
remove ensure_logrotate_configured from CIS profiles

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- remove the rule from cis for rhel7, rhel8, sle15

#### Rationale:

- the rule is marked as unscored/ manual.

### CODE REVIEW

**Comment by vojtapolasek** [comment]
@brett060102  @guangyee  is that okay for sle15?

**Comment by guangyee** [comment]
> @brett060102 @guangyee is that okay for sle15?

@abergmann what do you think? Not sure if we want to keep those type of rules around for a complete profile. I am fine with removing them. But please feel free to disagree.

**Comment by brett060102** [comment]
@vojtapolasek @abergmann is mostly out until Monday, I don't see any reason for not removing it for sle15. We have not done anything with that file in almost a year, but I know nothing about its function or purpose, but since we are only now getting sle15 rules in place, I can't see how removing that one would effect us.

**Review by ggbecker — APPROVED** [review]
sle15 folks are not against the removal from sle15/cis.profile and the rest LGTM.

**Pull request merged**
