### PR TITLE
OCP4: Add rule that checks cluster-wide proxy

### PR DESCRIPTION
**Pull request by JAORMX**
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Review by jhrozek — COMMENTED** [review]
Code-wise looks good. I'm not sure we'll be able to do much in terms of automated  testing in CI, so I wonder if we should tag the rule as FAIL-ing by default?

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 483fdea8b761944aac60bf1f3dfd9366269cf539

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 13177b2fd6e9140249115e196b2bcd777ef15e80

**Pull request merged**
