### PR TITLE
SLES-15-010353 map rule file_ownership_library_dirs

### PR DESCRIPTION
**Pull request by teacup-on-rockingchair**
#### Description:

- Add SLES-15-010353

#### Rationale:

-     Map SLES-15-010353 references and ids to file_ownership_library_dirs rule

### CODE REVIEW

**Review by brett060102 — COMMENTED** [review]
LGTM

**Review by brett060102 — COMMENTED** [review]
LGTM

**Comment by yuumasato** [comment]
@openscap-ci add to whitelist

**Comment by yuumasato** [comment]
@openscap-ci ok to test

**Comment by yuumasato** [comment]
@openscap-ci add to white list

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Review by yuumasato — APPROVED** [review]

**Pull request merged**
