### PR TITLE
Update accounts_passwords_pam_faillock_unlock_time to work with "never" as value

### LINKED ISSUE #5544: Pam module pam_faillock.so with value unlock_time=never causes OpenSCAP conversion error
#### Description of problem:

When `pam_faillock.so` parameter is configured with `unlock_time=never`, OpenSCAP throws an error:
```
OpenSCAP Error: Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
```

For `pam_faillock.so` settings `unlock_time=never` and `unlock_time=0` are equivalent, but for the OVAL content they are not. 
The check expects numbers, and the word `never`doesn't match, resulting in the error.

NOTE: The Content doesn't add `unlock_time=never`, but it can't cope with any added by other means.

##### Workaround
Change any occurrence of `unlock_time=never` to `unlock_time=0`.

#### SCAP Security Guide Version:
0.1.49

#### Steps to Reproduce:

1. `oscap xccdf eval --remediate --profile ncp --rule xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time ./ssg-rhel7-ds.xml`
2. `sed -i 's/unlock_time=0/unlock_time=never/g' /etc/pam.d/system-auth`
3. `oscap xccdf eval --profile ncp --rule xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time ./ssg-rhel7-ds.xml`
```
Title   Set Lockout Time for Failed Password Attempts
Rule    xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time
Ident   CCE-26884-7
E: oscap:     Error occured when comparing a variable 'oval:ssg-var_accounts_passwords_pam_faillock_unlock_time:var:1' value '0' with collected item entity = ''
E: oscap:     Error occured when comparing a variable 'oval:ssg-var_accounts_passwords_pam_faillock_unlock_time:var:1' value '0' with collected item entity = ''
Result  error

OpenSCAP Error: Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
Conversion of the string "" to an integer (64 bits) failed: Invalid argument [oval_cmp.c:111]
```

#### Actual Results:
`Result error`

#### Expected Results:
`Result pass`

#### Addition Information/Debugging Steps:

- The OVAL check expects digits after `unlock_time`: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_faillock_unlock_time/oval/shared.xml#L43
- The variable for unlock_time is a number: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/var_accounts_passwords_pam_faillock_unlock_time.var#L7
  Although there is a selector `never`, it is assigned a value of `0`.

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:
- Fixes a bug in the logic for unlock_time, the higher the unlock time, the more secure it it.
- Fixes the OVAL check to accept "never" in the config files.
- Adds test scenarios for the rule

#### Rationale:
- Fixes #5544

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule accounts_passwords_pam_faillock_unlock_time:
 Text changed in OVAL check.
 Node moved within OVAL check.
 Deleted attribute from OVAL check.
 Node deleted from OVAL check.
 New node inserted to OVAL check.
 Attribute value changed in OVAL check.

**Recommended tests to execute:**
 build_product fedora
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-fedora-ds.xml accounts_passwords_pam_faillock_unlock_time

**Comment by redhatrises** [comment]
Wow... great job on this!

**Comment by mildas** [comment]
**Changes identified:**
Rule accounts_passwords_pam_faillock_unlock_time:
 Deleted attribute from OVAL check.
 Node deleted from OVAL check.
 Attribute value changed in OVAL check.
 New node inserted to OVAL check.
 Node moved within OVAL check.
 Text changed in OVAL check.

**Recommended tests to execute:**
 build_product ol8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml accounts_passwords_pam_faillock_unlock_time

**Comment by jan-cerny** [comment]
```
[jcerny@thinkpad tests{pr/6003}]$ 
[jcerny@thinkpad tests{pr/6003}]$ 
[jcerny@thinkpad tests{pr/6003}]$ python3 test_suite.py rule --libvirt qemu:///system ssgts_rhel8 --datastream ../build/ssg-rhel8-ds.xml accounts_passwords_pam_faillock_unlock_time
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/tests/logs/rule-custom-2020-08-20-1516/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_accounts_passwords_pam_faillock_unlock_time
INFO - Script var_1800_and_config_never.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script var_default_and_config_never.pass.sh using profile (all) OK
INFO - Script var_default_and_config_0.pass.sh using profile (all) OK
INFO - Script var_1800_and_config_1800.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script var_1800_and_config_0.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script var_1800_and_config_3600_except_one.fail.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script var_1800_and_config_3600.pass.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script var_1800_and_config_600.fail.sh using profile xccdf_org.ssgproject.content_profile_pci-dss OK
INFO - Script var_default_and_config_600.fail.sh using profile (all) OK
[jcerny@thinkpad tests{pr/6003}]$ 
```

**Pull request merged**
