### PR TITLE
Convert Ansible Macros to use FQCN

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

* Use FQCN in Ansible macros
* Fix a bug in clean_components_post_updating 

#### Rationale:

* Reduce noise in Ansible Lint

### CODE REVIEW

**Comment by marcusburghardt** [comment]
The automatus failures seem legit, but I didn't go deep on that yet. Probably headers in some test scenario scripts need update.

**Review by marcusburghardt — COMMENTED** [review]
The changes here LGTM. The CI errors might not be related to these changes but likely previous issues in the affected rules. I think it is worth to investigate them.

**Comment by marcusburghardt** [comment]
Good to take in considerations cases like reported in https://github.com/ComplianceAsCode/content/issues/11529

**Comment by Mab879** [comment]
> Good to take in considerations cases like reported in #11529

Considering that, I thinking that this might not be good idea until we drop RHEL 7.

**Pull request closed without merging**
