### PR TITLE
Fix issue introduced in commit 1ba11cb

### PR DESCRIPTION
**Pull request by dodys**
#### Description:

root_permissions_syslibrary_files: Re-add file_regex otherwise remediation will fix directories instead of files, which is what this rule is about. This issue was introduced in commit 1ba11cb

### CODE REVIEW

**Review by jan-cerny — CHANGES_REQUESTED** [review]
I have found that the test scenario incorrect_groupowner.fail.sh now fails during the initial phase: 

```
[jcerny@thinkpad scap-security-guide{pr/9692}]$ python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel9 root_permissions_syslibrary_files
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2022-10-17-1446/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files
INFO - Script missing_file_test.pass.sh using profile (all) OK
ERROR - Script incorrect_groupowner.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files'.
INFO - Script correct_groupowner.pass.sh using profile (all) OK
[jcerny@thinkpad scap-security-guide{pr/9692}]$ python3 tests/automatus.py rule --remediate-using ansible --libvirt qemu:///system ssgts_rhel9 root_permissions_syslibrary_files
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2022-10-17-1447/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files
INFO - Script missing_file_test.pass.sh using profile (all) OK
INFO - Script correct_groupowner.pass.sh using profile (all) OK
ERROR - Script incorrect_groupowner.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files'.
```

It's because the test scenario template `shared/templates/file_groupowner/tests/incorrect_groupowner.fail.sh` doesn't support the situation when filepath list is a directory and the file_regex is used. It literally says: `Create specific tests for this rule because of regex`. So I think that you will have to create a test with the same name but specific for this rule in the rule's bash subdirectory.

**Comment by dodys** [comment]
> I have found that the test scenario incorrect_groupowner.fail.sh now fails during the initial phase:
> 
> ```
> [jcerny@thinkpad scap-security-guide{pr/9692}]$ python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel9 root_permissions_syslibrary_files
> Setting console output to log level INFO
> INFO - The base image option has not been specified, choosing libvirt-based test environment.
> INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2022-10-17-1446/test_suite.log
> INFO - xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files
> INFO - Script missing_file_test.pass.sh using profile (all) OK
> ERROR - Script incorrect_groupowner.fail.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files'.
> INFO - Script correct_groupowner.pass.sh using profile (all) OK
> [jcerny@thinkpad scap-security-guide{pr/9692}]$ python3 tests/automatus.py rule --remediate-using ansible --libvirt qemu:///system ssgts_rhel9 root_permissions_syslibrary_files
> Setting console output to log level INFO
> INFO - The base image option has not been specified, choosing libvirt-based test environment.
> INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2022-10-17-1447/test_suite.log
> INFO - xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files
> INFO - Script missing_file_test.pass.sh using profile (all) OK
> INFO - Script correct_groupowner.pass.sh using profile (all) OK
> ERROR - Script incorrect_groupowner.fail.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_root_permissions_syslibrary_files'.
> ```
> 
> It's because the test scenario template `shared/templates/file_groupowner/tests/incorrect_groupowner.fail.sh` doesn't support the situation when filepath list is a directory and the file_regex is used. It literally says: `Create specific tests for this rule because of regex`. So I think that you will have to create a test with the same name but specific for this rule in the rule's bash subdirectory.

we already have specific incorrect_group.fail.sh for this rule.
Would renaming it be enough?

**Comment by jan-cerny** [comment]
> we already have specific incorrect_group.fail.sh for this rule.

I don't think so, I can't find it, this rule doesn't even have a `tests` subdirectory.

**Comment by dodys** [comment]
> > we already have specific incorrect_group.fail.sh for this rule.
> 
> I don't think so, I can't find it, this rule doesn't even have a `tests` subdirectory.

sorry, I was looking at the wrong branch.
look at commit 380045139c63, that removed those tests. Reverting this commit should be enough I think

**Review by jan-cerny — APPROVED** [review]
@dodys great finding

thanks for fixing the tests!

**Comment by marcusburghardt** [comment]
Thanks @dodys

**Pull request merged**
