### PR TITLE
Added rules to PCI DSS 4.0 SLES 15 profile

### PR DESCRIPTION
**Pull request by rumch-se**
#### Description:

- _Added rules to SLES 15 PCI DSS 4.0 profile_

#### Rationale:

- The profile includes rules which support new recommendations of PCI DSS - 4.0

### CODE REVIEW

**Comment by Mab879** [comment]
@rumch-se Please rebase this PR.

**Comment by rumch-se** [comment]
Hi @Mab879 
I have done the requested rebase
Have a nice day
Rumen

**Review by Mab879 — CHANGES_REQUESTED** [review]
Thanks for the PR. It looks like the rule `sshd_set_max_sessions` needs a CCE assigned. Once the rule has a CCE assigned that should fix the tests.

**Review by Mab879 — APPROVED** [review]
Thanks for the PR; waving the Fedora Rawhide test as there is a bug in Fedora Rawhide currently.

**Pull request merged**
