### PR TITLE
Fix build of Playbooks for extended profiles

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:

ResolvableProfile class can properly resolve the extension relation in
profiles.  We don't need to have a second implementation of profile
resolution, we can reuse the ResolvableProfile class. Moreover, the
implementation in playbook_builder.py doesn't support rules removal
using exclamation mark, as described in #5874.

#### Rationale:

Fixes: #5874

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in build-scripts/compile_profiles.py.
 Python abstract syntax tree change found in ssg/build_yaml.py.
 Python abstract syntax tree change found in ssg/playbook_builder.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by jan-cerny** [comment]
@vojtapolasek @yuumasato Do you think that this is a candidate for cherry picking for 0.1.51 stabilization branch?

**Comment by matejak** [comment]
Great fix that reuses and streamlines the existing code while fixing a bug.

**Pull request merged**
