### PR TITLE
Remove OCP3 content

### PR DESCRIPTION
**Pull request by redhatrises**
- While OCP3.11 will not be EOL until June 2022. The content for it will no longer be developed as OCP4 content is prioritized.

### CODE REVIEW

**Comment by JAORMX** [comment]
```
 ValueError: Identifiers and values must be strings: cce@ocp4 in file /content/applications/openshift/etcd/etcd_peer_auto_tls/rule.yml 
```

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
I think the CI was still trying to build `ocp3` content.
@openscap-ci test this please

**Review by JAORMX — APPROVED** [review]
lgtm

**Review by jhrozek — APPROVED** [review]
/lgtm
this is awesome and will simplify our work a lot. Thanks!

**Pull request merged**
