### PR TITLE
Pci dss ssh rule

### PR DESCRIPTION
**Pull request by anivan-suse**
#### Description:

Add new rule to pci-dss, as described in CIS SLE15 benchmark document:
- sshd_set_exchange_algo

### CODE REVIEW

**Comment by marcusburghardt** [comment]
Could you rebase and solve the conflicts, please? By the way, are any of the existing rules useful for this case?

**Comment by marcusburghardt** [comment]
@anivan-suse , do you have plans to work on it soon?

**Comment by marcusburghardt** [comment]
This Draft PR was started by @anivan-suse but she is no longer active in this project.

@teacup-on-rockingchair , @rumch-se would you like to take on this PR?
If so, I believe the best way would be to propose a new PR based on this.

I am closing this one since it is in Draft and no more updates are expected from the author.

**Comment by teacup-on-rockingchair** [comment]
> This Draft PR was started by @anivan-suse but she is no longer active in this project.
> 
> @teacup-on-rockingchair , @rumch-se would you like to take on this PR? If so, I believe the best way would be to propose a new PR based on this.
> 
> I am closing this one since it is in Draft and no more updates are expected from the author.

Sure @marcusburghardt , can you please assign this to me

**Comment by teacup-on-rockingchair** [comment]
I double-checked the Draft PR by @anivan-suse. It basically confirmed another PR, I worked on recently #10032.  What the #1032 is missing the PCI DSS reference. So I would suggest to make a new PR or Re-Open this one and add that change to already integrated code. But in order to Re-Open the PR, I need to have such access rights I guess, because currently I cannot Re-Open the PR

**Comment by yuumasato** [comment]
@teacup-on-rockingchair I think a new PR would be preferred.

**Pull request closed without merging**
