### PR TITLE
Update SRG-OS-000368-GPOS-00154 for RHEL 9 STIG

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
Add fixtexts to rule using a new fixtext Jinja macro for the template mount_option

#### Rationale:
RHEL 9 STIG

### CODE REVIEW

**Review by ggbecker — CHANGES_REQUESTED** [review]
I believe we should also update the ocil_clause generated by `complete_ocil_entry_mount_option` to align better with RHEL8 STIG.

e.g. RHEL8 STIG:
`If the /boot file system does not have the "nosuid" option set, this is a finding.`

Current SRG mapping in the ocil clause part:
`If the is not present in the output line, or there is no output line at all, then this is a finding.`

**Comment by jan-cerny** [comment]
I have improved the OCIL macro

**Review by Mab879 — APPROVED** [review]

**Comment by Mab879** [comment]
Waving SSGTS since these are text-only changes.

**Pull request merged**
