### PR TITLE
OCP4 STIG: Move SRG-APP-000014-CTR-000040 to rule policy files

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- OCP4 STIG: SRG-APP-000014-CTR-000040 is now automated
- OCP4 STIG: Move metadata of SRG-APP-000014-CTR-000040 to rule policy files
- OCP4 STIG: Related rule should not reference SRG-APP-000014-CTR-000040

#### Rationale:

- OCP4 STIG cleanup

#### Review Hints:

- `export PYTHONPATH=$(pwd); python3 utils/create_srg_export.py -c controls/srg_ctr.yml -p ocp4 -m shared/references/disa-ctr-srg-v1r3.xml --out-format html --output /tmp/srg-mapping-ocp4.html`

### CODE REVIEW

**Comment by jhrozek** [comment]
OCP tests: a wild combination of time outs and cluster install failures.
/retest

**Comment by jhrozek** [comment]
PCI-DSS cluster didn't install again
/test e2e-aws-ocp4-pci-dss

**Comment by jhrozek** [comment]
The last failing check is the rawhide one where cmake segfaults. I don't think it's related at all.
@rhmdnd @Vincent056 PTAL

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Pull request merged**
