### PR TITLE
Revert PR #4766

### PR DESCRIPTION
**Pull request by redhatrises**
This reverts PR #4766 as it introduced an Ansible regression and is not the correct fix.

### CODE REVIEW

**Comment by jan-cerny** [comment]
Hi @redhatrises, could you explain the regression it introduced? Also, do you have any suggestion what would be a correct fix?

**Comment by yuumasato** [comment]
@redhatrises Reverting is not an option, as the remediation was causing the playbook run to abort.
Are you mostly concerned about warning of ansible-lint? Is it for Ansible Galaxy?

**Comment by redhatrises** [comment]
> @redhatrises Reverting is not an option, as the remediation was causing the playbook run to abort.
> Are you mostly concerned about warning of ansible-lint? Is it for Ansible Galaxy?

It is 100% the option when the solution is not correct.

**Comment by redhatrises** [comment]
> Hi @redhatrises, could you explain the regression it introduced? Also, do you have any suggestion what would be a correct fix?

There are a couple of options that exist. The `failed_when` can be set correctly based off of the rc code or get rid of shell and use command using Ansible filters instead of grep and awk.

**Comment by shawndwells** [comment]
@redhatrises agree this should be reverted, but what's the plan on a correct fix? Looks like merging this PR will block work on implementing an alternative implementation, but simultaneously we don't want content in a broken state for to long (even if upstream). 

Will you be able to submit a PR with an alternative implementation later today?

**Comment by redhatrises** [comment]
> @redhatrises agree this should be reverted, but what's the plan on a correct fix? Looks like merging this PR will block work on implementing an alternative implementation, but simultaneously we don't want content in a broken state for to long (even if upstream).
> 
> Will you be able to submit a PR with an alternative implementation later today?

PR will follow really quick once merged.

**Pull request merged**
