### PR TITLE
profile_tool.py: Measure gap in Ansible parity

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Enhance `profile_tool.py` to measure gap in Ansible-Bash parity.
- By @ggbecker: Implement HTML ansible parity statistics so it will show up in the jenkins job: https://jenkins.complianceascode.io/job/scap-security-guide-stats/Statistics/

#### Rationale:

- Data is power

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in build-scripts/profile_tool.py.
 Python abstract syntax tree change found in ssg/build_profile.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by ggbecker** [comment]
@yuumasato please check this out: https://github.com/yuumasato/scap-security-guide/pull/3

It adds HTML rendering support for `ansible_parity` attribute.

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in build-scripts/profile_tool.py.
 Python abstract syntax tree change found in ssg/build_profile.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in build-scripts/profile_tool.py.
 Python abstract syntax tree change found in ssg/build_profile.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in build-scripts/profile_tool.py.
 Python abstract syntax tree change found in ssg/build_profile.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by yuumasato** [comment]
@ggbecker Thank you for the review and addition to the PR!

**Pull request merged**
