### PR TITLE
Update ANSSI R67 requirement

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- add RHEL specific rules for the requirement
- change the platform OVAL for sssd-ldap to be applicable ONLY in case the id_provider is ldap, previously it was appplicable if the provider was not ACtive directory

#### Rationale:

- ANSSI alignment

### CODE REVIEW

**Comment by marcusburghardt** [comment]
Two rules are failing in testing-farm tests:
```
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands - fail
xccdf_org.ssgproject.content_rule_service_sssd_enabled - fail 
```
The issue seems legit, but needs more investigation.

**Review by Mab879 — CHANGES_REQUESTED** [review]
Please take a took at the CI failures.

**Comment by vojtapolasek** [comment]
During investigation of a different requirement, I found out that this requirement needs few more rules for the case of nss-pam-ldapd in RHEL 7. Marking as draft for now.

**Review by Mab879 — CHANGES_REQUESTED** [review]
Please update the components files.

**Comment by Mab879** [comment]
> content_rule_audit_rules_privileged_commands

@vojtapolasek this comment is still valid.

**Comment by Mab879** [comment]
The failures still look valid:

```
:: [ 09:45:37 ] :: [   FAIL   ] :: Rules not passing after remediation:
xccdf_org.ssgproject.content_rule_audit_rules_privileged_commands - fail
xccdf_org.ssgproject.content_rule_service_sssd_enabled - fail 
```

**Comment by vojtapolasek** [comment]
@Mab879  I think this comment explains it. Any additional questions?
https://github.com/ComplianceAsCode/content/pull/11642#issuecomment-1988857087

**Comment by Mab879** [comment]
> @Mab879 I think this comment explains it. Any additional questions? [#11642 (comment)](https://github.com/ComplianceAsCode/content/pull/11642#issuecomment-1988857087)

Those make sense. I would feel a bit more comfortable if we their was a PR with these waivers before we merge. I don't to fail everyone's CI for days.

**Review by Mab879 — APPROVED** [review]
Waving the SLES 15 Automatus as these rules are not in SLES 15.

**Pull request merged**
