### PR TITLE
Add ignore and rotate options to auditd/audisp variables

### PR DESCRIPTION
**Pull request by mildas**
#### Description:
Add missing options to auditd and audisp variables.

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by vojtapolasek** [comment]
Now when I am thinking about it, I wonder if these options should be actually available in the content. The option "ignore" will just ignore the problem, potentially filling up the storage space and therefore losing ability to write further logs. The option "rotate" will cause loss of older log records, potentially losing evidence. What do others think? @matejak  @yuumasato

**Comment by JAORMX** [comment]
@vojtapolasek I think that's still acceptable as you might have other mechanisms that provide supporting controls. e.g. you're using rsyslog or fluentd to ship audit logs immediately as they come. Rotation could also be happening externally, so in that case `ignore` might be an acceptable setting.

**Comment by yuumasato** [comment]
@JAORMX has a good point.
Just looking at the rule by itself there is no direct security benefit.
But in the context of a whole profile, or deployed system, the requirement could be addressed by other means and the newly added variable options may be needed.

**Review by yuumasato — APPROVED** [review]

**Pull request merged**
