### PR TITLE
Do not platform wrap empty Bash remediation

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Do not "platform wrap" empty Bash remediations

#### Rationale:

- The fix text for a rule can end up empty if a Jinja macro or conditional
doesn't render any text.
In these cases, avoid wrapping empty lines in an if-else, as this causes
syntax error.
- This doesn't manifest in current master (538fdd5a2b64c4932c32ed25cd817fd821039a36).
But it happens on v0.1.50, in rule `grub2_enable_selinux`. Before #5787, the remediation for `rhel8` is rendered empty.

### CODE REVIEW

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by JAORMX** [comment]
@openscap-ci test this please

**Comment by JAORMX** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
LGTM

**Pull request merged**
