### PR TITLE
Refactor & clean-up & tidy-up the ansible roles generator

### PR DESCRIPTION
**Pull request by isimluk**
These changes have no functional effect. It is only rewiring of the script to be more easily comprehended by humans.

 * split monster spaghetti class to two shorter ones, split is done to avoid feature creep, generation of ansible role is separated from github update logic
 * make code more declarative and thus easier to read and assess what is what

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in utils/upload_ansible_roles_to_galaxy.py. - ctest will be selected.

**Recommended tests to execute:**
 (cd build && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in utils/upload_ansible_roles_to_galaxy.py. - ctest will be selected.

**Recommended tests to execute:**
 (cd build && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in utils/upload_ansible_roles_to_galaxy.py. - ctest will be selected.

**Recommended tests to execute:**
 (cd build && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in utils/upload_ansible_roles_to_galaxy.py. - ctest will be selected.

**Recommended tests to execute:**
 (cd build && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in utils/upload_ansible_roles_to_galaxy.py. - ctest will be selected.

**Recommended tests to execute:**
 (cd build && ctest -j4)

**Comment by jan-cerny** [comment]
@mildas I think that the suggestion of your bot isn't applicable in this case because this script isn't tested by ctest.

**Comment by redhatrises** [comment]
Nice! LGTM

**Pull request merged**
