### PR TITLE
Fix Automatus Sanity

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Only run container rules on Automatus Sanity.

#### Rationale:
Less red in CI

### CODE REVIEW

**Comment by jan-cerny** [comment]
@Mab879 what else do we need?

**Comment by Mab879** [comment]
> @Mab879 what else do we need?

I still don't know the issue. The "Automatus Sanity / Run Tests" is still failing.

**Comment by Mab879** [comment]
> @Mab879 what else do we need?

After rebase my fix seems to work.

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
