### PR TITLE
SLES-15-030520 add to existing rule, audit_rules_kernel_module_loadin…

### PR DESCRIPTION
**Pull request by brett060102**
#### Description:

- SLES-15-030520  'Ensure auditd Collects Information on Kernel Module Unloading - delete_module'
simple change to add SLES-15-030520 existing  audit_rules_kernel_module_loading_delete/rule.yml 
and sle15 stig.profile
#### Rationale:

- enforce auditing of delete_module system call

### CODE REVIEW

**Comment by ggbecker** [comment]
@openscap-ci retest this please

**Comment by ggbecker** [comment]
please rebase on top of main branch, there was a test failure in the main branch

**Comment by brett060102** [comment]
hopefully that did it.

**Comment by brett060102** [comment]
Now, I am confused. https://github.com/brett060102/content/actions/runs/772210002 shows that build content failed, but https://github.com/ComplianceAsCode/content/pull/6877/checks?check_run_id=2404880923 shows that it passed.

Error is:
 Following selections were added to the rhel8's stig_gui profile:
 - file_owner_var_log_messages
 - file_owner_var_log
 - file_groupowner_var_log_messages
 - file_permissions_var_log_messages
 - file_permissions_var_log
 - file_groupowner_var_log
If changes to mentioned profiles are intentional, copy those compiled files, so they become the new reference:
cp '/home/runner/work/content/content/build/rhel8/profiles/stig_gui.profile' '/home/runner/work/content/content/tests/data/profile_stability/rhel8/stig_gui.profile'
Please remember that if you change a profile that is extended by other profiles, changes propagate to derived profiles. If those changes are unwanted, you have to supress them using explicit selections or !unselections in derived profiles.

But in this PR all test show passed.

**Comment by brett060102** [comment]
@ggbecker if things are not OK now, let me know, I have a couple of larger git hammers I can try. But as of this moment, my branch diff  with https://github.com/ComplianceAsCode/content/master shows only my changes.

**Comment by ggbecker** [comment]
> @ggbecker if things are not OK now, let me know, I have a couple of larger git hammers I can try. But as of this moment, my branch diff with https://github.com/ComplianceAsCode/content/master shows only my changes.

I think it's all good now

**Review by ggbecker — APPROVED** [review]

**Pull request merged**
