### PR TITLE
Enable socket_systemd-journal-remote_disabled rule for RHEL

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

The `socket_systemd-journal-remote_disabled` rule is applicable to RHEL8 and RHEL9 and is also part of `4.2.2.1.4` CIS requirement for both products.

This PR enables the rule for RHEL8 and RHEL9 and also update the `4.2.2.1.4` CIS requirement in the respective control files.
It was also introduced an Ansible remediation for the rule.

#### Rationale:

Better CIS coverage for RHEL.

### CODE REVIEW

**Comment by marcusburghardt** [comment]
When trying to execute `systemctl` command in the containers used by `Automatus` tests, this error is reported:
`System has not been booted with systemd as init system (PID 1). Can't operate.`

Therefore, it is expected the Automatus CS8, CS9 and Fedora fail.

**Comment by marcusburghardt** [comment]
I had to update the Ansible remediation to include a conditional in the task which ensures the `systemd-journal-remote.socket` is masked. It was also fixed the similar conditional in Bash remediation.

Finally the PR was rebased to reflect the most updated state of control files.

**Comment by Mab879** [comment]
I am waving the Automatus failures as the tests pass locally.

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
