### PR TITLE
Add rule to configure group owner of /usr/bin/sudo

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:
- Add new rule `sudo_dedicated_group`, set by variable  `var_sudo_dedicated_group`.
  - The group is created if it doesn't exist. (I'm not sure if this is a good idea)
  - I've added warnings about the remediation. It may set up an unmanageable system, if:
    -  the dedicated group has no members;
    - root login is not allowed.

#### Rationale:
- Restricting group owner of `/usr/bin/sudo` helps reduce surface attack.
- Helps cover ANSSI R57

### CODE REVIEW

**Comment by redhatrises** [comment]
@yuumasato can you fix the CCE conflict?

**Comment by yuumasato** [comment]
CCE conflict resolved.

**Review by matejak — CHANGES_REQUESTED** [review]
I have proposed an additional test as a separate commit, and some small modifications to the boilerplate code as suggestions.

Other than that, the PR looks just right.

**Review by matejak — APPROVED** [review]

**Comment by matejak** [comment]
Great, thank you for the PR!

**Pull request merged**
