### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Test build in Jenkins, it should have failed build in #5323.
   - It has CCE with invalid checksum value

### CODE REVIEW

**Comment by yuumasato** [comment]
This build should have failed, this branch contains the typo:
https://github.com/ComplianceAsCode/content/blob/b4e2419f498727d53706203cdd292dca76914861/linux_os/guide/services/obsolete/inetd_and_xinetd/file_owner_etc_hosts_allow/rule.yml

Locally the build fails for me.

There is something fishy going on with Jenkins.

**Comment by jan-cerny** [comment]
Which test should fail?

**Comment by yuumasato** [comment]
> Which test should fail?

The build itself should fail.

**Comment by ggbecker** [comment]
There is definitely something wrong with jenkins' pull request gating job. Here it is another victim https://github.com/ComplianceAsCode/content/pull/5542 as pointed out by: https://github.com/ComplianceAsCode/content/pull/5542#issuecomment-605852730

**Comment by ggbecker** [comment]
Looking into jenkins' logs I was unable to identify the cause. One thing I noticed is that the workspace: https://jenkins.complianceascode.io/view/SCAP%20Security%20Guide/job/scap-security-guide-pull-requests/ws/ does not contain the changes of the latest built Pull Request. So it looks like it's unable to update the repository locally. 

Does authorization token have expiration date?

**Comment by ggbecker** [comment]
@openscap-ci test this

**Comment by ggbecker** [comment]
@openscap-ci  test this please

**Pull request closed without merging**
