### PR TITLE
Fix deprecated IncludeConfig directive in rsyslog_files OVALs

### LINKED ISSUE #4363: Fix rsyslog_files rules for rsyslog v8.33.0
#### Description of problem:
Existing rsyslog_files rules and bash remediation scripts rely on $IncludeConfig directive which is deprecated starting from v8.33.0, include() object should be used instead:
https://www.rsyslog.com/doc/v8-stable/rainerscript/include.html

Affected tests:
- rsyslog_files_groupownership
- rsyslog_files_ownership
- rsyslog_files_permissions

#### SCAP Security Guide Version:
v0.1.43

#### Operating System Version:
Oracle Linux 8
Assume RHEL8 and latest Fedora should be affected as well

#### Steps to Reproduce:
1. run rsyslog_files_permissions evaluation
2. 
3.

#### Actual Results:
OVAL definition marked as failed with "Referenced variable has no values (oval:ssg-var_rfp_log_files_paths:var:1)."

#### Expected Results:
Evaluation passed

#### Addition Information/Debugging Steps:
Bash remediation script for rsyslog_files_permissions should be also revised to take into account  include() object

### PR DESCRIPTION
**Pull request by iokomin**
#### Description:
Fixes #4363 - $IncludeConfig directive is deprecated starting from rsyslog v8.33.0,
include() object should be used instead on RHEL8 and OL8.

Signed-off-by: Ilya Okomin <ilya.okomin@oracle.com>

#### Testing:
-Checked builds for ol7,ol8,rhel8
-Checked rules evaluation on ol8

### CODE REVIEW

**Comment by jan-cerny** [comment]
What if the user still uses the deprecated `$IncludeConfig` keyword? My understanding is that it's still possible to use it, it's only deprecated. We probably should check both `$IncludeConfig` and `include()`.

**Comment by iokomin** [comment]
@jan-cerny , thanks for your point, I think you are right and usage of both options might have place according to docs. I'll read more on how these two guys can be used together in rsyslog. 
If anyone already has a clear view on result rsyslog behavior - suggestions would be much appreciated.

**Comment by jvymazal** [comment]
My recommendation would be to definitely check both, while the new syntax is definitely superior, it is still safe to use both and rsyslog users are generally quite hesitant to make config changes and updates so currently you probably still encounter more of the old syntax.

**Comment by iokomin** [comment]
@jvymazal thanks for your input, I'll take it into account.

**Comment by iokomin** [comment]
@jan-cerny please find alternative implementation to support both rsyslog IncludeConfig directive and include() object.
Changes:
- Updated pattern to match both $IncludeConfig and include() entries
- Empty string added to this pattern to workaround FunctionGroup operations failure when no match found
- concatenation+split replaced by unique operation

Testing on OL8:
- checked /etc/rsyslog.conf with commented IncludeConfig and include lines (no match)
- checked /etc/rsyslog.conf with $IncludeConfig, multiline include() and single line include() entries

Note: 
I might think of rsyslog.conf file without empty lines and include entries where empty string workaround might not work. However, I suppose it would be a non-common case and it can be addressed in separate PR if needed as it requires more text processing. Thoughts?

**Comment by matejak** [comment]
The problem with this OVAL is its complexity and the relative inability to test it. Do you think that you could check out [the test suite](https://github.com/ComplianceAsCode/content/tree/master/tests) that is capable to test the OVAL in practice? If test scenarios are supplied, we will know what use cases the OVAL is able to handle and what not.

**Comment by iokomin** [comment]
@matejak thanks for your review. Honestly, suggested solution complexity is the same as the original one - only added alternative regex, also fixed existing issues: only one entry taken into account and failure when no entries matched. Anyway I'll take a look what could be added to the test suites list, definitely makes sense.

**Comment by iokomin** [comment]
@matejak please find test scenarios provided, see #4743
Note: Checked to work on OL backends, but should also be applicable on RHEL and Fedora.

**Comment by mildas** [comment]
@matejak This PR is ready to review. I merged test scenarios, so you can test it easily. Only ".fail.sh" test scenarios give ERROR during remediation part, because we don't have remediations for these rules.

@iokomin Thank you for creating tests! Wouldn't you like to also create remediations for them?

**Comment by iokomin** [comment]
@mildas thanks a lot for your review and checks. As for remediation scripts I'll give it a try.

**Comment by NicolasMarcotte** [comment]
@iokomin Concerning RHEL8,  I applied the regex directly in /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml , I wanted to see if it fixed that problem on fresh RHEL8 install and it did.

But it now produce the following warning: `E: oscap:     Failed to validate the pattern: pcre_exec() returned PCRE_ERROR_NOMATCH for pattern '^$' and a test path '/'. This indicates the pattern doesn't match a leading '/'.` when I run ` oscap xccdf eval    --rule xccdf_org.ssgproject.content_rule_rsyslog_files_groupownership  --oval-results --profile xccdf_org.ssgproject.content_profile_pci-dss /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml` as root.

On my system that warning can be suppressed without side-effects by adding a / inside the empty () to produce the following regex : `^(?:include\([\n\s]*file="([^\s;]+)".*|\$IncludeConfig[\s]+([^\s;]+)|(/))$`

**Comment by yuumasato** [comment]
@NicolasMarcotte I don't quite understand how the `/` fixed the openscap error.

Maybe taking a step back can help me. Is the regex trying to match the following?
- `include(file="some/path")`
- `$IncludeConfig (some/path)`
- `$IncludeConfig ()`

**Comment by iokomin** [comment]
@NicolasMarcotte thanks for pointing to this warning. 
Empty line match was introduced to workaround /etc/rsyslog.conf case when no include|$IncludeConfig match found - OVAL concat|unique operation returns "No values" if just one of it's arguments has no matched values (thus with empty line we'll have at least one for 99% sure).
Proposed regex change unfortunately won't work for the case when /etc/rsyslog.conf doesn't include any of include|$IncludeConfig lines. I'll take a look if this workaround could be workarounded to avoid warnings :)

**Comment by iokomin** [comment]
@yuumasato, I've checked DEVEL log and appears openscap ./src/OVAL/probes/oval_fts.c -> process_pattern_match() has sanity check limitation which requires file path pattern to match leading "/". Is there any elegant OVAL logic could be suggested to workaround rsyslog.conf case with empty include|$IncludeConfig set?

**Comment by yuumasato** [comment]
> @yuumasato, I've checked DEVEL log and appears openscap ./src/OVAL/probes/oval_fts.c -> process_pattern_match() has sanity check limitation which requires file path pattern to match leading "/".

@iokomin Interesting, so the problem is that the empty string is fed into `textfilecontent54_object` `filepath` `pattern_match` operation in [this line](https://github.com/ComplianceAsCode/content/pull/4379/files#diff-086f68e54c6fb45f0799567beb932498R54).

One thing that might work is to take `var_rfg_all_log_files_as_collection`, and filter out the empty string before using it in `object_rfg_log_files_paths`. I think this will require creation of an intermediate object and use of filters.
As `var_rfg_all_log_files_as_collection` concatenates a `literal_component`, we know that removing the empty string will not create an empty variable.

**Comment by iokomin** [comment]
@yuumasato  thanks for looking into it and your idea is absolutely clear to me. However could you please give a hint, how proposed filtering can be implemented? If you had working example or reference on existing piece of SSG OVAL code that would be really helpful to close this PR. Unfortunately I'm running out of ideas how to do this while these rules would be better to fix for a number of platforms and critical profiles.

**Comment by shawndwells** [comment]
bump to @yuumasato

**Comment by shawndwells** [comment]
and +cc to @matejak as owner of this PR

**Comment by yuumasato** [comment]
> @yuumasato thanks for looking into it and your idea is absolutely clear to me. However could you please give a hint, how proposed filtering can be implemented? If you had working example or reference on existing piece of SSG OVAL code that would be really helpful to close this PR. Unfortunately I'm running out of ideas how to do this while these rules would be better to fix for a number of platforms and critical profiles.

@iokomin Sorry, I don't have any working example. I'm not even sure my hackish idea works.
I may have time to tinker with it later this week.

**Comment by yuumasato** [comment]
@iokomin Hello, my original idea didn't work because `var_rfg_include_config_regex` returns one variable with multiple values. Because of the they way filters work (they remove the whole variable) the approach I mentioned would only work if there were multiple values with one value each.

But I came up with a solution that worked for me.
I don't see the issue with pcre anymore, but now it causes the following, :smiley: :
```
W: oscap:     Obtrusive data from probe!
W: oscap:     Obtrusive data from probe!
```
@jan-cerny Do you remember what these could be?

I expect build of this to fail without #5193

**Comment by yuumasato** [comment]
@iokomin Hope you don't mind that I pushed to your PR.
After #5193 is merged, could you rebase into latest master and check if it works for you?
Rebasing would also give easy access to the test scenarios.

**Comment by iokomin** [comment]
@yuumasato thanks for your time and sure your pushes are just welcome. I will definitely rebase and check your solution. The only question you can probably answer right away (that case which required workaround and I failed to resolve):
In your push if "object_var_rfg_include_config_regex" is empty, will "object_var_rfg_all_log_files" set be non empty containing value from "object_var_rfg_syslog_config"?

**Comment by yuumasato** [comment]
> In your push if "object_var_rfg_include_config_regex" is empty, will "object_var_rfg_all_log_files" set be non empty containing value from "object_var_rfg_syslog_config"?

Yes, the `<set>` will merge the two collection of objects, and it doesn't care if one of them is an empty set.. By default the operator is  `union`.

**Comment by yuumasato** [comment]
> now it causes the following,:
> 
> ```
> W: oscap:     Obtrusive data from probe!
> W: oscap:     Obtrusive data from probe!
> ```

There is https://bugzilla.redhat.com/show_bug.cgi?id=1722003 for this.

**Comment by yuumasato** [comment]
@iokomin #5193 was merged. Could you rebase onto latest master? Thanks

**Comment by iokomin** [comment]
@yuumasato awesome, checked your <set> solution to work as expected! dev branch rebased onto latest master.
Thanks a lot for your help with this PR.

**Comment by yuumasato** [comment]
> @yuumasato awesome, checked your solution to work as expected! dev branch rebased onto latest master.

Great!

@iokomin Do you still plan to add remediations to this PR?
If not, or if it would take some time, I would merge this.
Let's not hold this much longer.

**Comment by iokomin** [comment]
@yuumasato let's merge this OVAL fix while remediation part could be fixed as part of separate issue/PR. I have remediation work in plans however at the moment I have bunch of other content tasks w.r.t. OL8 release. Will do my best to look at remediation part as soon as rush is over.
Thanks again for your review and suggested fix.

**Comment by jan-cerny** [comment]
@yuumasato It's a warning message which meaning is unclear. It appears often when you use sets or variables. My understanding is that if `oscap` produces expected OVAL results the message could be removed.

**Pull request merged**
