### PR TITLE
Make Bash Jinja macros documentation pretty

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Make Bash Jinja macros documentation pretty.

#### Rationale:

- One more example of improved Jinja Macro documentation that can be used as inspiration.

  - Preview Before: https://complianceascode.readthedocs.io/en/latest/jinja_macros/bash.html#template-bash_package_install
  - Preview After: https://ggbecker-content.readthedocs.io/en/pretty-jinja-macros-doc/jinja_macros/bash.html#template-bash_package_install

### CODE REVIEW

**Comment by jan-cerny** [comment]
It looks better. I like very much that you posted the example links. Great!

**Comment by matejak** [comment]
It may be worth considering the [Napoleon extension](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) for Google-style docstrings that are nice to read by humans as well. That extension is widely supported.

**Comment by ggbecker** [comment]
> It may be worth considering the [Napoleon extension](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) for Google-style docstrings that are nice to read by humans as well. That extension is widely supported.

I'm not sure if that would work since we are using the `sphinxcontrib.jinjadomain` which has its own parser

**Comment by ggbecker** [comment]
@matejak see this: https://github.com/ggbecker/sphinxcontrib.jinjadomain/pull/1

**Pull request merged**
