### PR TITLE
Kubernetes Remediations: Add YAML separator

### PR DESCRIPTION
**Pull request by JAORMX**
This ensures that a correct YAML separator is added to all kubernetes
remediations.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by jhrozek** [comment]
Maybe a silly question, but does it matter if the magic comments that say which platform the remediation is for are after the separator?

**Comment by JAORMX** [comment]
> Maybe a silly question, but does it matter if the magic comments that say which platform the remediation is for are after the separator?

I don't know :/

**Comment by jhrozek** [comment]
On Fri, Jun 04, 2021 at 04:22:58AM -0700, Juan Osorio Robles wrote:
> > Maybe a silly question, but does it matter if the magic comments that say which platform the remediation is for are after the separator?
> 
> I don't know :/

np, let me check the built output.

**Review by jhrozek — APPROVED** [review]
the metadata seem to be retained, so lgtm

**Pull request merged**
