### PR TITLE
Add ansible remediation for accounts_umask_etc_profile

### PR DESCRIPTION
**Pull request by justin-stephenson**
#### Description:

- Add ansible remediation for `accounts_umask_etc_profile`

### CODE REVIEW

**Comment by jan-cerny** [comment]
Hi @justin-stephenson , thanks for your great patch. However, I have find out multiple problems with the rule `accounts_umask_etc_profile`:
1. umask should be set to 027 for accounts with uid >= 1000, but our rule doesn't check for uid
2. the corresponding OVAL  allows UMASK written in capitals, which I think won't work because bash is case sensitive, so we need to make the regex to match only `umask`.
3. /etc/profile can source  other scripts which can call again umask with a different value
I think if we will fix the rule we probably will need to modify the Ansible Playbook as well.

**Comment by redhatrises** [comment]
> Hi @justin-stephenson , thanks for your great patch. However, I have find out multiple problems with the rule `accounts_umask_etc_profile`:
> 
>     1. umask should be set to 027 for accounts with uid >= 1000, but our rule doesn't check for uid

@jan-cerny umask should be set for all accounts. Nothing in our rule says `uid >= 1000`

**Comment by justin-stephenson** [comment]
Thank you @jan-cerny for the review.

> Hi @justin-stephenson , thanks for your great patch. However, I have find out multiple problems with the rule `accounts_umask_etc_profile`:
> 
>     1. umask should be set to 027 for accounts with uid >= 1000, but our rule doesn't check for uid
> 
>     2. the corresponding OVAL  allows UMASK written in capitals, which I think won't work because bash is case sensitive, so we need to make the regex to match only `umask`.

Is this just a matter of changing `UMASK` to `umask` in `oval/shared.yml` for this rule?
> 
>     3. /etc/profile can source  other scripts which can call again umask with a different value
> 
To address this does it makes sense to create a drop directory file in `/etc/profile.d/` instead of replacing `/etc/profile` umask lines? The filename can use a high-number prefix to override other included files.

**Comment by redhatrises** [comment]
> Thank you @jan-cerny for the review.
> 
> > Hi @justin-stephenson , thanks for your great patch. However, I have find out multiple problems with the rule `accounts_umask_etc_profile`:
> > ```
> > 1. umask should be set to 027 for accounts with uid >= 1000, but our rule doesn't check for uid
> > 
> > 2. the corresponding OVAL  allows UMASK written in capitals, which I think won't work because bash is case sensitive, so we need to make the regex to match only `umask`.
> > ```
> 
> Is this just a matter of changing `UMASK` to `umask` in `oval/shared.yml` for this rule?

That should be fine.

> 
> > ```
> > 3. /etc/profile can source  other scripts which can call again umask with a different value
> > ```
> 
> To address this does it makes sense to create a drop directory file in `/etc/profile.d/` instead of replacing `/etc/profile` umask lines? The filename can use a high-number prefix to override other included files.

It should address both `/etc/profile` and `/etc/profile.d/`.

**Pull request merged**
