### PR TITLE
Make macros loading procedure deterministic and designate _general.jinja file to be first in the sequence

### PR DESCRIPTION
**Pull request by evgenyz**
As a follow-up to #8616.

Fixes potential problem:
```
[2/18] [fedora-content] compiling everything
FAILED: fedora/profiles /home/ekolesni/Devel/cc/content/build/fedora/profiles 
cd /home/ekolesni/Devel/cc/content/build/fedora && /usr/bin/cmake -E make_directory /home/ekolesni/Devel/cc/content/build/fedora/profiles && env PYTHONPATH=/home/ekolesni/Devel/cc/content /usr/bin/python3 /home/ekolesni/Devel/cc/content/build-scripts/compile_all.py --resolved-base /home/ekolesni/Devel/cc/content/build/fedora --controls-dir /home/ekolesni/Devel/cc/content/controls --build-config-yaml /home/ekolesni/Devel/cc/content/build/build_config.yml --product-yaml /home/ekolesni/Devel/cc/content/products/fedora/product.yml --sce-metadata /home/ekolesni/Devel/cc/content/build/fedora/checks/sce/metadata.json
Traceback (most recent call last):
  File "/home/ekolesni/Devel/cc/content/ssg/data_structures.py", line 142, in from_yaml
    data_dict = cls.parse_yaml_into_processed_dict(yaml_file, local_env_yaml, product_cpes)
  File "/home/ekolesni/Devel/cc/content/ssg/data_structures.py", line 109, in parse_yaml_into_processed_dict
    yaml_data = open_and_macro_expand(yaml_file, env_yaml)
  File "/home/ekolesni/Devel/cc/content/ssg/yaml.py", line 109, in open_and_macro_expand
    return open_and_expand(yaml_file, substitutions_dict)
  File "/home/ekolesni/Devel/cc/content/ssg/yaml.py", line 90, in open_and_expand
    expanded_template = process_file(yaml_file, substitutions_dict)
  File "/home/ekolesni/Devel/cc/content/ssg/jinja.py", line 129, in process_file
    return template.render(substitutions_dict)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ekolesni/Devel/cc/content/linux_os/guide/system/auditing/grub2_audit_backlog_limit_argument/rule.yml", line 45, in <module>
    {{{ fixtext_grub2_bootloader_argument("audit_backlog_limit", "8192") | indent(4) }}}
  File "/usr/lib/python3.10/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
  File "/home/ekolesni/Devel/cc/content/shared/macros/fixtext.jinja", line 230, in <module>
    $ sudo {{{ grub_command("add", argument + "=" + value) }}}
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'grub_command' is undefined
```

### CODE REVIEW

**Comment by evgenyz** [comment]
From CI:

```
Run python3 ./ctf/content_test_filtering.py pr --base 88569d6341689555232534a3bc39e914737123eb --remote_repo https://github.com/ComplianceAsCode/content --verbose --rule --output json 8840 > output.json
DEBUG   content_test_filtering - Getting files from 'git diff'
DEBUG   diff                   - Cloning repository to /tmp/tmp90r84uem directory
DEBUG   diff                   - Fetched to pr-8840 branch
DEBUG   diff                   - Comparing commit 88569d6341689555232534a3bc39e914737123eb with HEAD of pr-8840
DEBUG   JinjaAnalysis          - Analyzing Jinja macro file shared/macros/_general.jinja
Traceback (most recent call last):
  File "./ctf/content_test_filtering.py", line 44, in <module>
    diff_structure = diff_analysis.analyse_file(file_record)
  File "/home/runner/work/content/content/ctf/ctf/diff_analysis.py", line 54, in analyse_file
    return file_analyzer.process_analysis()
  File "/home/runner/work/content/content/ctf/ctf/analysis/JinjaAnalysis.py", line 290, in process_analysis
    diff = self.load_diff()
  File "/home/runner/work/content/content/ctf/ctf/analysis/JinjaAnalysis.py", line 208, in load_diff
    diff = diff["values_changed"]["root"]["diff"]
  File "/usr/lib/python3/dist-packages/deepdiff/helper.py", line 108, in __getitem__
    raise KeyError(new_key)
KeyError: 'values_changed'
Error: Process completed with exit code 1.
```

@ggbecker he-he :)

**Comment by Mab879** [comment]
This is a known issue, it seems. There is a PR to fix it: https://github.com/mildas/content-test-filtering/pull/31/files

**Comment by vojtapolasek** [comment]
@Mab879  are you sure that the PR you linked is relevant to this PR?

**Comment by Mab879** [comment]
> @Mab879 are you sure that the PR you linked is relevant to this PR?

Yes, it's similar to the code that wrote to fix this issue before I realized there was an open PR to fix it.

**Review by matejak — CHANGES_REQUESTED** [review]
What about renaming files to `number-basename.jinja` in a similar way as config files in `.d` config directories s.a. sshd, nginx and so on? Or, if it is possible, make sure that Jinja itself loads files in the correct order.
The proposed filename `_general.jinja` solves the lexicographic ordering problem in a hidden way, and doesn't offer any flexibility to control the loading order to a greater extent.

**Comment by evgenyz** [comment]
> What about renaming files to `number-basename.jinja` in a similar way as config files in `.d` config directories s.a. sshd, nginx and so on? Or, if it is possible, make sure that Jinja itself loads files in the correct order. The proposed filename `_general.jinja` solves the lexicographic ordering problem in a hidden way, and doesn't offer any flexibility to control the loading order to a greater extent.

Since `Environment`.`select_template` suffers from the same problem, I've switched to number prefixes.

**Comment by ggbecker** [comment]
The documentation files will need to be updated as well, for example:

https://github.com/ComplianceAsCode/content/blob/master/docs/jinja_macros/ansible.rst#L0-L1

**Comment by evgenyz** [comment]
> The documentation files will need to be updated as well, for example:
> 
> https://github.com/ComplianceAsCode/content/blob/master/docs/jinja_macros/ansible.rst#L0-L1

I wonder if we should rename rst files as well.

**Comment by Mab879** [comment]
> > The documentation files will need to be updated as well, for example:
> > https://github.com/ComplianceAsCode/content/blob/master/docs/jinja_macros/ansible.rst#L0-L1
> 
> I wonder if we should rename rst files as well.

We could that way the sections are listed in the same way as they are loaded. That might help better document this behavior. But I'm open to both ways.

**Review by matejak — APPROVED** [review]

**Comment by jan-cerny** [comment]
@evgenyz @Mab879 @matejak @ggbecker It's a good practice to create a feature branch in your fork to create a PR.

**Pull request merged**
