### PR TITLE
Add CMakelint

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

* Add cmakelint tests
* Fix cmakelint errors

#### Rationale:
Ensure that our CMake files are 

#### Review Hints:
Blocked by #10466

### CODE REVIEW

**Comment by jan-cerny** [comment]
The fails in testing farm jobs aren't related to this PR, they are caused by https://github.com/ComplianceAsCode/content/issues/10450.

**Comment by marcusburghardt** [comment]
https://github.com/ComplianceAsCode/content/pull/10466 is already merged. This PR is no longer blocked, according to the description.

**Review by marcusburghardt — APPROVED** [review]

**Review by jan-cerny — APPROVED** [review]
I have seen that the CI job Fedora Latest container installs the cmakelint from PIP 3 and I have also seen that it runs the CTest test test-cmakelint and that it passed. I was able to run it locally on my F 37 laptop with no problems. I have  checked that when I break the style guide the test starts to fail and points me to my problem:

```
[jcerny@thinkpad build{pr/10468}]$ ctest --verbose -R test-cmakelint
UpdateCTestConfiguration  from :/home/jcerny/work/git/scap-security-guide/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jcerny/work/git/scap-security-guide/build/DartConfiguration.tcl
Test project /home/jcerny/work/git/scap-security-guide/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 58
    Start 58: test-cmakelint

58: Test command: /usr/bin/env "PYTHONPATH=/home/jcerny/work/git/scap-security-guide" "cmakelint" "--config" "/home/jcerny/work/git/scap-security-guide/.cmakelintrc" "/home/jcerny/work/git/scap-security-guide/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/cmake/CopyFiles.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/FindOpenSCAP.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/FindPythonModule.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/GNUInstallDirs.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/SSGCommon.cmake" "/home/jcerny/work/git/scap-security-guide/products/alinux2/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/alinux3/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/anolis8/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/chromium/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/debian10/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/debian11/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/eks/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/example/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/fedora/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/firefox/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/macos1015/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ocp4/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ol7/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ol8/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ol9/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/opensuse/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhcos4/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhel7/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhel8/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhel9/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhv4/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/sle12/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/sle15/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu1604/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu1804/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu2004/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu2204/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/uos20/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/tests/CMakeLists.txt"
58: Working Directory: /home/jcerny/work/git/scap-security-guide/build/tests
58: Test timeout computed to be: 10000000
58: Total Errors: 0
1/1 Test #58: test-cmakelint ...................   Passed    0.08 sec

The following tests passed:
	test-cmakelint

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.08 sec
[jcerny@thinkpad build{pr/10468}]$ ctest --verbose -R test-cmakelint
UpdateCTestConfiguration  from :/home/jcerny/work/git/scap-security-guide/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jcerny/work/git/scap-security-guide/build/DartConfiguration.tcl
Test project /home/jcerny/work/git/scap-security-guide/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 58
    Start 58: test-cmakelint

58: Test command: /usr/bin/env "PYTHONPATH=/home/jcerny/work/git/scap-security-guide" "cmakelint" "--config" "/home/jcerny/work/git/scap-security-guide/.cmakelintrc" "/home/jcerny/work/git/scap-security-guide/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/cmake/CopyFiles.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/FindOpenSCAP.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/FindPythonModule.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/GNUInstallDirs.cmake" "/home/jcerny/work/git/scap-security-guide/cmake/SSGCommon.cmake" "/home/jcerny/work/git/scap-security-guide/products/alinux2/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/alinux3/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/anolis8/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/chromium/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/debian10/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/debian11/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/eks/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/example/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/fedora/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/firefox/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/macos1015/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ocp4/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ol7/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ol8/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ol9/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/opensuse/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhcos4/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhel7/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhel8/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhel9/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/rhv4/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/sle12/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/sle15/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu1604/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu1804/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu2004/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/ubuntu2204/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/products/uos20/CMakeLists.txt" "/home/jcerny/work/git/scap-security-guide/tests/CMakeLists.txt"
58: Working Directory: /home/jcerny/work/git/scap-security-guide/build/tests
58: Test timeout computed to be: 10000000
58: Total Errors: 1
58: /home/jcerny/work/git/scap-security-guide/CMakeLists.txt:5: Tab found; please use spaces [whitespace/tabs]
1/1 Test #58: test-cmakelint ...................***Failed    0.07 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.07 sec

The following tests FAILED:
	 58 - test-cmakelint (Failed)
Errors while running CTest
Output from these tests are in: /home/jcerny/work/git/scap-security-guide/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

Thanks!

**Pull request merged**
