### PR TITLE
OCP4: Add rules to verify OCP and OAuth audit logs

### PR DESCRIPTION
**Pull request by JAORMX**
These verify:

* File permissions
* File ownership
* Directory permissions
* auditd rule to check access to these files

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now c5e238a7d564dbafe4cd7c37e67c24c263903651

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 87f4add6e2c5c6c532779eca0862af7a244af6f8

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now e6ed327414f0617053d7b0a5934968079a546056

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
