### PR TITLE
Update SRG-OS-000425-GPOS-00189 for RHEL 9 STIG

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
Add fixtext for rule package_openssh-server_installed

#### Rationale:

RHEL 9 STIG

### CODE REVIEW

**Comment by ggbecker** [comment]
it's a good idea to cross the data with latest RHEL8 STIG as well, for example: the SRG here in the latest version of RHEL8 STIG has two assigned rules, one for the package installed and one for the service enabled.

I've found out that there is a typo in the SRG

https://github.com/ComplianceAsCode/content/blob/244458731deef03ccdb146f03cd172cd8e7f4f3b/linux_os/guide/services/ssh/service_sshd_enabled/rule.yml#L40

Instead of `SRG-OS-000423-GPOS-00189` it should be `SRG-OS-000425-GPOS-00189`  (423->425)

**Review by ggbecker — CHANGES_REQUESTED** [review]
see my latest comment

**Comment by ggbecker** [comment]
actually the SRG list for the sshd service enabled should be:

`SRG-OS-000423-GPOS-00187,SRG-OS-000424-GPOS-00188,SRG-OS-000425-GPOS-00189,SRG-OS-000426-GPOS-00190`

note that there a few typos in the first portion of the SRG for most of the items

https://github.com/ComplianceAsCode/content/blob/244458731deef03ccdb146f03cd172cd8e7f4f3b/linux_os/guide/services/ssh/service_sshd_enabled/rule.yml#L40

**Comment by jan-cerny** [comment]
I have updated the SRG mapping for rule service_sshd_enabled and then I have added OCIL clause and fixtext to that rule.

**Review by ggbecker — APPROVED** [review]

**Pull request merged**
