### PR TITLE
rhcos4: Add remediations and rules to enable usbguard

### PR DESCRIPTION
**Pull request by JAORMX**
These install usbguard through the RHCOS extension system in
MachineConfig

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 2be47afc90caa19f2e5d8fd96ab9a6eb4e6f9129

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now d988b1a3e86bdff6a5204938de1aa6068cf1dc96

**Comment by redhatrises** [comment]
So far looks good to me

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now cc8635e43175cac8a81699ed8b6980bf1640b568

**Comment by redhatrises** [comment]
This looks good to me

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now ab39487419f8d13c164fbc2a2f45f3e472cb783a

**Comment by JAORMX** [comment]
Something is really not working here. Gotta review the machineconfigs
```
     helpers.go:643: E2E-FAILURE: The expected result for the service_usbguard_enabled rule didn't match. Expected 'PASS', Got 'FAIL' 
```

**Comment by JAORMX** [comment]
For some reason usbguard doesn't end up running... it seems to work in my 4.7 deployment. I'll have to test in 4.6

**Review by jhrozek — APPROVED** [review]
Looks good visually, let's see if the remediations pass

**Pull request merged**
