### PR TITLE
ssg_test_suite: Fix SSH port handling for podman backend in rootless mode

### PR DESCRIPTION
**Pull request by evgenyz**
This patch will allow to use podman backend of the SSG Test Suite without elevated privileges.

### CODE REVIEW

**Comment by matejak** [comment]
This unfortunately duplicates #4544 to some extent, but it is just a couple of lines of code, so no big harm.
However, we have functions that use `scp`, which will need to be adopted as well for the rootless podman to work.

**Comment by jan-cerny** [comment]
@openscap-ci add to whitelist

**Comment by evgenyz** [comment]
Aha, OK. It worked for me like that `./test_suite.py profile --container ssg_test_suite --datastream ../build/ssg-fedora-ds-1.3.xml standard`. Anyway, I'll check previous approach and `scp`-related code.
Thanks for the review.

**Comment by evgenyz** [comment]
So, this is kind of hackiesh fix. I admit it. It is pretty simple, though.

Personally I would like to create some abstraction over ssh/scp and actively move it to DRY state, thus being able to affect SSH options without tapping into global variables. The question is — is it worth it?

**Comment by evgenyz** [comment]
My test command was `./test_suite.py rule --container ssg_test_suite --datastream ../build/ssg-fedora-ds-1.3.xml accounts_tmout`

**Comment by matejak** [comment]
I have tried the same command as you on Fedora.

It didn't work for me as root (which can be regarded as regression), I got the `ssh: connect to host 10.88.0.92 port 44875: Connection refused` error message. I got somewhat further as a normal user, but also no success. In the output, I got

```
ERROR - Cannot extract data tarball ./ssgts/./data.tar.
ERROR - Terminating due to error: Unable to upload test scripts: Cannot extract data tarball ./ssgts/./data.tar..
```

and the `data.upload.log` contain lots of erros s.a. `tar: ./utils.sh: Cannot change ownership to uid 102264, gid 102264: Invalid argument`. Could you please double-check?

Regarding optimal solution, I think that moving the SSH and SCP functions to `TestEnv` methods could do the trick, but if your approach works, I would call it good for the time being.

**Comment by jan-cerny** [comment]
@evgenyz You have to change `ssg-fedora-ds-1.3.xml` to `ssg-fedora-ds.xml` and then it works fine.

**Comment by matejak** [comment]
It looks like that the last error is more my `podman` setup. So the last think that remain is the case when `podman` is executed by root.

**Comment by evgenyz** [comment]
Fix for root is here.

I've checked it with podman (rootless) and regular podman as well as docker backends. And I did it from a fresh start (cleaned and rebuilt all containers and images). Everything works for me.

**Comment by matejak** [comment]
I can confirm that the root mode works for me. The approach cuts some corners, but it saved a lot of effort, good job!
@jan-cerny has confirmed that the rootless mode works for him, which is great. Thank you for the PR!

**Pull request merged**
