### PR TITLE
SSG debian9

### LINKED ISSUE #2839: Debian 9
Is OpenSCAP working on a Debian 9 guide?

### PR DESCRIPTION
**Pull request by DominiqueDevinci**
#### Description:

-  Debian9 configuration (adapted from debian8)

#### Rationale:

- In order to support debian 9 I've adapted the debian 8 configuration. 

However, i've noticed a potential issue in existing debian8 reference to CIS benchmark. For instance, [in this file](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/rule.yml) we have "cis@debian8: 5.1.4", but when i look at [CIS_Debian_Linux_8_Benchmark_v2.0.1.pdf](https://anonymousfiles.io/OZpjXFy6/), the reference seems wrong : "5.1.4 Ensure permissions on /etc/cron.daily are configured (Scored) "

So, i guess that this id refer to an old benchmark that i've not found (i've found this one but it's not coherent too : https://web.archive.org/web/20170609021036/http://benchmarks.cisecurity.org/tools2/linux/CIS_Debian_Benchmark_v1.0.pdf ). It's the link provided by the html report but the it's not working anymore (and not available without subscription on CIS) 
So i propose to update the reference with the current CIS benchmarks (for the moment i've not modify debian8 and don't reuse the cis references in debian9 ... @jan-cerny  i wait for approval for this, in case if i don't refer to the right benchmark).

- Fixes #2839

#### Demo
Some output results:
[oscap info ssg-debian9-ds.xml](https://pastebin.com/v53NjGBV)
[oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_anssi_np_nt28_restrictive [...]](https://pastebin.com/v53NjGBV)
And an example of report on a debian9 server: https://d0m.tech/report_debian9_v2.html (updated 17/10)

### CODE REVIEW

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@DominiqueDevinci This is an awesome contribution. Thanks for submitting this!

The Jenkins fail looks legitimate. I think you should add `debian9` to `prodtype` ltag in `linux_os/guide/services/apt/apt_conf_disallow_unauthenticated/rule.yml` and `linux_os/guide/services/apt/apt_sources_list_official/rule.yml` because these rules are part of your anssi_np_nt28_minimal profile.

**Comment by DominiqueDevinci** [comment]
@jan-cerny thanks, it's fixed. In fact i was really confused because it was compiling on my environment ... but it's because i had not merge last commits from master :)

**Comment by DominiqueDevinci** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@DominiqueDevinci That's perfect, but pull requests shouldn't contain "Merge ..." commits. Please remove eb10299 from here. You can try using rebase, eg.
```
git rebase upstream/master
git push -f origin contrib_debian9
```
Be careful because `push -f` can be a destructive operation.

**Comment by matejak** [comment]
add to whitelist

**Comment by matejak** [comment]
test this please

**Comment by DominiqueDevinci** [comment]
Ops my bad, i think it's ok now (i will also do that for other PR where i've use merge ... )
I'm now wokring on the other compilation issue (probably also because of some change in the master).

**Comment by jan-cerny** [comment]
Thanks

**Pull request merged**
