### PR TITLE
Set platform all for rules that are selected in RHEL9 STIG profile

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:
- Set platform all for rules that are selected in RHEL9 STIG profile

#### Rationale:

- Let's see what happens when we enable remediation for rules in RHEL9 STIG that didn't have the remediation enabled before.
- Prefer `multi_platform_all` and let `prodtype` decide which product that remediation will be applicable to.

### CODE REVIEW

**Comment by Mab879** [comment]
@ggbecker Can you please take a look at the Testing Farm failures?

**Comment by ggbecker** [comment]
> @ggbecker Can you please take a look at the Testing Farm failures?

There are too many of them... let's rerun and see if it improves.

**Comment by matejak** [comment]
I have tested this DS on a RHEL9 VM, and those rules worked in the sense that they were fixed, survived fixed during the next scan, and even survived the reboot. So I would expect the test failure to have other causes, could it be something related to test setup that may interfere with rules targeting SSH?
However, those rules don't work in the sense that SSHD doesn't start after the remediation. Culprits are rules regarding the openssh server that put the `CRYPTO_POLICY='...'` lines into the file.

**Comment by ggbecker** [comment]
I have disabled back again the remediations in RHEL9 for the following rules:


xccdf_org.ssgproject.content_rule_harden_sshd_ciphers_openssh_conf_crypto_policy - fail

xccdf_org.ssgproject.content_rule_harden_sshd_ciphers_opensshserver_conf_crypto_policy - fail

xccdf_org.ssgproject.content_rule_harden_sshd_macs_openssh_conf_crypto_policy - fail

xccdf_org.ssgproject.content_rule_harden_sshd_macs_opensshserver_conf_crypto_policy - fail

**Comment by ggbecker** [comment]
@Mab879 please keep an eye on this one. I believe it will be mergeable as soon as the tests finish.

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
