### PR TITLE
Introduce a script to compare ComplianceAsCode versions

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:

This PR is blocked by #10761 and will be rebased after it will be merged.

    
This commit introduces a new script compare_versions.py which can show    differences between two ComplianceAsCode versions.  Lists added or    removed rules, profiles, changes in profile composition and changes in    remediations and platforms.  For comparison, you can use git tags or    ComplianceAsCode JSON manifest files directly.  This new feature    leverages the ComplianceAsCode JSON manifests, which have been    introduced by https://github.com/ComplianceAsCode/content/pull/10761

#### Rationale:

Helps track changes between content and product.

#### Review Hints:

To compare 2 ComplianceAsCode JSON manifests, provide the manifest files.

```
python3 utils/compare_versions.py compare_manifests ~/manifests/old.json ~/manifests/new.json
```

To compare 2 upstream versions, you need to specify the version git tags and a product ID.

```
$ python3 utils/compare_versions.py compare_tags v0.1.67 v0.1.68 rhel9
```

### CODE REVIEW

**Comment by matejak** [comment]
I suggest decoupling the difference representation and the text interpretation of thereof. That way, not only will it be possible to test the code, but tweaks to the output won't interfere with the code doing other things.
I am thinking of a generic approach that would e.g. given the manifest and key `rules` would create a dict-like diff structure with e.g. `rules:added`, `rules:removed`, and `rules:stable` keys. Perhaps applying this somehow recursively would largely do the trick of producing a diff structure?

**Comment by jan-cerny** [comment]
I have rebased this PR on the top of the latest upstream master branch. 
I have slightly updated the logic to little split the logic from printing, but it's far away from what you wanted. The question is is it worth doing now or do we want to wait for the manifest adoption.

**Comment by jan-cerny** [comment]
I have resolved remaining CodeClimate problem and I have rebased this on the top of the latest upstream master branch.

**Review by matejak — APPROVED** [review]
I like the improvements.
The script works, and is able to demonstrate the potential of manifests. If the concept gains serious traction, it can be improved accordingly, but expending excess resources in this direction wouldn't be smart.

**Pull request merged**
