### PR TITLE
remove product specific disa and srg references

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

I used following commands to remove product specific disa and srg references and replace them with ones without product:
```
find linux_os/guide/ -name rule.yml -exec sed -i 's/disa@.*:/disa:/' {} \;
find linux_os/guide/ -name rule.yml -exec sed -i 's/srg@.*:/srg:/' {} \;
```

#### Rationale:

These references are not product specific. More information here:
https://public.cyber.mil/stigs/cci/
https://disa.mil/-/media/Files/DISA/News/Events/Symposium-2019/2---Kreigline_STIG-Panel-Briefing1_approved_Final.ashx

### CODE REVIEW

**Review by ggbecker — CHANGES_REQUESTED** [review]
The references need to be merged together. Otherwise, there will be duplicates

**Comment by vojtapolasek** [comment]
I see, I will fix it. Thank you.

**Comment by cipherboy** [comment]
@vojtapolasek If you pull the tool from #6882, you can run:

```
$ ./utils/fix_rules.py duplicate_subkeys
```

and it will help you find the duplicates :)

**Review by ggbecker — APPROVED** [review]
LGTM

**Pull request merged**
