### PR TITLE
Add new rule dconf_gnome_disable_ctrlaltdel_logout to RHEL7 STIG.

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:
- Add new rule dconf_gnome_disable_ctrlaltdel_logout to RHEL7 STIG.
  - This rule aims to check for GNOME configuration of logout shortcut
with Ctrl-Alt-Delete key combination. It disables the key combination to
avoid unintentional reboot, mainly when user is in console mode. In
graphical mode the risk is reduced due to confirmation prompt.

#### Rationale:

- Reference: https://vaulted.io/library/disa-stigs-srgs/red_hat_enterprise_linux_7_security_technical_implementation_guide/V-94843?version=v2r7

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule dconf_gnome_disable_ctrlaltdel_logout:
 Bash remediation is newly added.
 Ansible remediation newly added.
 OVAL check is newly added.
Profile stig on rhel7:
 Rule dconf_gnome_disable_ctrlaltdel_logout added to stig profile.

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_ctrlaltdel_logout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_ctrlaltdel_logout
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel7-ds.xml stig

**Comment by mildas** [comment]
**Changes identified:**
Rule dconf_gnome_disable_ctrlaltdel_logout:
 Bash remediation is newly added.
 Ansible remediation newly added.
 OVAL check is newly added.
Profile stig on rhel7:
 Rule dconf_gnome_disable_ctrlaltdel_logout added to stig profile.

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_ctrlaltdel_logout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_ctrlaltdel_logout
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhel7-ds.xml stig

**Comment by redhatrises** [comment]
This rule appears to already exist as dconf_gnome_disable_ctrlaltdel_reboot

**Comment by ggbecker** [comment]
> This rule appears to already exist as dconf_gnome_disable_ctrlaltdel_reboot

That's true. I'll re-evaluate that one and use it instead. Closing. Thanks

**Pull request closed without merging**
