### PR TITLE
RHCOS4: Add recommended chrony config

### PR DESCRIPTION
**Pull request by JAORMX**
This adds the recommended chrony config as a remediation for rhcos4
profiles.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
/retest

The test actually passed but OCP CI failed on the logs gathering tasks:

```
 time="2021-04-01T11:48:35Z" level=info msg="Container cp-entrypoint-wrapper in pod e2e-aws-ocp4-moderate-gather-extra completed successfully"
time="2021-04-01T11:48:45Z" level=info msg="Container sidecar in pod e2e-aws-ocp4-moderate-gather-extra completed successfully"
Gathering artifacts ...
The connection to the server api.ci-op-bd56dmhf-1708d.origin-ci-int-aws.dev.rhcloud.com:6443 was refused - did you specify the right host or port?
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-04-01T11:48:40Z"} 
```

**Comment by JAORMX** [comment]
This is not ready; we'll rework this configuration.

**Comment by JAORMX** [comment]
/test e2e-aws-ocp4-cis-node

couldn't create cluster

**Comment by JAORMX** [comment]
Still not looking good...

**Comment by mrogers950** [comment]
CI is having issues all around at the moment.

**Pull request merged**
