### PR TITLE
Skip configure_usbguard_auditbackend to unblock the e2e

### PR DESCRIPTION
**Pull request by Vincent056**
Let's skip this test to unblock the e2e, will add back later

### CODE REVIEW

**Comment by Vincent056** [comment]
Created the Jira card for tracking: https://issues.redhat.com/browse/CMP-1542

**Comment by jhrozek** [comment]
oops:
```
     helpers.go:815: E2E-ERROR: The e2e YAML for rule 'configure_usbguard_auditbackend' is malformed: {<nil> <nil> <nil>} . Got error: couldn't parse the result as string or map 
```

**Comment by Vincent056** [comment]
> oops:
> 
> ```
>      helpers.go:815: E2E-ERROR: The e2e YAML for rule 'configure_usbguard_auditbackend' is malformed: {<nil> <nil> <nil>} . Got error: couldn't parse the result as string or map 
> ```

that was an extra `---` just removed it

**Comment by marcusburghardt** [comment]
Also some related context mentioned in #9346

**Review by marcusburghardt — APPROVED** [review]

**Pull request merged**
