### PR TITLE
ocp4 e2e: Fix way of checking that nodes are ready

### PR DESCRIPTION
**Pull request by JAORMX**
The current way of checking that nodes are ready is error prone. This
attempts to fix it by also verifying that the configurations have
converged (desiredConfig is the currentconfig).

This also unties the check from MCO, and will only check this if the
MCO-expected annotation exists on the nodes.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@jhrozek What do you think about this?

**Comment by JAORMX** [comment]
uhm... Seems to me that the node checks are a bit racy and we don't have enough info from the nodes themselves. Might need to start checking for the machineconfigpool instead.

**Pull request closed without merging**
