### PR TITLE
Stig sle12 security patches up to date

### PR DESCRIPTION
**Pull request by abergmann**
#### Description:

This PR adds the ```security_patches_up_to_date``` rule to the SUSE Linux Enterprise Server 12 STIG profile and sets the correct SUSE package manager to ```zypper```.

_This PR is actually on top of #4847 and I'm a bit unsure if this is the right approach._

### CODE REVIEW

**Comment by redhatrises** [comment]
@openscap-ci add to whitelist

**Comment by redhatrises** [comment]
ping @abergmann this review is being hold up by #4847. Question is waiting your response.

**Comment by shawndwells** [comment]
@openscap-ci retest this please

**Comment by redhatrises** [comment]
@shawndwells please remove your commit from this PR. We don't want these type of commit messages in the tree.

**Comment by redhatrises** [comment]
Since 1158b9c cannot be removed. Opened #5192 as the successor to this PR.

**Pull request closed without merging**
