### PR TITLE
make RHEL-08-020231 automated again

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- change status to from "inherently met" to "automated again"

#### Rationale:

Reacting to https://github.com/ComplianceAsCode/content/pull/9113#discussion_r917695235

### CODE REVIEW

**Review by Mab879 — APPROVED** [review]

**Comment by ggbecker** [comment]
We are not currently using this stig_rhel8.yml file to generate our RHEL8 STIG profile and it already contains this rule:
https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile#L607-L611
```  
    # RHEL-08-020230
    - accounts_password_pam_minlen

    # RHEL-08-020231
    - accounts_password_minlen_login_defs
```

This change is probably irrelevant

**Comment by ggbecker** [comment]
> We are not currently using this stig_rhel8.yml file to generate our RHEL8 STIG profile and it already contains this rule: https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile#L607-L611
> 
> ```
>     # RHEL-08-020230
>     - accounts_password_pam_minlen
> 
>     # RHEL-08-020231
>     - accounts_password_minlen_login_defs
> ```
> 
> This change is probably irrelevant

and note that the original rule was `accounts_password_minlen_login_defs`, unless I'm not seeing something here.

**Comment by vojtapolasek** [comment]
I was not aware that this control file is not being used. Yes the original rule was accounts_password_minlen_login_defs. This rule got removed from all Fedora and RHEL profiles because it does not work in Fedora and RHEL.
So how is the controls/stig_rhel8.yml file used?

**Comment by yuumasato** [comment]
> We are not currently using this stig_rhel8.yml file to generate our RHEL8 STIG profile and it already contains this rule: https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile#L607-L611
> 
> ```
>     # RHEL-08-020230
>     - accounts_password_pam_minlen
> 
>     # RHEL-08-020231
>     - accounts_password_minlen_login_defs
> ```
> 
> This change is probably irrelevant

So would it be better to remove the file which is not used?
Although the file may be irrelevant, if we will not remove it, let's at least not keep misinformation there.

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
