### PR TITLE
Add transforms and html tables for ol7 and ol8

### PR DESCRIPTION
**Pull request by iokomin**
#### Description:

Added transforms and enabled html tables for ol7 and ol8.

#### Testing:
- checked successful ol7 and ol8 builds
- reviewed generated tables for security controls

### CODE REVIEW

**Comment by iokomin** [comment]
Note: 
Known issue for ssg_build_html_stig_tables enabled in ol7 - produced warning due to the stig_overlay.xml is missing. Overlay will be added next to https://github.com/ComplianceAsCode/content/pull/5631 merge, thus warning expected to be addressed.

**Comment by iokomin** [comment]
Moving to WIP to resolve failed tests.

**Comment by iokomin** [comment]
Tests failures resolved in updated PR.
Could you please review?

**Comment by jan-cerny** [comment]
@openscap-ci 

/ok-to-test

**Pull request merged**
