### PR TITLE
new template socket_disabled

### LINKED ISSUE #10894: [affects stabilization] Rule service_systemd-coredump_disabled is failing tests
#### Description of problem:
During the review of the productization test run test `/CoreOS/scap-security-guide/Sanity/test-rules-scenarios-per-profile OSPP 4/5` we discovered that the rule `service_systemd-coredump_disabled` fails the `service_disabled.pass.sh` test scenario in the intial phase for both Ansible and Bash remediations when Automatus is executed in a `combined` mode.

#### SCAP Security Guide Version:
current upstream master branch as of 2023-07-22 as of HEAD a96ccb9

#### Operating System Version:
RHEL 9

#### Steps to Reproduce:

1. python3 /tmp/tmp.PZKIYKxtbI/rpmbuild/BUILD/scap-security-guide-0.1.69/tests/test_suite.py combined                 --slice 4 5                 --libvirt qemu:///system test_suite_vm                 --datastream /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml                 --mode online                 --remediate-using bash                 --duplicate-templates                 --no-reports                 xccdf_org.ssgproject.content_profile_ospp
2. python3 /tmp/tmp.PZKIYKxtbI/rpmbuild/BUILD/scap-security-guide-0.1.69/tests/test_suite.py combined                 --slice 4 5                 --libvirt qemu:///system test_suite_vm                 --datastream /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml                 --mode online                 --remediate-using ansible                 --duplicate-templates                 --no-reports                 xccdf_org.ssgproject.content_profile_ospp

#### Actual Results:
```
INFO - xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled
ERROR - Script service_disabled.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled'.
```

#### Expected Results:
no errors are reported by Automatus

#### Additional Information/Debugging Steps:
no

### PR DESCRIPTION
**Pull request by vojtapolasek**
#### Description:

- add new simple template socket_disabled which disables and masks the Systemd socket
- use the template on rules socket_systemd-journal-remote_disabled and service_systemd-journal-remote_disabled

#### Rationale:

- sometimes we are only interested in disabling a socket, not a service. There is already a second case of such a rule and therefore I think we can use a template for this.

- Fixes #10894 

#### Review Hints:

1. ./build_product rhel9
2. cd tests
3. python automatus.py template --libvirt <your_qemu_specs> --duplicate-templates socket_disabled

### CODE REVIEW

**Comment by Mab879** [comment]
I'm getting some interesting Automatus results.
So in template mode, the tests fail:
```
$ ./automatus.py template --libvirt qemu:///system automatus_rhel_9_latest socket_disabled
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/Developer/ComplianceAsCode/content/tests/logs/template-custom-2023-07-26-1428/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled
INFO - Script socket_disabled.pass.sh using profile (all) OK
INFO - Script socket_enabled.fail.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_socket_systemd-journal-remote_disabled
INFO - Script socket_disabled.pass.sh using profile (all) OK
ERROR - Script socket_enabled.fail.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in pass, instead of expected fail during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_socket_systemd-journal-remote_disabled'.
```
And rule mode everything is fine
```
$ ./automatus.py rule --libvirt qemu:///system automatus_rhel_9_latest service_systemd-coredump_disabled,socket_systemd-journal-remote_disabled
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/Developer/ComplianceAsCode/content/tests/logs/rule-custom-2023-07-26-1410/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_service_systemd-coredump_disabled
INFO - Script socket_disabled.pass.sh using profile (all) OK
INFO - Script socket_enabled.fail.sh using profile (all) OK
```

Are you able to reproduce this @vojtapolasek?

**Comment by jan-cerny** [comment]
I think the problem is that the package that provides this unit isn't installed by default.

**Comment by vojtapolasek** [comment]
Yes, @jan-cerny  is probably right, I will modify the template include the package name so that it can be installed by Automatus.

**Comment by vojtapolasek** [comment]
@Mab879  @jan-cerny  I fixed it.

**Review by Mab879 — APPROVED** [review]
LGTM. Waving the Code climate findings as they are not worth fixing in this PR.

**Pull request closed without merging**
