### PR TITLE
Remove JBoss EAP6

### PR DESCRIPTION
**Pull request by redhatrises**
- Product is wayyy past EOL

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule checks:
 OVAL check for checks was deleted.
Rule jboss_eap_configure_application_authentication:
 OVAL check for jboss_eap_configure_application_authentication was deleted.
Rule jboss_eap_configure_auditing:
 OVAL check for jboss_eap_configure_auditing was deleted.
Rule jboss_eap_configure_keystore:
 OVAL check for jboss_eap_configure_keystore was deleted.
Rule jboss_eap_configure_logging_level:
 OVAL check for jboss_eap_configure_logging_level was deleted.
Rule jboss_eap_configure_management_authentication:
 OVAL check for jboss_eap_configure_management_authentication was deleted.
Rule jboss_eap_configure_security_manager:
 OVAL check for jboss_eap_configure_security_manager was deleted.
Rule jboss_eap_configure_syslog:
 OVAL check for jboss_eap_configure_syslog was deleted.
Rule jboss_eap_file_permissions:
 OVAL check for jboss_eap_file_permissions was deleted.
Rule jboss_eap_logs_permissions:
 OVAL check for jboss_eap_logs_permissions was deleted.
Rule jboss_eap_remove_jmx:
 OVAL check for jboss_eap_remove_jmx was deleted.
Rule jboss_eap_remove_quickstarts:
 OVAL check for jboss_eap_remove_quickstarts was deleted.
Rule jboss_eap_remove_unnecessary_apps:
 OVAL check for jboss_eap_remove_unnecessary_apps was deleted.
Rule jboss_eap_roll_over_transfer_logs:
 OVAL check for jboss_eap_roll_over_transfer_logs was deleted.
Rule jboss_eap_vendor_supported:
 OVAL check for jboss_eap_vendor_supported was deleted.
Others:
 Python abstract syntax tree change found in ssg/constants.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Review by shawndwells — APPROVED** [review]
Good call. Ack pending Jenkins.

**Comment by redhatrises** [comment]
Jenkins passed but didn't report status back to GH. The OCP CI pass / failure has no impact on this pr.

**Comment by isimluk** [comment]
Sorry to see you go. :hand:

**Pull request merged**
