### PR TITLE
New rule set_nftable_loopback_traffic

### PR DESCRIPTION
**Pull request by hagenest**
#### Description:

- Created a new rule for configuring the loopback traffic with nftables for SLES15 CIS. Also corrected CIS-IDs in the three loopback rules.

#### Rationale:

- My previous PR removed the nftables remediation and replaced it with needed iptables remediation instead. The nftables remediation has to be re-added in a new rule.

### CODE REVIEW

**Comment by teacup-on-rockingchair** [comment]
Could you please assign this one to me, as @hagenest has now moved to another project.

**Comment by marcusburghardt** [comment]
@teacup-on-rockingchair , can this PR be closed in favor of #10366 ? If so, I can help closing it since @hagenest is working in another project.

**Comment by teacup-on-rockingchair** [comment]
> @teacup-on-rockingchair , can this PR be closed in favor of #10366 ? If so, I can help closing it since @hagenest is working in another project.

Yes this is the idea, since I cannot commit to his repo I just took his code in pr #10366

**Comment by marcusburghardt** [comment]
Closed in favor of https://github.com/ComplianceAsCode/content/pull/10366

**Pull request closed without merging**
