### PR TITLE
OCP4: Don't use a list in platforms

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

The list notation doesn't work anymore, let's use a boolean "sentence"
instead.

#### Rationale:

Related: #8833

### CODE REVIEW

**Review by JAORMX — APPROVED** [review]

**Comment by JAORMX** [comment]
@jhrozek what's the issue?

**Comment by evgenyz** [comment]
> @jhrozek what's the issue?

https://github.com/ComplianceAsCode/content/issues/8853

**Comment by jhrozek** [comment]
/hold cancel
This should now work

**Comment by jhrozek** [comment]
/retest
cluster installation and remediation application timed out, respectively

**Comment by jhrozek** [comment]
The code change is trivial and was previously acked.
Merging.

**Pull request merged**
