### PR TITLE
Use templates to generate Machineconfigs

### PR DESCRIPTION
**Pull request by JAORMX**

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Macro file:
 Jinja macro file shared/macros-kubernetes.jinja is newly added.
Others:
 Python abstract syntax tree change found in ssg/jinja.py.
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Others:
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Macro file:
 Jinja macro file shared/macros-kubernetes.jinja is newly added.
Others:
 Python abstract syntax tree change found in ssg/jinja.py.
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Macro file:
 Jinja macro file shared/macros-kubernetes.jinja is newly added.
Others:
 Python abstract syntax tree change found in ssg/jinja.py.
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Macro file:
 Jinja macro file shared/macros-kubernetes.jinja is newly added.
Others:
 Python abstract syntax tree change found in ssg/jinja.py.
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Macro file:
 Jinja macro file shared/macros-kubernetes.jinja is newly added.
Others:
 Python abstract syntax tree change found in ssg/jinja.py.
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)

**Comment by mildas** [comment]
**Changes identified:**
Profile moderate on rhcos4:
 Rule  added to moderate profile.
Macro file:
 Jinja macro file shared/macros-kubernetes.jinja is newly added.
Others:
 Python abstract syntax tree change found in ssg/jinja.py.
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)
 build_product rhcos4
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhcos4-ds.xml moderate

**Comment by mildas** [comment]
**Changes identified:**
Profile moderate on rhcos4:
 Rule  added to moderate profile.
Macro file:
 Jinja macro file shared/macros-kubernetes.jinja is newly added.
Others:
 Python abstract syntax tree change found in ssg/jinja.py.
 Python abstract syntax tree change found in ssg/templates.py.

**Recommended tests to execute:**
 (cd build && cmake ../ && ctest -j4)
 build_product rhcos4
 tests/test_suite.py profile --libvirt qemu:///system test-suite-vm --datastream build/ssg-rhcos4-ds.xml moderate

**Comment by matejak** [comment]
LGTM, I propose to merge this and address possible typos later. The direction of this PR is perfect.

**Pull request merged**
