### PR TITLE
Add test scenarios for configure_crypto_policy and CIS profiles

### PR DESCRIPTION
**Pull request by matusmarhefka**
#### Description:

- Add test scenarios for `configure_crypto_policy` to cover CIS profiles.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@matusmarhefka Do you have any idea why it fails on the GH actions job when it passes for me locally normally?

[jcerny@thinkpad scap-security-guide{pr/7615}]$ python3 tests/test_suite.py rule --no-reports --libvirt qemu:///system ssgts_rhel8 configure_crypto_policy 
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2021-09-22-1629/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_configure_crypto_policy
INFO - Script config_and_current_same_time.pass.sh using profile (all) OK
INFO - Script config_newer_than_current.fail.sh using profile (all) OK
INFO - Script missing_nss_config.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script missing_policy.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script missing_policy.fail.sh using profile xccdf_org.ssgproject.content_profile_standard OK
INFO - Script missing_policy_file.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script missing_policy_file.fail.sh using profile xccdf_org.ssgproject.content_profile_standard OK
INFO - Script nss_config_as_file.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script nss_config_as_symlink.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script policy_default_nosha1_set.pass.sh using profile xccdf_org.ssgproject.content_profile_e8 OK
INFO - Script policy_default_set.pass.sh using profile xccdf_org.ssgproject.content_profile_standard OK
INFO - Script policy_fips_ospp_set.pass.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script wrong_policy.fail.sh using profile xccdf_org.ssgproject.content_profile_ospp OK
INFO - Script wrong_policy.fail.sh using profile xccdf_org.ssgproject.content_profile_standard OK
INFO - Script policy_default_cis_l1.pass.sh using profile xccdf_org.ssgproject.content_profile_cis_server_l1 OK
INFO - Script policy_default_cis_l1.pass.sh using profile xccdf_org.ssgproject.content_profile_cis_workstation_l1 OK
INFO - Script policy_future_cis_l2.pass.sh using profile xccdf_org.ssgproject.content_profile_cis OK
INFO - Script policy_future_cis_l2.pass.sh using profile xccdf_org.ssgproject.content_profile_cis_workstation_l2 OK

**Comment by jan-cerny** [comment]
EDIT: I can see it in the prescripts:

```
policy_future_cis_l2.pass.sh: line 5: update-crypto-policies: command not found
```

**Comment by jan-cerny** [comment]
Perhaps we need something in `# packages`?

**Comment by marcusburghardt** [comment]
> Perhaps we need something in `# packages`?

Yes, this should solve:
`packages = crypto-policies-scripts`

**Comment by matusmarhefka** [comment]
> > Perhaps we need something in `# packages`?
> 
> Yes, this should solve:
> `# packages = crypto-policies-scripts`

Yeah, I will add it. I think many test scenarios will need this because set of packages in containers is much smaller compared to a standard system installation.

**Comment by jan-cerny** [comment]
@matusmarhefka 

So now the SSGTS GH action has a different problem, this time with `nss_config_as_symlink.pass.sh`.

```
+ ln -s /usr/share/crypto-policies/FIPS/nss.txt /etc/crypto-policies/back-ends/nss.config
ln: failed to create symbolic link '/etc/crypto-policies/back-ends/nss.config': File exists
```

Are we OK with this or do we want to make the job green?

**Comment by matusmarhefka** [comment]
> @matusmarhefka
> 
> So now the SSGTS GH action has a different problem, this time with `nss_config_as_symlink.pass.sh`.
> 
> ```
> + ln -s /usr/share/crypto-policies/FIPS/nss.txt /etc/crypto-policies/back-ends/nss.config
> ln: failed to create symbolic link '/etc/crypto-policies/back-ends/nss.config': File exists
> ```
> 
> Are we OK with this or do we want to make the job green?

I will try to solve all the issues when running inside a container.

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
