### PR TITLE
Add Initial RHEL 7 CIS profile

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Initial RHEL7 CIS profile

~~[ ] Update RHEL7 CIS references~~

### CODE REVIEW

**Comment by redhatrises** [comment]
@yuumasato have you also compared this profile to the C2S profile?

**Comment by yuumasato** [comment]
> @yuumasato have you also compared this profile to the C2S profile?

Yes, they are very similar...but as far as I know (or told) they shouldn't be the same.

**Comment by yuumasato** [comment]
I've decide to update the references later, when there is consensus whether having `cis@rhel7` and `cis@rhel8` when references are similar is worth it.

**Comment by yuumasato** [comment]
Also, let's not block parallel work that can leverage a merged profile.

**Comment by redhatrises** [comment]
No argument here. Ack

**Pull request merged**
