### PR TITLE
add debian12 automatus workflow

### PR DESCRIPTION
**Pull request by a-skr**
#### Description:

- Add a debian12 dockerfile and a github workflow to test rules on debian12

#### Review Hints:

- based on automatus-ubuntu2204 workflow.

### CODE REVIEW

**Comment by Mab879** [comment]
Thanks for the PR, The Ubuntu 22.04 Automatus seems to be broken.

I'm working on a fix in #12121, however I have ran into a bit of wall, see that PR for more details.

So at this point I'm uncomfortable merging this.

**Comment by a-skr** [comment]
Then, I suggest to not merge it for now. I added xsltproc as part of this PR to fix the build, and I will add other relevant fixes once PR #12121 is in a good shape.

I'm also not sure of how to test this PR from my side, so any hint would be welcome.

**Comment by Mab879** [comment]
> Then, I suggest to not merge it for now. I added xsltproc as part of this PR to fix the build, and I will add other relevant fixes once PR #12121 is in a good shape.
Sounds good. Thanks.

> I'm also not sure of how to test this PR from my side, so any hint would be welcome.

The best way to test this PR is to add an Automatus test scenario to a rule that works well in container in a separate commit. That should cause the Content Test Filtering to run the tests on the rule you changed. Once your workflow is done you can remove that commit via a rebase. 

Something I did in the past is just add blank test (with a filename like `default_state.fail.sh`) to the rule `package_tmux_installed`.

**Comment by jan-cerny** [comment]
Hi @a-skr Can you check this again? https://github.com/ComplianceAsCode/content/pull/12230 has been merged.

**Comment by a-skr** [comment]
I think this PR can be considered for merging.

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
