### PR TITLE
[wip] remove outdated CCI and SRG mappings, remap to current SRG

### PR DESCRIPTION
**Pull request by shawndwells**
DISA updated their CCI and SRG control enumeration. All our mappings (OS SRG and VMM SRG) are now outdated. And there's no conversion to the new scheme to automate new mappings.

Removing everything and slowly adding them back in.

### CODE REVIEW

**Comment by shawndwells** [comment]
@tedbrunell did a few mappings. To complete the work, would guestimate at least 120 hours of dedicated non-interrupted time. Not sure what would be reasonable as an upper estimate. Maybe 160 hours? 

Multiple people can work on this simultaneously. Having two people dedicated for 2 weeks seems reasonable.... but would need to truly be dedicated.

**Comment by yuumasato** [comment]
@shawndwells Where can we get these new references?

**Comment by shawndwells** [comment]
On 7/23/19 12:14 PM, Watson Yuuma Sato wrote:
> @shawndwells <https://github.com/shawndwells> Where can we get these 
> new references?


https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=operating-systems%2Cgeneral-purpose-os


https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_General_Purpose_Operating_System_V1R5_SRG.zip

**Comment by dahaic** [comment]
@shawndwells this looks terrific. As we are already getting conflicts, would it be possible to submit it in smaller chunks? This size is nigh impossible to review.

**Comment by shawndwells** [comment]
addressed in another PR

**Comment by redhatrises** [comment]
Closing.

**Pull request closed without merging**
