### PR TITLE
OCP4: Add rules for AWS and GCP disk encryption

### PR DESCRIPTION
**Pull request by JAORMX**
This adds relevant rule to check if disk encryption has been enabled for
either AWS or GCP. They're currently not added to any profile but they
will in the future.

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now b1369634febe05e5d278d9a44c12d68b33d69dcc

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 8c4989285561dc835b08795d1ec9383f5b42d4d6

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 4545a1a72caf91e84b3688dd4b0a18b2f8e2b909

**Comment by ggbecker** [comment]
Logs contain: `jq '[.items[] | .spec.template.spec.providerSpec.value.osDisk.managedDisk.diskEncryptionSet.id]' ''
encryption_enabled.pass.sh: line 143: jq: command not found`

You need to install `jq` first in the test scenario code.

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 9ac27827f7440699be518d0db9bec9cbfe104fba

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 9f3a688ff8581facc1e6d6be52327f0a375d58e8

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 12eb1bc8d1f3f6e21d45206bed21b185d74e9bb9

**Review by sherine-k — APPROVED** [review]

**Review by ggbecker — APPROVED** [review]

**Pull request merged**
