### PR TITLE
OCPBUGS-13589: Remove sysctl file check rule from STIG profile

### PR DESCRIPTION
**Pull request by rhmdnd**
We already have a bunch of rules that check the values of kernel sysctl
settings alongside a rule the ensures the default sysctl settings are
used. But we also had a rule to ensure the sysctl kernel parameter
configuration file was on disk for each node in the cluster.

The rules are structured so that we only need to check if the defaults
are being used or that all individual checks are being satified. By
default the sysctl rules pass on OpenShift 4.13+.

This makes the sysctl file existence check obsolete, and confusing for
users because the file doesn't exist by default. This causes the rule to
fail because the file doesn't exist. Remediations for other sysctl rules
will create the file, but since they pass by default the remediations
are not generated. To get around this, the user either need to exclude
the rule in a tailored profile, or they need to put a specific file on
disk that doesn't do anything.

This commit removes the rule from the STIG, and relies on checking the the
default kernel parameters. This commit also removes sub-rules from the
profile, since those rules are essentially helper rules for
`kubelet_enable_protect_kernel_sysctl`, and we don't need to specify
them twice. So even though we're removing some rules from the profile,
we're not decreasing coverage.

### CODE REVIEW

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by BhargaviGudi** [comment]
Verification passed with 4.16.0-0.nightly-2024-03-21-152650 + [compliance-operator](https://github.com/ComplianceAsCode/compliance-operator)
1.  Install CO
2. Create ssb with profile/upstream-ocp4-stig profile/upstream-ocp4-stig-node
```
$ oc compliance bind -N test profile/upstream-ocp4-stig profile/upstream-ocp4-stig-node
Creating ScanSettingBinding test
$ oc get suite
NAME   PHASE   RESULT
test   DONE    NON-COMPLIANT
$ oc get scan
NAME                             PHASE   RESULT
upstream-ocp4-stig               DONE    NON-COMPLIANT
upstream-ocp4-stig-node-master   DONE    NON-COMPLIANT
upstream-ocp4-stig-node-worker   DONE    NON-COMPLIANT
$ oc get cr
NAME                                                              STATE
upstream-ocp4-stig-api-server-encryption-provider-cipher          NotApplied
upstream-ocp4-stig-audit-profile-set                              NotApplied
upstream-ocp4-stig-oauth-or-oauthclient-token-maxage              NotApplied
upstream-ocp4-stig-project-config-and-template-network-policy     NotApplied
upstream-ocp4-stig-project-config-and-template-network-policy-1   NotApplied
upstream-ocp4-stig-project-config-and-template-resource-quota     NotApplied
upstream-ocp4-stig-project-config-and-template-resource-quota-1   NotApplied
$ oc get ccr | grep kubelet-enable-protect
upstream-ocp4-stig-node-master-kubelet-enable-protect-kernel-defaults                   PASS     medium
upstream-ocp4-stig-node-master-kubelet-enable-protect-kernel-sysctl                     PASS     medium
upstream-ocp4-stig-node-worker-kubelet-enable-protect-kernel-defaults                   PASS     medium
upstream-ocp4-stig-node-worker-kubelet-enable-protect-kernel-sysctl                     PASS     medium
```
```
Create ssb with profile/upstream-ocp4-stig-v1r1
$ oc compliance bind -N test profile/upstream-ocp4-stig-v1r1
Creating ScanSettingBinding test
$ oc get suite
NAME   PHASE     RESULT
test   RUNNING   NOT-AVAILABLE
$ oc get suite
NAME   PHASE     RESULT
test   RUNNING   NOT-AVAILABLE
$ oc get suite
NAME   PHASE   RESULT
test   DONE    NON-COMPLIANT
$ oc get ccr | grep kubelet-enable-protect
$
```

**Pull request merged**
