### PR TITLE
OCPBUGS-28242: Fix remediation for service_debug-shell_disabled

### PR DESCRIPTION
**Pull request by Vincent056**
Added mask:true to the remediation. Previously the test was still failling after remediation applied, this is due to lack of mask in the remediation.

### CODE REVIEW

**Review by yuumasato — COMMENTED** [review]
@Vincent056 The rule is templated, can we leverage it?
https://github.com/ComplianceAsCode/content/blob/08ed709ef5f3bc3d25f9926a3f03664d53bbe67d/shared/templates/service_disabled/kubernetes.template

If we remove this file, the templated kubernetes remediations will be used.

**Comment by Vincent056** [comment]
> @Vincent056 The rule is templated, can we leverage it? https://github.com/ComplianceAsCode/content/blob/08ed709ef5f3bc3d25f9926a3f03664d53bbe67d/shared/templates/service_disabled/kubernetes.template
> 
> If we remove this file, the templated kubernetes remediations will be used.

yes, I think that's a good point

**Comment by BhargaviGudi** [comment]
verification passed with 4.16.0-0.nightly-2024-02-29-062601 + compliance-operator deployed from [PR-489](https://github.com/ComplianceAsCode/compliance-operator/pull/489) code

1. Install Co from [PR-489](https://github.com/ComplianceAsCode/compliance-operator/pull/489) code
2. ./utils/build_ds_container.py -i ghcr.io/complianceascode/k8scontent:11638
```
$ oc get pb
NAME              CONTENTIMAGE                                 CONTENTFILE         STATUS
ocp4              ghcr.io/complianceascode/k8scontent:latest   ssg-ocp4-ds.xml     VALID
rhcos4            ghcr.io/complianceascode/k8scontent:latest   ssg-rhcos4-ds.xml   VALID
upstream-ocp4     ghcr.io/complianceascode/k8scontent:11638    ssg-ocp4-ds.xml     VALID
upstream-rhcos4   ghcr.io/complianceascode/k8scontent:11638    ssg-rhcos4-ds.xml   VALID
```
3. Create ssb with both ocp4 and rhcos4 profiles
```$ oc compliance bind -N test -S default-auto-apply profile/upstream-ocp4-moderate profile/upstream-ocp4-moderate-node profile/upstream-rhcos4-moderate
Creating ScanSettingBinding test
$ oc get ccr -l compliance.openshift.io/automated-remediation=,compliance.openshift.io/check-status=FAIL  | wc -l
384
$ oc get suite
NAME   PHASE   RESULT
test   DONE    NON-COMPLIANT
$ oc get scan
NAME                                 PHASE   RESULT
upstream-ocp4-moderate               DONE    NON-COMPLIANT
upstream-ocp4-moderate-node-master   DONE    NON-COMPLIANT
upstream-ocp4-moderate-node-worker   DONE    NON-COMPLIANT
upstream-rhcos4-moderate-master      DONE    NON-COMPLIANT
upstream-rhcos4-moderate-worker      DONE    NON-COMPLIANT
```
4. Run second run of rescan
```$ oc compliance rerun-now scansettingbinding test
Rerunning scans from 'test': upstream-ocp4-moderate, upstream-ocp4-moderate-node-master, upstream-ocp4-moderate-node-worker, upstream-rhcos4-moderate-master, upstream-rhcos4-moderate-worker
Re-running scan 'openshift-compliance/upstream-ocp4-moderate'
Re-running scan 'openshift-compliance/upstream-ocp4-moderate-node-master'
Re-running scan 'openshift-compliance/upstream-ocp4-moderate-node-worker'
Re-running scan 'openshift-compliance/upstream-rhcos4-moderate-master'
Re-running scan 'openshift-compliance/upstream-rhcos4-moderate-worker'
$ oc get ccr -l compliance.openshift.io/automated-remediation=,compliance.openshift.io/check-status=FAIL
NAME                                                              STATUS   SEVERITY
upstream-rhcos4-moderate-master-configure-usbguard-auditbackend   FAIL     low
upstream-rhcos4-moderate-master-service-usbguard-enabled          FAIL     medium
upstream-rhcos4-moderate-master-usbguard-allow-hid-and-hub        FAIL     medium
upstream-rhcos4-moderate-worker-configure-usbguard-auditbackend   FAIL     low
upstream-rhcos4-moderate-worker-service-usbguard-enabled          FAIL     medium
upstream-rhcos4-moderate-worker-usbguard-allow-hid-and-hub        FAIL     medium
$ oc get ccr -l compliance.openshift.io/inconsistent-check
No resources found in openshift-compliance namespace.
```
5. Run third round of rescan. `rhcos4-service-debug-shell-disabled` is passed
```
 oc compliance rerun-now scansettingbinding test
Rerunning scans from 'test': upstream-ocp4-moderate, upstream-ocp4-moderate-node-master, upstream-ocp4-moderate-node-worker, upstream-rhcos4-moderate-master, upstream-rhcos4-moderate-worker
Re-running scan 'openshift-compliance/upstream-ocp4-moderate'
Re-running scan 'openshift-compliance/upstream-ocp4-moderate-node-master'
Re-running scan 'openshift-compliance/upstream-ocp4-moderate-node-worker'
Re-running scan 'openshift-compliance/upstream-rhcos4-moderate-master'
Re-running scan 'openshift-compliance/upstream-rhcos4-moderate-worker'
$ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master   rendered-master-a1f05cfbbaa21690581f59286ee079d0   True      False      False      3              3                   3                     0                      4h3m
worker   rendered-worker-18841050370cd5887121fc73e38c2ce6   True      False      False      3              3                   3                     0                      4h3m
$ oc get ccr -l compliance.openshift.io/automated-remediation=,compliance.openshift.io/check-status=FAIL
No resources found in openshift-compliance namespace.
$ oc get ccr -l compliance.openshift.io/inconsistent-check
No resources found in openshift-compliance namespace.
```

**Pull request merged**
