### PR TITLE
Improve service_disabled template

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

This rule is a rebase for the #9468 plus some additional improvements in conditionals.
In alignment to the remediation, conditionals for systemd units were included in the two test scenario scripts by the initial PR.

After the rebase, I improved the conditionals in test scenarios and bash remediation to remove unnecessary `grep` from the command.

#### Rationale:

Better alignment between remediation and test scenarios.
Simpler conditionals with faster commands.

#### Review Hints:

For testing this changes I chose some random rules which uses the `service_disabled` template.
This should be enough for testing the changes.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@marcusburghardt 

> For testing this changes I chose some random rules which uses the service_disabled template.

Can you give an example of a rule that had problems problems before and is fixed by this PR?

Also, my understanding of the original pr #9468 was that there was a problem with `service_telnet_disabled` but this rule still fails the automatus's tests even with this PR. I think there might be a problem related to the fact the the telnet service isn't provided by the `telnet` package but by the `telnet-server` package and the rule rule doesn't reflect this. Are the rules related to telnet service related to this PR and are they expected to be fixed here?

**Comment by marcusburghardt** [comment]
> @marcusburghardt
> 
> > For testing this changes I chose some random rules which uses the service_disabled template.
> 
> Can you give an example of a rule that had problems problems before and is fixed by this PR?
> 
> Also, my understanding of the original pr #9468 was that there was a problem with `service_telnet_disabled` but this rule still fails the automatus's tests even with this PR. I think there might be a problem related to the fact the the telnet service isn't provided by the `telnet` package but by the `telnet-server` package and the rule rule doesn't reflect this. Are the rules related to telnet service related to this PR and are they expected to be fixed here?

Actually, this PR is not fixing any issue, but only improving the conditional. In practice, the result is the same.
Regarding the issue with the `service_telnet_disabled`, you are correct. It is because the rule is using the wrong package name `telnet` (which is just a client) instead `telnet-server`. I saw this during my tests but I will update the rule in a separate PR.

So, in short, neither this PR or the old one are not related to the `service_telnet_disabled` issue but just the conditional improvement.

**Comment by marcusburghardt** [comment]
Once this PR is merged, I will send another PR fixing the `service_telnet_disabled` rule.

**Comment by jan-cerny** [comment]
thanks for clarification!

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
