### PR TITLE
edit remediation for dconf_gnome_disable_automount

### PR DESCRIPTION
**Pull request by cyarbrough76**
#### Description:

- _edit remediation for dconf_gnome_disable_automount change value to meet STIG requirement._

#### Rationale:

- _meet STIG requirement_

### CODE REVIEW

**Comment by mildas** [comment]
**Changes identified:**
Rule dconf_gnome_disable_automount:
 Template usage changed in ansible remediation.

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml dconf_gnome_disable_automount

**Comment by redhatrises** [comment]
This is not a STIG requirement. DISA RME doesn't care what the filename is called especially since the same results are achieved.

**Comment by cyarbrough76** [comment]
Yes we know but unfortunately their scanners do care. For those of us who have to deal with such things.

**Comment by redhatrises** [comment]
The official DISA SCAP benchmarks actually don't even scan for this.

**Pull request closed without merging**
