### PR TITLE
Sort prodtypes lexicographicaly.

### PR DESCRIPTION
**Pull request by matejak**
Originally, the PR was meant to mass-add the `ocp4` prodtype to rules. Then, it turned out that our prodtype-added tooling sorts the prodtype comma-separated string lexicographicaly, so adding a new prodtype that way generates a noisy diff.

As sorted prodtypes were liked by e.g. @shawndwells , I have mass-sorted prodtypes in all rules.

### CODE REVIEW

**Comment by matejak** [comment]
test this please

**Comment by jan-cerny** [comment]
Hi @matejak, please remove all changes that don't change anything.

**Comment by matejak** [comment]
You mean those changes where there was just a prodtype ordering change?

I would leave that there, having the data structured in a way that is stable wrt tooling we use in the project is a good thing.

**Comment by shawndwells** [comment]
> Ack, but holding off merge while @matejak and @jan-cerny discuss.
> 
> The sorting of `prodtype` is nice. Perhaps a seemingly small change, but helps with readability.

Spoke to @matejak in person. While this PR is appreciated by upstream community, it will cause many downstream issues in Red Hat's fork. Waiting a week or two for Red Hat release engineers to refactor downstream code, and this will be merged by them at that time.

Assigning PR back to @matejak to merge when downstream is ready.

**Comment by shawndwells** [comment]
@matejak added ``[WIP]`` to PR title. Know this is not really a work in progress, but wanted to somehow visually indicate not to merge yet.

**Comment by matejak** [comment]
I have changed the description and scope of the PR, so please check it out again.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@matejak please remove the conflicts

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
@jan-cerny Please review again and merge, this PR tends to develop conflicts.

**Pull request merged**
