### PR TITLE
Ubuntu 22.04 CIS

### PR DESCRIPTION
**Pull request by dodys**
#### Description:

- This PR introduces the base for Ubuntu 22.04 CIS.
- It adds:
1. ubuntu2204 to prodtype in rules
2. cis@ubuntu2204 references
3. fix grub2 path in product.yml
4. add avahi and dconf to platform_package_overrides
5. add multi_platform_ubuntu to some remediations
6. add some ubuntu specific template vars
7. address some rules descriptions
8. for faillock rules, added ubuntu specific oval 
9. and more

### CODE REVIEW

**Review by Mab879 — APPROVED** [review]
Thanks for the new profile! Since you are the only approver for Ubuntu products, I will handle the approval of this PR.

**Comment by Mab879** [comment]
I have run some local tests for failing Automatus tests, and they pass.

**Comment by dodys** [comment]
thanks @Mab879!

**Pull request merged**
