### PR TITLE
Add test for count_oval_objects

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Add `count_oval_objects.py` to CTest.

#### Rationale:

Ensure that the script keeps working.

### CODE REVIEW

**Review by jan-cerny — COMMENTED** [review]
Thanks for opening this PR. I think that the `count_oval_objects.py` might not work as expected. On RHEL 8 data stream I got suspiciously low numbers:

```
Count of used OVAL objects:
==================================================
textfilecontent54_object                        23
rpminfo_object                                  16
systemdunitproperty_object                       6
xmlfilecontent_object                            1
partition_object                                 1
environmentvariable58_object                     1
```

I think the problem might be in the XPath expression used in that script because they don't use namespaces.

**Comment by Mab879** [comment]
@jan-cerny I took a quick look at changing these XPath queries, and I was not getting anywhere fast. Is there one in particular that looks suspect to you?

**Comment by jan-cerny** [comment]
@Mab879 Thanks. I took a look and I find multiple problems with the script:

1. The script probably wasn't tested with content where the rules contain OCIL checks. Once a rule has both OVAL and OCILs it only searches OCIL. I think that the lines 61 - 79 should be shifted one level to the right, because of the `oval_root` variable.
2. It would be nice to skip OCIL checks completely, because the script purpose is to find OVAL objects and there are no OVAL objects in OCIL files.
3. Handling namespaces is done in a hacking way - see line 31. That confused me when I mentioned the XPath queries.

Also I think that the usefulness of this script is questionable. It counts OVAL objects that are used in rules. I think that we don't need this type of data. What do you think about removing the script?

**Comment by Mab879** [comment]
I agree that the usefulness is questionable. I will close this PR and create a new one that removes the script.

**Comment by Mab879** [comment]
#10133 contains the removal of this script.

**Pull request closed without merging**
