### PR TITLE
rpm_verify_hashes - changes in config files can be expected

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Ignore changes in RPM's config files

#### Rationale:

- This should help reduce false positives.

Still, some files make the rule fail.
For example, remediation for `require_singleuser_auth` edits `/usr/lib/systemd/system/rescue.service` and breaks its "integrity".
Not sure if `/usr/lib/systemd/system/rescue.service` can be considered a config file.
After remediation from fresh install of RHEL8.
```
[root@localhost ~]# rpm -Va | grep '..5'
S.5....T.  c /var/lib/unbound/root.key
S.5....T.  c /etc/profile
S.5....T.  c /etc/audit/audit-stop.rules
S.5....T.  c /etc/dnf/dnf.conf
S.5....T.  c /etc/security/pwquality.conf
S.5....T.  c /etc/pki/tls/openssl.cnf
S.5....T.  c /etc/issue
S.5....T.  c /etc/rsyslog.conf
S.5....T.  c /etc/ssh/sshd_config
S.5....T.  c /etc/login.defs
S.5....T.  c /etc/pam.d/password-auth
S.5....T.  c /etc/pam.d/system-auth
S.5....T.  c /etc/sysctl.conf
S.5....T.    /usr/lib/systemd/system/rescue.service
S.5....T.  c /etc/crypto-policies/config
```

### CODE REVIEW

**Comment by angystardust** [comment]
Hi @yuumasato We should definitely also exclude the "ghost" files from the rpm -V output to minimize false positive results.
For reference: 

> The --noghost option has been added to the rpm -V command.  If used with this option, rpm -V verifies only the non-ghost files that were altered, which helps diagnose system problems. (BZ#1395818) 
> The parameter behavior has been fixed in RHEL 7.6 GA:
> https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.6_release_notes/new_features_installation_and_booting
> https://access.redhat.com/errata/RHEA-2018:3250

**Comment by jan-cerny** [comment]
@angystardust Probably yes, nice catch.

However it still will not solve all the issues. The aforementioned example `/usr/lib/systemd/system/rescue.service` is neither config nor ghost file.

**Comment by angystardust** [comment]
Hi @jan-cerny in my testing env based on a RHEL7.5, the following command produces no output:
`rpm --noghost --noconfig -Va | grep '..5'`

**Comment by redhatrises** [comment]
> Hi @yuumasato We should definitely also exclude the "ghost" files from the rpm -V output to minimize false positive results.
> For reference:
> 
> > The --noghost option has been added to the rpm -V command.  If used with this option, rpm -V verifies only the non-ghost files that were altered, which helps diagnose system problems. (BZ#1395818)
> > The parameter behavior has been fixed in RHEL 7.6 GA:
> > https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.6_release_notes/new_features_installation_and_booting
> > https://access.redhat.com/errata/RHEA-2018:3250

If the ghost files are non-configuration files, this is a problem, and they should not be excluded at all.

**Comment by yuumasato** [comment]
I wonder what check is done to determine a change in a `ghost` file.
Just its existence can be considered a change?

**Comment by yuumasato** [comment]
> If the ghost files are non-configuration files, this is a problem, and they should not be excluded at all.

Good point.

**Comment by angystardust** [comment]
@yuumasato According to my understanding, ghost files are files whose contents are not included in the package payload so there's no way for rpm to verify their integrity

**Comment by yuumasato** [comment]
I am confused by the `config` and `ghost` and `md5_differs`, I'll look into tests for them.

**Pull request merged**
