### PR TITLE
Store rendered control files

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Store rendered (resolved) control files when building the content.
- The files are stored under `build/$product/controls/`
- This PR also adds support for reusing controls across different policies.

#### Rationale:

- Files can be used to display a policy and the relationship of controls with rules in the project.

Note: Seeking feedback and help on how to implement this properly.

### CODE REVIEW

**Comment by jan-cerny** [comment]
> Files can be used to display a policy and the relationship of controls with rules in the project.

Questions: What is the use-case for this? In what way do you want to show the relationship of controls and rules? What is the benefit of viewing "resolved controls" instead of the original source or the HTML output online?

**Comment by ggbecker** [comment]
> @ggbecker Thanks for explanation! If it needs to be in a YAML format I would prefer a "nice" YAML, with no build system internal details and no empty fields, so that it would be better readable.

Agree with the part that no build system internal details, but the empty fields might be useful in the future depending on the needs of a policy. This PR definitely needs more iterations.

It doesn't need to be a "nice" YAML since this will be consumed most likely by Compliance Operator which will parse the file and produce something else for example. So the empty fields are not really a problem.

**Comment by ggbecker** [comment]
[patch.txt](https://github.com/ComplianceAsCode/content/files/11736817/patch.txt)

**Comment by matejak** [comment]
It turned out that this feature interferes with the nested controls feature, when we define (sub)controls inside another controls, and the information is then discarded, so the compiled controls don't have it - they just have the expected rule selections without knowing how those got there.
I have handled that, so subcontrols are formally recorded, and I have extended the mechanics to allow not only definition of subcontrols, but also reference of controls from other policies, all handled the same way.
At this time, the PR contains "ugly" code, but it also contains tests of this functionality.

**Comment by ggbecker** [comment]
It looks good to me, but I think we should provide some examples of how to use the nested controls feature and how people can benefit from it to avoid code duplication.

**Review by ggbecker — COMMENTED** [review]
LGTM, thanks for the follow up work @matejak .

**Comment by jan-cerny** [comment]
@ggbecker What about the CodeClimate problems? And do you need a 3rd person to a review or do you plan to be the assignee?

**Review by jan-cerny — APPROVED** [review]
I have tried to reference some controls from other controls and I have watched that the rule selections propageted.

**Comment by jan-cerny** [comment]
CI fail on Rawhide is caused by OpenSCAP and isn't related to the contents of this PR, see https://github.com/OpenSCAP/openscap/issues/1995.

**Pull request merged**
