### PR TITLE
Enable configure_crypto_policy set DEFAULT test scenario for RHEL8.

### PR DESCRIPTION
**Pull request by ggbecker**
Enable set DEFAULT configure_crypto_policy test scenario for RHEL8.

### CODE REVIEW

**Comment by mildas** [comment]
What about other test scenarios for `configure_crypto_policy`?

**Comment by ggbecker** [comment]
> What about other test scenarios for `configure_crypto_policy`?

The other test scenarios are already configured to run for RHEL8, e.g.:
 https://github.com/ComplianceAsCode/content/blob/4aec5060d42009b5f3e9cbbd7ac24f6fa42f16e2/tests/data/group_system/group_software/group_integrity/group_crypto/rule_configure_crypto_policy/symlink_to_wrong_policy.fail.sh#L2

**Comment by mildas** [comment]
@ggbecker Ah, okay.
I have one question - does this test make sense? I mean the test sets crypto policies to `DEFAULT`, but OVAL expects `FIPS` value, so the test fails every time although it should pass (`*.pass.sh`). It would make sense for profile, that wants `DEFAULT`, but I didn't find any and it fails at fedora too.

**Comment by ggbecker** [comment]
> @ggbecker Ah, okay.
> I have one question - does this test make sense? I mean the test sets crypto policies to `DEFAULT`, but OVAL expects `FIPS` value, so the test fails every time although it should pass (`*.pass.sh`). It would make sense for profile, that wants `DEFAULT`, but I didn't find any and it fails at fedora too.

It makes sense only for the `standard` profile which uses default variable for this rule (`DEFAULT`). So we can just remove the OSPP profile from `profiles` header and it'll be ok.

**Comment by mildas** [comment]
Looks good, I will merge it after build passing.

**Pull request merged**
