### PR TITLE
Don't pass sssd rules when sssd.conf is absent

### LINKED ISSUE #9193: Rule sssd_offline_cred_expiration initially passes but fails later
#### Description of problem:
Rule `sssd_offline_cred_expiration passes` during remediation (direct pass), but fails after remediation and reboot.
Some other rule might be breaking the rule.

#### SCAP Security Guide Version:
stabilization-v0.1.63 (1907133)

#### Operating System Version:
RHEL-9

#### Steps to Reproduce:

1. `/tests/test_suite.py profile                         --libvirt qemu:///system test_suite_vm                         --datastream /tmp/ssg-rhel9-ds.xml                         --xccdf-id scap_org.open-scap_cref_ssg-rhel9-xccdf-1.2.xml                         --mode online                         --remediate-using oscap                         xccdf_org.ssgproject.content_profile_stig_gui`

#### Actual Results:
The rule passes at first, but the fails.

#### Expected Results:
The rule keeps passing.

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Remove definitions that made the following rules pass when `/etc/sssd/sssd/.conf` didn't exist.
  - `sssd_memcache_timeout`
  - `sssd_offline_cred_expiration`
  - `sssd_ssh_known_hosts_timeout`
- The rules don't pass when the config file is missing end up creating it when remediation is applied.
  This turns the result of therules that were passing due to missing config file to fail.

#### Rationale:

- Some sssd rules check if /etc/ssssd/sssd.conf` exists and pass the rule if the file is missing, but other rules don't check for it, like the following ones:
  -  `sssd_run_as_sssd_user`
  - `sssd_enable_smartcards`
  - ` sssd_enable_pam_services`
- The assumption is that the SSSD service is not in use when the config file is missing. But the passing rule can also  mislead one into thinking the file is configured: 
- This also makes the behaviour among sssd rules consistent.

- Related #1507
- Fixes #9193

### CODE REVIEW

**Review by mildas — APPROVED** [review]
LGTM, making behavior consistent makes sense. Tested with kickstart test on RHEL8 and RHEL9.

**Review by mildas — CHANGES_REQUESTED** [review]
Now, I've noticed that Automatus tests are not passing.

**Comment by yuumasato** [comment]
The tests pass on local VM.

I'm able to reproduce the issue when running it on containers, and I think I know what the issue is.
`tests/test_rule_in_container.sh --dontclean --remediate-using ansible --name ssg_test_suite --datastream build/ssg-rhel8-ds.xml --debug sssd_memcache_timeout`
Checking the logs I see that the playbook has a when clause that should not be there:
`    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"] `
And the `*-remediation.verbose.log` confirm that the no task has been run on the container:
```
TASK [Test for domain group] ***************************************************
Tuesday 26 July 2022  17:48:58 +0200 (0:00:00.789)       0:00:02.435 **********
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [dbg] *********************************************************************
Tuesday 26 July 2022  17:48:58 +0200 (0:00:00.025)       0:00:02.460 **********
ok: [localhost] => {
    "msg": "{'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}}"
}

TASK [Add default domain group (if no domain there)] ***************************
Tuesday 26 July 2022  17:48:58 +0200 (0:00:00.030)       0:00:02.490 **********
skipping: [localhost] => (item={'section': 'sssd', 'option': 'domains', 'value': 'default'})  => {"ansible_loop_var": "item", "changed": false, "item": {"option": "domains", "section": "sssd", "value": "default"}, "skip_reason": "Conditional result was False"}
skipping: [localhost] => (item={'section': 'domain/default', 'option': 'id_provider', 'value': 'files'})  => {"ansible_loop_var": "item", "changed": false, "item": {"option": "id_provider", "section": "domain/default", "value": "files"}, "skip_reason": "Conditional result was False"}

TASK [Configure SSSD's Memory Cache to Expire] *********************************
Tuesday 26 July 2022  17:48:58 +0200 (0:00:00.032)       0:00:02.523 **********
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}
```

**Comment by Mab879** [comment]
I can confirm that the tests pass on a VM.

```
$ ./tests/automatus.py rule --libvirt qemu:///system automatus_rhel_9_0 --datastream ./build/ssg-rhel9-ds.xml --remediate-using ansible   sssd_offline_cred_expiration
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/code/ComplianceAsCode/content/logs/rule-custom-2022-07-26-1117/test_suite.log
WARNING - Script cache_credentials_false.pass.sh is not applicable on given platform
INFO - xccdf_org.ssgproject.content_rule_sssd_offline_cred_expiration
INFO - Script comment.fail.sh using profile (all) OK
INFO - Script correct_value.pass.sh using profile (all) OK
INFO - Script wrong_section.fail.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
```

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
