### PR TITLE
Add CCE identifiers to OCP moderate profile rules

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by shawndwells** [comment]
@redhatrises could you post your script that added these? Would be nice to capture it somewhere.

**Comment by redhatrises** [comment]
> @redhatrises could you post your script that added these? Would be nice to capture it somewhere.

Prefer not. Script is intended to be thrown away.

**Comment by shawndwells** [comment]
> > @redhatrises could you post your script that added these? Would be nice to capture it somewhere.
> 
> Prefer not. Script is intended to be thrown away.

We'll likely need to bulk-add CCEs like this in the future. Would be great to not have to continuously re-invent scripts.

For clarity - meant post as a comment to this PR and did not mean add to the code repo. Akin to how the CSV-to-rule.yml scriplet @ https://github.com/ComplianceAsCode/content/pull/5083

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Pull request merged**
