### PR TITLE
Add Fedora to disk_partitioning/encrypt_partitions

### PR DESCRIPTION
**Pull request by maage**
#### Description:

Add "fedora" into prodtype and add respective URL in disk_partitioning/encrypt_partitions.

#### Rationale:

- Use common dot after URL, not per distro dot.
- Fedora does support encrypted partitions. There is documentation there.
- There is already one docs.fedoraproject.org URL in linux_os/guide/services/ntp/group.yml

### CODE REVIEW

**Comment by maage** [comment]
There does seem to be multiple ways how documentation URLs are presented when there is need for per prodtype documentation.
- Sometimes there is default (else) branch and sometimes not. This produces output like:
  "To enable smart card authentication, consult the documentation at:"
- Sometimes there is formatting or similar and sometimes there is not between branches of prodtypes. Example: linux_os/guide/system/selinux/group.yml
- If formatting is used, there is <b>, <tt> and <li><b> variants at least.
- It varies what prodtype is used as default.

I'm not sure what is the right way to handle any of these situations.

**Review by vojtapolasek — APPROVED** [review]
LGTM, thank you. The OCP tests failures are not related, changes are made only to rule description.

**Comment by maage** [comment]
Thanks

**Pull request merged**
