### PR TITLE
Fix sysctl OVAL 5.10 build

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Fix sysctl OVAL 5.10 build

### CODE REVIEW

**Comment by Mab879** [comment]
This PR appears to only fix the build for RHEL 8; this helps but doesn't appear to fix the complete OVAL 5.10 build.

**Comment by ggbecker** [comment]
> This PR appears to only fix the build for RHEL 8; this helps but doesn't appear to fix the complete OVAL 5.10 build.

All right, I'm going to check on other distributions as well. Thanks for the review.

**Comment by ggbecker** [comment]
I have simplified the PR and compared with previous 5.10 criteria and it should match correctly what is expected to be present in OVAL5.10. The 5.10 sanity build now includes all rhel versions.

**Review by yuumasato — APPROVED** [review]
LGTM

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
