### PR TITLE
Update CIS RHEL8 and RHEL7 controlfiles

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

Along the time, some new rules were included or updated.
Among these improvements, some CIS requirements were also covered.
This PR is updating the CIS RHEL contolfiles requirements based on existing rules.

#### Rationale:

Better CIS coverage for RHEL products.

#### Review Hints

I tried to keep one commit for each requirement for a easier review.
Some commits, with minor changes, were grouped when the requirements were related.

### CODE REVIEW

**Comment by marcusburghardt** [comment]
> package_rsync_removed

I saw the package name and systemd unit name have different names. I will send a fix for this rule and rebase this PR.

**Comment by marcusburghardt** [comment]
It was rebased after the #10053 be merged. Lets see if it solves the issue when scanning the CIS profile.

**Comment by Mab879** [comment]
There is some issue with RHEL 7 tests. Can you please take a look?

**Comment by mildas** [comment]
I will check the Automatus.

About failing Testing Farm, `rsync` is needed for `tmt` test execution. Check Ansible hardening `tmt` logs - https://artifacts.dev.testing-farm.io/7e691dfe-566b-47af-a608-14843fae2ede/work-ansible-cis07mjemex/log.txt - after machine hardening and reboot, `tmt` finds out `rsync` is not there and installs it again:
```
19:20:47         Ensure that rsync is installed on the guest.
...
19:20:47         Execute command 'yum install -y rsync' on guest '3.142.123.15'.
```

**Comment by mildas** [comment]
`package_rsync_removed` was unselected in machine hardening tests because `rsync` is required for `tmt`.
Other tests where `rsync` is not required will test it.

**Comment by marcusburghardt** [comment]
This meantime a new rule was introduced in the project and the last commit in this PR includes it to RHEL products.

**Review by Mab879 — APPROVED** [review]
Thanks for the PR and getting everything fixed.

**Pull request merged**
