### PR TITLE
Add rule to check if OS is 64-bit when supported by CPU

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Add rule that checks if the system supports 64-bit operating systems
  - The rule fails if CPU supports for 64-bit operations, but installed OS is not a 64-bit one.

#### Rationale:
- Supports ANSSI BP-028 R10
  - Preference to 64-bit operating systems should be given when supported

### CODE REVIEW

**Review by jan-cerny — COMMENTED** [review]
This looks fine. It passes on my 64 bit system.

**Comment by yuumasato** [comment]
@jan-cerny Thank you for the review, rule description and rationale are updated.

**Comment by jan-cerny** [comment]
@yuumasato thanks, LGTM

**Pull request merged**
