### PR TITLE
Add a rule for EKC CIS section 5.5

### PR DESCRIPTION
**Pull request by rhmdnd**
The compliance-operator doesn't have the ability to query AWS IAM
endpoints, yet. But we can at least provide the user with the audit and
remediation steps so they can do it manually.

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
@rhmdnd the CI failure happened because there's no check in the rule right?

**Comment by rhmdnd** [comment]
> @rhmdnd the CI failure happened because there's no check in the rule right?

Correct. I believe the testing infrastructure is expecting a test:

```
 ---------Bash Remediation Logs---------
ERROR - No tests found matching the rule ID(s) 'iam_integration'
WARNING - Nothing has been tested!
---------Ansible Remediation Logs---------
ERROR - No tests found matching the rule ID(s) 'iam_integration'
WARNING - Nothing has been tested!
```

We don't have anything to automate, but we need rules defined even if they just relay manual remediation steps.

We could open a separate issue to resolve this, like skipping rule test validation if it doesn't contain a check.

**Comment by jhrozek** [comment]
> > @rhmdnd the CI failure happened because there's no check in the rule right?
> 
> Correct. I believe the testing infrastructure is expecting a test:
> 
> ```
>  ---------Bash Remediation Logs---------
> ERROR - No tests found matching the rule ID(s) 'iam_integration'
> WARNING - Nothing has been tested!
> ---------Ansible Remediation Logs---------
> ERROR - No tests found matching the rule ID(s) 'iam_integration'
> WARNING - Nothing has been tested!
> ```
> 
> We don't have anything to automate, but we need rules defined even if they just relay manual remediation steps.
> 
> We could open a separate issue to resolve this, like skipping rule test validation if it doesn't contain a check.

Thanks!

**Pull request merged**
