### PR TITLE
Check if all rules in profile exist

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
Prints an error message and aborts the build if profile selects a rule that doesn't exist or isn't present in the built product. The check is done early in the build process which means users won't have to validate the built content to find mistakes such as typo in rule ID in the profile file.

To enable this I had to remove groups selected in profile. This is OK because selecting a group in a profile doesn't have any effect. All rules are unselected by default and if you don't select the rules explicitly in the profile they aren't evaluated regardless the parent group. In other words, selecting groups doesn't affect selecting rules.

#### Rationale:
We want to catch a wrong rule in profile during the build.

Fixes: #4541

### CODE REVIEW

**Comment by mildas** [comment]
Wouldn't it be better to load also groups and check for them (if rule doesn't exist and if group doesn't exist then throw error) than deleting groups from RHEL6 profiles?

**Comment by jan-cerny** [comment]
@mildas But why would anybody select groups in profiles?

**Comment by matejak** [comment]
Profiles should select only rules.
Selecting groups is just noise, as it doesn't have any effect. As groups can grow or shrink uncontrollably, the feature of selecting groups would be potentially quite dangerous.

**Comment by ggbecker** [comment]
> Wouldn't it be better to load also groups and check for them (if rule doesn't exist and if group doesn't exist then throw error) than deleting groups from RHEL6 profiles?

I agree, but with a slightly different approach. Basically add an extra check if the selection matches a group and if so, it throws a different message for example: "You have selected a group instead of a rule. Groups have no effect in the profile and are not allowed to be selected. Please remove before proceeding". I couldn't find any documentation related to this and it might confuse the user.

**Comment by ggbecker** [comment]
LGTM. Tested with groups and non existent rules and it works great. Thanks for the patch. Waiting on the build to merge.

**Pull request merged**
