### PR TITLE
Change rule to use variable when auditing faillock

### PR DESCRIPTION
**Pull request by Mackemania**
#### Description:

- Some benchmarks specify different paths when monitoring the faillock file, depending on if a permanent faillock path has been configured. This updates the audit_rules_login_event_faillock to use the variable var_accounts_passwords_pam_faillock_dir instead of the profile faillock_path

### CODE REVIEW

**Comment by Mackemania** [comment]
> I think it would be better to modify the audit_rules_login_events template in a way that the template could generate content that uses a variable. That way we would avoid code duplication.

I will check it out, thanks

**Comment by Mab879** [comment]
I ran the Automatus tests locally and got the following results

```
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/code/ComplianceAsCode/content/tests/logs/rule-custom-2023-08-23-0817/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock
INFO - Script auditctl_wrong_rule.fail.sh using profile (all) OK
INFO - Script auditctl_wrong_rule_without_key.fail.sh using profile (all) OK
ERROR - Script auditctl_correct_without_key.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
INFO - Script auditctl_remove_all_rules.fail.sh using profile (all) OK
ERROR - Script augenrules_correct_extra_permission.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
INFO - Script augenrules_wrong_rule_without_key.fail.sh using profile (all) OK
ERROR - Script augenrules_correct_without_key.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
ERROR - Script auditctl_correct.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
ERROR - Script auditctl_correct_extra_permission.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
INFO - Script augenrules_wrong_rule.fail.sh using profile (all) OK
INFO - Script augenrules_remove_all_rules.fail.sh using profile (all) OK
ERROR - Script augenrules_correct.pass.sh using profile (all) found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
```

They do pass on master (2ea9497d44fd969e3356aadec53aa44df9751418).

**Comment by Mackemania** [comment]
> I ran the Automatus tests locally and got the following results
> 
> ```
> Setting console output to log level INFO
> INFO - The base image option has not been specified, choosing libvirt-based test environment.
> INFO - Logging into /home/mburket/code/ComplianceAsCode/content/tests/logs/rule-custom-2023-08-23-0817/test_suite.log
> INFO - xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock
> INFO - Script auditctl_wrong_rule.fail.sh using profile (all) OK
> INFO - Script auditctl_wrong_rule_without_key.fail.sh using profile (all) OK
> ERROR - Script auditctl_correct_without_key.pass.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
> INFO - Script auditctl_remove_all_rules.fail.sh using profile (all) OK
> ERROR - Script augenrules_correct_extra_permission.pass.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
> INFO - Script augenrules_wrong_rule_without_key.fail.sh using profile (all) OK
> ERROR - Script augenrules_correct_without_key.pass.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
> ERROR - Script auditctl_correct.pass.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
> ERROR - Script auditctl_correct_extra_permission.pass.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
> INFO - Script augenrules_wrong_rule.fail.sh using profile (all) OK
> INFO - Script augenrules_remove_all_rules.fail.sh using profile (all) OK
> ERROR - Script augenrules_correct.pass.sh using profile (all) found issue:
> ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage 
> ERROR - The initial scan failed for rule 'xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock'.
> ```
> 
> They do pass on master ([2ea9497](https://github.com/ComplianceAsCode/content/commit/2ea9497d44fd969e3356aadec53aa44df9751418)).

Thank you, I will check out what's causing the issues

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
