### PR TITLE
Added SLES 15/12 CCE codes related to the rules ...backup_etc_group

### PR DESCRIPTION
**Pull request by rumch-se**
#### Description:

- _Added 6 SLES-15/12 CCE numbers to the rules file_groupowner_backup_etc_group, file_owner_backup_etc_group, and file_permissions_backup_etc_group_

#### Rationale:

- The rules will be used in new profile(s)

### CODE REVIEW

**Comment by matejak** [comment]
Where do those codes come from? We need to make sure that they are indeed unique.

**Comment by matejak** [comment]
> ...
> I work at SUSE and here is my profile (https://www.linkedin.com/in/rumen-chikov) . The codes was provided by NIST to my company by a request from me, and we keep them in internal repo.
>  ...

Would it be possible to transfer (at least part) of those CCEs to the project? We have Red Hat codes in https://github.com/ComplianceAsCode/content/blob/master/shared/references/cce-redhat-avail.txt and the script https://github.com/ComplianceAsCode/content/blob/master/utils/fix_rules.py can be used to assign those identifiers to rules in a safe and automated manner, which would be the best. As codes are introduced to the repository, they can't be "stolen" without noticing.

I am not insisting, we can merge the PR if you confirm that you know what you are doing and that you use correct CCEs, but I think that our transparent in-repository approach is simply the best.

**Comment by marcusburghardt** [comment]
> > ...
> > I work at SUSE and here is my profile (https://www.linkedin.com/in/rumen-chikov) . The codes was provided by NIST to my company by a request from me, and we keep them in internal repo.
> > ...
> 
> Would it be possible to transfer (at least part) of those CCEs to the project? We have Red Hat codes in https://github.com/ComplianceAsCode/content/blob/master/shared/references/cce-redhat-avail.txt and the script https://github.com/ComplianceAsCode/content/blob/master/utils/fix_rules.py can be used to assign those identifiers to rules in a safe and automated manner, which would be the best. As codes are introduced to the repository, they can't be "stolen" without noticing.
> 
> I am not insisting, we can merge the PR if you confirm that you know what you are doing and that you use correct CCEs, but I think that our transparent in-repository approach is simply the best.

It would be great to have the SUSE CCEs list in the project, but I would suggest to introduce this list in another PR. I agree with @matejak that we can merge this PR once the required tests finish. By the way, I think a `commit --amend` would be necessary to trigger the tests again.

**Comment by rumch-se** [comment]
Hello @marcusburghardt 

I don't know how do you manage CCE codes related to Redhat's products. You will find as an attachment a file (taken from our repo) which presents our approach. When a SUSE's developer needs a code - he/she adds after the code the name/title of the rule and makes a pull request. He/she does this in advance.  At the moment the file presents only the codes which were assigned to different rules. You can see that we have 2 groups of codes for each of our products - SLES 12 and SLES 15. They were ordered from NIST in such a manner. 

Also our development process includes a step which checks if CCE code is unique. We have to do that before pull request to upstream. 

I have opened the file cce-redhat-avail.txt - and it has only codes. May I think that your logic is the following - when you need a code - this code will be taken from this file and will be used/assigned to the rule/requirement and after the number of the codes will be reduced with 1? Do you have a way to see which the distribution of the codes between the rules? 

I think that we can add SUSE CCE codes to the project - but should we remove the descriptive part - i.e. file to be as cce-redhat-avail.txt ? According to "As codes are introduced to the repository, they can't be "stolen" without noticing." - our motivation is the following - when SUSE provides rules / SUSE has to support/maintain these rules when some of our customers has a issue with a specific rule.  In other words - we need to be sure that the SUSE's CCE code was assigned to a rule by us. How will the process proposed by you help?  I will need more details on this topic.          
 
Have a nice day
Rumen
[suse_cce_codes.txt](https://github.com/ComplianceAsCode/content/files/9798283/suse_cce_codes.txt)

**Comment by ggbecker** [comment]
Our cce-redhat-avail.txt file contains available CCEs that don't have any rule associated with, as per your assumption, yes, everytime we want to assign a new CCE to a rule, we go to that file and pick one from it, then we remove the CCE from the file and assign to the rule.

What we are asking here is that you provide the list of available CCEs you have that are not assigned to any rules so far and we include them into the project then you will follow the same process we follow when assigning CCEs to rules.

I hope that it makes things clear.

**Comment by rumch-se** [comment]
Hello @ggbecker and @marcusburghardt 

I will provide your proposal to all developers+their line managers (we are two teams) who are working on this topic. We have to discuss internally - because it will change a little bit - our process.  

Have a nice day
Rumen

**Comment by rumch-se** [comment]
Hello @ggbecker and @marcusburghardt 

Just now I have created a PR https://github.com/ComplianceAsCode/content/pull/9709 with SUSE CCE's codes
May you check it?

Have a nice day
Rumen

**Review by marcusburghardt — APPROVED** [review]

**Comment by marcusburghardt** [comment]
@rumch-se , I reviewed this PR and the changes are ready to be merged. However, it is blocked by some CI tests. To make sure the content will be merged without issues, could you rebase the PR on the latest master, please? This will also trigger the CI tests again and hopefully everything will be good.

**Comment by rumch-se** [comment]
Hello @marcusburghardt
I have done a rebase of this PR
Have a nice day
Rumen

**Review by marcusburghardt — APPROVED** [review]

**Pull request merged**
