### PR TITLE
OL8 stig prodtype and platform

### PR DESCRIPTION
**Pull request by freddieRv**
#### Description:

- Add OL prodtype and platform to rules and remediation content part of the OL8 draft stig profile

#### Rationale:

- The OL8 DISA STIG v1r1 profile was released earlier this year and it has not been implemented in the scap-security-guide project.

### CODE REVIEW

**Review by ggbecker — APPROVED** [review]

**Review by Mab879 — APPROVED** [review]

**Comment by ggbecker** [comment]
@freddieRv Please rebase this on top of latest main branch as we have done some changes in the GH checks and the required test is now missing so we can merge this.

**Comment by freddieRv** [comment]
@ggbecker I just rebased and now I see a failing test, would this be a blocker?

**Comment by Mab879** [comment]
@freddieRv That test is not blocker. Thanks for doing the rebase.

**Pull request merged**
