### PR TITLE
Remove kubelet_disable_hostname_override rule

### PR DESCRIPTION
**Pull request by JAORMX**
This check is no longer applicable as we need the override to ensure
upgrades work for OpenStacka and AWS.

### CODE REVIEW

**Comment by jhrozek** [comment]
FWIW, I think that removing the rule is better than having it around as manual but without any clear steps, because what we tend to see if that people don't like manual checks and expect more or less automated compliant/non-compliant answer. A manual check with no instructions would likely just increase the support load, so I think it's even better to remove the check completely.

**Review by jhrozek — COMMENTED** [review]
don't you also need to remove the rule from the profiles?

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 1e98036fac6467e450f96d22ef26fbc06b1d1b9b

**Review by jhrozek — APPROVED** [review]
Locally the build went fine, let's see if CI goes through this time.

**Pull request merged**
