### PR TITLE
Add an automated check for OCP4 benchmark 1.3.5

### PR DESCRIPTION
**Pull request by lbragstad**
Benchmark 1.3.5 ensure the API server is configured to use TLS. This
commit automates the check.

#### Description:

- Add an automated check for benchmark 1.3.5

#### Rationale:

- This benchmark ensures the API server is configured to use TLS.

### CODE REVIEW

**Comment by jhrozek** [comment]
@openscap-ci ok to test

**Comment by jhrozek** [comment]
@openscap-ci add to whitelist

**Comment by lbragstad** [comment]
I'm going to close this MR in favor of https://github.com/ComplianceAsCode/content/pull/6198

**Pull request closed without merging**
