### PR TITLE
Add unit tests of XCCDF 1.2 elements

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
This PR adds simple unit tests for `_to_xml_element()` methods of Rule, Profile, Value, and Group class in ssg.build_yaml module.

The unit test fixtures will use example data created from real-world resolved rules, profile, value, and group that were taken from build executed on current master.

#### Rationale:
Increases testing of build scripts.

### CODE REVIEW

**Comment by jan-cerny** [comment]
I believe that the 2 similar blocks of code are OK because they work with different items: rules and groups.

**Comment by matejak** [comment]
I am not a big fan of tests that contain an overwhelming amount of low-level asserts. Those tests may be challenging to maintain, because when an assert starts to fail, what to do? Modify the test, modify test data, or look into the source code? In some cases when the situation is unclear and time pressure is present, a wrong action may be taken.
Wouldn't it be possible to use e.g. [xmldiff](https://xmldiff.readthedocs.io/en/stable/) with pretty-printed XML reference data? If a failure occurs in such case, there will be a much simpler question - there will be no low-level asserts, only the expected XML vs obtained XML, and the decision of how to handle the discrepancy would be much more transparent.

**Review by Mab879 — COMMENTED** [review]
Do we want this kind of path in the repo? I agree with @matejak regarding the number low level asserts.

**Comment by jan-cerny** [comment]
I have removed the hard coded definition location paths.

**Comment by jan-cerny** [comment]
We have discussed this to @matejak  and we have found out it's also possible to use xmldiff with this type of tests it allows us to store expected XML outputs as separate files and also it allows us to detect all differences from the expected output immediately. I have add conditional imports to make the tests skip  that require xmldiff and lxml when they aren't available because xmldiff isn't present on all systems where we would like to run our tests because xmldiff can be at this moment installed only using pip, it isn't packaged in most of Linux distributions.

**Review by Mab879 — CHANGES_REQUESTED** [review]
I like this approach better. I think we should document the need for the `xmldiff` python package in the building CaC doc. 

Can you add a new line of the files like `tests/unit/ssg-module/data/accounts_tmout.xml` or will that cause issues with the XML diff?

I think we can waive the code climate duplication errors.

**Comment by jan-cerny** [comment]
I have add documentation text.

> Can you add a new line of the files like tests/unit/ssg-module/data/accounts_tmout.xml or will that cause issues with the XML diff?

Unfortunately, xmldiff is sensitive on whitespace before and after tags. I don't like this behavior of xmldiff, but it seems that we will either have to live with that or invent some sort of whitespace normalization that would be executed before the test data would be passed to xmldiff.

@matejak has pointed to me https://xmldiff.readthedocs.io/en/stable/api.html#using-formatters but we have found that it's related to the diff output instead of input. Then I did an experiment where I add a newline after a tag to the test data and whatever argument I put into this `formatter` class the diff still showed the newline. :crying_cat_face:

**Comment by jan-cerny** [comment]
> Unfortunately, xmldiff is sensitive on whitespace before and after tags.

But now, an unexpected twist: we have found that this isn't true for the `diff_files` method. When using the `diff_trees` it is sensitive on whitespace and when using `diff_files` method it isn't sensitive on whitespace.

So we can save the actual outputs produced by the SUT to temporary files and then compare the temporary files with the test data files using the `diff_files`.

**Comment by jan-cerny** [comment]
I have se diff_files instead of diff_trees

**Review by Mab879 — APPROVED** [review]

**Pull request merged**
