### PR TITLE
Update OVAL, ansible an tests in audit_rules_suid_privilege_function rule

### PR DESCRIPTION
**Pull request by Xeicker**
#### Description:

- Change `audit_rules_suid_privilege_function` rule to not check if `euid=0` or `egid=0` in OL8
- Update ansible for this rule

#### Rationale:

- This is to be better aligned with OL8 DISA STIG
- Ansible update objective is to avoid adding extra lines when the audit rules are in place but not written exactly equal 

#### Review Hints:

- Automatus tests should cover these changes

### CODE REVIEW

**Review by freddieRv — COMMENTED** [review]
Changes LGTM

**Review by vojtapolasek — CHANGES_REQUESTED** [review]
Hello, and thank you for the PR, it looks nice. Just a note... I see you converted some lineinfile tasks into ansible.builtin.lineinfile tasks... could you please do it for all other tasks in that remediation while you are at it?
Thank you.

**Review by freddieRv — APPROVED** [review]
Changes LGTM.

Thanks for the efforts @Xeicker

**Review by vojtapolasek — APPROVED** [review]
Looks good now, thank you.

**Pull request merged**
