### PR TITLE
CIS 1.2.12: Add check and test for AlwaysPullImages

### PR DESCRIPTION
**Pull request by mrogers950**

### CODE REVIEW

**Review by JAORMX — CHANGES_REQUESTED** [review]
Seems that this check is commented out in the profile. Could you enable it?

**Comment by mrogers950** [comment]
@JAORMX fixed

**Review by JAORMX — APPROVED** [review]
Nice! Will merge once this passes CI.

**Comment by JAORMX** [comment]
@openscap-ci test this please

**Pull request merged**
