### PR TITLE
Code Climate Config

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

* Set pycodestyle max line length to 99, per the style guide
* Set Code Climate line limit to 400.

#### Rationale:

Get code climate with less noise and make it follow our guidelines.

### CODE REVIEW

**Comment by matejak** [comment]
Love it!

What about excluding all folders except those that contain Python code? i.e. everything except `ssg`, `build-scripts`, `utils`, `tests` and `shared` (as there are template preprocessing functions)

**Comment by Mab879** [comment]
> Love it!
> 
> What about excluding all folders except those that contain Python code? i.e. everything except `ssg`, `build-scripts`, `utils`, `tests` and `shared` (as there are template preprocessing functions)

So it seems that Code Climate works on an excluding method instead of an including method. So I don't think it's worth it, and the builds with Code Climate seem to be fast enough.

We also have markdown checking, so we don't just want to check Python code.

**Comment by matejak** [comment]
> > Love it!
> > What about excluding all folders except those that contain Python code? i.e. everything except `ssg`, `build-scripts`, `utils`, `tests` and `shared` (as there are template preprocessing functions)
> 
> So it seems that Code Climate works on an excluding method instead of an including method. So I don't think it's worth it, and the builds with Code Climate seem to be fast enough.
> 
> We also have markdown checking, so we don't just want to check Python code.

It is more about the [code](https://codeclimate.com/github/ComplianceAsCode/content/code) in the CodeClimate project entry - there is some serious noise there. So what about excluding `linux_os`, `applications` and `products` to begin with? That should reduce the file count, and it also isn't fragile or too specific.

**Review by matejak — APPROVED** [review]

**Comment by matejak** [comment]
Great, thanks!

**Pull request merged**
