### PR TITLE
scap-security-guide: add openembedded distro support

### PR DESCRIPTION
**Pull request by akuster**
includes a standard profile for out-of-the-box checks

#### Description:

This enables support for an OpenEmbedded based system.  OpenEmbedded is a Framework for building a custom distribution. One such distribution is the Yocto Project's "Poky reference distribution".  Openscap and scap-security-guide are part of a security layer  I maintain which allows users  to add security applications to their builds. 

#### Rationale:
In the spirit of opensource I am upstream my changes. I am not sure if this meet the intent or objective of the project. I  wanted to included a baseline set of tests that  pass  if run on on a default build.

### CODE REVIEW

**Comment by akuster** [comment]
Hello, I see there is a test-cmakelint error. I take it I need to correct that and do a v2 on the pull request?

**Review by Mab879 — CHANGES_REQUESTED** [review]
Sorry for the delay in review. One additional question we have is your plans on keeping this updated.

Thanks for the PR.

**Comment by akuster** [comment]
No worries. I plan on keeping it updated. I was waiting to see if these changes where going to be accepted before sending additional changes.

thanks

**Review by Mab879 — APPROVED** [review]
LGTM.

Thanks for the PR!

**Pull request merged**
