### PR TITLE
Update netrc requirement in CIS for RHEL8

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

Included `accounts_users_netrc_file_permissions` rule in the CIS controlfile for RHEL8.

#### Rationale:

Better CIS coverage for RHEL8.

### CODE REVIEW

**Review by Mab879 — DISMISSED** [review]

**Comment by Mab879** [comment]
```
:: [ 13:57:08 ] :: [   FAIL   ] :: Rules not passing after remediation:

xccdf_org.ssgproject.content_rule_accounts_users_netrc_file_permissions - fail 
```

The testing farm failure for RHEL 9 doesn't appear to be false positive.

@marcusburghardt what do you think?

**Comment by marcusburghardt** [comment]
> ```
> :: [ 13:57:08 ] :: [   FAIL   ] :: Rules not passing after remediation:
> 
> xccdf_org.ssgproject.content_rule_accounts_users_netrc_file_permissions - fail 
> ```
> 
> The testing farm failure for RHEL 9 doesn't appear to be false positive.
> 
> @marcusburghardt what do you think?

It was legit. I just updated the rule to handle cases where there is no interactive user on the system.
Test scenarios for these cases have also been included.
Commit e304bc572fbc71ebaa6c97e34b9ee9d064f13c5c

**Comment by marcusburghardt** [comment]
`Automatus CS9` is failing because this rule is restricted to `rhel8` on its prodtype definition.

**Review by Mab879 — APPROVED** [review]
Thanks for the test fix!

**Pull request merged**
