### PR TITLE
Remove any ocurrence of silent from /etc/pam.d/postlogin

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Update display_login_attempts so that the silent options is not used with module pam_lastlogin.so.

#### Rationale:

- Before, the silent option would be removed only in a very specific condition.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@yuumasato Can we have a test scenario covering this situation?

**Comment by yuumasato** [comment]
@jan-cerny There were already some test scenarios that handled the `silent` case. I have aligned them with the remediations.

**Review by jan-cerny — APPROVED** [review]

**Comment by yuumasato** [comment]
> Is there any specific reason to remove the `silent` for the last line with the `optional` control?

Yes, STIG, https://stigs.mab879.com/products/rhel7/v3r7/RHEL-07-040530/

As the impact is an extra line printed out during login, I didn't consider it a problem.

**Comment by marcusburghardt** [comment]
In my opinion, we should update the rule description and inform STIG so they also have opportunity to polish the requirement. It is not a big deal because the rule is still doing what is expected, but it is an avoidable regression in user experience. I can create an issue to get more opinion about that. Thanks for clarifying the context.

**Comment by yuumasato** [comment]
> In my opinion, we should update the rule description

Are you thinking of something more verbose?
https://github.com/ComplianceAsCode/content/pull/9009/files#diff-dcabcef1c7dd2e948ce3bcb07aa5f0d3a424ee2184eac1e84236ab6b588bff60R17-R18

>  and inform STIG so they also have opportunity to polish the requirement.

Yes, we plan to discuss this with DISA.

**Comment by marcusburghardt** [comment]
Issue opened: https://github.com/ComplianceAsCode/content/issues/9031

**Pull request merged**
