### PR TITLE
Add ubuntu2404 to GitHub Actions

### PR DESCRIPTION
**Pull request by Mab879**
#### Description:

Add ubuntu2404 to GitHub Actions

#### Rationale:

Catch issues in CI.

### CODE REVIEW

**Comment by Mab879** [comment]
Blocked by #12615

**Comment by dodys** [comment]
> Blocked by #12615

PR #12617 is now merged

**Review by dodys — CHANGES_REQUESTED** [review]
@Mab879 could you please rebase this PR. It should be good to merge after it.

**Comment by dodys** [comment]
I will merge as is since this should be passing now.

**Review by dodys — APPROVED** [review]
lgtm, thanks

**Review by dodys — CHANGES_REQUESTED** [review]
@Mab879 could you please rebase this PR. It should be good to merge after it.

**Comment by Mab879** [comment]
> @Mab879 could you please rebase this PR. It should be good to merge after it.

Done. Sorry for the delay, I was out of office last week.

**Review by dodys — APPROVED** [review]
thanks!

**Pull request merged**
