### PR TITLE
OCP: Only run controller_insecure_port_disabled for OCP 4.6-4.9

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

Commit:
https://github.com/kubernetes/kubernetes/commit/e481d9996591331d6173e4cb146afcaf5e0308f1

Removed the port option of kube-controller-manager and refactored the
insecure port handling. Instead of the port option, there's now
'secure-port' that defaults to 10257 and the insecure handling is
enabled by setting secure-port to 0. Before we write a rule for that,
let's fix the existing rule to unblock our CI.

#### Rationale:

Unblocks OCP CI.

### CODE REVIEW

**Comment by jhrozek** [comment]
e2e can't install clusters :-(

/test e2e-aws-ocp4-cis-node
/test e2e-aws-ocp4-moderate-node

**Comment by Vincent056** [comment]
I fixed the rule here: https://github.com/ComplianceAsCode/content/pull/8104, I added check for disabled insecure port, in addition, to check for binding address

**Comment by jhrozek** [comment]
```
     keycloakidp.go:89: 
        	Error Trace:	keycloakidp.go:89
        	            				helpers.go:416
        	            				e2e_test.go:91
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestE2e/Configure_test_IdP 
```

**Comment by jhrozek** [comment]
Your PR is much better, thanks, closing in favour of #8104

**Pull request closed without merging**
