### PR TITLE
Add rule for CIS 4.1.9

### PR DESCRIPTION
**Pull request by vakwetu**
#### Description:

- Add rule for  4.1.9

### CODE REVIEW

**Comment by jhrozek** [comment]
Looks like CI itself is having issues, the build.log says: `   * could not run steps: step e2e-aws-rhcos4-e8 failed: failed to acquire lease: status 502 Bad Gateway, status code 502 `

**Comment by JAORMX** [comment]
/retest

AWS is having trouble spawning clusters

**Comment by JAORMX** [comment]
Seems that there's something wrong with the check:

```
    helpers.go:534: Result - Name: cis-node-platform-scan-1-file-permissions-worker-kubeconfig - Status: FAIL - Severity: medium
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/ComplianceAsCode_content/6210/pull-ci-ComplianceAsCode-content-master-e2e-aws-ocp4-cis-node/1316127712175198208/artifacts/e2e-aws-ocp4-cis-node/container-logs/test.log

**Comment by yuumasato** [comment]
Funky, for some reason the remediations are not being generated...

**Comment by yuumasato** [comment]
Another thing that is funky is that when I was testing `file_owner_worker_ca` and `file_groupowner_worker_ca`, they were passing by default in my cluster.
```
    helpers.go:534: Result - Name: cis-node-platform-scan-1-file-owner-worker-ca - Status: FAIL - Severity: medium
    helpers.go:534: Result - Name: cis-node-platform-scan-1-file-groupowner-worker-ca - Status: FAIL - Severity: medium
```

**Review by jhrozek — APPROVED** [review]
I tested the rule manually and it works fine. The test failures were caused by a bug in the e2e test runner and were fixed in a separate PR.

**Pull request merged**
