### PR TITLE
Reduce duplicate OVALs in built data stream

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
Refactor build system to prevent duplication of applicability OVAL checks in the built data stream.
That is achieved the following way:
- the ssg-product-cpe-oval.xml is now created in a separate build step
- the ssg-product-cpe-oval.xml is now created without using ssg-product-oval.xml
- the ssg-product-cpe-oval.xml is now created without scanning the `linux_os/guide` tree
- OVAL checks used in CPE OVAL are now moved to shared/applicability/oval
- OVAL checks used in templated platforms now have their own special data type `cpe-oval`
- OVAL checks used in templated platforms are generated to a separate directory by the template engine

For more details, please read commit messages of each commit.

#### Rationale:
The OVAL checks that are used for platform definition should be present only in ssg-product-cpe-oval.xml. They were duplicated to the ssg-product-oval.xml which should contain only OVALs used in XCCDF rules. The duplicate OVAL checks in ssg-product-oval.xml data stream component aren't used by anything. 

Fixes: #9920

#### Review Hints:
Review the commits in sequence.

Compare generated CPE OVAL file on master and with the current patch. You can use https://fedorapeople.org/~jcerny/list_definitions.py to list OVAL definition IDs in a file.

### CODE REVIEW

**Comment by jan-cerny** [comment]
I have added commits addressing the CodeClimate issues. That caused that the amount of commits is too high for a review. So I have decided that I will move the commits that change the ssg.build_ovals to a separate PR https://github.com/ComplianceAsCode/content/pull/10048. That means this PR is now blocked by https://github.com/ComplianceAsCode/content/pull/10048 and will be rebased on master after https://github.com/ComplianceAsCode/content/pull/10048 will be merged.

**Comment by jan-cerny** [comment]
The PR https://github.com/ComplianceAsCode/content/pull/10048 has been merged so I have rebased this PR on the top of the master branch.

**Comment by jan-cerny** [comment]
I have rebased the PR on the top of the latest upstream master branch.

**Review by Mab879 — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
