### PR TITLE
Update PR workflow actions to run only on latest push

### PR DESCRIPTION
**Pull request by Vincent056**
#### Description:

Update all the PR-triggered workflows so they cancel previous action jobs in favor of new action jobs for the same PR when a new change is pushed

### CODE REVIEW

**Review by rhmdnd — APPROVED** [review]
LGTM, so long as the maintainers of the other workflows are good with the change, too.

cc: @ggbecker

**Review by Mab879 — APPROVED** [review]
LGTM.

Thanks.

**Comment by Vincent056** [comment]
> However it seems that some the builds are stuck. @Vincent056 you may need to push again to get those to trigger.

thanks for the review, just pushed again

**Comment by rhmdnd** [comment]
Looks like the Fedora builds are still stuck?

**Pull request merged**
