### PR TITLE
Add a test for pcre2 compatibility

### PR DESCRIPTION
**Pull request by jan-cerny**
This test will ensure that the regular expressions used in OVAL checks are compatible with the pcre2 library. This will be important when OpenSCAP will move to use pcre2 internally.

The test collects regular expressions used in SCAP source data streams and tries to compile these regular expressions using the code from pcre2 library.

Unfortunately, a large amount of regular expressions used in our OVAL checks are composed dynamically using data collected during the scan from the evaluated system. These regular expressions won't be tested by this test that performs a static analysis. I think that possible problems with these expressions could be caught by Automatus test scenarios eventually.

Related to: https://bugzilla.redhat.com/show_bug.cgi?id=2128342

#### Review Hints:

1. sudo pip3 install pcre2
2. break some regular expression in an OVAL check in your favorite rule to make the regular expression invalid
3. build the content
4. cd build && ctest --verbose -R check-pcre2-compatibility-ssg-rhel9-ds.xml

### CODE REVIEW

**Review by Mab879 — APPROVED** [review]
Thanks for the PR! I'm okay with not having this checked with mypy as the prce2 library doesn't support types.


I was able to get the test to fail by modifying a regex.

**Review by Mab879 — CHANGES_REQUESTED** [review]
Looks like we need to add `--no-use-pep517` to the Debian 10 pip install.

**Comment by jan-cerny** [comment]
@Mab879 Where should I put this option? To pip command in .github/workflows/gate.yaml ?

**Comment by Mab879** [comment]
> @Mab879 Where should I put this option? To pip command in .github/workflows/gate.yaml ?

Yes

**Comment by jan-cerny** [comment]
it seems that pip on Debian doesn't know this option

**Comment by Mab879** [comment]
I think I found a work around:

Add `libpcre2-dev` to the apt-get line.

Use `python3 -m pip` vs `pip3`. That worked in a container on my box.

**Comment by Mab879** [comment]
It seems that the Python package `cmake` doesn't work with the older version of pip in Debian. We could upgrade pip using itself, but I will leave that up to you.

**Comment by jan-cerny** [comment]
I have made the test running only on the Fedora worker. I have rebased this PR on the top of the latest upstream master branch.

**Review by Mab879 — APPROVED** [review]
Thanks for the PR and the work to get the CI work!

**Pull request merged**
