### PR TITLE
Add more precise URI for SRG CTR

### PR DESCRIPTION
**Pull request by yuumasato**
#### Description:

- Add more specific URI for  `SRG-APP-XXXXXX-CTR-XXXXXX` references: `container-platform`
  - https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform
- Update product stability data to include new `app-srg-ctr` reference URI.
  - `test_product_stability.py --update-reference-data`

#### Rationale:

- The `container-platform` URI more accurately points to the source of SRG CTR.
- These SRGs are not yet parsed by CO, so this change should not have any impact there.

#### Review Hints:

- Build `ocp4` and `rhcos4` and check that the `SRG-APP-XXXXXX-CTR-XXXXX` references have `href` pointing to `   https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform`

### CODE REVIEW

**Review by dodys — APPROVED** [review]
lgtm, thanks!

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by xiaojiey** [comment]
@yuumasato Just one question: I verified with command `./build_product ocp4` command. But I didn't see anything related in the downstream CRD. Is it expected? Thanks.
```
$ egrep -nr  "application-servers"
ocp4/product.yml:132:  app-srg: https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=application-servers
ocp4/ssg-ocp4-xccdf.xml:45: <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=application-servers">app-srg</xccdf-1.2:reference>
ssg-ocp4-xccdf.xml:46:  <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=application-servers">app-srg</xccdf-1.2:reference>
ssg-ocp4-ds-1.2.xml:163:      <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=application-servers">app-srg</xccdf-1.2:reference>
ssg-ocp4-ds.xml:163:      <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=application-servers">app-srg</xccdf-1.2:reference>
[xiyuan@fedora build (pr-11647)]$ egrep -nr "=container-platform" | head
ocp4/product.yml:133:  app-srg-ctr: https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform
ocp4/ssg-ocp4-xccdf.xml:46: <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">app-srg-ctr</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4447:    <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000384-CTR-000915</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4478:    <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000384-CTR-000915</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4515:    <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000516-CTR-001325</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4563:    <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000131-CTR-000285</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4674:     <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000126-CTR-000275</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4675:     <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000219-CTR-000550</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4676:     <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000411-CTR-000995</xccdf-1.2:reference>
ocp4/ssg-ocp4-xccdf.xml:4677:     <xccdf-1.2:reference href="https://public.cyber.mil/stigs/downloads/?_dl_facet_stigs=container-platform">SRG-APP-000412-CTR-001000</xccdf-1.2:reference>
```

**Comment by yuumasato** [comment]
> @yuumasato Just one question: I verified with command `./build_product ocp4` command. But I didn't see anything related in the downstream CRD. Is it expected? Thanks.

@xiaojiey correct , no new CRDs are expected.
The new URI is to be consumed by the parser added in
https://github.com/ComplianceAsCode/compliance-operator/pull/494

**Comment by yuumasato** [comment]
I have folded these commits into #11593.

The STIG ID URI required updates as well, so I decide to merge these PRs, as they are both touching similar code and require updates to the product stability data.

**Pull request closed without merging**
