### PR TITLE
Remove the RHCOS4 OSPP profile

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

remove the RHCOS4 OSPP profile

#### Rationale:
It was unmaintained, didn't really work because the profile contained
rules that could only work on RHEL and was confusing users who thought
that this was a Red Hat maintained profile.

### CODE REVIEW

**Comment by rhmdnd** [comment]
What was OSPP for initially? Id d it actually correspond to a standard?

**Comment by jhrozek** [comment]
So the OSPP RHCOS4 profile wasn't created by us, but the previous CaC maintainers. The standard can be found here: https://commoncriteriaportal.org/files/ppfiles/PP_OS_V4.2.1.pdf
I'm not sure about the relation between OSPP and the other standard to be honest, but I think it's better to not ship a profile we don't maintain rather than pretend we do.
If we want to keep the profile around, let's at least switch to `documentation_complete: false` so it doesn't get build by default (but it would still get built in our content container where we build with `--debug`..)

**Comment by rhmdnd** [comment]
> So the OSPP RHCOS4 profile wasn't created by us, but the previous CaC maintainers. The standard can be found here: https://commoncriteriaportal.org/files/ppfiles/PP_OS_V4.2.1.pdf I'm not sure about the relation between OSPP and the other standard to be honest, but I think it's better to not ship a profile we don't maintain rather than pretend we do. If we want to keep the profile around, let's at least switch to `documentation_complete: false` so it doesn't get build by default (but it would still get built in our content container where we build with `--debug`..)

I'm good with removing it if it's incomplete and doesn't work. Unless we need some sort of formal deprecation period before we remove things like this.

**Comment by jhrozek** [comment]
Hmm, that's a good idea, maybe we can set the profile as `documentation_complete: false` for a bit and remove maybe after some releases.

@mrogers950 do you remember the history behind this profile?

**Comment by mrogers950** [comment]
It was a part of the really old STIG draft. If it pops up again for us I think it would need a re-eval at this point, so I'm good with deleting it.

**Comment by jhrozek** [comment]
Then let's this get acked :-)

**Comment by jan-cerny** [comment]
@jhrozek the CI fail looks legit, you will probably need to modify ssg_build_html_profile_table in /products/rhcos4/CMakeLists.txt, please also take a look if there aren't other remainders from ospp

**Comment by rhmdnd** [comment]
It also appears we have a potential regression with `sysctl_kernel_yama_ptrace_scope`

```
helpers.go:807: Result - Name: e2e-high-worker-sysctl-kernel-yama-ptrace-scope - Status: FAIL - Severity: medium
helpers.go:814: E2E-FAILURE: The expected result for the sysctl_kernel_yama_ptrace_scope rule didn't match. Expected 'PASS', Got 'FAIL' 
```

**Comment by jhrozek** [comment]
Cool, now it's only the OCP checks failing

**Comment by jan-cerny** [comment]
@jhrozek thanks for the investigation!

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
