### PR TITLE
Re-organize `tests/fmf-plans` into a more concise format

### PR DESCRIPTION
**Pull request by comps**
#### Description:

- This is about cleaning up and re-organizing `tests/fmf-plans/` into what I feel is a more concise and organized form.
- The end result should be nicely named TMT plans in Testing Farm (without `/tests/fmf-plans` prefix), and with TMT HTML reports available in the Testing Farm data dir structure
  - Unfortunately, there's no easy way to expose the path to this HTML on the Packit GH check page.

- Note that this brings in a testing change - currently, some Beakerlib-based tests from fedoraproject.org run on Fedora via Testing Farm
  - `Sanity/ansible-allowed-modules`
  - `Sanity/smoke-test` (rpmbuild + CTest)

  these would not be running on Fedora anymore, where Contest is not supported. However, given their nature, I believe running them on CentOS Stream is sufficient.
  - @mildas @matusmarhefka Please comment whether this is okay.
  - If so, then this PR also requires the removal of `testing-farm:fedora-39-x86_64` from the "required" Github checks.

#### Review Hints:

- See individual commits, they usually have descriptions detailing the rationale for each change.

### CODE REVIEW

**Comment by mildas** [comment]
The changes look fine and no problem on my side in regards of not running tests on Fedora anymore.

However, the html-links tests seems quite flaky for GH CI, that's something to solve before merging this PR. I've also noticed it in productization that some links time out but are fine in re-run. And then there's the certificate problem which might be temporary issue but still it would block PRs.
Thus, I wonder if we want to have html-links enabled in CI. Content contains a lot of links a it might happen quite often that one link here or there will fail because of some temporary external problem.

**Comment by comps** [comment]
> The changes look fine and no problem on my side in regards of not running tests on Fedora anymore.

:+1: 

> However, the html-links tests seems quite flaky for GH CI, that's something to solve before merging this PR. I've also noticed it in productization that some links time out but are fine in re-run. And then there's the certificate problem which might be temporary issue but still it would block PRs. Thus, I wonder if we want to have html-links enabled in CI. Content contains a lot of links a it might happen quite often that one link here or there will fail because of some temporary external problem.

Then we should probably just get rid of the test. Something that fails frequently enough that it would cause issues in pull requests, and is as insignificant as broken HTTP links in text, is not worth the combined days/weeks of human time investigating the failures.

**Comment by mildas** [comment]
Are you fine with excluding the html-link test from here, then we can also exclude it from daily productization and run it only in stabilization test runs?

**Comment by comps** [comment]
> Are you fine with excluding the html-link test from here, then we can also exclude it from daily productization and run it only in stabilization test runs?

I've pushed a commit disabling it here, for now, to not block https://github.com/ComplianceAsCode/content/pull/11807 or whatever new PR I'll make with those changes. .. We can adjust the exclusion later if needed.

**Comment by mildas** [comment]
As https://github.com/RHSecurityCompliance/contest/pull/148 got merged, now we need to wait until https://github.com/ComplianceAsCode/content/pull/11796 is merged

**Review by Mab879 — APPROVED** [review]
LGTM.

Thanks for the work.

**Pull request merged**
