### PR TITLE
SLES-15-030400 rule

### PR DESCRIPTION
**Pull request by rumch-se**
Added platform clause

#### Description:

-_SLES-15-030400 rule _

#### Rationale:

- _Review requested_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

### CODE REVIEW

**Comment by vojtapolasek** [comment]
@openscap-ci  test this please

**Comment by vojtapolasek** [comment]
Hello @rumch-se , thank you for the rule. It looks good. Could you please just modify tests so that they correctly enable / disable augenrules / auditctl? See here for example:
https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/tests

**Comment by vojtapolasek** [comment]
@openscap-ci test this please

**Comment by ggbecker** [comment]
@openscap-ci ok to test

**Pull request merged**
