### PR TITLE
Fix regex in file_ownership_audit_configuration

### PR DESCRIPTION
**Pull request by marcusburghardt**
#### Description:

This regex was not matching the files as expected. After some minor changes with escapes, it is working.

#### Rationale:

Fix CI test `Automatus Sanity / Run Tests (pull_request)`

#### Review Hints:

```
./tests/automatus.py rule --libvirt qemu:///session rhel9 --datastream build/ssg-rhel9-ds.xml --dontclean --remediate-using bash file_ownership_audit_configuration
./tests/automatus.py rule --libvirt qemu:///session rhel9 --datastream build/ssg-rhel9-ds.xml --dontclean --remediate-using ansible file_ownership_audit_configuration
```

Reference:
https://www.gnu.org/software/findutils/manual/html_node/find_html/Regular-Expressions.html#Regular-Expressions

### CODE REVIEW

**Comment by marcusburghardt** [comment]
> @marcusburghardt
> 
> I think the updated version is also wrong. The updated OVAL check contains `\(` which matches the `(` literally. You can see in the OVAL results that it didn't found the `/etc/audit/audit.rules` and `/etc/audit/auditd.conf` which should be flagged by the checks. On the other hand, it seems to fix the failing test scenario because it changed the Bash remediation. I think the problem is that there needs to be a different type of regular expression in OVAL than in the bash `find` command that is used for the remediation. OVAL should contain PCRE where parenthesis mean optional match but find should contain Emacs regex where parenthesis mean literal parenthesis. But, we put the same string into both OVAL and Bash.
> 
> Also, take a look that there are multiple occurrences of this regex: file_groupownership_audit_configuration, file_ownership_audit_configuration, ile_permissions_audit_configuration.

Yes, the original issue was in the `find` command used in Bash remediation. If this break the OVAL, we need to find another solution. : (

**Comment by marcusburghardt** [comment]
It should be fine now. More details in the last commit message.

**Comment by marcusburghardt** [comment]
I just force-pushed to re-trigger some stalled testing-farm CI tests.

**Comment by jan-cerny** [comment]
@marcusburghardt There is the same regex also in file_groupownership_audit_configuration and file_permissions_audit_configuration. Can you check if we need to change these rules as well?

**Comment by marcusburghardt** [comment]
> file_groupownership_audit_configuration

Thanks for noticing this. I updated them in https://github.com/ComplianceAsCode/content/pull/12029/commits/fe7a5ea0330d04bf73e362e18d4945dcbdb68483

**Comment by marcusburghardt** [comment]
> > file_groupownership_audit_configuration
> 
> Thanks for noticing this. I updated them in [fe7a5ea](https://github.com/ComplianceAsCode/content/commit/fe7a5ea0330d04bf73e362e18d4945dcbdb68483). But hold a little until I finish the tests, please.

Should be ok now. My local tests are green for these three rules.

**Review by dodys — APPROVED** [review]
lgtm, thanks!

**Review by jan-cerny — APPROVED** [review]

**Pull request merged**
