### PR TITLE
Fix AIDE rules

### PR DESCRIPTION
**Pull request by jan-cerny**
#### Description:
- remove confused TS linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/tests/db_malformed.fail.sh
- in rule aide_build_database do not require existence of the /var/lib/aide/aide.db.new.gz which isn't needed for aide to work
- in rule aide_periodic_cron_checking make the regular expression flexible to match different forms of the aide command in /etc/cron.daily/.*
- add new TSs

For more details please read commit messages of every commit.

#### Rationale:
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2175684

#### Review Hints:
Use the test scenarios added in this PR.

#### Question:
Should also regular expressions for /etc/crontab be changed?

### CODE REVIEW

**Review by marcusburghardt — APPROVED** [review]
LGTM. Thanks for the good commit messages. I know it is not part of the scope, but it seems we have the opportunity to simplify this OVAL. Most of the content in the `sle` conditional is duplicated. Let me know if you plan to take a look on this in this PR. Otherwise I am fine with this in a separate PR.

**Comment by jan-cerny** [comment]
Nice idea, I will take a look what I can do

**Comment by jan-cerny** [comment]
I have simplified the OVAL file

**Review by marcusburghardt — APPROVED** [review]
Amazing. Thanks @jan-cerny

**Comment by marcusburghardt** [comment]
The testing-farm errors in CS8 and CS9 are not related to this PR.
The error is already reported: https://github.com/ComplianceAsCode/content/issues/10450

**Pull request merged**
