### PR TITLE
OCP4: fixes to YAML test manifests

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- OCP4: Add more test manifests
- OCP4: lowercase several rules

See the commit messages for more details.

#### Rationale:

- Provides better coverage in the OCP4 test suite

#### Review Hints:

N/A

### CODE REVIEW

**Review by jan-cerny — APPROVED** [review]

**Comment by jhrozek** [comment]
The new patches just mark the `kubeadm_removed` rule as always failing: we do keep kubeadm around in our tests.

**Comment by jhrozek** [comment]
uh-oh, I didn't expect this:
```
    helpers.go:808: Result - Name: e2e-moderate-audit-profile-set - Status: FAIL - Severity: medium
    helpers.go:815: E2E-FAILURE: The expected result for the audit_profile_set rule didn't match. Expected 'PASS', Got 'FAIL'
```
because 1) I thought that the profile is set by default and 2) if we don't set the profile, then it's a bug IMO

**Comment by jhrozek** [comment]
but hey, our e2e tests are catching issues.

**Comment by jhrozek** [comment]
> uh-oh, I didn't expect this:
> 
> ```
>     helpers.go:808: Result - Name: e2e-moderate-audit-profile-set - Status: FAIL - Severity: medium
>     helpers.go:815: E2E-FAILURE: The expected result for the audit_profile_set rule didn't match. Expected 'PASS', Got 'FAIL'
> ```
> 
> because 1) I thought that the profile is set by default and 2) if we don't set the profile, then it's a bug IMO

Ah, OK, they are set by default, but every profile expects a different value, so that's why we get pass/fail on different profiles. OK, we need to implement per-profile expected results.

**Pull request merged**
