### PR TITLE
Various python fixes

### PR DESCRIPTION
**Pull request by maage**
#### Description:

Collection of various python code fixes and some style changes.

#### Rationale:

Improve `mkdir_p` and then use it everywhere. There was duplicate implementations. Now also handle errors when directory already exists if there is issues with parallelism for example. Patch could further improved if only recent python versions are used.

Fix `escape_regex` to match comment.

Probably search and replace fix with xccdf version.

Some duplicate code. Some codes I wonder how it was previously working as intended.

Bad helper in automatus. 

And then some style changes that I see as obvious.

#### Review Hints:

pyflakes / flake8 issues are only reduced before and after this patch. If you ignore file length.

Parallel builds to check `mkdir_p` before and after. It might be possible to effectively and repeatedly to see issues this might require cmake modifications to allow further parallelism. 

`escape_regex` change might cause xml modifications.

Sofar only built and run ctest with this.

### CODE REVIEW

**Comment by maage** [comment]
I think these are unrelated and change, if any, is not obvious.
https://codeclimate.com/github/ComplianceAsCode/content/pull/10345

**Review by Mab879 — CHANGES_REQUESTED** [review]
The changes look good, please rebase the MR to remove the merge commit.

**Comment by maage** [comment]
> The changes look good, please rebase the MR to remove the merge commit.

Now should be rebased to fresh master w/o merge commits.

**Review by Mab879 — APPROVED** [review]
Thanks for the PR! This should improve many things. I am waving the Code Climate findings as they are on existing code.

**Pull request merged**
