### PR TITLE
Make sure that 'prodtype' and 'platform' don't contain spaces

### PR DESCRIPTION
**Pull request by redhatrises**
- Spaces in prodtype and platform should be stripped and not exist in our content

### CODE REVIEW

**Comment by jan-cerny** [comment]
@redhatrises I think our build scripts can handle the spaces. Have you encountered any situation when the spaces in prodtype or platform caused problems? I'm just curious. Otherwise LGTM.

**Comment by redhatrises** [comment]
> @redhatrises I think our build scripts can handle the spaces. Have you encountered any situation when the spaces in prodtype or platform caused problems? I'm just curious. Otherwise LGTM.

@jan-cerny it isn't really about the build system handling it as it is more about content consistency (e.g. `multi_platform_rhel, multi_platform_fedora,multi_platform_ol` vs `multi_platform_rhel,multi_platform_fedora,multi_platform_ol` as well as making it easier to update platform or prodtype without having to account for spaces.

**Comment by shawndwells** [comment]
@redhatrises build failure

`````
Traceback (most recent call last):
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/build-scripts/combine_remediations.py", line 108, in <module>
    main()
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/build-scripts/combine_remediations.py", line 74, in main
    remediation.process(remediation_obj, env_yaml, fixes, rule_id)
  File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/ssg/build_remediations.py", line 248, in process
    raise ValueError(msg)
ValueError: Comma-separated 'Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8, multi_platform_fedora, multi_platform_ol,multi_platform_rhv' platforms in '/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/linux_os/guide/system/auditing/auditd_configure_rules/directory_access_var_log_audit/bash/shared.sh' contains whitespace.
`````

**Comment by redhatrises** [comment]
> @redhatrises build failure
> 
> ```
> Traceback (most recent call last):
>   File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/build-scripts/combine_remediations.py", line 108, in <module>
>     main()
>   File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/build-scripts/combine_remediations.py", line 74, in main
>     remediation.process(remediation_obj, env_yaml, fixes, rule_id)
>   File "/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/ssg/build_remediations.py", line 248, in process
>     raise ValueError(msg)
> ValueError: Comma-separated 'Red Hat Enterprise Linux 7,Red Hat Enterprise Linux 8, multi_platform_fedora, multi_platform_ol,multi_platform_rhv' platforms in '/home/jenkins/workspace/scap-security-guide-pull-requests/label/rhel7/linux_os/guide/system/auditing/auditd_configure_rules/directory_access_var_log_audit/bash/shared.sh' contains whitespace.
> ```

Thanks @shawndwells. Fixed

**Comment by jan-cerny** [comment]
@redhatrises thanks, that was my understanding

**Pull request merged**
