### PR TITLE
Extend openshift_cluster_setting macro to support lists.

### PR DESCRIPTION
**Pull request by ggbecker**
#### Description:

- Extend openshift_cluster_setting macro to support lists.

### CODE REVIEW

**Comment by jhrozek** [comment]
This works for me and is better than my solution that added another macro that always took a list. Would you mind resubmitting without that change to the rule?

**Comment by ggbecker** [comment]
> This works for me and is better than my solution that added another macro that always took a list. Would you mind resubmitting without that change to the rule?

Done.

**Comment by jhrozek** [comment]
`[31mERRO[0m[2021-06-07T17:51:27Z]   * could not run steps: step e2e-aws-ocp4-cis failed: failed to acquire lease for "aws-quota-slice": resources not found `
looks like CI has trouble installing cluster. I'm going to just kick the job.

**Review by jhrozek — APPROVED** [review]
LGTM

**Comment by JAORMX** [comment]
/lgtm

@jhrozek thanks for the pointer!

**Pull request merged**
