### PR TITLE
SRG-APP-000014-CTR-000035: Use policy files

### PR DESCRIPTION
**Pull request by jhrozek**
#### Description:

- SRG-APP-000014-CTR-000035: Move the fix and check into policy files - uses per-rule policy files instead of replies in the control file itself
- SRG-APP-000014-CTR-000035: Is now automated - we claimed the control is still manual and pointed to a card that's been addressed

#### Rationale:

- Using per-rule policy files would make generating the spreadsheet easier

#### Review Hints:
N/A

### CODE REVIEW

**Comment by jhrozek** [comment]
@Mab879 @ggbecker since this is my first time submitting the new policy file, I wanted to ask you for a review.

Also a related question: What is the guidance on using `related_rules`? I see that they're seldom used in `gpos`, but quite often used in `ctr`. In case of this rule, it even seems like the rule is not very related. FIPS is related in the sense that without FIPS, there's no way of ensuring compliant TLS, on the other hand there's several rules more directly related to crypto..

**Comment by jhrozek** [comment]
@TrilokGeer @bharath-b-rh you might be interested in this PR (related to https://issues.redhat.com/browse/CMP-1732)

**Comment by Mab879** [comment]
Your new policy files look good to me.

You can use the `related_rules` as you see fit; I don't think we have any official guidance on how they are used. A quick search of the Python files in the projects suggests that the `related_rules` key is not used in any outputs or scripts, so the `related_rules` key currently is just for content authors or people reading the controls files.

**Comment by jhrozek** [comment]
@Mab879 thanks for taking a look, could I get a formal review, then?

**Review by Mab879 — APPROVED** [review]
From a policy file perspective, LGTM. However, I can't review the content itsself.

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by jhrozek** [comment]
thanks for the review, just rebased on the current master.

**Comment by jhrozek** [comment]
/retest
cluster install time outs

**Comment by jhrozek** [comment]
good ol' cluster install failures
/retest

**Comment by jhrozek** [comment]
The OCP4 CI is incredibly flaky lately
/retest

**Pull request merged**
